In [34]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\myenv\lib\site-packages (1.7.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.22.0 in c:\users\hp\myenv\lib\site-packages (from scikit-learn) (2.1.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\hp\myenv\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\myenv\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\myenv\lib\site-packages (from scikit-learn) (3.6.0)

In [35]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [36]:
dst = pd.read_csv("Marksheet.csv") #data collecting

In [37]:
dst

    Student_Name  Hindi  English  Maths  Science  SST  Total  Percentage
0    Arjun Singh     45     49.0     56       63   70  283.0        56.6
1    Mohit Yadav     46     53.0     59       64   68  290.0        58.0
2    Amit tiwari     47     48.0     45       67   56  263.0        52.6
3     Sumit Negi     48     49.0     50       62   67  276.0        55.2
4      Rohit Raj     49     48.5     54       45   78  274.5        54.9
5   Shivani Negi     50     48.0     55       78   89  320.0        64.0
6          Jyoti     51     47.5     58       87   90  333.5        66.7
7          Arpit     52     47.0     57       65   76  297.0        59.4
8   Surjan Singh     53     46.5     67       65   78  309.5        61.9
9      Duryodhan     54     46.0     78       45   65  288.0        57.6
10         Bheem     55     45.5     79       59   45  283.5        56.7
11         Nakul     56     45.0     60       76   76  313.0        62.6
12        Sahdev     57     44.5     80       56   87  324.5        64.9
13       Krishna     58     44.0     90       56   68  316.0        63.2
14      Bheeshma     56     87.0     57       87   44  331.0        66.2
15         Kunti     66     78.0     54       76   55  329.0        65.8
16  Dhritrashtra     77     76.0     77       67   66  363.0        72.6
17      Shantanu     88     67.0     66       65   77  363.0        72.6
18        Bharat     57     66.0     55       69   67  314.0        62.8

In [45]:
x = pd.DataFrame(dst.iloc[:,2:4])  #independent column
y = pd.DataFrame(dst.iloc[:,-1]) #dependent column

In [46]:
x

    English  Maths
0      49.0     56
1      53.0     59
2      48.0     45
3      49.0     50
4      48.5     54
5      48.0     55
6      47.5     58
7      47.0     57
8      46.5     67
9      46.0     78
10     45.5     79
11     45.0     60
12     44.5     80
13     44.0     90
14     87.0     57
15     78.0     54
16     76.0     77
17     67.0     66
18     66.0     55

In [47]:
y

    Percentage
0         56.6
1         58.0
2         52.6
3         55.2
4         54.9
5         64.0
6         66.7
7         59.4
8         61.9
9         57.6
10        56.7
11        62.6
12        64.9
13        63.2
14        66.2
15        65.8
16        72.6
17        72.6
18        62.8

In [48]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/3,random_state= 0) #split the datatset

In [49]:
#fitting the linear regression model to the trainging dataset

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [50]:
#prediction of test data and training data set result
x_test_pred = regressor.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,x_test_pred)

0.10550233981394064

In [51]:
x_train_pred = regressor.predict(x_train)