In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("gemstone.csv")

In [3]:
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [4]:
## lets drop the id column
df = df.drop(labels=["id"],axis = 1)
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [5]:
x = df.drop(labels= ["price"], axis = 1)
y = df[["price"]]

In [6]:
categorical_col=x.select_dtypes(include="object").columns
numerical_col=x.select_dtypes(exclude="object").columns

In [7]:
numerical_col

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [8]:
#define the columns for encoding

cut_categories = ["Fair","Good","Very Good","Premium","Ideal"]
color_categories = ["D","E","F","G","H","I","J"]
clarity_categories = ["I1","SI2","SI1","VS2","VS1","VVS2","VVS1","IF"]

In [9]:
from sklearn.impute import SimpleImputer      #handling missing values
from sklearn.preprocessing import StandardScaler   #handling feature scaling
from sklearn.preprocessing import OrdinalEncoder    #Ordinal Encoding

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [10]:
num_pipeline = Pipeline(
    steps = [
        ("imputer",SimpleImputer(strategy = "median")),
        ("scaler",StandardScaler())
    ]
)
cat_pipeline = Pipeline(
    steps = [
        ("imputer", SimpleImputer(strategy = "most_frequent")),
        ("ordinalencoder", OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories])),
        ("scaler",StandardScaler())
    ]
)

In [ ]:
#columns transformer
ColumnsTansformer([