In [39]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [40]:
titanic = sns.load_dataset('titanic')

# Select only the columns you want
columns = ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 
           'fare', 'embarked', 'class', 'who', 'adult_male', 
           'deck', 'alive', 'alone']

df = titanic[columns]
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck alive  alone
0    man        True  NaN    no  False
1  woman       False    C   yes  False
2  woman       False  NaN   yes   True
3  woman       False    C   yes  False
4    man        True  NaN    no   True

In [41]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,no,True

In [42]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'alive', 'alone'],
      dtype='object')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    object
 3   age         714 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   embarked    889 non-null    object
 8   class       891 non-null    category
 9   who         891 non-null    object
 10  adult_male  891 non-null    bool
 11  deck        203 non-null    category
 12  alive       891 non-null    object
 13  alone       891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(4)
memory usage: 73.7+ KB

In [44]:
df.drop(['deck','embarked','alive','class','who','adult_male',],axis = 1,inplace = True)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(1)
memory usage: 49.7+ KB

In [46]:
df['age'].fillna(df['age'].mean(),inplace = True)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(1)
memory usage: 49.7+ KB

In [48]:
df.dropna(subset=['embarked'], inplace=True)

KeyError: ['embarked']

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(1)
memory usage: 49.7+ KB

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder

In [51]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare  alone
0         0       3    male  22.0      1      0   7.2500  False
1         1       1  female  38.0      1      0  71.2833  False
2         1       3  female  26.0      0      0   7.9250   True
3         1       1  female  35.0      1      0  53.1000  False
4         0       3    male  35.0      0      0   8.0500   True

In [52]:
# Create an instance of LabelEncoder
le = LabelEncoder()
le_sex = LabelEncoder()
le_embarked = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])

KeyError: 'embarked'

In [53]:
int_columns = ['survived', 'pclass', 'sex', 'sibsp', 'parch', 'embarked']
df[int_columns] = df[int_columns].astype(int)

KeyError: "['embarked'] not in index"

In [54]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  alone
0         0       3    1  22.0      1      0   7.2500  False
1         1       1    0  38.0      1      0  71.2833  False
2         1       3    0  26.0      0      0   7.9250   True
3         1       1    0  35.0      1      0  53.1000  False
4         0       3    1  35.0      0      0   8.0500   True