In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vikas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [58]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')
fake['label'] = 1
true['label'] = 0 
news= pd.concat([fake, true], ignore_index=True)
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1

In [59]:
print(f"Dataset shape: {news.shape}")
print("\nMissing values:\n", news.isnull().sum())

Dataset shape: (44898, 5)

Missing values:
 title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [55]:
news.dropna(subset="text",axis=0)

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
68511,"Donald Trump, Germany’s disfavored son – POLITICO","KALLSTADT, Germany — Few places in Germany are...",left-news,"Nov 14, 2017",0
68512,BREAKING: Hollywood Legend Just Died Of Terrib...,Hollywood loses yet another one of their deare...,left-news,"Nov 14, 2017",0
68513,Worst. President. Ever.,"As my 25th wedding anniversary approached, I t...",left-news,"Nov 14, 2017",0
68514,Don King drops N-word while introducing Donald...,Story highlights Trump was sitting in a chair ...,left-news,"Nov 14, 2017",0
68515,Donald Trump Jr. Compares Syrian Refugees to S...,"Donald Trump Jr., a son of the Republican pres...",left-news,"Nov 14, 2017",0

In [9]:
news.title[0]

' Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing'

In [10]:
news.text[0]

'Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t even allow him to rise above the gutter long enough to wish the American citizens a happy new year!  Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes you  Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 a great year for America, but I ll also accept regaining control of Congress.  Miranda Yaver (@mirandayaver) December 31, 2017Do you hear yourself talk? When you have to include that many people that hate you you have to wonder? Why do the they all hate me?  Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses the word Haters in a New Years wish??  Marlene (@marlene399) December 31, 2017You can t just say happy new year?  Koren pollitt (@Korencarpenter) December 31, 2017Here s Trump s New Year s Eve tweet from 2016.Happy New Year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. Love!  Donald J. Trump (@realDonaldTrump) December 31, 2016This is nothing new for Trump. He s been doing this for years.Trump has directed messages to his  enemies  and  haters  for New Year s, Easter, Thanksgiving, and the anniversary of 9/11. pic.twitter.com/4FPAe2KypA  Daniel Dale (@ddale8) December 31, 2017Trump s holiday tweets are clearly not presidential.How long did he work at Hallmark before becoming President?  Steven Goodine (@SGoodine) December 31, 2017He s always been like this . . . the only difference is that in the last few years, his filter has been breaking down.  Roy Schulze (@thbthttt) December 31, 2017Who, apart from a teenager uses the term haters?  Wendy (@WendyWhistles) December 31, 2017he s a fucking 5 year old  Who Knows (@rainyday80) December 31, 2017So, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.Photo by Andrew Burton/Getty Images.'

In [11]:
news['content'] = news['title'] + ' ' + news['text']

In [12]:
news.content

0         Donald Trump Sends Out Embarrassing New Year’...
1         Drunk Bragging Trump Staffer Started Russian ...
2         Sheriff David Clarke Becomes An Internet Joke...
3         Trump Is So Obsessed He Even Has Obama’s Name...
4         Pope Francis Just Called Out Donald Trump Dur...
                               ...
44893    'Fully committed' NATO backs new U.S. approach...
44894    LexisNexis withdrew two products from Chinese ...
44895    Minsk cultural hub becomes haven from authorit...
44896    Vatican upbeat on possibility of Pope Francis ...
44897    Indonesia to buy $1.14 billion worth of Russia...
Name: content, Length: 44898, dtype: object

In [14]:
ps = PorterStemmer()
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [ps.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content
news['content'] = news['content'].apply(stemming)
print("Sample processed content:\n", news['content'].iloc[2])

Sample processed content:
 sheriff david clark becom internet joke threaten poke peopl eye friday reveal former milwauke sheriff david clark consid homeland secur secretari donald trump administr email scandal januari brief run plane clark fellow passeng dan black later detain polic reason whatsoev except mayb feel hurt clark messag polic stop black deplan search warrant execut fbi see exchang clark call fake news even though copi search warrant internet unintimid lib media attempt smear discredit fake news report design silenc former sheriff tweet continu poke eye sharp stick bitch slap scum bag til get attack better peopl maga unintimid lib media attempt smear discredit fake news report design silenc continu poke eye sharp stick bitch slap scum bag til get attack better peopl maga pic twitter com xtzw pdu b david clark jr sheriffclark decemb stop break news lie lib media make fake news smear antidot go right punch nose make tast blood noth get bulli like lie lib media attent better give tast blood neverbackdown pic twitter com ny pshcr david clark jr sheriffclark decemb internet call local newspap search warrant fake chose file charg time mean especi continu lie month decis charg clark email search warrant file http co zcbyc wp b keithleblanc keithleblanc decemb hope rest villag peopl implic kirk ketchum kirkketchum decemb slaw bake potato french fri pic twitter com fwfxszupxi alt immigr alt usci decemb pic twitter com ymsobljfxu pendulum swinger pendulumswngr decemb call polic friend stand someon made fun hat chri jackson chriscjackson decemb master pshop hat seem never tire think steeli resolv one visibl eye pic twitter com dwr k zezv chri mohney chrismohney decemb indic finger mani peopl die jail think finger short dipshit ike barinholtz ikebarinholtz decemb rofl internet tough guy fake flair pic twitter com ulcfddhkdi kellmecrazi kel moonfac decemb edgi buddi mr smh mrssmh decemb break applebe aaron feltrrr decemb tri earn still relev badg circusrebel circusdrew decemb make sure hydrat drink lot water rumor prison deni water prison offici robert klinc robertklinc decemb terril thoma year old black man die thirst clark milwauke counti jail cell april victim homicid thought point repeat enough photo spencer platt getti imag

In [15]:
X = news['content'].values
y = news['label'].values

vectorizer = TfidfVectorizer()
vectorizer.fit(X)

X = vectorizer.transform(X)

print(f"Shape of TF-IDF matrix: {X.shape}")

Shape of TF-IDF matrix: (44898, 89868)

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

Training set shape: (35918, 89868)
Testing set shape: (8980, 89868)

In [17]:
# Initialize and train model
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [18]:
train_y_pred = model.predict(X_train)
train_accuracy = accuracy_score(train_y_pred, Y_train)
print(f'Training Accuracy: {train_accuracy:.4f}')

test_y_pred = model.predict(X_test)
test_accuracy = accuracy_score(test_y_pred, Y_test)
print(f'Testing Accuracy: {test_accuracy:.4f}')

Training Accuracy: 0.9909
Testing Accuracy: 0.9882

In [10]:
_, test_indices = train_test_split(news_df.index, test_size=0.2, stratify=news_df['label'], random_state=2)

original_index = test_indices[10]

original_data = news_df.loc[original_index]

print("Original Index in Dataset:", original_index)
print("\nTitle:", original_data['title'])
print("\nText:", original_data['text'])
print("\nProcessed Content:", original_data['content'])
print("\nTrue Label:", "Fake" if original_data['label'] == 1 else "Real")

input_data = X_test[10]
prediction = model.predict(input_data)

print("\nPredicted Label:", "The News is Fake" if prediction[0] == 1 else "The News is Real")

Original Index in Dataset: 18576

Title: MANCHESTER: MUSLIM WOMAN Wearing HAND GRENADE, Machine Gun, Knife Images On Burqa Says She’s Worried About Facing “Islamaphobia” After Terror Attack [VIDEO]

Text: A Muslim woman was criticised after she wore a burka emblazoned with weapons in a TV interview about the Manchester terror attackThe woman, named only as  Sid , was part of a group of Muslims interviewed by Channel 4 News journalist Krishnan Guru-Murthy in the Rusholme area of Manchester, which is home to the largest Libyan community in Europe.The group vehemently condemned the Manchester Arena attack by 22-year-old suicide bomber Salman Abedi, who is of Libyan descent.But some viewers criticised Sid over her decision to wear a burka printed with a pistol, grenade, knife and machine gun spelling the word  love .One wrote:  Channel 4 news contributor in full hijab, top to toe with comedy glasses, images of knife & hand grenade emblazoned across the front! Ffs.The interview with the Muslim woman named  Sid  begins at the 6:12 mark of the video. Sid tells the interviewer,  I know I m a good Muslim I don t need to prove anything .Watch:Another Twitter user said:  Channel 4 actually broadcast this. Nothing says love like a hand grenade & flick-knife. For entire story: Daily Mail

Processed Content: manchest muslim woman wear hand grenad machin gun knife imag burqa say worri face islamaphobia terror attack video muslim woman criticis wore burka emblazon weapon tv interview manchest terror attackth woman name sid part group muslim interview channel news journalist krishnan guru murthi rusholm area manchest home largest libyan commun europ group vehement condemn manchest arena attack year old suicid bomber salman abedi libyan descent viewer criticis sid decis wear burka print pistol grenad knife machin gun spell word love one wrote channel news contributor full hijab top toe comedi glass imag knife hand grenad emblazon across front ff interview muslim woman name sid begin mark video sid tell interview know good muslim need prove anyth watch anoth twitter user said channel actual broadcast noth say love like hand grenad flick knife entir stori daili mail

True Label: Fake

Predicted Label: The News is Fake