In [1]:
import pandas as pd

In [2]:
marks = [20,21,22,23,24,25]
A =pd.Series(data = marks)
print(A)

0    20
1    21
2    22
3    23
4    24
5    25
dtype: int64

In [3]:
city = ['BHOPAL', 'INDORE','GOA','DELHI','NOIDA','MANALI']
B =pd.Series(data = marks,index = city)
B

BHOPAL    20
INDORE    21
GOA       22
DELHI     23
NOIDA     24
MANALI    25
dtype: int64

In [4]:
info = {'name':'ram','age':23,'city':'bhopal','weight':60}
C = pd.Series(info)
C

name         ram
age           23
city      bhopal
weight        60
dtype: object

In [5]:
C['age']

23

In [6]:
C['name']

'ram'

In [7]:
C['age']=230
C

name         ram
age          230
city      bhopal
weight        60
dtype: object

In [8]:
A

0    20
1    21
2    22
3    23
4    24
5    25
dtype: int64

In [9]:
A[1:4]

1    21
2    22
3    23
dtype: int64

In [10]:
A =pd.Series({1:44,2:55,3:88})
A

1    44
2    55
3    88
dtype: int64

In [11]:
A[:]=0
A

1    0
2    0
3    0
dtype: int64

In [12]:
columns = ['NAME','AGE','MARKS']
data = [['a',21,41],
        ['b',24,25],
        ['c',25,26]]

In [13]:
df = pd.DataFrame(data=data,columns=columns)
df

  NAME  AGE  MARKS
0    a   21     41
1    b   24     25
2    c   25     26

In [14]:
columns = ['NAME','ID','City']
data = [[1,'A','BHOPAL'],
        [2,'B','GOA'],
        [3,'C','DELHI']]
df = pd.DataFrame(data=data,columns=columns)
df

   NAME ID    City
0     1  A  BHOPAL
1     2  B     GOA
2     3  C   DELHI

In [15]:
index = ['bhopal','indore','delhi']

In [16]:
DETAILS={'ID':[1,2,3],'NAME':['A','B','C']}
df2 = pd.DataFrame(DETAILS,index=index)
df2

        ID NAME
bhopal   1    A
indore   2    B
delhi    3    C

In [19]:
columns = ['ID','physics','Chemistry','maths']
data = [[1,30,55,56],
        [2,33,45,67],
        [3,56,67,89]]
df = pd.DataFrame(data=data,columns=columns)
df

   ID  physics  Chemistry  maths
0   1       30         55     56
1   2       33         45     67
2   3       56         67     89

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("RegularSeasonCompactResults.csv")

In [4]:
df

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [5]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [6]:
df.tail()

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

In [7]:
df.shape

(145289, 8)

In [8]:
df.size

1162312

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145289 entries, 0 to 145288
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Season  145289 non-null  int64
 1   Daynum  145289 non-null  int64
 2   Wteam   145289 non-null  int64
 3   Wscore  145289 non-null  int64
 4   Lteam   145289 non-null  int64
 5   Lscore  145289 non-null  int64
 6   Wloc    145289 non-null  object
 7   Numot   145289 non-null  int64
dtypes: int64(7), object(1)
memory usage: 8.9+ MB

In [10]:
df.head(10)

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0
6    1985      25   1228      64   1226      44    N      0
7    1985      25   1242      58   1268      56    N      0
8    1985      25   1260      98   1133      80    H      0
9    1985      25   1305      97   1424      89    H      0

In [11]:
df.tail(10)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145279    2016     131   1392      80   1436      74    H      0
145280    2016     131   1401      71   1261      38    N      0
145281    2016     131   1419      82   1426      71    N      0
145282    2016     131   1433      76   1172      54    N      0
145283    2016     131   1451      62   1285      59    N      0
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

In [12]:
df[10:20]

    Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
10    1985      25   1307     103   1288      71    H      0
11    1985      25   1344      75   1438      71    N      0
12    1985      25   1374      91   1411      72    H      0
13    1985      25   1412      70   1397      65    N      0
14    1985      25   1417      87   1225      58    H      0
15    1985      26   1116      65   1368      62    H      0
16    1985      26   1120      92   1391      50    H      0
17    1985      26   1135      65   1306      60    A      0
18    1985      26   1143      58   1388      53    H      0
19    1985      26   1153      50   1184      48    H      0

In [13]:
df[55:61]

    Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
55    1985      27   1268      72   1397      49    N      0
56    1985      27   1314      81   1200      65    N      0
57    1985      27   1323      67   1264      56    H      0
58    1985      27   1412      50   1242      46    N      0
59    1985      27   1458      93   1288      78    H      0
60    1985      28   1104      81   1137      56    H      0

In [14]:
df.columns

Index(['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc',
       'Numot'],
      dtype='object')

In [15]:
df.columns.tolist()

['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc', 'Numot']

In [16]:
df.describe()

,Season,Daynum,Wteam,Wscore,Lteam,Lscore,Numot
count,145289.000000,145289.000000,145289.000000,145289.000000,145289.000000,145289.000000,145289.000000
mean,2001.574834,75.223816,1286.720646,76.600321,1282.864064,64.497009,0.044387
std,9.233342,33.287418,104.570275,12.173033,104.829234,11.380625,0.247819
min,1985.000000,0.000000,1101.000000,34.000000,1101.000000,20.000000,0.000000
25%,1994.000000,47.000000,1198.000000,68.000000,1191.000000,57.000000,0.000000
50%,2002.000000,78.000000,1284.000000,76.000000,1280.000000,64.000000,0.000000
75%,2010.000000,103.000000,1379.000000,84.000000,1375.000000,72.000000,0.000000
max,2016.000000,132.000000,1464.000000,186.000000,1464.000000,150.000000,6.000000

In [17]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [18]:
#aggregate function
df['Wteam']

0         1228
1         1106
2         1112
3         1165
4         1192
          ...
145284    1114
145285    1163
145286    1246
145287    1277
145288    1386
Name: Wteam, Length: 145289, dtype: int64

In [19]:
df['Wteam'].mean()

np.float64(1286.7206464357246)

In [20]:
df['Wteam'].median()

np.float64(1284.0)

In [21]:
df['Wteam'].std()

np.float64(104.57027504914535)

In [22]:
df['Wteam'].mode()

0    1181
Name: Wteam, dtype: int64

In [23]:
df['Wteam'].var()

np.float64(10934.94242385391)

In [24]:
np.mean(df['Wteam'])

np.float64(1286.7206464357246)

In [25]:
np.median(df['Wteam'])

np.float64(1284.0)

In [26]:
np.mode(df['Wteam'])

AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
np.std(df['Wteam'])

In [ ]:
np.var(df['Wteam'])

In [27]:
df['Wteam'].min()

np.int64(1101)

In [28]:
df['Wteam'].max()

np.int64(1464)

In [29]:
df[10:20:2]

    Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
10    1985      25   1307     103   1288      71    H      0
12    1985      25   1374      91   1411      72    H      0
14    1985      25   1417      87   1225      58    H      0
16    1985      26   1120      92   1391      50    H      0
18    1985      26   1143      58   1388      53    H      0

In [30]:
df[-1:-21:-2]

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145288    2016     132   1386      87   1433      74    N      0
145286    2016     132   1246      82   1401      77    N      1
145284    2016     132   1114      70   1419      50    N      0
145282    2016     131   1433      76   1172      54    N      0
145280    2016     131   1401      71   1261      38    N      0
145278    2016     131   1386      82   1173      79    N      0
145276    2016     131   1372      82   1394      60    N      0
145274    2016     131   1345      76   1276      59    N      0
145272    2016     131   1314      61   1438      57    N      0
145270    2016     131   1277      64   1268      61    N      0

In [31]:
df.iloc[0:6]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0

In [32]:
df.iloc[0:6,0:3]

   Season  Daynum  Wteam
0    1985      20   1228
1    1985      25   1106
2    1985      25   1112
3    1985      25   1165
4    1985      25   1192
5    1985      25   1218

In [33]:
df.iloc[-1:-6:-1,-1:-3:-1]

        Numot Wloc
145288      0    N
145287      0    N
145286      1    N
145285      0    N
145284      0    N

In [34]:
df.iloc[-1:-6:-1,-4:-7:-1]

        Lteam  Wscore  Wteam
145288   1433      87   1386
145287   1345      66   1277
145286   1401      82   1246
145285   1272      72   1163
145284   1419      70   1114

In [35]:
df.iloc[0:3,2:5]

   Wteam  Wscore  Lteam
0   1228      81   1328
1   1106      77   1354
2   1112      63   1223

In [36]:
df.loc[2:6]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0
6    1985      25   1228      64   1226      44    N      0

In [43]:
df.loc[2:6,1:3]

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [44]:
df.loc[2:6,["Daynum","Wteam"]]

   Daynum  Wteam
2      25   1112
3      25   1165
4      25   1192
5      25   1218
6      25   1228

In [45]:
df["Wscore"].max()

np.int64(186)

In [46]:
df["Wscore"].idxmax()

24970

In [47]:
df.iloc[24970]

Season    1991
Daynum      68
Wteam     1258
Wscore     186
Lteam     1109
Lscore     140
Wloc         H
Numot        0
Name: 24970, dtype: object

In [48]:
df["Season"].unique()

array([1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
       1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

In [49]:
df["Season"].nunique()

32

In [50]:
df["Season"].value_counts()

Season
2016    5369
2014    5362
2015    5354
2013    5320
2010    5263
2012    5253
2009    5249
2011    5246
2008    5163
2007    5043
2006    4757
2005    4675
2003    4616
2004    4571
2002    4555
2000    4519
2001    4467
1999    4222
1998    4167
1997    4155
1992    4127
1991    4123
1996    4122
1995    4077
1994    4060
1990    4045
1989    4037
1993    3982
1988    3955
1987    3915
1986    3783
1985    3737
Name: count, dtype: int64

In [51]:
df["Season"].unique()

array([1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
       1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

In [52]:
df.sort_values(by=["Wscore"])

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
128582    2013     116   1264      34   1193      31    H      0
5364      1986      77   1229      35   1166      34    A      0
69336     2001     126   1206      35   1423      33    N      0
118590    2011     130   1336      36   1458      33    N      0
20246     1990      47   1374      36   1426      31    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
20022     1990      40   1116     166   1109     101    H      0
24341     1991      47   1328     172   1258     112    H      0
19653     1990      30   1328     173   1109     101    H      0
17867     1989      92   1258     181   1109     150    H      0
24970     1991      68   1258     186   1109     140    H      0

[145289 rows x 8 columns]

In [53]:
df.sort_values(by=["Wscore"],ascending= [False])

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
24970     1991      68   1258     186   1109     140    H      0
17867     1989      92   1258     181   1109     150    H      0
19653     1990      30   1328     173   1109     101    H      0
24341     1991      47   1328     172   1258     112    H      0
20022     1990      40   1116     166   1109     101    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
20246     1990      47   1374      36   1426      31    H      0
118590    2011     130   1336      36   1458      33    N      0
69336     2001     126   1206      35   1423      33    N      0
5364      1986      77   1229      35   1166      34    A      0
128582    2013     116   1264      34   1193      31    H      0

[145289 rows x 8 columns]

In [59]:
df.sort_values(by=["Wteam"],ascending=[False])

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
114074    2011      23   1464      73   1405      67    H      0
4467      1986      47   1464      64   1320      62    H      0
144171    2016     106   1464      92   1227      91    H      2
5396      1986      77   1464      75   1184      69    H      0
5341      1986      75   1464      75   1287      48    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
139440    2015     120   1101      83   1223      71    H      0
143283    2016      89   1101      80   1249      71    H      0
135619    2015      31   1101      72   1170      61    H      0
137131    2015      71   1101      95   1322      81    A      0
136740    2015      62   1101      87   1146      70    H      0

[145289 rows x 8 columns]

In [63]:
df.sort_values(by=["Wteam","Wscore"],ascending=[False,True])

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
62239     2000      65   1464      43   1237      41    A      0
12511     1988      57   1464      48   1186      47    H      0
40469     1995      46   1464      53   1293      48    N      0
119031    2012      18   1464      53   1415      49    H      1
11835     1988      33   1464      54   1368      51    N      0
...        ...     ...    ...     ...    ...     ...  ...    ...
136740    2015      62   1101      87   1146      70    H      0
142481    2016      71   1101      87   1322      72    H      0
144622    2016     117   1101      87   1309      84    H      0
144430    2016     111   1101      91   1368      80    H      0
137131    2015      71   1101      95   1322      81    A      0

[145289 rows x 8 columns]

In [64]:
df["Wloc"].value_counts()

Wloc
H    86471
A    44229
N    14589
Name: count, dtype: int64

In [65]:
df.sample(5)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
46158     1996      89   1129      69   1286      61    H      0
120321    2012      50   1317      82   1212      40    H      0
26585     1991     105   1192      78   1318      66    H      0
107014    2009     105   1288      55   1126      44    H      0
129912    2014      19   1314      82   1350      72    N      0

In [66]:
#to get the values only from data
df.values

array([[1985, 20, 1228, ..., 64, 'N', 0],
       [1985, 25, 1106, ..., 70, 'H', 0],
       [1985, 25, 1112, ..., 56, 'H', 0],
       ...,
       [2016, 132, 1246, ..., 77, 'N', 1],
       [2016, 132, 1277, ..., 62, 'N', 0],
       [2016, 132, 1386, ..., 74, 'N', 0]], dtype=object)

In [67]:
#to get the data of all dta types
df.dtypes

Season     int64
Daynum     int64
Wteam      int64
Wscore     int64
Lteam      int64
Lscore     int64
Wloc      object
Numot      int64
dtype: object

In [68]:
df.isnull()

        Season  Daynum  Wteam  Wscore  Lteam  Lscore   Wloc  Numot
0        False   False  False   False  False   False  False  False
1        False   False  False   False  False   False  False  False
2        False   False  False   False  False   False  False  False
3        False   False  False   False  False   False  False  False
4        False   False  False   False  False   False  False  False
...        ...     ...    ...     ...    ...     ...    ...    ...
145284   False   False  False   False  False   False  False  False
145285   False   False  False   False  False   False  False  False
145286   False   False  False   False  False   False  False  False
145287   False   False  False   False  False   False  False  False
145288   False   False  False   False  False   False  False  False

[145289 rows x 8 columns]

In [69]:
df.isnull().sum()

Season    0
Daynum    0
Wteam     0
Wscore    0
Lteam     0
Lscore    0
Wloc      0
Numot     0
dtype: int64

In [70]:
#to check the rows in the data
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
145284    False
145285    False
145286    False
145287    False
145288    False
Length: 145289, dtype: bool

In [71]:
df.drop_duplicates()

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [72]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [76]:
df.rename(columns={"Season":"Year"})

        Year  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0       1985      20   1228      81   1328      64    N      0
1       1985      25   1106      77   1354      70    H      0
2       1985      25   1112      63   1223      56    H      0
3       1985      25   1165      70   1432      54    H      0
4       1985      25   1192      86   1447      74    H      0
...      ...     ...    ...     ...    ...     ...  ...    ...
145284  2016     132   1114      70   1419      50    N      0
145285  2016     132   1163      72   1272      58    N      0
145286  2016     132   1246      82   1401      77    N      1
145287  2016     132   1277      66   1345      62    N      0
145288  2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [78]:
df.rename(columns={"Season":"Year"},inplace=True)
df

        Year  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0       1985      20   1228      81   1328      64    N      0
1       1985      25   1106      77   1354      70    H      0
2       1985      25   1112      63   1223      56    H      0
3       1985      25   1165      70   1432      54    H      0
4       1985      25   1192      86   1447      74    H      0
...      ...     ...    ...     ...    ...     ...  ...    ...
145284  2016     132   1114      70   1419      50    N      0
145285  2016     132   1163      72   1272      58    N      0
145286  2016     132   1246      82   1401      77    N      1
145287  2016     132   1277      66   1345      62    N      0
145288  2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [80]:
df.rename(columns={"Season":"Year","Wteam":"team","Wscore":"raj"},inplace=True)
df

        Year  Daynum  team  raj  Lteam  Lscore Wloc  Numot
0       1985      20  1228   81   1328      64    N      0
1       1985      25  1106   77   1354      70    H      0
2       1985      25  1112   63   1223      56    H      0
3       1985      25  1165   70   1432      54    H      0
4       1985      25  1192   86   1447      74    H      0
...      ...     ...   ...  ...    ...     ...  ...    ...
145284  2016     132  1114   70   1419      50    N      0
145285  2016     132  1163   72   1272      58    N      0
145286  2016     132  1246   82   1401      77    N      1
145287  2016     132  1277   66   1345      62    N      0
145288  2016     132  1386   87   1433      74    N      0

[145289 rows x 8 columns]

In [90]:
df["New_year"]=df['Year']+10

In [91]:
df

        Year  Daynum  team  raj  Lteam  Lscore  New_year
0       1985      20  1228   81   1328      64      1995
1       1985      25  1106   77   1354      70      1995
2       1985      25  1112   63   1223      56      1995
3       1985      25  1165   70   1432      54      1995
4       1985      25  1192   86   1447      74      1995
...      ...     ...   ...  ...    ...     ...       ...
145284  2016     132  1114   70   1419      50      2026
145285  2016     132  1163   72   1272      58      2026
145286  2016     132  1246   82   1401      77      2026
145287  2016     132  1277   66   1345      62      2026
145288  2016     132  1386   87   1433      74      2026

[145289 rows x 7 columns]

In [92]:
#to set any coulmns
df.set_index('Year')

      Daynum  team  raj  Lteam  Lscore  New_year
Year
1985      20  1228   81   1328      64      1995
1985      25  1106   77   1354      70      1995
1985      25  1112   63   1223      56      1995
1985      25  1165   70   1432      54      1995
1985      25  1192   86   1447      74      1995
...      ...   ...  ...    ...     ...       ...
2016     132  1114   70   1419      50      2026
2016     132  1163   72   1272      58      2026
2016     132  1246   82   1401      77      2026
2016     132  1277   66   1345      62      2026
2016     132  1386   87   1433      74      2026

[145289 rows x 6 columns]

In [93]:
df.set_index('Year',inplace=True)

In [94]:
df

      Daynum  team  raj  Lteam  Lscore  New_year
Year
1985      20  1228   81   1328      64      1995
1985      25  1106   77   1354      70      1995
1985      25  1112   63   1223      56      1995
1985      25  1165   70   1432      54      1995
1985      25  1192   86   1447      74      1995
...      ...   ...  ...    ...     ...       ...
2016     132  1114   70   1419      50      2026
2016     132  1163   72   1272      58      2026
2016     132  1246   82   1401      77      2026
2016     132  1277   66   1345      62      2026
2016     132  1386   87   1433      74      2026

[145289 rows x 6 columns]

In [96]:
df.reset_index(inplace=True)

In [97]:
df

        Year  Daynum  team  raj  Lteam  Lscore  New_year
0       1985      20  1228   81   1328      64      1995
1       1985      25  1106   77   1354      70      1995
2       1985      25  1112   63   1223      56      1995
3       1985      25  1165   70   1432      54      1995
4       1985      25  1192   86   1447      74      1995
...      ...     ...   ...  ...    ...     ...       ...
145284  2016     132  1114   70   1419      50      2026
145285  2016     132  1163   72   1272      58      2026
145286  2016     132  1246   82   1401      77      2026
145287  2016     132  1277   66   1345      62      2026
145288  2016     132  1386   87   1433      74      2026

[145289 rows x 7 columns]

In [98]:
#to rename the index
df.rename(index={0:"Bhopal"},inplace=True)

In [99]:
df

        Year  Daynum  team  raj  Lteam  Lscore  New_year
Bhopal  1985      20  1228   81   1328      64      1995
1       1985      25  1106   77   1354      70      1995
2       1985      25  1112   63   1223      56      1995
3       1985      25  1165   70   1432      54      1995
4       1985      25  1192   86   1447      74      1995
...      ...     ...   ...  ...    ...     ...       ...
145284  2016     132  1114   70   1419      50      2026
145285  2016     132  1163   72   1272      58      2026
145286  2016     132  1246   82   1401      77      2026
145287  2016     132  1277   66   1345      62      2026
145288  2016     132  1386   87   1433      74      2026

[145289 rows x 7 columns]

In [3]:
x={'Id':[1,2,3,4],"Name":['ram','shyam','sanyam','priyam'],'Age':[20,21,22,23]}

In [4]:
x=pd.DataFrame(x)

In [5]:
x

   Id    Name  Age
0   1     ram   20
1   2   shyam   21
2   3  sanyam   22
3   4  priyam   23

In [6]:
y={'Id':[3,4,5,6],"City":['Bhopal','Indore','Bhopal','Goa'],'Salary':[10,20,30,40]}

In [7]:
y=pd.DataFrame(y)

In [8]:
y

   Id    City  Salary
0   3  Bhopal      10
1   4  Indore      20
2   5  Bhopal      30
3   6     Goa      40

In [9]:
a=pd.concat([x,y],axis=0)

In [10]:
a

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0     NaN     NaN
3   4  priyam  23.0     NaN     NaN
0   3     NaN   NaN  Bhopal    10.0
1   4     NaN   NaN  Indore    20.0
2   5     NaN   NaN  Bhopal    30.0
3   6     NaN   NaN     Goa    40.0

In [11]:
b=pd.concat([x,y],axis=0,ignore_index=True)

In [12]:
b

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0     NaN     NaN
3   4  priyam  23.0     NaN     NaN
4   3     NaN   NaN  Bhopal    10.0
5   4     NaN   NaN  Indore    20.0
6   5     NaN   NaN  Bhopal    30.0
7   6     NaN   NaN     Goa    40.0

In [13]:
a=pd.concat([x,y],axis=1)

In [14]:
a

   Id    Name  Age  Id    City  Salary
0   1     ram   20   3  Bhopal      10
1   2   shyam   21   4  Indore      20
2   3  sanyam   22   5  Bhopal      30
3   4  priyam   23   6     Goa      40

In [15]:
b=pd.concat([x,y],axis=0,keys=["x","y"])

In [16]:
b

     Id    Name   Age    City  Salary
x 0   1     ram  20.0     NaN     NaN
  1   2   shyam  21.0     NaN     NaN
  2   3  sanyam  22.0     NaN     NaN
  3   4  priyam  23.0     NaN     NaN
y 0   3     NaN   NaN  Bhopal    10.0
  1   4     NaN   NaN  Indore    20.0
  2   5     NaN   NaN  Bhopal    30.0
  3   6     NaN   NaN     Goa    40.0

In [17]:
x._append(y)

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0     NaN     NaN
3   4  priyam  23.0     NaN     NaN
0   3     NaN   NaN  Bhopal    10.0
1   4     NaN   NaN  Indore    20.0
2   5     NaN   NaN  Bhopal    30.0
3   6     NaN   NaN     Goa    40.0

In [18]:
x

   Id    Name  Age
0   1     ram   20
1   2   shyam   21
2   3  sanyam   22
3   4  priyam   23

In [19]:
y

   Id    City  Salary
0   3  Bhopal      10
1   4  Indore      20
2   5  Bhopal      30
3   6     Goa      40

In [20]:
inner=pd.merge(x,y,on='Id',how='inner')

In [21]:
inner

   Id    Name  Age    City  Salary
0   3  sanyam   22  Bhopal      10
1   4  priyam   23  Indore      20

In [22]:
Left=pd.merge(x,y,on='Id',how='left')

In [23]:
Left

   Id    Name  Age    City  Salary
0   1     ram   20     NaN     NaN
1   2   shyam   21     NaN     NaN
2   3  sanyam   22  Bhopal    10.0
3   4  priyam   23  Indore    20.0

In [24]:
right=pd.merge(x,y,on='Id',how='right')

In [25]:
right

   Id    Name   Age    City  Salary
0   3  sanyam  22.0  Bhopal      10
1   4  priyam  23.0  Indore      20
2   5     NaN   NaN  Bhopal      30
3   6     NaN   NaN     Goa      40

In [26]:
outer=pd.merge(x,y,on='Id',how='outer')
outer

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0  Bhopal    10.0
3   4  priyam  23.0  Indore    20.0
4   5     NaN   NaN  Bhopal    30.0
5   6     NaN   NaN     Goa    40.0

In [27]:
x

   Id    Name  Age
0   1     ram   20
1   2   shyam   21
2   3  sanyam   22
3   4  priyam   23

In [28]:
outer

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0  Bhopal    10.0
3   4  priyam  23.0  Indore    20.0
4   5     NaN   NaN  Bhopal    30.0
5   6     NaN   NaN     Goa    40.0

In [29]:
inner

   Id    Name  Age    City  Salary
0   3  sanyam   22  Bhopal      10
1   4  priyam   23  Indore      20

In [30]:
outer['Last_name']='Sharma'

In [31]:
outer

   Id    Name   Age    City  Salary Last_name
0   1     ram  20.0     NaN     NaN    Sharma
1   2   shyam  21.0     NaN     NaN    Sharma
2   3  sanyam  22.0  Bhopal    10.0    Sharma
3   4  priyam  23.0  Indore    20.0    Sharma
4   5     NaN   NaN  Bhopal    30.0    Sharma
5   6     NaN   NaN     Goa    40.0    Sharma

In [32]:
outer['full_name']=outer['Name']+outer['Last_name']

In [33]:
outer

   Id    Name   Age    City  Salary Last_name     full_name
0   1     ram  20.0     NaN     NaN    Sharma     ramSharma
1   2   shyam  21.0     NaN     NaN    Sharma   shyamSharma
2   3  sanyam  22.0  Bhopal    10.0    Sharma  sanyamSharma
3   4  priyam  23.0  Indore    20.0    Sharma  priyamSharma
4   5     NaN   NaN  Bhopal    30.0    Sharma           NaN
5   6     NaN   NaN     Goa    40.0    Sharma           NaN

In [34]:
outer.fillna('x',inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_27268\895014583.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'x' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  outer.fillna('x',inplace=True)

In [35]:
outer

   Id    Name   Age    City Salary Last_name     full_name
0   1     ram  20.0       x      x    Sharma     ramSharma
1   2   shyam  21.0       x      x    Sharma   shyamSharma
2   3  sanyam  22.0  Bhopal   10.0    Sharma  sanyamSharma
3   4  priyam  23.0  Indore   20.0    Sharma  priyamSharma
4   5       x     x  Bhopal   30.0    Sharma             x
5   6       x     x     Goa   40.0    Sharma             x

In [36]:
outer['Name']=outer['Name'].replace("x","SHAYAM")

In [37]:
outer

   Id    Name   Age    City Salary Last_name     full_name
0   1     ram  20.0       x      x    Sharma     ramSharma
1   2   shyam  21.0       x      x    Sharma   shyamSharma
2   3  sanyam  22.0  Bhopal   10.0    Sharma  sanyamSharma
3   4  priyam  23.0  Indore   20.0    Sharma  priyamSharma
4   5  SHAYAM     x  Bhopal   30.0    Sharma             x
5   6  SHAYAM     x     Goa   40.0    Sharma             x

In [38]:
outer.drop(columns=['Name','Last_name'],inplace=True)

In [39]:
outer

   Id   Age    City Salary     full_name
0   1  20.0       x      x     ramSharma
1   2  21.0       x      x   shyamSharma
2   3  22.0  Bhopal   10.0  sanyamSharma
3   4  23.0  Indore   20.0  priyamSharma
4   5     x  Bhopal   30.0             x
5   6     x     Goa   40.0             x