In [1]:
#EDA PROJECT ON CARS DATASET
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("Cars (1).csv")

In [3]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,New_Price,Price
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,12.05 kmpl,2179 CC,120 bhp,Black/Silver,8.0,5.0,NaN,6.00
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,21.1 kmpl,998 CC,100 bhp,Others,5.0,4.0,NaN,8.32
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,11.68 kmpl,2498 CC,112 bhp,White,7.0,5.0,NaN,4.00
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,24.0 kmpl,1120 CC,70 bhp,White,5.0,4.0,NaN,3.49
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,Others,8.0,5.0,NaN,6.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5956,Honda Civic,Pune,2011.0,47000.0,Petrol,Automatic,Second,13.9 kmpl,1799 CC,130.3 bhp,Others,5.0,4.0,NaN,4.50
5957,Hyundai i20,Delhi,2013.0,63777.0,Petrol,Manual,First,18.5 kmpl,1197 CC,82.9 bhp,Black/Silver,5.0,4.0,NaN,3.67
5958,Maruti Swift,Coimbatore,2016.0,37806.0,Petrol,Manual,First,20.4 kmpl,1197 CC,81.80 bhp,Black/Silver,5.0,4.0,NaN,5.20
5959,Mercedes-Benz SLK-Class,Coimbatore,2016.0,22732.0,Petrol,Automatic,First,18.1 kmpl,3498 CC,306 bhp,Black/Silver,2.0,2.0,NaN,55.54
5960,Hyundai i10,Kolkata,2016.0,7000.0,Petrol,Manual,First,20.36 kmpl,1197 CC,78.9 bhp,White,5.0,4.0,NaN,3.60

In [4]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,New_Price,Price
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,12.05 kmpl,2179 CC,120 bhp,Black/Silver,8.0,5.0,NaN,6.00
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,21.1 kmpl,998 CC,100 bhp,Others,5.0,4.0,NaN,8.32
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,11.68 kmpl,2498 CC,112 bhp,White,7.0,5.0,NaN,4.00
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,24.0 kmpl,1120 CC,70 bhp,White,5.0,4.0,NaN,3.49
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,Others,8.0,5.0,NaN,6.40

In [5]:
df.tail()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,New_Price,Price
5956,Honda Civic,Pune,2011.0,47000.0,Petrol,Automatic,Second,13.9 kmpl,1799 CC,130.3 bhp,Others,5.0,4.0,NaN,4.50
5957,Hyundai i20,Delhi,2013.0,63777.0,Petrol,Manual,First,18.5 kmpl,1197 CC,82.9 bhp,Black/Silver,5.0,4.0,NaN,3.67
5958,Maruti Swift,Coimbatore,2016.0,37806.0,Petrol,Manual,First,20.4 kmpl,1197 CC,81.80 bhp,Black/Silver,5.0,4.0,NaN,5.20
5959,Mercedes-Benz SLK-Class,Coimbatore,2016.0,22732.0,Petrol,Automatic,First,18.1 kmpl,3498 CC,306 bhp,Black/Silver,2.0,2.0,NaN,55.54
5960,Hyundai i10,Kolkata,2016.0,7000.0,Petrol,Manual,First,20.36 kmpl,1197 CC,78.9 bhp,White,5.0,4.0,NaN,3.60

In [6]:
df.sample(5)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,New_Price,Price
3601,Honda Jazz,Mumbai,2018.0,3000.0,Petrol,Automatic,First,19.0 kmpl,1199 CC,88.7 bhp,Others,5.0,4.0,10.81 Lakh,8.25
4183,BMW X5,Chennai,2016.0,45000.0,Diesel,Automatic,First,15.97 kmpl,2993 CC,258 bhp,White,5.0,4.0,NaN,57.00
737,Toyota Innova,Bangalore,2017.0,53841.0,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,Others,7.0,4.0,28.05 Lakh,20.50
1585,Volkswagen Ameo,Kochi,2018.0,31426.0,Diesel,Manual,First,21.66 kmpl,1498 CC,108.62 bhp,Black/Silver,5.0,4.0,9.72 Lakh,7.90
852,Chevrolet Aveo,Coimbatore,2010.0,64236.0,Petrol,Manual,First,14.7 kmpl,1150 CC,76 bhp,White,5.0,4.0,NaN,2.44

In [7]:
df.shape

(5961, 15)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5961 entries, 0 to 5960
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               5961 non-null   object
 1   Location           5950 non-null   object
 2   Year               5959 non-null   float64
 3   Kilometers_Driven  5953 non-null   float64
 4   Fuel_Type          5961 non-null   object
 5   Transmission       5934 non-null   object
 6   Owner_Type         5946 non-null   object
 7   Mileage            5959 non-null   object
 8   Engine             5944 non-null   object
 9   Power              5929 non-null   object
 10  Colour             5950 non-null   object
 11  Seats              5956 non-null   float64
 12  No. of Doors       5960 non-null   float64
 13  New_Price          824 non-null    object
 14  Price              5961 non-null   float64
dtypes: float64(5), object(10)
memory usage: 698.7+ KB

In [9]:
df.describe()

              Year  Kilometers_Driven        Seats  No. of Doors        Price
count  5959.000000       5.953000e+03  5956.000000   5960.000000  5961.000000
mean   2013.389159       5.871110e+04     5.269140      4.114933     9.528103
std       3.243051       9.171221e+04     0.789048      0.344757    11.214382
min    1998.000000       1.710000e+02     2.000000      2.000000     0.440000
25%    2011.500000       3.393100e+04     5.000000      4.000000     3.500000
50%    2014.000000       5.300000e+04     5.000000      4.000000     5.660000
75%    2016.000000       7.300000e+04     5.000000      4.000000    10.000000
max    2019.000000       6.500000e+06    10.000000      5.000000   160.000000

In [10]:
df.isnull().sum()

Name                    0
Location               11
Year                    2
Kilometers_Driven       8
Fuel_Type               0
Transmission           27
Owner_Type             15
Mileage                 2
Engine                 17
Power                  32
Colour                 11
Seats                   5
No. of Doors            1
New_Price            5137
Price                   0
dtype: int64

In [11]:
df.drop(columns=["New_Price"],inplace = True)

In [12]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,Price
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,12.05 kmpl,2179 CC,120 bhp,Black/Silver,8.0,5.0,6.00
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,21.1 kmpl,998 CC,100 bhp,Others,5.0,4.0,8.32
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,11.68 kmpl,2498 CC,112 bhp,White,7.0,5.0,4.00
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,24.0 kmpl,1120 CC,70 bhp,White,5.0,4.0,3.49
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,Others,8.0,5.0,6.40

In [13]:
#spliting the mileage column into mileage_value and mileage unit
df[['Mileage_value', 'Mileage_unit']] = df['Mileage'].str.extract(r'(\d+\.?\d*)\s*(.*)', expand=True)

In [14]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,12.05 kmpl,2179 CC,120 bhp,Black/Silver,8.0,5.0,6.00,12.05,kmpl
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,21.1 kmpl,998 CC,100 bhp,Others,5.0,4.0,8.32,21.1,kmpl
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,11.68 kmpl,2498 CC,112 bhp,White,7.0,5.0,4.00,11.68,kmpl
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,24.0 kmpl,1120 CC,70 bhp,White,5.0,4.0,3.49,24.0,kmpl
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,Others,8.0,5.0,6.40,12.8,kmpl

In [15]:
df[['Engine_value', 'Engine_unit']] = df['Engine'].str.extract(r'(\d+\.?\d*)\s*(.*)', expand=True)

In [16]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,12.05 kmpl,2179 CC,120 bhp,Black/Silver,8.0,5.0,6.00,12.05,kmpl,2179,CC
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,21.1 kmpl,998 CC,100 bhp,Others,5.0,4.0,8.32,21.1,kmpl,998,CC
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,11.68 kmpl,2498 CC,112 bhp,White,7.0,5.0,4.00,11.68,kmpl,2498,CC
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,24.0 kmpl,1120 CC,70 bhp,White,5.0,4.0,3.49,24.0,kmpl,1120,CC
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,Others,8.0,5.0,6.40,12.8,kmpl,2494,CC

In [17]:
df[['power_value', 'power_unit']] = df['Power'].str.extract(r'(\d+\.?\d*)\s*(.*)', expand=True)

In [18]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit,power_value,power_unit
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,12.05 kmpl,2179 CC,120 bhp,Black/Silver,8.0,5.0,6.00,12.05,kmpl,2179,CC,120,bhp
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,21.1 kmpl,998 CC,100 bhp,Others,5.0,4.0,8.32,21.1,kmpl,998,CC,100,bhp
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,11.68 kmpl,2498 CC,112 bhp,White,7.0,5.0,4.00,11.68,kmpl,2498,CC,112,bhp
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,24.0 kmpl,1120 CC,70 bhp,White,5.0,4.0,3.49,24.0,kmpl,1120,CC,70,bhp
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,Others,8.0,5.0,6.40,12.8,kmpl,2494,CC,102,bhp

In [19]:
df.drop(columns=["Power","Engine","Mileage"],inplace=True)

In [20]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit,power_value,power_unit
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,Black/Silver,8.0,5.0,6.00,12.05,kmpl,2179,CC,120,bhp
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,Others,5.0,4.0,8.32,21.1,kmpl,998,CC,100,bhp
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,White,7.0,5.0,4.00,11.68,kmpl,2498,CC,112,bhp
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,White,5.0,4.0,3.49,24.0,kmpl,1120,CC,70,bhp
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,Others,8.0,5.0,6.40,12.8,kmpl,2494,CC,102,bhp

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5961 entries, 0 to 5960
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               5961 non-null   object
 1   Location           5950 non-null   object
 2   Year               5959 non-null   float64
 3   Kilometers_Driven  5953 non-null   float64
 4   Fuel_Type          5961 non-null   object
 5   Transmission       5934 non-null   object
 6   Owner_Type         5946 non-null   object
 7   Colour             5950 non-null   object
 8   Seats              5956 non-null   float64
 9   No. of Doors       5960 non-null   float64
 10  Price              5961 non-null   float64
 11  Mileage_value      5959 non-null   object
 12  Mileage_unit       5959 non-null   object
 13  Engine_value       5944 non-null   object
 14  Engine_unit        5944 non-null   object
 15  power_value        5826 non-null   object
 16  power_unit         5826 non-null   object
dtypes: float64(5), object(12)
memory usage: 791.8+ KB

In [22]:
#converting mileage engine power value into numeric
df['Mileage_value']=df['Mileage_value'].astype('float')

In [23]:
df['Engine_value']=df['Engine_value'].astype('float')

In [24]:
df["power_value"]=pd.to_numeric(df["power_value"],errors="coerce")

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5961 entries, 0 to 5960
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               5961 non-null   object
 1   Location           5950 non-null   object
 2   Year               5959 non-null   float64
 3   Kilometers_Driven  5953 non-null   float64
 4   Fuel_Type          5961 non-null   object
 5   Transmission       5934 non-null   object
 6   Owner_Type         5946 non-null   object
 7   Colour             5950 non-null   object
 8   Seats              5956 non-null   float64
 9   No. of Doors       5960 non-null   float64
 10  Price              5961 non-null   float64
 11  Mileage_value      5959 non-null   float64
 12  Mileage_unit       5959 non-null   object
 13  Engine_value       5944 non-null   float64
 14  Engine_unit        5944 non-null   object
 15  power_value        5826 non-null   float64
 16  power_unit         5826 non-null   object
dtypes: float64(8), object(9)
memory usage: 791.8+ KB

In [26]:
df[df.duplicated()==True]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit,power_value,power_unit
5648,Maruti Alto,Hyderabad,2007.0,52195.0,Petrol,Manual,First,Others,5.0,4.0,1.75,19.70,kmpl,796.0,CC,46.3,bhp
5779,Maruti Baleno,Kolkata,2016.0,29000.0,Diesel,Manual,First,Black/Silver,5.0,4.0,6.50,27.39,kmpl,1248.0,CC,74.0,bhp

In [27]:
df.drop_duplicates(inplace=True)

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.isnull().sum()

Name                   0
Location              11
Year                   2
Kilometers_Driven      8
Fuel_Type              0
Transmission          27
Owner_Type            15
Colour                11
Seats                  5
No. of Doors           1
Price                  0
Mileage_value          2
Mileage_unit           2
Engine_value          17
Engine_unit           17
power_value          135
power_unit           135
dtype: int64

In [30]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit,power_value,power_unit
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,Black/Silver,8.0,5.0,6.00,12.05,kmpl,2179.0,CC,120.0,bhp
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,Others,5.0,4.0,8.32,21.10,kmpl,998.0,CC,100.0,bhp
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,White,7.0,5.0,4.00,11.68,kmpl,2498.0,CC,112.0,bhp
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,White,5.0,4.0,3.49,24.00,kmpl,1120.0,CC,70.0,bhp
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,Others,8.0,5.0,6.40,12.80,kmpl,2494.0,CC,102.0,bhp

In [31]:
meidan_col = ["Kilometers_Driven"]
cat_col=["Location","Year","Transmission","Owner_Type","Colour","Seats","No. of Doors"]

In [32]:
df.isnull().sum()

Name                   0
Location              11
Year                   2
Kilometers_Driven      8
Fuel_Type              0
Transmission          27
Owner_Type            15
Colour                11
Seats                  5
No. of Doors           1
Price                  0
Mileage_value          2
Mileage_unit           2
Engine_value          17
Engine_unit           17
power_value          135
power_unit           135
dtype: int64

In [37]:
for i in df.columns:
    if i in meidan_col:
        df[i].fillna(df[i].median(),inplace =True)
    elif i in cat_col:
        df[i].fillna(df[i].mode()[0],inplace=True)
    else:
        continue

C:\Users\HP\AppData\Local\Temp\ipykernel_36364\1495394033.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_36364\1495394033.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].median(),inplace =True)
C:\Users\HP\AppData\Local\Temp\ipykernel_36364\1495394033.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)

In [38]:
df.isnull().sum()

Name                   0
Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Colour                 0
Seats                  0
No. of Doors           0
Price                  0
Mileage_value          2
Mileage_unit           2
Engine_value          17
Engine_unit           17
power_value          135
power_unit           135
dtype: int64

In [39]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit,power_value,power_unit
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,Black/Silver,8.0,5.0,6.00,12.05,kmpl,2179.0,CC,120.0,bhp
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,Others,5.0,4.0,8.32,21.10,kmpl,998.0,CC,100.0,bhp
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,White,7.0,5.0,4.00,11.68,kmpl,2498.0,CC,112.0,bhp
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,White,5.0,4.0,3.49,24.00,kmpl,1120.0,CC,70.0,bhp
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,Others,8.0,5.0,6.40,12.80,kmpl,2494.0,CC,102.0,bhp

In [40]:
df[df["Mileage_unit"].isnull()]

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit,power_value,power_unit
4027,Toyota Prius,Mumbai,2011.0,44000.0,Electric,Automatic,First,Others,5.0,4.0,12.75,NaN,NaN,1798.0,CC,73.0,bhp
5242,Mahindra E,Chennai,2016.0,50000.0,Electric,Automatic,First,White,5.0,4.0,13.00,NaN,NaN,72.0,CC,41.0,bhp

In [41]:
df["Mileage_unit"].mode()[0]

'kmpl'

In [42]:
df["Mileage_unit"].fillna(df["Mileage_unit"].mode()[0],inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_36364\3096972740.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Mileage_unit"].fillna(df["Mileage_unit"].mode()[0],inplace=True)

In [43]:
df["Mileage_unit"].isnull().sum()

np.int64(0)

In [44]:
a = df.groupby("Mileage_unit")["Mileage_value"].mean().values[1]

In [45]:
df["Mileage_value"].fillna(a,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_36364\874576225.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Mileage_value"].fillna(a,inplace=True)

In [49]:
unit = ["Engine_unit","power_unit"]
median = ["power_value","Engine_value"]

In [50]:
for i in df.columns:
    if i in unit:
        df[i].fillna(df[i].mode()[0],inplace=True)
    elif i in median:
        df[i].fillna(df[i].median(),inplace=True)
    else:
        continue

C:\Users\HP\AppData\Local\Temp\ipykernel_36364\3666615582.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_36364\3666615582.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_36364\3666615582.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].median(),inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_36364\3666615582.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)

In [51]:
df.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Colour               0
Seats                0
No. of Doors         0
Price                0
Mileage_value        0
Mileage_unit         0
Engine_value         0
Engine_unit          0
power_value          0
power_unit           0
dtype: int64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5959 entries, 0 to 5960
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               5959 non-null   object
 1   Location           5959 non-null   object
 2   Year               5959 non-null   float64
 3   Kilometers_Driven  5959 non-null   float64
 4   Fuel_Type          5959 non-null   object
 5   Transmission       5959 non-null   object
 6   Owner_Type         5959 non-null   object
 7   Colour             5959 non-null   object
 8   Seats              5959 non-null   float64
 9   No. of Doors       5959 non-null   float64
 10  Price              5959 non-null   float64
 11  Mileage_value      5959 non-null   float64
 12  Mileage_unit       5959 non-null   object
 13  Engine_value       5959 non-null   float64
 14  Engine_unit        5959 non-null   object
 15  power_value        5959 non-null   float64
 16  power_unit         5959 non-null   object
dtypes: float64(8), object(9)
memory usage: 838.0+ KB

In [53]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Colour,Seats,No. of Doors,Price,Mileage_value,Mileage_unit,Engine_value,Engine_unit,power_value,power_unit
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,Black/Silver,8.0,5.0,6.00,12.05,kmpl,2179.0,CC,120.0,bhp
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,Others,5.0,4.0,8.32,21.10,kmpl,998.0,CC,100.0,bhp
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,White,7.0,5.0,4.00,11.68,kmpl,2498.0,CC,112.0,bhp
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,White,5.0,4.0,3.49,24.00,kmpl,1120.0,CC,70.0,bhp
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,Others,8.0,5.0,6.40,12.80,kmpl,2494.0,CC,102.0,bhp

In [59]:
df[['Company_Name', 'Model_Name']] = df['Name'].str.split(' ',n=1,expand = True)

In [64]:
df[["Company_Name","Model_Name"]]

       Company_Name Model_Name
0          Mahindra    Scorpio
1            Maruti     Baleno
2          Mahindra       Xylo
3           Hyundai      Grand
4            Toyota     Innova
...             ...        ...
5956          Honda      Civic
5957        Hyundai        i20
5958         Maruti      Swift
5959  Mercedes-Benz  SLK-Class
5960        Hyundai        i10

[5959 rows x 2 columns]

In [60]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Colour,Seats,No. of Doors,...,Engine_value,Engine_unit,power_value,power_unit,Name_value,Name_unit,Name_model,Name_company,Company_Name,Model_Name
0,Mahindra Scorpio,Pune,2012.0,99000.0,Diesel,Manual,Third,Black/Silver,8.0,5.0,...,2179.0,CC,120.0,bhp,NaN,NaN,NaN,NaN,Mahindra,Scorpio
1,Maruti Baleno,Kochi,2018.0,18678.0,Petrol,Manual,First,Others,5.0,4.0,...,998.0,CC,100.0,bhp,NaN,NaN,NaN,NaN,Maruti,Baleno
2,Mahindra Xylo,Bangalore,2013.0,197000.0,Diesel,Manual,First,White,7.0,5.0,...,2498.0,CC,112.0,bhp,NaN,NaN,NaN,NaN,Mahindra,Xylo
3,Hyundai Grand,Delhi,2014.0,45000.0,Diesel,Manual,First,White,5.0,4.0,...,1120.0,CC,70.0,bhp,NaN,NaN,NaN,NaN,Hyundai,Grand
4,Toyota Innova,Delhi,2011.0,65000.0,Diesel,Manual,First,Others,8.0,5.0,...,2494.0,CC,102.0,bhp,NaN,NaN,NaN,NaN,Toyota,Innova

In [61]:
df["Company_Name"].unique()

array(['Mahindra', 'Maruti', 'Hyundai', 'Toyota', 'Honda', 'Chevrolet',
       'Audi', 'Skoda', 'Renault', 'Land', 'BMW', 'ISUZU', 'Jaguar',
       'Mercedes-Benz', 'Volkswagen', 'Tata', 'Mitsubishi', 'Ford',
       'Nissan', 'Volvo', 'Fiat', 'Porsche', 'Mini', 'Datsun', 'Jeep',
       'Force', 'Isuzu', 'Smart', 'Lamborghini', 'Bentley'], dtype=object)

In [62]:
df["Model_Name"].unique()

array(['Scorpio', 'Baleno', 'Xylo', 'Grand', 'Innova', 'WRV', 'Verna',
       'Fortuner', 'Beat', 'A6', 'i20', 'Laura', 'City', 'Q7', 'Duster',
       'Ertiga', 'Rover Freelander', 'Rapid', 'Zen', '3', 'Wagon', 'Jazz',
       'Vitara', 'D-MAX', 'SX4', 'i10', 'Amaze', 'Xcent', 'F', 'C-Class',
       'Polo', '5', 'Thar', 'Alto', 'A3', 'Xenon', 'X1', 'Getz', 'Vento',
       'Sail', 'Jetta', 'Ciaz', 'CR-V', 'XUV500', 'New', 'Civic',
       'Superb', 'Ritz', 'Pajero', 'Corolla', 'Elantra', 'Figo', 'EON',
       'Teana', 'Swift', 'CLA', 'Rover Range', 'Q3', 'Fiesta', 'Indica',
       'Ecosport', 'S80', 'Fabia', 'A4', 'E-Class', 'Brio',
       'Rover Discovery', 'Ikon', 'Santa', 'Bolero', 'Dzire', 'KWID',
       'Celerio', 'Optra', 'GLC', 'X3', 'Micra', 'Etios', 'Creta',
       'Endeavour', '7', 'X5', 'Octavia', 'Zest', 'Scala', 'B',
       'EcoSport', 'TUV', 'Hexa', 'Elite', 'Accent', 'GLE', 'Linea',
       'Omni', 'Q5', 'Passat', 'Panamera', 'BRV', 'Cooper', 'Indigo',
       'A-Star', 'Nano', 'Santro', 'Tiguan', 'R-Class', 'Accord', 'GO',
       'Aspire', 'Camry', 'Cruze', 'Sunny', 'redi-GO', 'Compass', 'RS5',
       'S60', 'Punto', 'XC60', 'Mobilio', 'Manza', 'S', 'Eeco', 'GLA',
       'Bolt', '6', 'Grande', 'Esteem', 'M-Class', 'TT', 'Yeti', 'Ameo',
       'Logan', 'Pulse', 'Ignis', 'GL-Class', 'XF', 'Lancer', 'SLC',
       'Cayenne', 'A', 'Avventura', 'Safari', 'Terrano', '800', 'S-Class',
       'Aveo', 'Mustang', 'V40', 'A7', 'Sumo', 'One', 'Tiago', 'Verito',
       'CLS-Class', 'Platinum', 'SLK-Class', 'X-Trail', 'Z4', 'Cedia',
       'XJ', 'Enjoy', 'XUV300', 'Cayman', 'Spark', 'KUV', 'Sonata',
       'Quanto', 'Renault', 'CrossPolo', 'Captur', 'SL-Class', 'Jeep',
       'S-Cross', 'Fluence', 'Fusion', 'MUX', 'X6', 'Qualis', '1000',
       'Outlander', 'Ssangyong', 'Fortwo', 'Koleos', 'Tigor', 'GLS',
       'Evalia', 'Nexon', 'BR-V', 'XE', '1', 'Freestyle', 'Siena',
       'Classic', 'WR-V', 'NuvoSport', 'Gallardo', 'Montero', 'Redi',
       'Countryman', 'Prius', 'Petra', 'XC90', 'Tucson', 'A8', 'Beetle',
       'Continental', 'Captiva', 'Clubman', 'Boxster', 'E'], dtype=object)

In [63]:
df["Model_Name"] = df["Model_Name"].str.replace("Rover","")

In [65]:
df["Model_Name"] = df["Model_Name"].str.replace("Range","Range rover")

In [66]:
df["Model_Name"].unique()

array(['Scorpio', 'Baleno', 'Xylo', 'Grand', 'Innova', 'WRV', 'Verna',
       'Fortuner', 'Beat', 'A6', 'i20', 'Laura', 'City', 'Q7', 'Duster',
       'Ertiga', ' Freelander', 'Rapid', 'Zen', '3', 'Wagon', 'Jazz',
       'Vitara', 'D-MAX', 'SX4', 'i10', 'Amaze', 'Xcent', 'F', 'C-Class',
       'Polo', '5', 'Thar', 'Alto', 'A3', 'Xenon', 'X1', 'Getz', 'Vento',
       'Sail', 'Jetta', 'Ciaz', 'CR-V', 'XUV500', 'New', 'Civic',
       'Superb', 'Ritz', 'Pajero', 'Corolla', 'Elantra', 'Figo', 'EON',
       'Teana', 'Swift', 'CLA', ' Range rover', 'Q3', 'Fiesta', 'Indica',
       'Ecosport', 'S80', 'Fabia', 'A4', 'E-Class', 'Brio', ' Discovery',
       'Ikon', 'Santa', 'Bolero', 'Dzire', 'KWID', 'Celerio', 'Optra',
       'GLC', 'X3', 'Micra', 'Etios', 'Creta', 'Endeavour', '7', 'X5',
       'Octavia', 'Zest', 'Scala', 'B', 'EcoSport', 'TUV', 'Hexa',
       'Elite', 'Accent', 'GLE', 'Linea', 'Omni', 'Q5', 'Passat',
       'Panamera', 'BRV', 'Cooper', 'Indigo', 'A-Star', 'Nano', 'Santro',
       'Tiguan', 'R-Class', 'Accord', 'GO', 'Aspire', 'Camry', 'Cruze',
       'Sunny', 'redi-GO', 'Compass', 'RS5', 'S60', 'Punto', 'XC60',
       'Mobilio', 'Manza', 'S', 'Eeco', 'GLA', 'Bolt', '6', 'Grande',
       'Esteem', 'M-Class', 'TT', 'Yeti', 'Ameo', 'Logan', 'Pulse',
       'Ignis', 'GL-Class', 'XF', 'Lancer', 'SLC', 'Cayenne', 'A',
       'Avventura', 'Safari', 'Terrano', '800', 'S-Class', 'Aveo',
       'Mustang', 'V40', 'A7', 'Sumo', 'One', 'Tiago', 'Verito',
       'CLS-Class', 'Platinum', 'SLK-Class', 'X-Trail', 'Z4', 'Cedia',
       'XJ', 'Enjoy', 'XUV300', 'Cayman', 'Spark', 'KUV', 'Sonata',
       'Quanto', 'Renault', 'CrossPolo', 'Captur', 'SL-Class', 'Jeep',
       'S-Cross', 'Fluence', 'Fusion', 'MUX', 'X6', 'Qualis', '1000',
       'Outlander', 'Ssangyong', 'Fortwo', 'Koleos', 'Tigor', 'GLS',
       'Evalia', 'Nexon', 'BR-V', 'XE', '1', 'Freestyle', 'Siena',
       'Classic', 'WR-V', 'NuvoSport', 'Gallardo', 'Montero', 'Redi',
       'Countryman', 'Prius', 'Petra', 'XC90', 'Tucson', 'A8', 'Beetle',
       'Continental', 'Captiva', 'Clubman', 'Boxster', 'E'], dtype=object)

In [68]:
#number of cars by location
df["Location"].value_counts()

Location
Mumbai        792
Hyderabad     738
Kochi         646
Coimbatore    630
Pune          611
Delhi         549
Kolkata       525
Chennai       489
Jaipur        406
Bangalore     351
Ahmedabad     222
Name: count, dtype: int64

In [69]:
df["Location"].value_counts().head()

Location
Mumbai        792
Hyderabad     738
Kochi         646
Coimbatore    630
Pune          611
Name: count, dtype: int64

In [70]:
#no of cars by year
df["Year"].value_counts()

Year
2014.0    795
2016.0    739
2015.0    736
2013.0    642
2017.0    586
2012.0    573
2011.0    461
2010.0    338
2018.0    298
2009.0    196
2008.0    170
2007.0    122
2019.0    101
2006.0     75
2005.0     55
2004.0     28
2002.0     14
2003.0     13
2001.0      7
2000.0      4
1998.0      4
1999.0      2
Name: count, dtype: int64

In [71]:
df["Year"].nunique()

22

In [74]:
df["Fuel_Type"].value_counts()

Fuel_Type
Diesel      3187
Petrol      2704
CNG           56
LPG           10
Electric       2
Name: count, dtype: int64

In [75]:
df["Transmission"].value_counts()

Transmission
Manual       4250
Automatic    1709
Name: count, dtype: int64

In [76]:
df["Owner_Type"].value_counts()

Owner_Type
First             4888
Second             953
Third              110
Fourth & Above       8
Name: count, dtype: int64

In [77]:
df["Seats"].value_counts()

Seats
5.0     5016
7.0      674
8.0      117
4.0       99
6.0       31
2.0       17
10.0       3
9.0        2
Name: count, dtype: int64

In [78]:
df["Colour"].value_counts()

Colour
White           2126
Others          1986
Black/Silver    1847
Name: count, dtype: int64

In [79]:
df["No. of Doors"].value_counts()

No. of Doors
4.0    5223
5.0     719
2.0      17
Name: count, dtype: int64

In [80]:
df["Company_Name"].value_counts()

Company_Name
Maruti           1187
Hyundai          1100
Honda             601
Toyota            410
Mercedes-Benz     318
Volkswagen        315
Ford              298
Mahindra          272
BMW               267
Audi              236
Tata              184
Skoda             173
Renault           143
Chevrolet         113
Nissan             91
Land               57
Jaguar             40
Mitsubishi         27
Mini               26
Fiat               25
Volvo              21
Porsche            18
Jeep               15
Datsun             13
Force               3
ISUZU               2
Isuzu               1
Smart               1
Lamborghini         1
Bentley             1
Name: count, dtype: int64

In [81]:
df["Company_Name"].value_counts().head()

Company_Name
Maruti           1187
Hyundai          1100
Honda             601
Toyota            410
Mercedes-Benz     318
Name: count, dtype: int64

In [82]:
df["Model_Name"].value_counts()

Model_Name
Swift          343
City           265
i20            247
Verna          170
Innova         164
              ...
Beetle           1
Continental      1
Clubman          1
Boxster          1
E                1
Name: count, Length: 209, dtype: int64

In [83]:
df["Model_Name"].value_counts().head()

Model_Name
Swift     343
City      265
i20       247
Verna     170
Innova    164
Name: count, dtype: int64

In [87]:
b = df.groupby("Company_Name")["Price"].mean()

In [88]:
b

Company_Name
Audi              25.537712
BMW               25.243146
Bentley           59.000000
Chevrolet          2.944248
Datsun             3.049231
Fiat               3.340800
Force              9.333333
Ford               6.900067
Honda              5.430948
Hyundai            5.363673
ISUZU             12.045000
Isuzu             20.000000
Jaguar            37.632250
Jeep              18.718667
Lamborghini      120.000000
Land              39.861053
Mahindra           8.045919
Maruti             4.556664
Mercedes-Benz     26.809874
Mini              26.896923
Mitsubishi        11.058889
Nissan             4.738352
Porsche           48.348333
Renault            5.773986
Skoda              7.559075
Smart              3.000000
Tata               3.559457
Toyota            11.601073
Volkswagen         5.307270
Volvo             18.802857
Name: Price, dtype: float64

In [91]:
df.groupby("Company_Name")["Price"].mean().head(5)

Company_Name
Audi         25.537712
BMW          25.243146
Bentley      59.000000
Chevrolet     2.944248
Datsun        3.049231
Name: Price, dtype: float64

In [92]:
df.groupby("Company_Name")["Price"].mean().tail(5)

Company_Name
Smart          3.000000
Tata           3.559457
Toyota        11.601073
Volkswagen     5.307270
Volvo         18.802857
Name: Price, dtype: float64

In [93]:
df.groupby("Location")["Price"].mean()

Location
Ahmedabad      8.505586
Bangalore     13.498291
Chennai        7.810204
Coimbatore    15.114524
Delhi          9.759617
Hyderabad      9.808672
Jaipur         5.881429
Kochi         11.220944
Kolkata        5.667848
Mumbai         9.445732
Pune           6.761424
Name: Price, dtype: float64

In [94]:
df.groupby("Company_Name")["Price"].mean().sort_values().tail(5)

Company_Name
Jaguar          37.632250
Land            39.861053
Porsche         48.348333
Bentley         59.000000
Lamborghini    120.000000
Name: Price, dtype: float64

In [95]:
df.groupby("Location")["Price"].mean().sort_values().head(5)

Location
Kolkata      5.667848
Jaipur       5.881429
Pune         6.761424
Chennai      7.810204
Ahmedabad    8.505586
Name: Price, dtype: float64

In [99]:
df.groupby("Model_Name")["Mileage_value"].max().sort_values().tail(5)

Model_Name
Dzire      28.40
Swift      28.40
Celerio    31.79
Alto       33.44
Wagon      33.54
Name: Mileage_value, dtype: float64

In [ ]:
bbb