In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_json("D:\Myfile.json")

In [4]:
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [5]:
df1=pd.read_json('Myfile.json')

In [6]:
df1

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [7]:
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [8]:
df['class'].unique()

array(['Four', 'Three', 'Fifth', 'Five', 'Six', 'Seven', 'Nine', 'Eight'],
      dtype=object)

In [9]:
df['class'].nunique()

8

In [10]:
df.gender.value_counts()

gender
male      18
female    17
Name: count, dtype: int64

In [11]:
df.nlargest(3,'mark')

    id       name  class  mark  gender
32  33  Kenn Rein    Six    96  female
11  12      Recky    Six    94  female
31  32  Binn Rott  Seven    90  female

In [12]:
df.nsmallest(4,'mark')

    id       name  class  mark gender
18  19      Tinny   Nine    18   male
16  17      Tumyu    Six    54   male
2    3     Arnold  Three    55   male
5    6  Alex John   Four    55   male

# Read json file from loc. other than current working directory

In [13]:
df2=pd.read_json("D:\Myfile.json")

In [14]:
df2

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

# Read json from load function

In [15]:
f=open('Myfile.json')

In [16]:
import json

In [17]:
df3=json.load(f)

In [18]:
data=pd.DataFrame(df3)

In [19]:
data

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

# Read json file from web

In [20]:
df4=pd.read_json('https://www.plus2net.com/php_tutorial/student.json')

In [21]:
df4

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow    Six    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [22]:
for i in df3:
    print(i)

{'id': 1, 'name': 'John Deo', 'class': 'Four', 'mark': 75, 'gender': 'female'}
{'id': 2, 'name': 'Max Ruin', 'class': 'Three', 'mark': 85, 'gender': 'male'}
{'id': 3, 'name': 'Arnold', 'class': 'Three', 'mark': 55, 'gender': 'male'}
{'id': 4, 'name': 'Krish Star', 'class': 'Four', 'mark': 60, 'gender': 'female'}
{'id': 5, 'name': 'John Mike', 'class': 'Four', 'mark': 60, 'gender': 'female'}
{'id': 6, 'name': 'Alex John', 'class': 'Four', 'mark': 55, 'gender': 'male'}
{'id': 7, 'name': 'My John Rob', 'class': 'Fifth', 'mark': 78, 'gender': 'male'}
{'id': 8, 'name': 'Asruid', 'class': 'Five', 'mark': 85, 'gender': 'male'}
{'id': 9, 'name': 'Tes Qry', 'class': 'Six', 'mark': 78, 'gender': 'male'}
{'id': 10, 'name': 'Big John', 'class': 'Four', 'mark': 55, 'gender': 'female'}
{'id': 11, 'name': 'Ronald', 'class': 'Six', 'mark': 89, 'gender': 'female'}
{'id': 12, 'name': 'Recky', 'class': 'Six', 'mark': 94, 'gender': 'female'}
{'id': 13, 'name': 'Kty', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
{'id': 14, 'name': 'Bigy', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
{'id': 15, 'name': 'Tade Row', 'class': 'Four', 'mark': 88, 'gender': 'male'}
{'id': 16, 'name': 'Gimmy', 'class': 'Four', 'mark': 88, 'gender': 'male'}
{'id': 17, 'name': 'Tumyu', 'class': 'Six', 'mark': 54, 'gender': 'male'}
{'id': 18, 'name': 'Honny', 'class': 'Five', 'mark': 75, 'gender': 'male'}
{'id': 19, 'name': 'Tinny', 'class': 'Nine', 'mark': 18, 'gender': 'male'}
{'id': 20, 'name': 'Jackly', 'class': 'Nine', 'mark': 65, 'gender': 'female'}
{'id': 21, 'name': 'Babby John', 'class': 'Four', 'mark': 69, 'gender': 'female'}
{'id': 22, 'name': 'Reggid', 'class': 'Seven', 'mark': 55, 'gender': 'female'}
{'id': 23, 'name': 'Herod', 'class': 'Eight', 'mark': 79, 'gender': 'male'}
{'id': 24, 'name': 'Tiddy Now', 'class': 'Seven', 'mark': 78, 'gender': 'male'}
{'id': 25, 'name': 'Giff Tow', 'class': 'Six', 'mark': 88, 'gender': 'male'}
{'id': 26, 'name': 'Crelea', 'class': 'Seven', 'mark': 79, 'gender': 'male'}
{'id': 27, 'name': 'Big Nose', 'class': 'Three', 'mark': 81, 'gender': 'female'}
{'id': 28, 'name': 'Rojj Base', 'class': 'Seven', 'mark': 86, 'gender': 'female'}
{'id': 29, 'name': 'Tess Played', 'class': 'Seven', 'mark': 55, 'gender': 'male'}
{'id': 30, 'name': 'Reppy Red', 'class': 'Six', 'mark': 79, 'gender': 'female'}
{'id': 31, 'name': 'Marry Toeey', 'class': 'Four', 'mark': 88, 'gender': 'male'}
{'id': 32, 'name': 'Binn Rott', 'class': 'Seven', 'mark': 90, 'gender': 'female'}
{'id': 33, 'name': 'Kenn Rein', 'class': 'Six', 'mark': 96, 'gender': 'female'}
{'id': 34, 'name': 'Gain Toe', 'class': 'Seven', 'mark': 69, 'gender': 'male'}
{'id': 35, 'name': 'Rows Noump', 'class': 'Six', 'mark': 88, 'gender': 'female'}

# Create json from dictionary

In [23]:
my_dict={
    'Name':['Rahul','Anurag','Veer'],
    'ID':[1,2,3],
    'Marks_in_M1':[54,61,49],
    'Marks_in_M2':[49,55,48]
}

In [24]:
df5=pd.DataFrame(my_dict)

In [25]:
df5

     Name  ID  Marks_in_M1  Marks_in_M2
0   Rahul   1           54           49
1  Anurag   2           61           55
2    Veer   3           49           48

In [26]:
df_j=df5.to_json()

In [27]:
df_j

'{"Name":{"0":"Rahul","1":"Anurag","2":"Veer"},"ID":{"0":1,"1":2,"2":3},"Marks_in_M1":{"0":54,"1":61,"2":49},"Marks_in_M2":{"0":49,"1":55,"2":48}}'

In [28]:
df_j=df5.to_json(orient='split')

In [29]:
df_j

'{"columns":["Name","ID","Marks_in_M1","Marks_in_M2"],"index":[0,1,2],"data":[["Rahul",1,54,49],["Anurag",2,61,55],["Veer",3,49,48]]}'

In [30]:
df6=pd.read_json(df_j)
df6

ValueError: All arrays must be of the same length

In [31]:
df6=pd.read_json(df_j,orient='split')
df6

     Name  ID  Marks_in_M1  Marks_in_M2
0   Rahul   1           54           49
1  Anurag   2           61           55
2    Veer   3           49           48

In [32]:
df_j1=df6.to_json()
df_j1

'{"Name":{"0":"Rahul","1":"Anurag","2":"Veer"},"ID":{"0":1,"1":2,"2":3},"Marks_in_M1":{"0":54,"1":61,"2":49},"Marks_in_M2":{"0":49,"1":55,"2":48}}'

In [33]:
df7=pd.read_json(df_j1)

In [34]:
df7

     Name  ID  Marks_in_M1  Marks_in_M2
0   Rahul   1           54           49
1  Anurag   2           61           55
2    Veer   3           49           48

In [35]:
df_j2=df7.to_json(orient='index')
df_j2

'{"0":{"Name":"Rahul","ID":1,"Marks_in_M1":54,"Marks_in_M2":49},"1":{"Name":"Anurag","ID":2,"Marks_in_M1":61,"Marks_in_M2":55},"2":{"Name":"Veer","ID":3,"Marks_in_M1":49,"Marks_in_M2":48}}'

In [36]:
df8=pd.read_json(df_j2)
df8

                 0       1     2
Name         Rahul  Anurag  Veer
ID               1       2     3
Marks_in_M1     54      61    49
Marks_in_M2     49      55    48

In [37]:
df8=pd.read_json(df_j2,orient='index')
df8

     Name  ID  Marks_in_M1  Marks_in_M2
0   Rahul   1           54           49
1  Anurag   2           61           55
2    Veer   3           49           48

In [38]:
df_j3=df8.to_json(orient='records')
df_j3

'[{"Name":"Rahul","ID":1,"Marks_in_M1":54,"Marks_in_M2":49},{"Name":"Anurag","ID":2,"Marks_in_M1":61,"Marks_in_M2":55},{"Name":"Veer","ID":3,"Marks_in_M1":49,"Marks_in_M2":48}]'

In [39]:
df9=pd.read_json(df_j3)
df9

     Name  ID  Marks_in_M1  Marks_in_M2
0   Rahul   1           54           49
1  Anurag   2           61           55
2    Veer   3           49           48

In [40]:
df_j4=df9.to_json(orient='columns')
df_j4

'{"Name":{"0":"Rahul","1":"Anurag","2":"Veer"},"ID":{"0":1,"1":2,"2":3},"Marks_in_M1":{"0":54,"1":61,"2":49},"Marks_in_M2":{"0":49,"1":55,"2":48}}'

In [41]:
df10=pd.read_json(df_j4,orient='records')
df10

     Name  ID  Marks_in_M1  Marks_in_M2
0   Rahul   1           54           49
1  Anurag   2           61           55
2    Veer   3           49           48

In [42]:
df_j5=df10.to_json()
df_j5

'{"Name":{"0":"Rahul","1":"Anurag","2":"Veer"},"ID":{"0":1,"1":2,"2":3},"Marks_in_M1":{"0":54,"1":61,"2":49},"Marks_in_M2":{"0":49,"1":55,"2":48}}'

In [43]:
df11=pd.read_json(df_j5)
df11

     Name  ID  Marks_in_M1  Marks_in_M2
0   Rahul   1           54           49
1  Anurag   2           61           55
2    Veer   3           49           48

In [44]:
df_j5=df10.to_json(orient='values')
df_j5

'[["Rahul",1,54,49],["Anurag",2,61,55],["Veer",3,49,48]]'

In [45]:
df11=pd.read_json(df_j5,orient='values')
df11

        0  1   2   3
0   Rahul  1  54  49
1  Anurag  2  61  55
2    Veer  3  49  48

# Pandas have a nice inbuilt fuction called json_normalize() to flatten the simple to moderately semi-structured nested JSON structures to flat tables.

In [46]:
df = pd.DataFrame({
    'student_id': [1, 2, 3],
    'student_name': ['Alice', 'Bob', 'Chris'],
    'student_info': [
        {'gender': 'F', 'age': 20},
        {'gender': 'M', 'age': 22},
        {'gender': 'M', 'age': 33}
    ]
})

In [47]:
df2=pd.json_normalize(df['student_info'])

In [48]:
df2

  gender  age
0      F   20
1      M   22
2      M   33

In [49]:
df3=pd.concat([df,df2],axis=1)

In [50]:
df3

   student_id student_name                student_info gender  age
0           1        Alice  {'gender': 'F', 'age': 20}      F   20
1           2          Bob  {'gender': 'M', 'age': 22}      M   22
2           3        Chris  {'gender': 'M', 'age': 33}      M   33

In [51]:
df3.drop(columns='student_info',inplace=True)

In [52]:
df3

   student_id student_name gender  age
0           1        Alice      F   20
1           2          Bob      M   22
2           3        Chris      M   33