## import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("employee_data_200.csv")

In [3]:
df.shape

(250, 10)

In [4]:
df.ndim

2

In [9]:
df.columns

Index(['EmpId', 'FirstNme', 'LstName', 'Dept', 'Positon', 'Slary', 'HireDat',
       'BrthDate', 'Phne', 'Emil'],
      dtype='object')

1. Load the CSV file employee_data_200.csv into a DataFrame

2. Display the first 10 rows of the DataFrame.

3. Display the last 10 rows of the DataFrame.

4. Display the name of all Department.

5. Display the name of all Position.

6. Rename the columns to their correct names: EmployeeID, FirstName, LastName, Department, Position, Salary, HireDate, BirthDate,
   Phone, Email.

7. Insert Full_Name column between LastName and Department.

8. Add three columns(Len_First, Len_Last, Len_Dept) which show lenght of FirstName , LastName and Department columns.

9. Add new column category which is based on salary column. If salary value is =>90000 then category column must show OFFICER-  LEVEL1, If salary value is less than 90000 and =>75000 then category column must show OFFICER-LEVEL2, If salary value is less than 75000 and =>50000 then category column must show OFFICER-LEVEL3, If salary value is less than <50000 then category column must show TEMPERORY.

10. Display column name with index number of column.

11. Display rows from index number 45 to 79 of the DataFrame.

12. Display Full_Name of employee which is on 6th row of the DataFrame.

13. Display all rows from index 65 to end of dataframe.

14. Display rows from index number 5 to 10 for Full_Name, Salary and Dept columns of the DataFrame.

15. Get a summary of the DataFrame, including data types and missing values.

16. Display the summary of DataFrame which shows all detail except column names.

17. Display the summary of DataFrame which shows all detail except memory use.

18. Identify and remove duplicate rows from  DataFrame and keep last value of duplicate row. Index of result must be start from 0.

19. Delete Len_First column.

20. Delete Len_Last and Len_Dept column.

21. Insert three columns A, B and C at 0,1 and 2 index position with static value 5,6 and 7.

22. Delete three columns A, B and C using range() method.

23. Filter the DataFrame to show only employees in the IT department.

24. Filter the DataFrame to show only employees with a salary greater than $75,000.

25. Convert HireDate and BirthDate columns to datetime format.

26. Calculate the tenure of each employee in years (from HireDate to the current date).

27. Calculate the highest salary of the 5 employees.

28. Calculate the lowest salary of the 5 employees.

29. Calculate the average salary of the employees.

30. Find the highest and lowest salary in the DataFrame.

31. Delete rows where employee salary is less than 50000.

32. Create dataframe using sales file which is on https://raw.githubusercontent.com/ffzs/dataset/master/sales.csv

33. Find out duplicate rows based on the value of 'ORDERDATE' and 'AMOUNTINFO' columns

34. Delete rows where 'ORDERDATE' and 'AMOUNTINFO' columns values are duplicate

35. select 120 random rows from dataframe.

36. Select 25% random rows from dataframe.

37. Select 3 random columns from dataframe

In [12]:
df.head(10)

,EmpId,FirstNme,LstName,Dept,Positon,Slary,HireDat,BrthDate,Phne,Emil
0,45,John,Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com
1,48,John,Smith,Sales,Consultant,57951,2018-03-27,1977-01-26,555-8765,john.doe@example.com
2,65,Jane,Smith,Finance,Manager,93005,2016-11-24,1989-12-05,555-8765,john.doe@example.com
3,68,Bob,Doe,HR,Developer,68007,2016-07-08,1974-02-01,555-3456,jane.smith@example.com
4,68,John,Williams,IT,Developer,56091,2020-09-14,1980-04-25,555-5678,jane.smith@example.com
5,10,Alice,Doe,HR,Developer,84381,2015-12-22,1973-02-28,555-1234,jane.smith@example.com
6,84,Jane,Brown,Finance,Coordinator,91470,2019-09-17,1991-06-13,555-8765,jane.smith@example.com
7,22,Jane,Smith,HR,Consultant,57581,2019-09-27,1996-12-23,555-8765,david.brown@example.com
8,37,David,Brown,HR,Consultant,72111,2015-03-23,1974-07-23,555-5678,john.doe@example.com
9,88,John,Doe,Marketing,Analyst,78782,2020-09-17,1979-05-17,555-4321,jane.smith@example.com

In [14]:
df.tail(10)

,EmpId,FirstNme,LstName,Dept,Positon,Slary,HireDat,BrthDate,Phne,Emil
240,33,Jane,Williams,IT,Developer,60525,2016-01-13,1993-10-03,555-5678,alice.williams@example.com
241,22,Jane,Brown,Finance,Coordinator,91847,2016-05-13,1996-08-30,555-5678,bob.johnson@example.com
242,100,Alice,Smith,IT,Manager,75983,2015-01-17,1992-12-16,555-1234,bob.johnson@example.com
243,38,David,Williams,Marketing,Coordinator,89855,2020-07-16,1983-08-24,555-5678,bob.johnson@example.com
244,4,John,Johnson,Finance,Developer,80642,2015-07-01,1992-01-01,555-4321,alice.williams@example.com
245,95,Bob,Brown,Marketing,Analyst,55912,2020-03-08,1973-03-21,555-5678,jane.smith@example.com
246,37,John,Doe,Sales,Coordinator,94503,2018-01-28,1976-05-02,555-1234,jane.smith@example.com
247,48,Alice,Smith,IT,Developer,74354,2015-04-27,1984-10-07,555-5678,alice.williams@example.com
248,99,Jane,Brown,IT,Developer,70594,2018-05-19,1998-03-16,555-5678,john.doe@example.com
249,30,David,Johnson,Finance,Coordinator,66138,2017-10-25,1978-10-17,555-3456,alice.williams@example.com

In [16]:
df.columns.values.tolist()

['EmpId',
 'FirstNme',
 'LstName',
 'Dept',
 'Positon',
 'Slary',
 'HireDat',
 'BrthDate',
 'Phne',
 'Emil']

In [17]:
df.Dept.unique()

array(['IT', 'Sales', 'Finance', 'HR', 'Marketing'], dtype=object)

In [18]:
df.Positon.unique()

array(['Consultant', 'Manager', 'Developer', 'Coordinator', 'Analyst'],
      dtype=object)

In [19]:
df.Dept.nunique()

5

In [20]:
df.Positon.nunique()

5

In [22]:
df.columns

Index(['EmpId', 'FirstNme', 'LstName', 'Dept', 'Positon', 'Slary', 'HireDat',
       'BrthDate', 'Phne', 'Emil'],
      dtype='object')

In [23]:
df.columns = 'EmployeeID', 'FirstName', 'LastName', 'Department', 'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email'

In [25]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'Department', 'Position',
       'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email'],
      dtype='object')

In [29]:
for i,j in enumerate(df.columns):
    print(i, " ",j)

0   EmployeeID
1   FirstName
2   LastName
3   Department
4   Position
5   Salary
6   HireDate
7   BirthDate
8   Phone
9   Email

In [34]:
df.insert(3,'FullName',df.FirstName+' '+df.LastName)

In [36]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'FullName', 'Department',
       'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email'],
      dtype='object')

In [38]:
df['Len_First'] = df.FirstName.str.len()
df['Len_Last'] = df.LastName.str.len()
df['Len_Dept'] = df.Department.str.len()

In [40]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'FullName', 'Department',
       'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email',
       'Len_First', 'Len_Last', 'Len_Dept'],
      dtype='object')

In [42]:
cat = []
for i in df.Salary:
    if i>=90000:
        cat.append('OFFICER_LEVEL1')
    elif i>=75000:
        cat.append('OFFICER_LEVEL2')
    elif i>=50000:
        cat.append('OFFICER_LEVEL3')
    else:
        cat.append('Temporary')
        
df['Category'] = cat

In [44]:
df[['Salary','Category']].sort_values('Salary',ascending=False)

     Salary        Category
125   99317  OFFICER_LEVEL1
208   99212  OFFICER_LEVEL1
146   99212  OFFICER_LEVEL1
87    99083  OFFICER_LEVEL1
239   99083  OFFICER_LEVEL1
..      ...             ...
23    51344  OFFICER_LEVEL3
108   51064  OFFICER_LEVEL3
102   51004  OFFICER_LEVEL3
209   50611  OFFICER_LEVEL3
35    50611  OFFICER_LEVEL3

[250 rows x 2 columns]

In [46]:
df.iloc[45:80,]

,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Len_First,Len_Last,Len_Dept,Category
45,33,Jane,Williams,Jane Williams,IT,Developer,60525,2016-01-13,1993-10-03,555-5678,alice.williams@example.com,4,8,2,OFFICER_LEVEL3
46,32,David,Williams,David Williams,Finance,Developer,62902,2015-08-20,1976-01-09,555-5678,john.doe@example.com,5,8,7,OFFICER_LEVEL3
47,75,Bob,Johnson,Bob Johnson,Finance,Consultant,84427,2017-01-07,1975-12-11,555-5678,jane.smith@example.com,3,7,7,OFFICER_LEVEL2
48,24,Bob,Smith,Bob Smith,Sales,Analyst,90094,2017-05-31,1975-11-01,555-1234,alice.williams@example.com,3,5,5,OFFICER_LEVEL1
49,36,John,Doe,John Doe,Finance,Analyst,71707,2017-09-21,1984-04-19,555-4321,bob.johnson@example.com,4,3,7,OFFICER_LEVEL3
50,76,Jane,Brown,Jane Brown,Sales,Developer,79122,2019-12-26,1970-03-31,555-4321,bob.johnson@example.com,4,5,5,OFFICER_LEVEL2
51,56,John,Smith,John Smith,IT,Analyst,57484,2020-10-17,1994-06-26,555-3456,alice.williams@example.com,4,5,2,OFFICER_LEVEL3
52,29,David,Brown,David Brown,Finance,Consultant,77271,2019-11-24,1978-09-21,555-8765,david.brown@example.com,5,5,7,OFFICER_LEVEL2
53,35,John,Brown,John Brown,HR,Manager,89603,2016-01-06,1992-11-08,555-1234,alice.williams@example.com,4,5,2,OFFICER_LEVEL2
54,1,Alice,Johnson,Alice Johnson,Finance,Coordinator,56388,2018-10-30,1991-12-18,555-4321,john.doe@example.com,5,7,7,OFFICER_LEVEL3
55,1,Bob,Doe,Bob Doe,Sales,Consultant,93593,2019-05-04,1974-03-18,555-5678,jane.smith@example.com,3,3,5,OFFICER_LEVEL1
56,37,John,Doe,John Doe,Sales,Coordinator,94503,2018-01-28,1976-05-02,555-1234,jane.smith@example.com,4,3,5,OFFICER_LEVEL1
57,54,John,Williams,John Williams,HR,Developer,64272,2019-05-25,1975-02-17,555-1234,jane.smith@example.com,4,8,2,OFFICER_LEVEL3
58,6,Jane,Smith,Jane Smith,HR,Manager,79073,2020-06-08,1984-03-12,555-5678,jane.smith@example.com,4,5,2,OFFICER_LEVEL2
59,39,Jane,Smith,Jane Smith,Sales,Consultant,96760,2019-06-24,1976-04-14,555-3456,david.brown@example.com,4,5,5,OFFICER_LEVEL1
60,18,John,Doe,John Doe,Sales,Analyst,66627,2020-10-20,1986-04-22,555-4321,bob.johnson@example.com,4,3,5,OFFICER_LEVEL3
61,80,Alice,Brown,Alice Brown,Finance,Manager,85349,2015-05-10,1979-10-18,555-8765,bob.johnson@example.com,5,5,7,OFFICER_LEVEL2
62,5,John,Williams,John Williams,Sales,Consultant,80302,2015-07-19,1992-07-30,555-3456,alice.williams@example.com,4,8,5,OFFICER_LEVEL2
63,43,Alice,Williams,Alice Williams,HR,Manager,97002,2018-01-29,1973-08-09,555-8765,jane.smith@example.com,5,8,2,OFFICER_LEVEL1
64,59,John,Brown,John Brown,Finance,Developer,85983,2018-12-06,1992-06-25,555-8765,bob.johnson@example.com,4,5,7,OFFICER_LEVEL2
65,32,David,Williams,David Williams,Sales,Analyst,85568,2015-04-07,1972-10-04,555-4321,john.doe@example.com,5,8,5,OFFICER_LEVEL2
66,2,David,Brown,David Brown,IT,Coordinator,96865,2019-04-29,1980-05-09,555-1234,alice.williams@example.com,5,5,2,OFFICER_LEVEL1
67,66,John,Williams,John Williams,HR,Coordinator,72794,2018-08-18,1983-03-14,555-5678,david.brown@example.com,4,8,2,OFFICER_LEVEL3
68,42,Jane,Doe,Jane Doe,IT,Coordinator,68065,2015-04-11,1988-07-26,555-8765,bob.johnson@example.com,4,3,2,OFFICER_LEVEL3
69,58,Alice,Williams,Alice Williams,Finance,Consultant,64467,2015-12-03,1984-06-25,555-3456,jane.smith@example.com,5,8,7,OFFICER_LEVEL3
70,36,David,Williams,David Williams,HR,Manager,82329,2015-04-23,1970-07-28,555-4321,david.brown@example.com,5,8,2,OFFICER_LEVEL2
71,12,Alice,Smith,Alice Smith,Finance,Analyst,67181,2017-06-08,1977-05-28,555-4321,john.doe@example.com,5,5,7,OFFICER_LEVEL3
72,47,Bob,Williams,Bob Williams,Marketing,Analyst,73747,2016-01-08,1976-02-12,555-3456,john.doe@example.com,3,8,9,OFFICER_LEVEL3
73,83,Jane,Brown,Jane Brown,HR,Consultant,87328,2019-02-15,1998-04-20,555-8765,john.doe@example.com,4,5,2,OFFICER_LEVEL2
74,92,Jane,Doe,Jane Doe,Finance,Analyst,85042,2017-05-25,1976-05-15,555-8765,david.brown@example.com,4,3,7,OFFICER_LEVEL2
75,1,Bob,Williams,Bob Williams,IT,Analyst,61908,2015-12-08,1973-11-17,555-8765,bob.johnson@example.com,3,8,2,OFFICER_LEVEL3
76,15,Jane,Doe,Jane Doe,Finance,Manager,75021,2017-10-23,1983-06-28,555-3456,bob.johnson@example.com,4,3,7,OFFICER_LEVEL2
77,100,David,Doe,David Doe,Sales,Manager,80554,2018-02-06,1997-08-03,555-8765,jane.smith@example.com,5,3,5,OFFICER_LEVEL2
78,54,Bob,Williams,Bob Williams,Sales,Manager,75700,2015-09-01,1973-04-08,555-3456,david.brown@example.com,3,8,5,OFFICER_LEVEL2
79,13,David,Smith,David Smith,IT,Consultant,97238,2016-01-10,1997-07-16,555-4321,bob.johnson@example.com,5,5,2,OFFICER_LEVEL1

In [48]:
df.iloc[65:,]

,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Len_First,Len_Last,Len_Dept,Category
65,32,David,Williams,David Williams,Sales,Analyst,85568,2015-04-07,1972-10-04,555-4321,john.doe@example.com,5,8,5,OFFICER_LEVEL2
66,2,David,Brown,David Brown,IT,Coordinator,96865,2019-04-29,1980-05-09,555-1234,alice.williams@example.com,5,5,2,OFFICER_LEVEL1
67,66,John,Williams,John Williams,HR,Coordinator,72794,2018-08-18,1983-03-14,555-5678,david.brown@example.com,4,8,2,OFFICER_LEVEL3
68,42,Jane,Doe,Jane Doe,IT,Coordinator,68065,2015-04-11,1988-07-26,555-8765,bob.johnson@example.com,4,3,2,OFFICER_LEVEL3
69,58,Alice,Williams,Alice Williams,Finance,Consultant,64467,2015-12-03,1984-06-25,555-3456,jane.smith@example.com,5,8,7,OFFICER_LEVEL3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,95,Bob,Brown,Bob Brown,Marketing,Analyst,55912,2020-03-08,1973-03-21,555-5678,jane.smith@example.com,3,5,9,OFFICER_LEVEL3
246,37,John,Doe,John Doe,Sales,Coordinator,94503,2018-01-28,1976-05-02,555-1234,jane.smith@example.com,4,3,5,OFFICER_LEVEL1
247,48,Alice,Smith,Alice Smith,IT,Developer,74354,2015-04-27,1984-10-07,555-5678,alice.williams@example.com,5,5,2,OFFICER_LEVEL3
248,99,Jane,Brown,Jane Brown,IT,Developer,70594,2018-05-19,1998-03-16,555-5678,john.doe@example.com,4,5,2,OFFICER_LEVEL3
249,30,David,Johnson,David Johnson,Finance,Coordinator,66138,2017-10-25,1978-10-17,555-3456,alice.williams@example.com,5,7,7,OFFICER_LEVEL3

In [50]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'FullName', 'Department',
       'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email',
       'Len_First', 'Len_Last', 'Len_Dept', 'Category'],
      dtype='object')

In [52]:
[(i,j) for i,j in enumerate(df.columns)]

[(0, 'EmployeeID'),
 (1, 'FirstName'),
 (2, 'LastName'),
 (3, 'FullName'),
 (4, 'Department'),
 (5, 'Position'),
 (6, 'Salary'),
 (7, 'HireDate'),
 (8, 'BirthDate'),
 (9, 'Phone'),
 (10, 'Email'),
 (11, 'Len_First'),
 (12, 'Len_Last'),
 (13, 'Len_Dept'),
 (14, 'Category')]

In [54]:
df.iloc[5:11,[1,3,6]]

   FirstName       FullName  Salary
5      Alice      Alice Doe   84381
6       Jane     Jane Brown   91470
7       Jane     Jane Smith   57581
8      David    David Brown   72111
9       John       John Doe   78782
10      John  John Williams   66082

In [56]:
df.at[6,'FullName']

'Jane Brown'

In [58]:
df.iloc[65,]

EmployeeID                      32
FirstName                    David
LastName                  Williams
FullName            David Williams
Department                   Sales
Position                   Analyst
Salary                       85568
HireDate                2015-04-07
BirthDate               1972-10-04
Phone                     555-4321
Email         john.doe@example.com
Len_First                        5
Len_Last                         8
Len_Dept                         5
Category            OFFICER_LEVEL2
Name: 65, dtype: object

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  250 non-null    int64
 1   FirstName   250 non-null    object
 2   LastName    250 non-null    object
 3   FullName    250 non-null    object
 4   Department  250 non-null    object
 5   Position    250 non-null    object
 6   Salary      250 non-null    int64
 7   HireDate    250 non-null    object
 8   BirthDate   250 non-null    object
 9   Phone       250 non-null    object
 10  Email       250 non-null    object
 11  Len_First   250 non-null    int64
 12  Len_Last    250 non-null    int64
 13  Len_Dept    250 non-null    int64
 14  Category    250 non-null    object
dtypes: int64(5), object(10)
memory usage: 29.4+ KB

In [62]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Columns: 15 entries, EmployeeID to Category
dtypes: int64(5), object(10)
memory usage: 29.4+ KB

In [64]:
df.info(memory_usage=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  250 non-null    int64
 1   FirstName   250 non-null    object
 2   LastName    250 non-null    object
 3   FullName    250 non-null    object
 4   Department  250 non-null    object
 5   Position    250 non-null    object
 6   Salary      250 non-null    int64
 7   HireDate    250 non-null    object
 8   BirthDate   250 non-null    object
 9   Phone       250 non-null    object
 10  Email       250 non-null    object
 11  Len_First   250 non-null    int64
 12  Len_Last    250 non-null    int64
 13  Len_Dept    250 non-null    int64
 14  Category    250 non-null    object
dtypes: int64(5), object(10)

In [66]:
df.duplicated().sum()

50

In [68]:
df.drop_duplicates(keep='last', ignore_index=True, inplace = True)

In [70]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'FullName', 'Department',
       'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email',
       'Len_First', 'Len_Last', 'Len_Dept', 'Category'],
      dtype='object')

In [72]:
del df['Len_First']

In [74]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'FullName', 'Department',
       'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email',
       'Len_Last', 'Len_Dept', 'Category'],
      dtype='object')

In [76]:
df.drop(columns=['Len_Last', 'Len_Dept'],inplace=True)

In [78]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'FullName', 'Department',
       'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email',
       'Category'],
      dtype='object')

In [80]:
df.insert(0,'A',5)
df.insert(1,'B',6)
df.insert(2,'C',7)

In [82]:
df.head()

,A,B,C,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category
0,5,6,7,45,John,Smith,John Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com,OFFICER_LEVEL3
1,5,6,7,68,Bob,Doe,Bob Doe,HR,Developer,68007,2016-07-08,1974-02-01,555-3456,jane.smith@example.com,OFFICER_LEVEL3
2,5,6,7,68,John,Williams,John Williams,IT,Developer,56091,2020-09-14,1980-04-25,555-5678,jane.smith@example.com,OFFICER_LEVEL3
3,5,6,7,10,Alice,Doe,Alice Doe,HR,Developer,84381,2015-12-22,1973-02-28,555-1234,jane.smith@example.com,OFFICER_LEVEL2
4,5,6,7,84,Jane,Brown,Jane Brown,Finance,Coordinator,91470,2019-09-17,1991-06-13,555-8765,jane.smith@example.com,OFFICER_LEVEL1

In [84]:
df.shape

(200, 15)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   A           200 non-null    int64
 1   B           200 non-null    int64
 2   C           200 non-null    int64
 3   EmployeeID  200 non-null    int64
 4   FirstName   200 non-null    object
 5   LastName    200 non-null    object
 6   FullName    200 non-null    object
 7   Department  200 non-null    object
 8   Position    200 non-null    object
 9   Salary      200 non-null    int64
 10  HireDate    200 non-null    object
 11  BirthDate   200 non-null    object
 12  Phone       200 non-null    object
 13  Email       200 non-null    object
 14  Category    200 non-null    object
dtypes: int64(5), object(10)
memory usage: 23.6+ KB

In [88]:
df.columns.values.tolist()

['A',
 'B',
 'C',
 'EmployeeID',
 'FirstName',
 'LastName',
 'FullName',
 'Department',
 'Position',
 'Salary',
 'HireDate',
 'BirthDate',
 'Phone',
 'Email',
 'Category']

In [90]:
df.isna().sum()

A             0
B             0
C             0
EmployeeID    0
FirstName     0
LastName      0
FullName      0
Department    0
Position      0
Salary        0
HireDate      0
BirthDate     0
Phone         0
Email         0
Category      0
dtype: int64

In [92]:
df[df.Department=='IT']

,A,B,C,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category
0,5,6,7,45,John,Smith,John Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com,OFFICER_LEVEL3
2,5,6,7,68,John,Williams,John Williams,IT,Developer,56091,2020-09-14,1980-04-25,555-5678,jane.smith@example.com,OFFICER_LEVEL3
7,5,6,7,71,John,Williams,John Williams,IT,Analyst,66082,2016-07-03,1970-07-04,555-4321,bob.johnson@example.com,OFFICER_LEVEL3
40,5,6,7,56,John,Smith,John Smith,IT,Analyst,57484,2020-10-17,1994-06-26,555-3456,alice.williams@example.com,OFFICER_LEVEL3
49,5,6,7,42,Jane,Doe,Jane Doe,IT,Coordinator,68065,2015-04-11,1988-07-26,555-8765,bob.johnson@example.com,OFFICER_LEVEL3
54,5,6,7,1,Bob,Williams,Bob Williams,IT,Analyst,61908,2015-12-08,1973-11-17,555-8765,bob.johnson@example.com,OFFICER_LEVEL3
56,5,6,7,13,David,Smith,David Smith,IT,Consultant,97238,2016-01-10,1997-07-16,555-4321,bob.johnson@example.com,OFFICER_LEVEL1
59,5,6,7,76,Alice,Johnson,Alice Johnson,IT,Analyst,52422,2015-07-30,1975-11-27,555-1234,bob.johnson@example.com,OFFICER_LEVEL3
65,5,6,7,16,Jane,Williams,Jane Williams,IT,Manager,69768,2018-12-14,1977-08-24,555-3456,bob.johnson@example.com,OFFICER_LEVEL3
76,5,6,7,36,John,Brown,John Brown,IT,Consultant,71511,2019-05-18,1995-10-30,555-4321,david.brown@example.com,OFFICER_LEVEL3
97,5,6,7,36,David,Smith,David Smith,IT,Coordinator,72448,2016-03-25,1996-11-03,555-4321,alice.williams@example.com,OFFICER_LEVEL3
103,5,6,7,82,John,Brown,John Brown,IT,Developer,98764,2016-03-13,1984-12-18,555-8765,john.doe@example.com,OFFICER_LEVEL1
104,5,6,7,51,John,Johnson,John Johnson,IT,Analyst,68931,2018-05-01,1974-04-15,555-1234,alice.williams@example.com,OFFICER_LEVEL3
108,5,6,7,59,Bob,Smith,Bob Smith,IT,Manager,71540,2015-12-04,1982-07-30,555-5678,john.doe@example.com,OFFICER_LEVEL3
109,5,6,7,66,Bob,Doe,Bob Doe,IT,Coordinator,78070,2019-05-28,1999-01-11,555-8765,alice.williams@example.com,OFFICER_LEVEL2
110,5,6,7,11,Jane,Doe,Jane Doe,IT,Developer,71262,2017-01-10,1981-07-01,555-4321,john.doe@example.com,OFFICER_LEVEL3
112,5,6,7,12,Alice,Doe,Alice Doe,IT,Manager,63304,2017-01-09,1992-05-26,555-4321,jane.smith@example.com,OFFICER_LEVEL3
121,5,6,7,78,Alice,Doe,Alice Doe,IT,Consultant,68973,2015-05-24,1988-03-30,555-4321,bob.johnson@example.com,OFFICER_LEVEL3
122,5,6,7,31,John,Brown,John Brown,IT,Developer,76865,2016-12-08,1972-08-06,555-3456,alice.williams@example.com,OFFICER_LEVEL2
128,5,6,7,73,John,Williams,John Williams,IT,Consultant,83537,2017-11-16,1998-05-04,555-8765,david.brown@example.com,OFFICER_LEVEL2
129,5,6,7,27,John,Williams,John Williams,IT,Analyst,54354,2019-06-08,1994-04-16,555-1234,david.brown@example.com,OFFICER_LEVEL3
138,5,6,7,78,John,Doe,John Doe,IT,Coordinator,84074,2020-11-06,1988-09-17,555-5678,john.doe@example.com,OFFICER_LEVEL2
145,5,6,7,61,David,Williams,David Williams,IT,Developer,85548,2017-05-20,1978-11-24,555-5678,john.doe@example.com,OFFICER_LEVEL2
153,5,6,7,2,David,Brown,David Brown,IT,Coordinator,96865,2019-04-29,1980-05-09,555-1234,alice.williams@example.com,OFFICER_LEVEL1
156,5,6,7,96,John,Smith,John Smith,IT,Manager,76637,2015-03-31,1985-03-14,555-3456,david.brown@example.com,OFFICER_LEVEL2
157,5,6,7,73,David,Brown,David Brown,IT,Developer,66620,2020-04-22,1996-03-21,555-4321,bob.johnson@example.com,OFFICER_LEVEL3
162,5,6,7,66,David,Brown,David Brown,IT,Manager,68775,2018-12-30,1984-04-06,555-4321,jane.smith@example.com,OFFICER_LEVEL3
163,5,6,7,37,David,Johnson,David Johnson,IT,Analyst,66419,2015-03-15,1990-03-28,555-1234,alice.williams@example.com,OFFICER_LEVEL3
165,5,6,7,48,David,Johnson,David Johnson,IT,Coordinator,96670,2018-02-28,1975-01-16,555-1234,john.doe@example.com,OFFICER_LEVEL1
169,5,6,7,14,Bob,Williams,Bob Williams,IT,Consultant,94304,2017-04-03,1985-09-28,555-3456,jane.smith@example.com,OFFICER_LEVEL1
170,5,6,7,33,Jane,Smith,Jane Smith,IT,Consultant,81943,2017-09-01,1981-01-25,555-3456,david.brown@example.com,OFFICER_LEVEL2
174,5,6,7,71,Alice,Doe,Alice Doe,IT,Coordinator,75909,2018-05-12,1986-04-03,555-3456,bob.johnson@example.com,OFFICER_LEVEL2
178,5,6,7,44,Alice,Johnson,Alice Johnson,IT,Coordinator,81337,2020-01-26,1983-11-19,555-1234,alice.williams@example.com,OFFICER_LEVEL2
182,5,6,7,5,David,Brown,David Brown,IT,Manager,84343,2020-09-30,1974-01-26,555-8765,david.brown@example.com,OFFICER_LEVEL2
190,5,6,7,33,Jane,Williams,Jane Williams,IT,Developer,60525,2016-01-13,1993-10-03,555-5678,alice.williams@example.com,OFFICER_LEVEL3
192,5,6,7,100,Alice,Smith,Alice Smith,IT,Manager,75983,2015-01-17,1992-12-16,555-1234,bob.johnson@example.com,OFFICER_LEVEL2
197,5,6,7,48,Alice,Smith,Alice Smith,IT,Developer,74354,2015-04-27,1984-10-07,555-5678,alice.williams@example.com,OFFICER_LEVEL3
198,5,6,7,99,Jane,Brown,Jane Brown,IT,Developer,70594,2018-05-19,1998-03-16,555-5678,john.doe@example.com,OFFICER_LEVEL3

In [94]:
df[df.Salary>=75000]

,A,B,C,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category
3,5,6,7,10,Alice,Doe,Alice Doe,HR,Developer,84381,2015-12-22,1973-02-28,555-1234,jane.smith@example.com,OFFICER_LEVEL2
4,5,6,7,84,Jane,Brown,Jane Brown,Finance,Coordinator,91470,2019-09-17,1991-06-13,555-8765,jane.smith@example.com,OFFICER_LEVEL1
8,5,6,7,89,Alice,Johnson,Alice Johnson,Sales,Coordinator,90580,2015-12-29,1989-12-05,555-3456,david.brown@example.com,OFFICER_LEVEL1
9,5,6,7,89,Bob,Smith,Bob Smith,HR,Coordinator,79212,2016-07-06,1983-11-23,555-5678,john.doe@example.com,OFFICER_LEVEL2
10,5,6,7,13,Alice,Brown,Alice Brown,HR,Consultant,76673,2020-03-18,1998-07-23,555-8765,david.brown@example.com,OFFICER_LEVEL2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,5,6,7,22,Jane,Brown,Jane Brown,Finance,Coordinator,91847,2016-05-13,1996-08-30,555-5678,bob.johnson@example.com,OFFICER_LEVEL1
192,5,6,7,100,Alice,Smith,Alice Smith,IT,Manager,75983,2015-01-17,1992-12-16,555-1234,bob.johnson@example.com,OFFICER_LEVEL2
193,5,6,7,38,David,Williams,David Williams,Marketing,Coordinator,89855,2020-07-16,1983-08-24,555-5678,bob.johnson@example.com,OFFICER_LEVEL2
194,5,6,7,4,John,Johnson,John Johnson,Finance,Developer,80642,2015-07-01,1992-01-01,555-4321,alice.williams@example.com,OFFICER_LEVEL2
196,5,6,7,37,John,Doe,John Doe,Sales,Coordinator,94503,2018-01-28,1976-05-02,555-1234,jane.smith@example.com,OFFICER_LEVEL1

In [96]:
df.Salary.mean()

75815.555

In [98]:
df.Salary.max()

99317

In [100]:
df.Salary.min()

50611

In [102]:
df.nlargest(5,['Salary'])

,A,B,C,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category
93,5,6,7,60,Jane,Williams,Jane Williams,HR,Coordinator,99317,2018-12-27,1993-07-18,555-5678,david.brown@example.com,OFFICER_LEVEL1
158,5,6,7,44,Alice,Johnson,Alice Johnson,Sales,Analyst,99212,2015-12-31,1993-04-14,555-1234,david.brown@example.com,OFFICER_LEVEL1
189,5,6,7,4,Alice,Doe,Alice Doe,Finance,Developer,99083,2016-06-23,1996-05-23,555-5678,alice.williams@example.com,OFFICER_LEVEL1
111,5,6,7,87,Alice,Williams,Alice Williams,Finance,Consultant,99075,2018-12-10,1979-02-22,555-4321,jane.smith@example.com,OFFICER_LEVEL1
87,5,6,7,78,Bob,Doe,Bob Doe,Marketing,Manager,98825,2016-04-29,1996-02-01,555-8765,john.doe@example.com,OFFICER_LEVEL1

In [104]:
df.HireDate.dtypes

dtype('O')

In [106]:
df.HireDate = pd.to_datetime(df.HireDate)

In [108]:
df.HireDate.dtypes

dtype('<M8[ns]')

In [110]:
df.BirthDate = pd.to_datetime(df.BirthDate)

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   A           200 non-null    int64
 1   B           200 non-null    int64
 2   C           200 non-null    int64
 3   EmployeeID  200 non-null    int64
 4   FirstName   200 non-null    object
 5   LastName    200 non-null    object
 6   FullName    200 non-null    object
 7   Department  200 non-null    object
 8   Position    200 non-null    object
 9   Salary      200 non-null    int64
 10  HireDate    200 non-null    datetime64[ns]
 11  BirthDate   200 non-null    datetime64[ns]
 12  Phone       200 non-null    object
 13  Email       200 non-null    object
 14  Category    200 non-null    object
dtypes: datetime64[ns](2), int64(5), object(8)
memory usage: 23.6+ KB

In [114]:
from datetime import date

In [116]:
date.today()

datetime.date(2024, 10, 19)

In [118]:
df['Experience'] = pd.Timestamp.now() - df.HireDate

In [120]:
df

,A,B,C,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category,Experience
0,5,6,7,45,John,Smith,John Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com,OFFICER_LEVEL3,2930 days 12:31:58.551064
1,5,6,7,68,Bob,Doe,Bob Doe,HR,Developer,68007,2016-07-08,1974-02-01,555-3456,jane.smith@example.com,OFFICER_LEVEL3,3025 days 12:31:58.551064
2,5,6,7,68,John,Williams,John Williams,IT,Developer,56091,2020-09-14,1980-04-25,555-5678,jane.smith@example.com,OFFICER_LEVEL3,1496 days 12:31:58.551064
3,5,6,7,10,Alice,Doe,Alice Doe,HR,Developer,84381,2015-12-22,1973-02-28,555-1234,jane.smith@example.com,OFFICER_LEVEL2,3224 days 12:31:58.551064
4,5,6,7,84,Jane,Brown,Jane Brown,Finance,Coordinator,91470,2019-09-17,1991-06-13,555-8765,jane.smith@example.com,OFFICER_LEVEL1,1859 days 12:31:58.551064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,5,6,7,95,Bob,Brown,Bob Brown,Marketing,Analyst,55912,2020-03-08,1973-03-21,555-5678,jane.smith@example.com,OFFICER_LEVEL3,1686 days 12:31:58.551064
196,5,6,7,37,John,Doe,John Doe,Sales,Coordinator,94503,2018-01-28,1976-05-02,555-1234,jane.smith@example.com,OFFICER_LEVEL1,2456 days 12:31:58.551064
197,5,6,7,48,Alice,Smith,Alice Smith,IT,Developer,74354,2015-04-27,1984-10-07,555-5678,alice.williams@example.com,OFFICER_LEVEL3,3463 days 12:31:58.551064
198,5,6,7,99,Jane,Brown,Jane Brown,IT,Developer,70594,2018-05-19,1998-03-16,555-5678,john.doe@example.com,OFFICER_LEVEL3,2345 days 12:31:58.551064
199,5,6,7,30,David,Johnson,David Johnson,Finance,Coordinator,66138,2017-10-25,1978-10-17,555-3456,alice.williams@example.com,OFFICER_LEVEL3,2551 days 12:31:58.551064

In [122]:
pd.DatetimeIndex(df.HireDate).year

Int64Index([2016, 2016, 2020, 2015, 2019, 2019, 2015, 2016, 2015, 2016,
            ...
            2016, 2016, 2015, 2020, 2015, 2020, 2018, 2015, 2018, 2017],
           dtype='int64', name='HireDate', length=200)

In [124]:
df['Year'] = pd.Timestamp.now().year - pd.DatetimeIndex(df.HireDate).year

In [126]:
df['Month'] = pd.Timestamp.now().month - pd.DatetimeIndex(df.HireDate).month

In [128]:
df.head()

,A,B,C,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category,Experience,Year,Month
0,5,6,7,45,John,Smith,John Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com,OFFICER_LEVEL3,2930 days 12:31:58.551064,8,0
1,5,6,7,68,Bob,Doe,Bob Doe,HR,Developer,68007,2016-07-08,1974-02-01,555-3456,jane.smith@example.com,OFFICER_LEVEL3,3025 days 12:31:58.551064,8,3
2,5,6,7,68,John,Williams,John Williams,IT,Developer,56091,2020-09-14,1980-04-25,555-5678,jane.smith@example.com,OFFICER_LEVEL3,1496 days 12:31:58.551064,4,1
3,5,6,7,10,Alice,Doe,Alice Doe,HR,Developer,84381,2015-12-22,1973-02-28,555-1234,jane.smith@example.com,OFFICER_LEVEL2,3224 days 12:31:58.551064,9,-2
4,5,6,7,84,Jane,Brown,Jane Brown,Finance,Coordinator,91470,2019-09-17,1991-06-13,555-8765,jane.smith@example.com,OFFICER_LEVEL1,1859 days 12:31:58.551064,5,1

In [130]:
date.today()

datetime.date(2024, 10, 19)

In [132]:
df.columns

Index(['A', 'B', 'C', 'EmployeeID', 'FirstName', 'LastName', 'FullName',
       'Department', 'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone',
       'Email', 'Category', 'Experience', 'Year', 'Month'],
      dtype='object')

In [134]:
df.drop(columns=df.iloc[:,range(3)],inplace=True)

In [136]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'FullName', 'Department',
       'Position', 'Salary', 'HireDate', 'BirthDate', 'Phone', 'Email',
       'Category', 'Experience', 'Year', 'Month'],
      dtype='object')

### Pivot_table and Groupby

#### 1. To calculate maximum and min salary in each department.

In [142]:
df.pivot_table(index='Department',values = 'Salary', aggfunc=[np.max,np.min])

              max    min
           Salary Salary
Department
Finance     99083  52352
HR          99317  51344
IT          98764  52422
Marketing   98825  50611
Sales       99212  51064

In [144]:
#  Or
df.groupby('Department')['Salary'].agg([np.max,np.min])

              max    min
Department
Finance     99083  52352
HR          99317  51344
IT          98764  52422
Marketing   98825  50611
Sales       99212  51064

#### 2. To calculate maximum and min salary in each department by position.¶

In [148]:
df.head(1)

,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category,Experience,Year,Month
0,45,John,Smith,John Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com,OFFICER_LEVEL3,2930 days 12:31:58.551064,8,0

In [162]:
df.pivot_table(index=['Department','Position'],values='Salary',aggfunc=[np.min,np.max])

                          min    max
                       Salary Salary
Department Position
Finance    Analyst      53313  85042
           Consultant   57505  99075
           Coordinator  52352  96404
           Developer    58248  99083
           Manager      73325  96720
HR         Analyst      69641  70433
           Consultant   57581  87328
           Coordinator  59690  99317
           Developer    53995  92160
           Manager      51344  97002
IT         Analyst      52422  68931
           Consultant   68973  97238
           Coordinator  68065  96865
           Developer    56091  98764
           Manager      63304  84343
Marketing  Analyst      55912  97810
           Consultant   63444  96179
           Coordinator  51004  96843
           Developer    53966  88477
           Manager      50611  98825
Sales      Analyst      53958  99212
           Consultant   57951  96760
           Coordinator  51064  94503
           Developer    53742  79334
           Manager      51631  98259

In [168]:
# OR

In [166]:
df.groupby(['Department','Position'])['Salary'].agg([np.min,np.max])

                          min    max
Department Position
Finance    Analyst      53313  85042
           Consultant   57505  99075
           Coordinator  52352  96404
           Developer    58248  99083
           Manager      73325  96720
HR         Analyst      69641  70433
           Consultant   57581  87328
           Coordinator  59690  99317
           Developer    53995  92160
           Manager      51344  97002
IT         Analyst      52422  68931
           Consultant   68973  97238
           Coordinator  68065  96865
           Developer    56091  98764
           Manager      63304  84343
Marketing  Analyst      55912  97810
           Consultant   63444  96179
           Coordinator  51004  96843
           Developer    53966  88477
           Manager      50611  98825
Sales      Analyst      53958  99212
           Consultant   57951  96760
           Coordinator  51064  94503
           Developer    53742  79334
           Manager      51631  98259

In [154]:
df[(df.Department=='Finance')&(df.Position=='Analyst')]

,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category,Experience,Year,Month
38,36,John,Doe,John Doe,Finance,Analyst,71707,2017-09-21,1984-04-19,555-4321,bob.johnson@example.com,OFFICER_LEVEL3,2585 days 12:31:58.551064,7,1
51,12,Alice,Smith,Alice Smith,Finance,Analyst,67181,2017-06-08,1977-05-28,555-4321,john.doe@example.com,OFFICER_LEVEL3,2690 days 12:31:58.551064,7,4
53,92,Jane,Doe,Jane Doe,Finance,Analyst,85042,2017-05-25,1976-05-15,555-8765,david.brown@example.com,OFFICER_LEVEL2,2704 days 12:31:58.551064,7,5
71,86,Alice,Smith,Alice Smith,Finance,Analyst,74208,2020-01-18,1998-12-08,555-8765,alice.williams@example.com,OFFICER_LEVEL3,1736 days 12:31:58.551064,4,9
72,49,Jane,Williams,Jane Williams,Finance,Analyst,78616,2018-06-28,1979-02-16,555-5678,bob.johnson@example.com,OFFICER_LEVEL2,2305 days 12:31:58.551064,6,4
73,50,Jane,Johnson,Jane Johnson,Finance,Analyst,72075,2016-07-27,1993-12-09,555-4321,jane.smith@example.com,OFFICER_LEVEL3,3006 days 12:31:58.551064,8,3
140,57,Bob,Johnson,Bob Johnson,Finance,Analyst,53313,2016-03-10,1972-09-13,555-8765,jane.smith@example.com,OFFICER_LEVEL3,3145 days 12:31:58.551064,8,7

In [146]:
df.pivot_table(index=['Department','Position'],values = 'Salary',aggfunc=np.max)

                        Salary
Department Position
Finance    Analyst       85042
           Consultant    99075
           Coordinator   96404
           Developer     99083
           Manager       96720
HR         Analyst       70433
           Consultant    87328
           Coordinator   99317
           Developer     92160
           Manager       97002
IT         Analyst       68931
           Consultant    97238
           Coordinator   96865
           Developer     98764
           Manager       84343
Marketing  Analyst       97810
           Consultant    96179
           Coordinator   96843
           Developer     88477
           Manager       98825
Sales      Analyst       99212
           Consultant    96760
           Coordinator   94503
           Developer     79334
           Manager       98259

### 3. To calculate no.of employee department and position wise and also calulate min, max salary.

In [175]:
df.pivot_table(index=['Department','Position'],values=['Salary','FirstName'],
               aggfunc={'Salary':[np.max,np.min],'FirstName':len})

                       FirstName Salary
                             len    max    min
Department Position
Finance    Analyst             7  85042  53313
           Consultant          9  99075  57505
           Coordinator        12  96404  52352
           Developer          10  99083  58248
           Manager             5  96720  73325
HR         Analyst             2  70433  69641
           Consultant          6  87328  57581
           Coordinator         8  99317  59690
           Developer          10  92160  53995
           Manager            12  97002  51344
IT         Analyst             7  68931  52422
           Consultant          7  97238  68973
           Coordinator         8  96865  68065
           Developer           9  98764  56091
           Manager             7  84343  63304
Marketing  Analyst             7  97810  55912
           Consultant          5  96179  63444
           Coordinator         9  96843  51004
           Developer           6  88477  53966
           Manager             6  98825  50611
Sales      Analyst            14  99212  53958
           Consultant          7  96760  57951
           Coordinator        10  94503  51064
           Developer           4  79334  53742
           Manager            13  98259  51631

#### 4. To calculate  max and min salary of Analyst of each department.

In [202]:
table = df.pivot_table(index=['Department','Position'],values = 'Salary',aggfunc=[np.min,np.max])

In [204]:
df.Position.unique()

array(['Consultant', 'Developer', 'Coordinator', 'Analyst', 'Manager'],
      dtype=object)

In [206]:
table

                          min    max
                       Salary Salary
Department Position
Finance    Analyst      53313  85042
           Consultant   57505  99075
           Coordinator  52352  96404
           Developer    58248  99083
           Manager      73325  96720
HR         Analyst      69641  70433
           Consultant   57581  87328
           Coordinator  59690  99317
           Developer    53995  92160
           Manager      51344  97002
IT         Analyst      52422  68931
           Consultant   68973  97238
           Coordinator  68065  96865
           Developer    56091  98764
           Manager      63304  84343
Marketing  Analyst      55912  97810
           Consultant   63444  96179
           Coordinator  51004  96843
           Developer    53966  88477
           Manager      50611  98825
Sales      Analyst      53958  99212
           Consultant   57951  96760
           Coordinator  51064  94503
           Developer    53742  79334
           Manager      51631  98259

In [210]:
T1 = table.query('Position == "Analyst"')

In [216]:
T1

                       min    max
                    Salary Salary
Department Position
Finance    Analyst   53313  85042
HR         Analyst   69641  70433
IT         Analyst   52422  68931
Marketing  Analyst   55912  97810
Sales      Analyst   53958  99212

#### 5. To calculate max and min salary of Analyst of each department. And sort it by min salary.

In [227]:
T1.columns

MultiIndex([('min', 'Salary'),
            ('max', 'Salary')],
           )

In [229]:
T1.sort_values([('min', 'Salary')])

                       min    max
                    Salary Salary
Department Position
IT         Analyst   52422  68931
Finance    Analyst   53313  85042
Sales      Analyst   53958  99212
Marketing  Analyst   55912  97810
HR         Analyst   69641  70433

In [231]:
T1.sort_values([('min', 'Salary')], ascending=False)

                       min    max
                    Salary Salary
Department Position
HR         Analyst   69641  70433
Marketing  Analyst   55912  97810
Sales      Analyst   53958  99212
Finance    Analyst   53313  85042
IT         Analyst   52422  68931

In [174]:
table.query('Position == "Analyst"').sort_values(by='Salary',ascending=False)

                     Salary
Department Position
Sales      Analyst    99212
Marketing  Analyst    97810
Finance    Analyst    85042
HR         Analyst    70433
IT         Analyst    68931

In [236]:
table1 = df.pivot_table(index=['Department','Position'],values = 'Salary',aggfunc=[np.max,np.min])

In [238]:
table1

                          max    min
                       Salary Salary
Department Position
Finance    Analyst      85042  53313
           Consultant   99075  57505
           Coordinator  96404  52352
           Developer    99083  58248
           Manager      96720  73325
HR         Analyst      70433  69641
           Consultant   87328  57581
           Coordinator  99317  59690
           Developer    92160  53995
           Manager      97002  51344
IT         Analyst      68931  52422
           Consultant   97238  68973
           Coordinator  96865  68065
           Developer    98764  56091
           Manager      84343  63304
Marketing  Analyst      97810  55912
           Consultant   96179  63444
           Coordinator  96843  51004
           Developer    88477  53966
           Manager      98825  50611
Sales      Analyst      99212  53958
           Consultant   96760  57951
           Coordinator  94503  51064
           Developer    79334  53742
           Manager      98259  51631

#### 6. To calculate max and min salary of Analyst and Consultant of IT and Sales department. And sort it by min salary.

In [241]:
table1.query('Department.isin(["Sales","IT"])& Position.isin(["Analyst","Consultant"])')

                         max    min
                      Salary Salary
Department Position
IT         Analyst     68931  52422
           Consultant  97238  68973
Sales      Analyst     99212  53958
           Consultant  96760  57951

In [243]:
#  OR

In [245]:
df[(df.Department.isin(['IT','Sales']))&(df.Position.isin(["Analyst","Consultant"]))].groupby(['Department','Position'])['Salary'].agg([np.max,np.min])

                         max    min
Department Position
IT         Analyst     68931  52422
           Consultant  97238  68973
Sales      Analyst     99212  53958
           Consultant  96760  57951

In [168]:
df.head()

,EmployeeID,FirstName,LastName,FullName,Department,Position,Salary,HireDate,BirthDate,Phone,Email,Category,Experience,Year,Month
0,45,John,Smith,John Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com,OFFICER_LEVEL3,2929 days 11:40:27.091750,8,0
1,68,Bob,Doe,Bob Doe,HR,Developer,68007,2016-07-08,1974-02-01,555-3456,jane.smith@example.com,OFFICER_LEVEL3,3024 days 11:40:27.091750,8,3
2,68,John,Williams,John Williams,IT,Developer,56091,2020-09-14,1980-04-25,555-5678,jane.smith@example.com,OFFICER_LEVEL3,1495 days 11:40:27.091750,4,1
3,10,Alice,Doe,Alice Doe,HR,Developer,84381,2015-12-22,1973-02-28,555-1234,jane.smith@example.com,OFFICER_LEVEL2,3223 days 11:40:27.091750,9,-2
4,84,Jane,Brown,Jane Brown,Finance,Coordinator,91470,2019-09-17,1991-06-13,555-8765,jane.smith@example.com,OFFICER_LEVEL1,1858 days 11:40:27.091750,5,1

In [198]:
df.pivot_table(index='Department', columns='Position',values = 'Salary', aggfunc=[np.max,np.min]).query('Department =="IT"')

               max                                              min  \
Position   Analyst Consultant Coordinator Developer Manager Analyst
Department
IT           68931      97238       96865     98764   84343   52422


Position   Consultant Coordinator Developer Manager
Department
IT              68973       68065     56091   63304

In [33]:
sale = pd.read_csv("https://raw.githubusercontent.com/ffzs/dataset/master/sales.csv")

In [34]:
sale.shape

(86135, 4)

In [35]:
sale.head()

   USERID   ORDERDATE     ORDERID  AMOUNTINFO
0  142074  2016-01-01  4196439032      9399.0
1   56927  2016-01-01  4198324983      8799.0
2   87058  2016-01-01  4191287379      6899.0
3  136104  2016-01-01  4198508313      5999.0
4  117831  2016-01-01  4202238313      5399.0

In [36]:
sale.sort_values('AMOUNTINFO')

       USERID   ORDERDATE     ORDERID  AMOUNTINFO
86134   61176  2016-12-29  4195479740         0.5
57642  150380  2016-09-02  4195823198         0.5
57641  146000  2016-09-02  3844483725         0.5
57640   63703  2016-09-02  4199758473         0.5
5926    82148  2016-01-24  4198382457         0.5
...       ...         ...         ...         ...
260     65456  2016-01-02  4195643356         NaN
62134  122134  2016-09-21  3826649773         NaN
70342  116995  2016-10-24  3981569421         NaN
80110   98888  2016-12-06  3814398698         NaN
86069  145951  2016-12-29  4139830098         NaN

[86135 rows x 4 columns]

In [37]:
sale.columns

Index(['USERID', 'ORDERDATE', 'ORDERID', 'AMOUNTINFO'], dtype='object')

In [38]:
s1 = sale.copy()

In [39]:
s1.shape

(86135, 4)

In [43]:
s1.duplicated(['ORDERDATE', 'AMOUNTINFO']).sum()

38973

In [32]:
sale.drop_duplicates(subset=['ORDERDATE', 'AMOUNTINFO'])

       USERID   ORDERDATE     ORDERID  AMOUNTINFO
0      142074  2016-01-01  4196439032      9399.0
1       56927  2016-01-01  4198324983      8799.0
2       87058  2016-01-01  4191287379      6899.0
3      136104  2016-01-01  4198508313      5999.0
4      117831  2016-01-01  4202238313      5399.0
...       ...         ...         ...         ...
86124   66477  2016-12-29  4097385870         6.0
86128  124262  2016-12-29  4120675167         5.9
86129   96216  2016-12-29  4107523260         4.0
86130  110416  2016-12-29  4111876729         3.9
86131  149172  2016-12-29  4182928398         0.5

[47162 rows x 4 columns]

In [23]:
deleted_rows

       USERID   ORDERDATE     ORDERID  AMOUNTINFO
0      142074  2016-01-01  4196439032      9399.0
1       56927  2016-01-01  4198324983      8799.0
2       87058  2016-01-01  4191287379      6899.0
3      136104  2016-01-01  4198508313      5999.0
4      117831  2016-01-01  4202238313      5399.0
...       ...         ...         ...         ...
86124   66477  2016-12-29  4097385870         6.0
86128  124262  2016-12-29  4120675167         5.9
86129   96216  2016-12-29  4107523260         4.0
86130  110416  2016-12-29  4111876729         3.9
86131  149172  2016-12-29  4182928398         0.5

[47162 rows x 4 columns]