In [3]:
import numpy as np
import pandas as pd

# Create a series

### Creating an empty series

Series() function of Pandas is used to create a series. A basic series, which can be created is an Empty Series.

In [8]:
S1 = pd.Series()
print(S1)

Series([], dtype: float64)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_15844\4195686867.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  S1 = pd.Series()

### Creating a series from array

In order to create a series from NumPy array, we have to import numpy module and have to use array() function.

In [12]:
# Simple array
d1 = np.array(['c','o','d','i','n','g'])
S2 = pd.Series(d1)
print(S2)

0    c
1    o
2    d
3    i
4    n
5    g
dtype: object

### Creating a series from array with an index

In order to create a series by explicitly proving index instead of the default, we have to provide a list of elements to the index parameter with the same number of elements as it is an array.

In [20]:
data = np.array(['c','o','d','i','n','g'])
S3 = pd.Series(data,index=[10,11,12,13,14,15])
print(S3)

10    c
11    o
12    d
13    i
14    n
15    g
dtype: object

### Creating a series from Lists

In order to create a series from list, we have to first create a list after that we can create a series from list.

In [7]:
L1 = ['c','o','d','i','n','g']
S4 = pd.Series(L1)
print(S4)

0    c
1    o
2    d
3    i
4    n
5    g
dtype: object

### Creating a series from Dictionary

In order to create a series from the dictionary, we have to first create a dictionary after that we can make a series using dictionary. Dictionary keys are used to construct indexes of Series.

In [5]:
# a simple dictionary
dict = {'K1': 10,
        'K2': 20,
        'K3': 30}
 
# create series from dictionary
ser = pd.Series(dict)
 
print(ser)

K1    10
K2    20
K3    30
dtype: int64

In [9]:
dict = {'K1':10,'K2':20,'K3':30}
ser = pd.Series(dict, index = ['a','b','c','K1','K2'])
ser

a      NaN
b      NaN
c      NaN
K1    10.0
K2    20.0
dtype: float64

### Creating a series from Scalar value

In order to create a series from scalar value, an index must be provided. The scalar value will be repeated to match the length of the index.

In [13]:
# Giving a scalar value with index
S5 = pd.Series(10, index = [0,1,2,3,4,5])
print(S5)

0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64

In [15]:
# Giving a scalar value with index
S5 = pd.Series(10, index = range(1,20,2))
print(S5)

1     10
3     10
5     10
7     10
9     10
11    10
13    10
15    10
17    10
19    10
dtype: int64

In [16]:
# Giving a scalar value with index
S5 = pd.Series(10)
print(S5)

0    10
dtype: int64

In [17]:
# Giving a scalar value with index
S5 = pd.Series(10, index = range(10))
print(S5)

0    10
1    10
2    10
3    10
4    10
5    10
6    10
7    10
8    10
9    10
dtype: int64

### Creating a series using NumPy functions

In order to create a series using numpy function, we can use different function of numpy like numpy.linspace().

In [20]:
# Series with numpy linspace()
s6 = pd.Series(np.linspace(3,33,3))
print(s6)

0     3.0
1    18.0
2    33.0
dtype: float64

In [21]:
# Series with numpy linspace()
s6 = pd.Series(np.linspace(3,33,10))
print(s6)

0     3.000000
1     6.333333
2     9.666667
3    13.000000
4    16.333333
5    19.666667
6    23.000000
7    26.333333
8    29.666667
9    33.000000
dtype: float64

In [11]:
# Series with numpy linspace()
s6 = pd.Series(np.linspace(3,33,10,retstep=True))
print(s6)

0    [3.0, 6.333333333333334, 9.666666666666668, 13...
1                                             3.333333
dtype: object

In [13]:
# Series with numpy linspace()
s6 = pd.Series(np.linspace(3,33,10,endpoint=False))
print(s6)

0     3.0
1     6.0
2     9.0
3    12.0
4    15.0
5    18.0
6    21.0
7    24.0
8    27.0
9    30.0
dtype: float64

In [17]:
# Series with numpy linspace()
s6 = pd.Series(np.linspace(3,33,10, dtype=int))
print(s6)

0     3
1     6
2     9
3    13
4    16
5    19
6    23
7    26
8    29
9    33
dtype: int32

NumPy linspace() Arguments
start: The starting value of the sequence.
stop: The end value of the sequence.
num (optional): The specified interval. The default is 50, and it must be non-negative.
endpoint (optional): If True (default), stop is the last sample. If False, the stop value is not included in the sequence generated by linspace(). This means that the function will create evenly spaced samples within the range from start to just before stop, effectively excluding the stop value itself from the sequence. This can be useful when you need a range that approaches but does not reach the endpoint, allowing for more flexible control over the range of values generated.
retstep (optional): If True, returns (samples, step), where step is the spacing between samples.
dtype (optional): The type of the output array. If not given, the dtype will be determined by the start and stop arguments.
axis (optional): The axis in the result to store the samples, only when working with multi-dimensional arrays.

### Creating a Series using range function

In [25]:
range(10)

range(0, 10)

In [23]:
S7 = pd.Series(range(10))
print(S7)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [23]:
S7 = pd.Series(range(1,10))
print(S7)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [24]:
S7 = pd.Series(range(1,30,3))
print(S7)

0     1
1     4
2     7
3    10
4    13
5    16
6    19
7    22
8    25
9    28
dtype: int64

### Creating a Series using mathematical expressions

In [27]:
ser = np.arange(10,15)
print(ser)

[10 11 12 13 14]

In [29]:
ser1 = pd.Series(ser*5,index=ser)
print(ser1)

10    50
11    55
12    60
13    65
14    70
dtype: int32

In [31]:
ser = np.arange(1,101)
print(ser)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

In [35]:
ser1 = pd.Series(ser**2,index=ser)
print(ser1)

1          1
2          4
3          9
4         16
5         25
       ...
96      9216
97      9409
98      9604
99      9801
100    10000
Length: 100, dtype: int32

# Pandas Series – Attributes and Methods

#### series.index

In [3]:
cities = ['Kolkata', 'Chicago', 'Toronto', 'Lisbon']
populations = [14.85, 2.71, 2.93, 0.51]
city_series = pd.Series(populations, index=cities)
city_series.index

Index(['Kolkata', 'Chicago', 'Toronto', 'Lisbon'], dtype='object')

In [4]:
city_series.index = ['KOL', 'CHI', 'TOR', 'LIS']
city_series.index

Index(['KOL', 'CHI', 'TOR', 'LIS'], dtype='object')

In [35]:
S8 = pd.Series(range(10,35), name='Example')
S8

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
15    25
16    26
17    27
18    28
19    29
20    30
21    31
22    32
23    33
24    34
Name: Example, dtype: int64

In [36]:
S8.name

'Example'

In [37]:
S8.shape

(25,)

In [38]:
S8.size

25

In [39]:
S8.ndim

1

In [40]:
S8.hasnans

False

In [41]:
S8.index

RangeIndex(start=0, stop=25, step=1)

In [42]:
S8.dtypes

dtype('int64')

In [44]:
S8.info()

<class 'pandas.core.series.Series'>
RangeIndex: 25 entries, 0 to 24
Series name: Example
Non-Null Count  Dtype
--------------  -----
25 non-null     int64
dtypes: int64(1)
memory usage: 332.0 bytes

In [45]:
S8.head(4)

0    10
1    11
2    12
3    13
Name: Example, dtype: int64

In [46]:
S8.tail(2)

23    33
24    34
Name: Example, dtype: int64

In [47]:
S8.describe()

count    25.000000
mean     22.000000
std       7.359801
min      10.000000
25%      16.000000
50%      22.000000
75%      28.000000
max      34.000000
Name: Example, dtype: float64

In [48]:
S8.value_counts()

Example
10    1
23    1
33    1
32    1
31    1
30    1
29    1
28    1
27    1
26    1
25    1
24    1
22    1
11    1
21    1
20    1
19    1
18    1
17    1
16    1
15    1
14    1
13    1
12    1
34    1
Name: count, dtype: int64

In [49]:
S8.values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34], dtype=int64)

In [50]:
S8.dtype

dtype('int64')

In [51]:
S8.empty

False

In [52]:
S8.isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: Example, dtype: bool

In [53]:
S8.isna().sum()

S8.notna()
S8.notnull()
S8.notna().sum()
S8.notnull().sum()

0

In [54]:
S8

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
15    25
16    26
17    27
18    28
19    29
20    30
21    31
22    32
23    33
24    34
Name: Example, dtype: int64

In [110]:
S9 = pd.Series([1,2,3,4])
print(S9)

0    1
1    2
2    3
3    4
dtype: int64

In [111]:
S9.sum()

10

In [112]:
S9.array

<NumpyExtensionArray>
[1, 2, 3, 4]
Length: 4, dtype: int64

In [113]:
S9

0    1
1    2
2    3
3    4
dtype: int64

In [114]:
S9.nbytes

32

In [116]:
S9

0    1
1    2
2    3
3    4
dtype: int64

In [117]:
S9.add(1)

0    2
1    3
2    4
3    5
dtype: int64

In [118]:
S9.div(2)

0    0.5
1    1.0
2    1.5
3    2.0
dtype: float64

In [119]:
S9.mul(2)

0    2
1    4
2    6
3    8
dtype: int64

In [128]:
S10 = pd.Series([3,4,5,6])
print(S10)

0    3
1    4
2    5
3    6
dtype: int64

In [129]:
S9.add(S10)

0     4
1     6
2     8
3    10
dtype: int64

In [130]:
S9.div(S10)

0    0.333333
1    0.500000
2    0.600000
3    0.666667
dtype: float64

In [131]:
S9.mul(S10)

0     3
1     8
2    15
3    24
dtype: int64

In [132]:
S9.mod(S10)

0    1
1    2
2    3
3    4
dtype: int64

In [135]:
S9

0    1
1    2
2    3
3    4
dtype: int64

In [1]:
L5 = [2,3,4,5]

#### Pandas Series.to_numpy()

In [1]:
# importing pandas 
import pandas as pd  
  
# reading the csv   
data = pd.read_csv("nba.csv")  
     
 
# creating series form weight column 
s1 = pd.Series(data['Weight'].head()) 

print(s1)
print(type(s1))
# using to_numpy() function 
print(s1.to_numpy())
print(s1.to_numpy(dtype='float'))
print(s1.to_numpy(dtype='int64'))
print(s1.to_numpy(dtype='str'))

0    180.0
1    235.0
2    205.0
3    185.0
4    231.0
Name: Weight, dtype: float64
<class 'pandas.core.series.Series'>
[180. 235. 205. 185. 231.]
[180. 235. 205. 185. 231.]
[180 235 205 185 231]
['180.0' '235.0' '205.0' '185.0' '231.0']

In [3]:
data.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0

In [4]:
data.shape

(458, 9)

In [6]:
len(data.columns)

9

In [4]:
data.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [12]:
data.Weight.head()

0    180.0
1    235.0
2    205.0
3    185.0
4    231.0
Name: Weight, dtype: float64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [6]:
data.size

4122

In [8]:
data.ndim

2

In [31]:
type(s1)

pandas.core.series.Series

#### Pandas Series.mod()

In [23]:
a = pd.Series([5, 10, 14, np.nan], index=['a', 'b', 'c', 'd'])
b = pd.Series([2, np.nan, 4, 2], index=['a', 'b', 'c', 'd'])
print(a)
print(b)
print(a.mod(b))
print(a.mod(b,fill_value=3))

a     5.0
b    10.0
c    14.0
d     NaN
dtype: float64
a    2.0
b    NaN
c    4.0
d    2.0
dtype: float64
a    1.0
b    NaN
c    2.0
d    NaN
dtype: float64
a    1.0
b    1.0
c    2.0
d    1.0
dtype: float64

In [52]:
# importing pandas module   
import pandas as pd  
    
# reading csv file from url   
data = pd.read_csv("nba.csv")  
    
# creating short data of 5 rows  
short_data = data.head()

In [53]:
type(short_data)

pandas.core.frame.DataFrame

In [54]:
short_data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [64]:
# creating list with 5 values  
list =[1, 2, 3, 4, 3]  
    
# finding remainder 
# creating new column  
short_data["Remainder"]= short_data["Salary"].mod(list, fill_value=8)  
    
# display  
short_data

C:\Users\lenovo\AppData\Local\Temp\ipykernel_8500\544443738.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  short_data["Remainder"]= short_data["Salary"].mod(list, fill_value=8)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Remainder
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,0.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,1.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,0.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2.0

#### pandas.Series.mode

In [67]:
s = pd.Series([4, 4, 2, 2, 4, None])
s.mode()

0    4.0
dtype: float64

In [14]:
s = pd.Series([2, 4, 8, 2, 4,6,6, None])
s.mode()

0    2.0
1    4.0
2    6.0
dtype: float64

In [72]:
# dropna = False , means Don’t consider counts of NaN.

s = pd.Series([2, 4, None, None, 4, None])
print(s.mode(dropna=False))
s = pd.Series([2, 4, None, None, 4, None])
print(s.mode())

0   NaN
dtype: float64
0    4.0
dtype: float64

#### Pandas Series.mean(), min(), max(), sum(), std()

Pandas Series.mean() function return the mean of the underlying data in the given Series object.

In [85]:
# Creating the Series 
sr = pd.Series([10, 25, 3, 25, 24, 6]) 
  
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr) 

# return the mean 
result = sr.mean() 
  
# Print the result 
print(result)

Coca Cola    10
Sprite       25
Coke          3
Fanta        25
Dew          24
ThumbsUp      6
dtype: int64
15.5

In [88]:
# Creating the Series 
sr = pd.Series([19.5, 16.8, None, 22.78, 16.8, 20.124, None, 18.1002, 19.5]) 
  
# Print the series 
print(sr) 

# return the mean 
# dont skip all the missing values 
result1 = sr.mean(skipna=False) 
  
# Print the result 
print(result1) 

# skip all the missing values 
result = sr.mean(skipna = True) 
  
# Print the result 
print(result)

0    19.5000
1    16.8000
2        NaN
3    22.7800
4    16.8000
5    20.1240
6        NaN
7    18.1002
8    19.5000
dtype: float64
nan
19.086314285714284

In [94]:
# Creating the Series 
sr = pd.Series([10, 25, 3, 25, 24, 6]) 
  
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr) 

print("Maximum Value:- ",sr.max()) 
print("Mimimum Value:- ",sr.min()) 
print("Sum of Value:- ",sr.sum()) 
print("Standard Deviation Value:- ",sr.std())

Coca Cola    10
Sprite       25
Coke          3
Fanta        25
Dew          24
ThumbsUp      6
dtype: int64
Maximum Value:-  25
Mimimum Value:-  3
Sum of Value:-  93
Standard Deviation Value:-  10.290772565750348

#### Pandas Series.isna() , Pandas Series.notna(), Pandas Series.dropna()

Pandas Series.isna() function detect missing values in the given series object. It return a boolean same-sized object indicating if the values are NA. Missing values gets mapped to True and non-missing value gets mapped to False. Pandas Series.notna() function Detect existing (non-missing) values. This function return a boolean object having the size same as the object, indicating if the values are missing values or not. Non-missing values get mapped to True.
Pandas Series.dropna() function return a new Series with missing values in the given series object removed.

In [18]:
import numpy as np

In [22]:
# Creating the Series 
sr = pd.Series([10, 25, 3, np.nan,25, 24, np.nan]) 
  
# Print the series 
print(sr) 
print(sr.isna())
print(sr.isnull())
print(sr.isna().sum())
print(sr.isnull().sum())
print(sr.notna())
print(sr.notnull())

0    10.0
1    25.0
2     3.0
3     NaN
4    25.0
5    24.0
6     NaN
dtype: float64
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
2
2
0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool
0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool

In [103]:
# Creating the Series 
sr = pd.Series([10, np.nan, 3,np.nan, 24, None]) 
  
# Print the series 
print(sr) 
print(sr.isna())
print(sr.isnull())
print("Total Missing Values:- ",sr.isna().sum())

0    10.0
1     NaN
2     3.0
3     NaN
4    24.0
5     NaN
dtype: float64
0    False
1     True
2    False
3     True
4    False
5     True
dtype: bool
0    False
1     True
2    False
3     True
4    False
5     True
dtype: bool
Total Missing Values:-  3

In [106]:
# Creating the Series 
sr = pd.Series([10, np.nan, 3,np.nan, 24, None]) 
  
# Print the series 
print(sr) 
print(sr.notna())
print(sr.notnull())
print("Total Not Missing Values:- ",sr.notnull().sum())

0    10.0
1     NaN
2     3.0
3     NaN
4    24.0
5     NaN
dtype: float64
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
Total Not Missing Values:-  3

In [1]:
import numpy as np
import pandas as pd

In [9]:
# Creating the Series 
sr = pd.Series([10, np.nan, 3,np.nan, 24, None]) 
  
# Print the series 
print(sr) 
print(sr.notna())
print(sr.notnull())
print("Total Missing Values:- ",sr.notnull().sum())

sr.dropna(inplace=True)
print("Total Missing Values:- ",sr.isnull().sum())

0    10.0
1     NaN
2     3.0
3     NaN
4    24.0
5     NaN
dtype: float64
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
Total Missing Values:-  3
Total Missing Values:-  0

#### Pandas Series.drop()

Pandas Series.drop() function return Series with specified index labels removed. It remove elements of a Series based on specifying the index labels.

In [11]:
# Creating the Series 
sr = pd.Series([80, 25, 3, 25, 24, 6]) 
print(sr)
  
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr)

0    80
1    25
2     3
3    25
4    24
5     6
dtype: int64
Coca Cola    80
Sprite       25
Coke          3
Fanta        25
Dew          24
ThumbsUp      6
dtype: int64

In [13]:
# Creating the Series 
sr = pd.Series([80, 25, 3, 25, 24, 6]) 
print(sr)
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr) 

# drop the passed labels 
result = sr.drop(labels = ['Sprite', 'Dew'])  
  
# Print the result 
print(result)

0    80
1    25
2     3
3    25
4    24
5     6
dtype: int64
Coca Cola    80
Sprite       25
Coke          3
Fanta        25
Dew          24
ThumbsUp      6
dtype: int64
Coca Cola    80
Coke          3
Fanta        25
ThumbsUp      6
dtype: int64

#### pandas.Series.eq, lt, gt, le,ge, ne

Pandas series.eq() is used to compare every element of Caller series with passed series. It returns True for every element which is Equal to the element in passed series.

In [74]:
a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
print(a)
print(b)
a.eq(b, fill_value=0)

a    1.0
b    1.0
c    1.0
d    NaN
dtype: float64
a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64

a     True
b    False
c    False
d    False
e    False
dtype: bool

In [78]:
# creating series 1  
series1 = pd.Series([70, 5, 0, 225, 1, 16, np.nan, 10, np.nan])  
     
# creating series 2  
series2 = pd.Series([70, np.nan, 2, 23, 1, 95, 53, 10, 5])  
   
# NaN replacement 
replace_nan = 5
   
# calling and returning to result variable 
result = series1.eq(series2, fill_value = replace_nan) 
   
# display  
result

0     True
1     True
2    False
3    False
4     True
5    False
6    False
7     True
8     True
dtype: bool

#### pandas.Series.le

Pandas series.eq() is used to compare every element of Caller series with passed series. It returns True for every element which is less than or Equal to the element in passed series.

In [76]:
a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
print(a)
print(b)
a.le(b, fill_value=0)

a    1.0
b    1.0
c    1.0
d    NaN
dtype: float64
a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64

a     True
b    False
c    False
d     True
e    False
dtype: bool

In [83]:
  
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.le(series2, fill_value = replace_nan) 
  
# display  
result

0    False
1     True
2     True
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

#### pandas.Series.lt

Pandas series.it() is used to compare every element of Caller series with passed series. It returns True for every element which is Less than to the element in passed series.

In [17]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.lt(series2, fill_value = replace_nan) 
  
# display  
result

0    False
1     True
2    False
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

#### pandas.Series.gt

Pandas series.gt() is used to compare every element of Caller series with passed series. It returns True for every element which is Greater than to the element in passed series.

In [16]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.gt(series2, fill_value = replace_nan) 
  
# display  
result

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8    False
dtype: bool

#### pandas.Series.ge

Pandas series.ge() is used to compare every element of Caller series with passed series. It returns True for every element which is Greater than or Equal to the element in passed series.

In [79]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.ge(series2, fill_value = replace_nan) 
  
# display  
result

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8    False
dtype: bool

In [80]:
# creating series 1  
series1 = pd.Series(['A', 0, 'c', 43, 9, 'e', np.nan, 'x', np.nan])  
    
# creating series 2  
series2 = pd.Series(['v', np.nan, 'c', 23, 5, 'D', 54, 'p', 19])  
  
# NaN replacement 
replace_nan = 14
  
# calling and returning to result variable 
result = series1.ge(series2, fill_value = replace_nan) 
  
# display  
result

0    False
1    False
2     True
3     True
4     True
5     True
6    False
7     True
8    False
dtype: bool

In [81]:
# As it can be seen in output, in case of strings, the comparison was made using their ASCII values.

#### Pandas Series.ne

Pandas series.ne() is used to compare every element of Caller series with passed series. It returns True for every element which is Not Equal to the element in passed series.

In [82]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.ne(series2, fill_value = replace_nan) 
  
# display  
result

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7     True
8     True
dtype: bool

#### idxmax(), idxmin(), sort_values(), sort_index(), head(), tail()

Method to extract the index positions of the highest values in a Series

Method to extract the index positions of the lowest values in a Series

Method is called on a Series to sort the values in ascending or descending order

Method is called on a pandas Series to sort it by the index instead of its values

Method is used to return a specified number of rows from the beginning of a Series. The method returns a brand new Series

Method is used to return a specified number of rows from the end of a Series. The method returns a brand new Series

In [23]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, 2, 10, 6]) 
print(series1.idxmax())
print(series1.idxmin())
print(series1.sort_values())
print(series1.sort_values(ascending=False))
print(series1.sort_index())
print(series1.sort_index(ascending=False))
print(series1.head(2))
print(series1.head())
print(series1.tail(2))
print(series1.tail())

3
1
1      0
4      1
2      2
6      2
8      6
7     10
5     16
0     70
3    225
dtype: int64
3    225
0     70
5     16
7     10
8      6
2      2
6      2
4      1
1      0
dtype: int64
0     70
1      0
2      2
3    225
4      1
5     16
6      2
7     10
8      6
dtype: int64
8      6
7     10
6      2
5     16
4      1
3    225
2      2
1      0
0     70
dtype: int64
0    70
1     0
dtype: int64
0     70
1      0
2      2
3    225
4      1
dtype: int64
7    10
8     6
dtype: int64
4     1
5    16
6     2
7    10
8     6
dtype: int64