In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }, index= [0,1,2,3],
)
df2 = pd.DataFrame(
    {
         "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    }, index=[4,5,6,7]
)
df3 = pd.DataFrame(
    {
       "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"], 
    }, index=[8,9,10,11]
)

In [3]:
frames = [df1,df2,df3]

In [4]:
result = pd.concat(frames)

In [5]:
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [6]:
d1 = pd.DataFrame(
    {
       "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "E": ["C8", "C9", "C10", "C11"],
        "F": ["D8", "D9", "D10", "D11"], 
    }
)

In [7]:
pd.concat([df1,df2,df3,d1])

      A    B    C    D    E    F
0    A0   B0   C0   D0  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN
4    A4   B4   C4   D4  NaN  NaN
5    A5   B5   C5   D5  NaN  NaN
6    A6   B6   C6   D6  NaN  NaN
7    A7   B7   C7   D7  NaN  NaN
8    A8   B8   C8   D8  NaN  NaN
9    A9   B9   C9   D9  NaN  NaN
10  A10  B10  C10  D10  NaN  NaN
11  A11  B11  C11  D11  NaN  NaN
0    A8   B8  NaN  NaN   C8   D8
1    A9   B9  NaN  NaN   C9   D9
2   A10  B10  NaN  NaN  C10  D10
3   A11  B11  NaN  NaN  C11  D11

In [8]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[2, 3, 6, 7],
)

In [9]:
result = pd.concat([df1,df4],axis=0)

In [10]:
result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [11]:
result = pd.concat([df1,df4],axis=1)

In [12]:
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [13]:
result = pd.concat([df1,df4],axis=1,join='outer')

In [14]:
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [15]:
#leftjoin
result = pd.concat([df1,df4],axis=1).reindex(df1.index)
result

    A   B   C   D    B    D    F
0  A0  B0  C0  D0  NaN  NaN  NaN
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2   B2   D2   F2
3  A3  B3  C3  D3   B3   D3   F3

In [17]:
result = pd.concat([df1,df4],axis=1).reindex(df4.index) #right join
result

     A    B    C    D   B   D   F
2   A2   B2   C2   D2  B2  D2  F2
3   A3   B3   C3   D3  B3  D3  F3
6  NaN  NaN  NaN  NaN  B6  D6  F6
7  NaN  NaN  NaN  NaN  B7  D7  F7

In [18]:
result = pd.concat([df1,df4],axis=1,join='inner')

In [19]:
result

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

In [20]:
result = pd.concat([df1,df4])
result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [22]:
result = pd.concat([df1,df4],ignore_index=True,sort=False) #ignore index
result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [ ]:
#concatenation series and dataframe
s1 = pd.Series(['X0','X1','X2','X3'])
result = pd.concat([df1,s1],axis=1)

In [24]:
result

    A   B   C   D   0
0  A0  B0  C0  D0  X0
1  A1  B1  C1  D1  X1
2  A2  B2  C2  D2  X2
3  A3  B3  C3  D3  X3

In [25]:
s1 = pd.Series(['X0','X1','X2','X3'])
result = pd.concat([df1,s1,s1,s1,s1,s1],axis=1)

In [26]:
result

    A   B   C   D   0   1   2   3   4
0  A0  B0  C0  D0  X0  X0  X0  X0  X0
1  A1  B1  C1  D1  X1  X1  X1  X1  X1
2  A2  B2  C2  D2  X2  X2  X2  X2  X2
3  A3  B3  C3  D3  X3  X3  X3  X3  X3

In [27]:
result = pd.concat([df1,s1],ignore_index=True,axis=1)
result

    0   1   2   3   4
0  A0  B0  C0  D0  X0
1  A1  B1  C1  D1  X1
2  A2  B2  C2  D2  X2
3  A3  B3  C3  D3  X3

In [28]:
result = pd.concat(frames,keys=['x','y','z'])
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

In [29]:
result.loc['x']

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [30]:
#merge
left = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)
right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

In [31]:
result=pd.merge(left,right,on='key')

In [32]:
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [34]:
result=pd.merge(left,right,on='key',how='inner')

In [35]:
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [36]:
result=pd.merge(left,right,on='key',how='left')

In [37]:
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [38]:
result=pd.merge(left,right,on='key',how='right')
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [39]:
result=pd.merge(left,right,on='key',how='outer')
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [40]:
left = pd.DataFrame(
   {
      "key1": ["K0", "K0", "K1", "K2"],
      "key2": ["K0", "K1", "K0", "K1"],
      "A": ["A0", "A1", "A2", "A3"],
      "B": ["B0", "B1", "B2", "B3"],
   }
)
right = pd.DataFrame(
   {
      "key1": ["K0", "K1", "K1", "K2"],
      "key2": ["K0", "K0", "K0", "K0"],
      "C": ["C0", "C1", "C2", "C3"],
      "D": ["D0", "D1", "D2", "D3"],
   }
)

In [41]:
result = pd.merge(left,right,on=['key1','key2'])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [42]:
result = pd.merge(left,right,on=['key1','key2'],how='inner')
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [43]:
result = pd.merge(left,right,on=['key1','key2'],how='outer')
result

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN