In [1]:
import numpy as np 
import pandas as pd

In [2]:
df1 = pd.read_csv('Example1.csv')

In [3]:
df1.head()

,IMPDS Deduplication,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,S.No.,District Name,Total Duplicate Records,Total Field Survey,Recommended for Cancellation/Blocked
1,1,AGAR MALWA,997,961,35
2,2,ALIRAJPUR,492,480,17
3,3,ANUPPUR,2077,1981,165
4,4,ASHOKNAGAR,336,335,89

In [4]:
df2 = pd.read_csv('Example2.csv')

In [5]:
df2.head()

                             IMPDS Deduplication::::
0  S.No.:District Name:Total Duplicate Records:To...
1                            1:AGAR MALWA:997:961:35
2                             2:ALIRAJPUR:492:480:17
3                            3:ANUPPUR:2077:1981:165
4                            4:ASHOKNAGAR:336:335:89

In [6]:
df3 = pd.read_csv('Example2.csv', sep=':')

In [8]:
df3.head()

,IMPDS Deduplication,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,S.No.,District Name,Total Duplicate Records,Total Field Survey,Recommended for Cancellation/Blocked
1,1,AGAR MALWA,997,961,35
2,2,ALIRAJPUR,492,480,17
3,3,ANUPPUR,2077,1981,165
4,4,ASHOKNAGAR,336,335,89

In [9]:
df4 = pd.read_csv('Example2.csv', sep=':', header=1)

In [10]:
df4.head()

,S.No.,District Name,Total Duplicate Records,Total Field Survey,Recommended for Cancellation/Blocked
0,1,AGAR MALWA,997,961,35
1,2,ALIRAJPUR,492,480,17
2,3,ANUPPUR,2077,1981,165
3,4,ASHOKNAGAR,336,335,89
4,5,BALAGHAT,5285,5246,284

In [11]:
df5 = pd.read_csv('Example2.csv', sep=':', header=1,nrows=7)

In [12]:
df5

,S.No.,District Name,Total Duplicate Records,Total Field Survey,Recommended for Cancellation/Blocked
0,1,AGAR MALWA,997,961,35
1,2,ALIRAJPUR,492,480,17
2,3,ANUPPUR,2077,1981,165
3,4,ASHOKNAGAR,336,335,89
4,5,BALAGHAT,5285,5246,284
5,6,BARWANI,2360,2353,201
6,7,BETUL,1809,1770,32

In [14]:
df6 = pd.read_csv('Example2.csv', sep=':', header=1,nrows=7, usecols=[0,2,4])

In [15]:
df6

   S.No.  Total Duplicate Records  Recommended for Cancellation/Blocked
0      1                      997                                    35
1      2                      492                                    17
2      3                     2077                                   165
3      4                      336                                    89
4      5                     5285                                   284
5      6                     2360                                   201
6      7                     1809                                    32

In [16]:
df6 = pd.read_csv('Example2.csv', sep=':', header=1,nrows=7, usecols=[1,3])

In [17]:
df6

  District Name  Total Field Survey
0    AGAR MALWA                 961
1     ALIRAJPUR                 480
2       ANUPPUR                1981
3    ASHOKNAGAR                 335
4      BALAGHAT                5246
5       BARWANI                2353
6         BETUL                1770

In [19]:
df5.columns

Index(['S.No.', 'District Name', 'Total Duplicate Records',
       'Total Field Survey', 'Recommended for Cancellation/Blocked'],
      dtype='object')

In [21]:
df7 = pd.read_csv('Example2.csv', sep=':', header=1,nrows=7, usecols=['District Name', 'Total Duplicate Records'])

In [22]:
df7

  District Name  Total Duplicate Records
0    AGAR MALWA                      997
1     ALIRAJPUR                      492
2       ANUPPUR                     2077
3    ASHOKNAGAR                      336
4      BALAGHAT                     5285
5       BARWANI                     2360
6         BETUL                     1809

In [28]:
df8 = pd.read_csv('Example2.csv', sep=':', header=1,nrows=7, index_col=[0])

In [29]:
df8.head()

,District Name,Total Duplicate Records,Total Field Survey,Recommended for Cancellation/Blocked
S.No.,,,,
1,AGAR MALWA,997,961,35
2,ALIRAJPUR,492,480,17
3,ANUPPUR,2077,1981,165
4,ASHOKNAGAR,336,335,89
5,BALAGHAT,5285,5246,284

In [30]:
df9 = pd.read_csv('Example2.csv', sep=':', skiprows=5)

In [31]:
df9.head()

   4 ASHOKNAGAR   336   335   89
0  5   BALAGHAT  5285  5246  284
1  6    BARWANI  2360  2353  201
2  7      BETUL  1809  1770   32
3  8      BHIND   688   670  190
4  9     BHOPAL  3923  3867  721

In [33]:
df10 = pd.read_csv('Example2.csv', sep=':', header=1,nrows=7, index_col=[0], chunksize=10)

In [34]:
df10

In [39]:
df11 = pd.read_excel('ex2.xlsx')

In [40]:
df11.tail()

,Sno,Team,Position,Name,Number,Age,Height,Weight,College,Salary
145,145,Washington Wizards,PF,Drew Gooden,90,34,6-10,250.0,Kansas,3300000.0
146,146,Washington Wizards,PG,Ramon Sessions,7,30,6-3,190.0,Nevada,2170465.0
147,147,Washington Wizards,SF,Jared Dudley,1,30,6-7,225.0,Boston College,4375000.0
148,148,Washington Wizards,SG,Alan Anderson,6,33,6-6,220.0,Michigan State,4000000.0
149,Total,NaN,NaN,NaN,2601,4066,0,NaN,NaN,NaN

In [41]:
df12 = pd.read_excel('ex2.xlsx', skipfooter=1)

In [43]:
df12.tail()

,Sno,Team,Position,Name,Number,Age,Height,Weight,College,Salary
144,144,Washington Wizards,C,Marcin Gortat,13,32,6-11,240,North Carolina State,11217391
145,145,Washington Wizards,PF,Drew Gooden,90,34,6-10,250,Kansas,3300000
146,146,Washington Wizards,PG,Ramon Sessions,7,30,6-3,190,Nevada,2170465
147,147,Washington Wizards,SF,Jared Dudley,1,30,6-7,225,Boston College,4375000
148,148,Washington Wizards,SG,Alan Anderson,6,33,6-6,220,Michigan State,4000000