In [45]:
import numpy as np
import pandas as pd

In [47]:
df=pd.read_excel('sales-funnel.xlsx')

In [49]:
df

,Account,Name,Rep,Manager,Product,Quantity,Price,Status
0,714466,Trantow-Barrows,Craig Booker,Debra Henley,CPU,1,30000,presented
1,714466,Trantow-Barrows,Craig Booker,Debra Henley,Software,1,10000,presented
2,714466,Trantow-Barrows,Craig Booker,Debra Henley,Maintenance,2,5000,pending
3,737550,"Fritsch, Russel and Anderson",Craig Booker,Debra Henley,CPU,1,35000,declined
4,146832,Kiehn-Spinka,Daniel Hilton,Debra Henley,CPU,2,65000,won
5,218895,Kulas Inc,Daniel Hilton,Debra Henley,CPU,2,40000,pending
6,218895,Kulas Inc,Daniel Hilton,Debra Henley,Software,1,10000,presented
7,412290,Jerde-Hilpert,John Smith,Debra Henley,Maintenance,2,5000,pending
8,740150,Barton LLC,John Smith,Debra Henley,CPU,1,35000,declined
9,141962,Herman LLC,Cedric Moss,Fred Anderson,CPU,2,65000,won
10,163416,Purdy-Kunde,Cedric Moss,Fred Anderson,CPU,1,30000,presented
11,239344,Stokes LLC,Cedric Moss,Fred Anderson,Maintenance,1,5000,pending
12,239344,Stokes LLC,Cedric Moss,Fred Anderson,Software,1,10000,presented
13,307599,"Kassulke, Ondricka and Metz",Wendy Yule,Fred Anderson,Maintenance,3,7000,won
14,688981,Keeling LLC,Wendy Yule,Fred Anderson,CPU,5,100000,won
15,729833,Koepp Ltd,Wendy Yule,Fred Anderson,CPU,2,65000,declined
16,729833,Koepp Ltd,Wendy Yule,Fred Anderson,Monitor,2,5000,presented

In [50]:
pd.pivot_table(df,index=['Manager','Rep'],values=['Price'],aggfunc=[np.mean,len])

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\2323121681.py:1: FutureWarning: The provided callable <function mean at 0x0000016327112980> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,index=['Manager','Rep'],values=['Price'],aggfunc=[np.mean,len])

                                     mean   len
                                    Price Price
Manager       Rep
Debra Henley  Craig Booker   20000.000000     4
              Daniel Hilton  38333.333333     3
              John Smith     20000.000000     2
Fred Anderson Cedric Moss    27500.000000     4
              Wendy Yule     44250.000000     4

In [52]:
pd.pivot_table(df,index=['Manager','Rep'],values=['Price'],columns='Product',aggfunc=np.sum)

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\914273088.py:1: FutureWarning: The provided callable <function sum at 0x00000163271118A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=['Manager','Rep'],values=['Price'],columns='Product',aggfunc=np.sum)

                                Price
Product                           CPU Maintenance Monitor Software
Manager       Rep
Debra Henley  Craig Booker    65000.0      5000.0     NaN  10000.0
              Daniel Hilton  105000.0         NaN     NaN  10000.0
              John Smith      35000.0      5000.0     NaN      NaN
Fred Anderson Cedric Moss     95000.0      5000.0     NaN  10000.0
              Wendy Yule     165000.0      7000.0  5000.0      NaN

In [55]:
pd.pivot_table(df,index=['Manager','Rep'],values=['Price'],columns='Product',aggfunc=np.sum,fill_value=0)

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\2884246736.py:1: FutureWarning: The provided callable <function sum at 0x00000163271118A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=['Manager','Rep'],values=['Price'],columns='Product',aggfunc=np.sum,fill_value=0)

                              Price
Product                         CPU Maintenance Monitor Software
Manager       Rep
Debra Henley  Craig Booker    65000        5000       0    10000
              Daniel Hilton  105000           0       0    10000
              John Smith      35000        5000       0        0
Fred Anderson Cedric Moss     95000        5000       0    10000
              Wendy Yule     165000        7000    5000        0

In [57]:
pd.pivot_table(df,index=['Manager','Rep'],values=['Price','Quantity'],columns='Product',aggfunc=np.sum,fill_value=0)

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\3660751736.py:1: FutureWarning: The provided callable <function sum at 0x00000163271118A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=['Manager','Rep'],values=['Price','Quantity'],columns='Product',aggfunc=np.sum,fill_value=0)

                              Price                              Quantity  \
Product                         CPU Maintenance Monitor Software      CPU
Manager       Rep
Debra Henley  Craig Booker    65000        5000       0    10000        2
              Daniel Hilton  105000           0       0    10000        4
              John Smith      35000        5000       0        0        1
Fred Anderson Cedric Moss     95000        5000       0    10000        3
              Wendy Yule     165000        7000    5000        0        7


Product                     Maintenance Monitor Software
Manager       Rep
Debra Henley  Craig Booker            2       0        1
              Daniel Hilton           0       0        1
              John Smith              2       0        0
Fred Anderson Cedric Moss             1       0        1
              Wendy Yule              3       2        0

In [58]:
pd.pivot_table(df,index=['Manager','Rep','Product'],values=['Price','Quantity'],aggfunc=[np.sum,np.mean],fill_value=0)

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\3352771503.py:1: FutureWarning: The provided callable <function sum at 0x00000163271118A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=['Manager','Rep','Product'],values=['Price','Quantity'],aggfunc=[np.sum,np.mean],fill_value=0)
C:\Users\HP\AppData\Local\Temp\ipykernel_25944\3352771503.py:1: FutureWarning: The provided callable <function mean at 0x0000016327112980> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,index=['Manager','Rep','Product'],values=['Price','Quantity'],aggfunc=[np.sum,np.mean],fill_value=0)

                                            sum              mean
                                          Price Quantity    Price Quantity
Manager       Rep           Product
Debra Henley  Craig Booker  CPU           65000        2  32500.0      1.0
                            Maintenance    5000        2   5000.0      2.0
                            Software      10000        1  10000.0      1.0
              Daniel Hilton CPU          105000        4  52500.0      2.0
                            Software      10000        1  10000.0      1.0
              John Smith    CPU           35000        1  35000.0      1.0
                            Maintenance    5000        2   5000.0      2.0
Fred Anderson Cedric Moss   CPU           95000        3  47500.0      1.5
                            Maintenance    5000        1   5000.0      1.0
                            Software      10000        1  10000.0      1.0
              Wendy Yule    CPU          165000        7  82500.0      3.5
                            Maintenance    7000        3   7000.0      3.0
                            Monitor        5000        2   5000.0      2.0

In [60]:
pd.pivot_table(df,index=['Manager','Rep','Product'],values=['Price','Quantity'],aggfunc=[np.sum,np.mean],fill_value=0,margins=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\1351226111.py:1: FutureWarning: The provided callable <function sum at 0x00000163271118A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(df,index=['Manager','Rep','Product'],values=['Price','Quantity'],aggfunc=[np.sum,np.mean],fill_value=0,margins=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_25944\1351226111.py:1: FutureWarning: The provided callable <function mean at 0x0000016327112980> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,index=['Manager','Rep','Product'],values=['Price','Quantity'],aggfunc=[np.sum,np.mean],fill_value=0,margins=True)

                                            sum                   mean  \
                                          Price Quantity         Price
Manager       Rep           Product
Debra Henley  Craig Booker  CPU           65000        2  32500.000000
                            Maintenance    5000        2   5000.000000
                            Software      10000        1  10000.000000
              Daniel Hilton CPU          105000        4  52500.000000
                            Software      10000        1  10000.000000
              John Smith    CPU           35000        1  35000.000000
                            Maintenance    5000        2   5000.000000
Fred Anderson Cedric Moss   CPU           95000        3  47500.000000
                            Maintenance    5000        1   5000.000000
                            Software      10000        1  10000.000000
              Wendy Yule    CPU          165000        7  82500.000000
                            Maintenance    7000        3   7000.000000
                            Monitor        5000        2   5000.000000
All                                      522000       30  30705.882353


                                         Quantity
Manager       Rep           Product
Debra Henley  Craig Booker  CPU          1.000000
                            Maintenance  2.000000
                            Software     1.000000
              Daniel Hilton CPU          2.000000
                            Software     1.000000
              John Smith    CPU          1.000000
                            Maintenance  2.000000
Fred Anderson Cedric Moss   CPU          1.500000
                            Maintenance  1.000000
                            Software     1.000000
              Wendy Yule    CPU          3.500000
                            Maintenance  3.000000
                            Monitor      2.000000
All                                      1.764706

In [61]:
df.pivot_table(index=['Manager','Status'],columns='Product',values=['Price','Quantity'],aggfunc={'Quantity':len ,'Price':np.sum},fill_value=0)

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\293089584.py:1: FutureWarning: The provided callable <function sum at 0x00000163271118A0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index=['Manager','Status'],columns='Product',values=['Price','Quantity'],aggfunc={'Quantity':len ,'Price':np.sum},fill_value=0)

                          Price                              Quantity  \
Product                     CPU Maintenance Monitor Software      CPU
Manager       Status
Debra Henley  declined    70000           0       0        0        2
              pending     40000       10000       0        0        1
              presented   30000           0       0    20000        1
              won         65000           0       0        0        1
Fred Anderson declined    65000           0       0        0        1
              pending         0        5000       0        0        0
              presented   30000           0    5000    10000        1
              won        165000        7000       0        0        2


Product                 Maintenance Monitor Software
Manager       Status
Debra Henley  declined            0       0        0
              pending             2       0        0
              presented           0       0        2
              won                 0       0        0
Fred Anderson declined            0       0        0
              pending             1       0        0
              presented           0       1        1
              won                 1       0        0

In [63]:
table=pd.pivot_table(df,index=['Manager','Status'],columns=['Product'],values=['Price','Quantity'],aggfunc={'Quantity':len ,'Price':np.sum},fill_value=0)
table

C:\Users\HP\AppData\Local\Temp\ipykernel_25944\574357355.py:1: FutureWarning: The provided callable <function sum at 0x00000163271118A0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  table=pd.pivot_table(df,index=['Manager','Status'],columns=['Product'],values=['Price','Quantity'],aggfunc={'Quantity':len ,'Price':np.sum},fill_value=0)

                          Price                              Quantity  \
Product                     CPU Maintenance Monitor Software      CPU
Manager       Status
Debra Henley  declined    70000           0       0        0        2
              pending     40000       10000       0        0        1
              presented   30000           0       0    20000        1
              won         65000           0       0        0        1
Fred Anderson declined    65000           0       0        0        1
              pending         0        5000       0        0        0
              presented   30000           0    5000    10000        1
              won        165000        7000       0        0        2


Product                 Maintenance Monitor Software
Manager       Status
Debra Henley  declined            0       0        0
              pending             2       0        0
              presented           0       0        2
              won                 0       0        0
Fred Anderson declined            0       0        0
              pending             1       0        0
              presented           0       1        1
              won                 1       0        0

# ADVANCE PIVOT FILTERING

In [68]:
table.query('Manager==["Debra Henley"]')

                        Price                              Quantity  \
Product                   CPU Maintenance Monitor Software      CPU
Manager      Status
Debra Henley declined   70000           0       0        0        2
             pending    40000       10000       0        0        1
             presented  30000           0       0    20000        1
             won        65000           0       0        0        1


Product                Maintenance Monitor Software
Manager      Status
Debra Henley declined            0       0        0
             pending             2       0        0
             presented           0       0        2
             won                 0       0        0

In [72]:
table.query('Status==["pending","won"]')

                        Price                              Quantity  \
Product                   CPU Maintenance Monitor Software      CPU
Manager       Status
Debra Henley  pending   40000       10000       0        0        1
              won       65000           0       0        0        1
Fred Anderson pending       0        5000       0        0        0
              won      165000        7000       0        0        2


Product               Maintenance Monitor Software
Manager       Status
Debra Henley  pending           2       0        0
              won               0       0        0
Fred Anderson pending           1       0        0
              won               1       0        0