# Filtering

In [1]:
import numpy as np
import pandas as pd

#### We are going to use dataset containing details of flights departing from NYC in 2013. This dataset has 336776 rows and 16 columns.

In [3]:
#df = pd.read_csv("https://raw.githubusercontent.com/JackyP/testing/master/datasets/nycflights.csv", usecols=range(1,17))

In [39]:
df = pd.read_csv("nycflights.csv",usecols = range(1,17))

In [41]:
df.columns

Index(['year', 'month', 'day', 'dep_time', 'dep_delay', 'arr_time',
       'arr_delay', 'carrier', 'tailnum', 'flight', 'origin', 'dest',
       'air_time', 'distance', 'hour', 'minute'],
      dtype='object')

In [ ]:
###### df.info()

In [44]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Columns: 16 entries, year to minute
dtypes: float64(7), int64(5), object(4)
memory usage: 41.1+ MB

In [45]:
df.columns

Index(['year', 'month', 'day', 'dep_time', 'dep_delay', 'arr_time',
       'arr_delay', 'carrier', 'tailnum', 'flight', 'origin', 'dest',
       'air_time', 'distance', 'hour', 'minute'],
      dtype='object')

In [46]:
df[5:7]

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
5,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0
6,2013,1,1,555.0,-5.0,913.0,19.0,B6,N516JB,507,EWR,FLL,158.0,1065,5.0,55.0

In [47]:
df.head(1)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0

In [50]:
df.iloc[0,1:5]

month            1
day              1
dep_time     517.0
dep_delay      2.0
Name: 0, dtype: object

In [55]:
df.shape

(336776, 16)

df.describe()

In [58]:
df.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0

## Filter pandas dataframe by column value

#### Condition : Select flights details of JetBlue Airways that has 2 letters carrier code B6 with origin from JFK airport

### Method 1 : DataFrame Way

In [64]:
df.columns

Index(['year', 'month', 'day', 'dep_time', 'dep_delay', 'arr_time',
       'arr_delay', 'carrier', 'tailnum', 'flight', 'origin', 'dest',
       'air_time', 'distance', 'hour', 'minute'],
      dtype='object')

In [66]:
newdf = df[df.origin == "JFK"]
newdf.shape

(111276, 16)

In [68]:
newdf = df[df['origin'] == "JFK"]
newdf.shape

(111276, 16)

In [70]:
df.origin.unique()

array(['EWR', 'LGA', 'JFK', 'jfk', 'Jfk', 'jFk'], dtype=object)

In [72]:
df.origin = df.origin.str.upper()

In [74]:
df.origin.unique()

array(['EWR', 'LGA', 'JFK'], dtype=object)

In [76]:
newdf = df[df['origin'] == "JFK"]
newdf.shape

(111279, 16)

In [32]:
newdf

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
8,2013,1,1,557.0,-3.0,838.0,-8.0,B6,N593JB,79,JFK,MCO,140.0,944,5.0,57.0
10,2013,1,1,558.0,-2.0,849.0,-2.0,B6,N793JB,49,JFK,PBI,149.0,1028,5.0,58.0
11,2013,1,1,558.0,-2.0,853.0,-3.0,B6,N657JB,71,JFK,TPA,158.0,1005,5.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336766,2013,9,30,2240.0,-10.0,2347.0,-20.0,B6,N281JB,2002,JFK,BUF,52.0,301,22.0,40.0
336767,2013,9,30,2241.0,-5.0,2345.0,-16.0,B6,N346JB,486,JFK,ROC,47.0,264,22.0,41.0
336768,2013,9,30,2307.0,12.0,2359.0,1.0,B6,N565JB,718,JFK,BOS,33.0,187,23.0,7.0
336769,2013,9,30,2349.0,-10.0,325.0,-25.0,B6,N516JB,745,JFK,PSE,196.0,1617,23.0,49.0
336771,2013,9,30,NaN,NaN,NaN,NaN,9E,NaN,3393,JFK,DCA,NaN,213,NaN,NaN

In [33]:
newdf.origin.unique()

array(['JFK'], dtype=object)

In [34]:
newdf.origin.value_counts()

origin
JFK    111279
Name: count, dtype: int64

In [29]:
newdf = df[(df['origin'] == "JFK") & (df['carrier'] == "B6")]
newdf.shape

(42076, 16)

In [13]:
newdf = df[(df.origin == 'JFK') & (df.carrier == 'B6')]
newdf.shape

(42076, 16)

### Method 2 : Query Function

#### This method is elegant and more readable and you don't need to mention dataframe name everytime when you specify columns (variables).

In [82]:
newdf = df.query('origin=="JFK" | carrier == "B6"')
newdf.shape

(123838, 16)

### Method 3 : loc function

In [15]:
newdf = df.loc[(df.origin=='JFK')&(df.carrier=='B6')]
newdf.shape

(42076, 16)

In [16]:
''' loc is an abbreviation of location term. 
All these 3 methods return same output. 
It's just a different ways of doing filtering rows.'''

" loc is an abbreviation of location term. A\nll these 3 methods return same output. \nIt's just a different ways of doing filtering rows."

## Filter Pandas Dataframe by Row and Column Position

#### Suppose you want to select specific rows by their position (let's say from second through fifth row). We can use df.iloc[ ] function for the same.

In [12]:
print(df.iloc[:5,]) #First 5 rows
print(df.iloc[1:5,]) #Second to Fifth row
print(df.iloc[5,0]) #Sixth row and 1st column
print(df.iloc[1:5,0]) #Second to Fifth row, first column
print(df.iloc[1:5,:5]) #Second to Fifth row, first 5 columns
print(df.iloc[2:7,1:3]) #Third to Seventh row, 2nd and 3rd column

   year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
0  2013      1    1     517.0        2.0     830.0       11.0      UA  N14228
1  2013      1    1     533.0        4.0     850.0       20.0      UA  N24211
2  2013      1    1     542.0        2.0     923.0       33.0      AA  N619AA
3  2013      1    1     544.0       -1.0    1004.0      -18.0      B6  N804JB
4  2013      1    1     554.0       -6.0     812.0      -25.0      DL  N668DN

   flight origin dest  air_time  distance  hour  minute
0    1545    EWR  IAH     227.0      1400   5.0    17.0
1    1714    LGA  IAH     227.0      1416   5.0    33.0
2    1141    JFK  MIA     160.0      1089   5.0    42.0
3     725    JFK  BQN     183.0      1576   5.0    44.0
4     461    LGA  ATL     116.0       762   5.0    54.0
   year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
1  2013      1    1     533.0        4.0     850.0       20.0      UA  N24211
2  2013      1    1     542.0        2.0     923.0       33.0      AA  N619AA
3  2013      1    1     544.0       -1.0    1004.0      -18.0      B6  N804JB
4  2013      1    1     554.0       -6.0     812.0      -25.0      DL  N668DN

   flight origin dest  air_time  distance  hour  minute
1    1714    LGA  IAH     227.0      1416   5.0    33.0
2    1141    JFK  MIA     160.0      1089   5.0    42.0
3     725    JFK  BQN     183.0      1576   5.0    44.0
4     461    LGA  ATL     116.0       762   5.0    54.0
2013
1    2013
2    2013
3    2013
4    2013
Name: year, dtype: int64
   year  month  day  dep_time  dep_delay
1  2013      1    1     533.0        4.0
2  2013      1    1     542.0        2.0
3  2013      1    1     544.0       -1.0
4  2013      1    1     554.0       -6.0
   month  day
2      1    1
3      1    1
4      1    1
5      1    1
6      1    1

## Selecting multiple values of a column

In [37]:
df.origin.unique()

array(['EWR', 'LGA', 'JFK'], dtype=object)

In [13]:
# long way
newdf = df[(df.origin=='JFK')|(df.origin=='LGA')]
print(newdf.shape)
print(newdf.head(2))

(215941, 16)
   year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
1  2013      1    1     533.0        4.0     850.0       20.0      UA  N24211
2  2013      1    1     542.0        2.0     923.0       33.0      AA  N619AA

   flight origin dest  air_time  distance  hour  minute
1    1714    LGA  IAH     227.0      1416   5.0    33.0
2    1141    JFK  MIA     160.0      1089   5.0    42.0

In [14]:
# smart way
newdf = df[df.origin.isin(['JFK','LGA'])]
print(newdf.shape)
print(newdf.head(2))

(215941, 16)
   year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
1  2013      1    1     533.0        4.0     850.0       20.0      UA  N24211
2  2013      1    1     542.0        2.0     923.0       33.0      AA  N619AA

   flight origin dest  air_time  distance  hour  minute
1    1714    LGA  IAH     227.0      1416   5.0    33.0
2    1141    JFK  MIA     160.0      1089   5.0    42.0

## How to negate the whole condition

In [15]:
newdf = df[~((df.origin=='JFK')&(df.carrier=='B6'))]
print(newdf.shape)

(294700, 16)

In [34]:
df

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,NaN,NaN,NaN,9E,NaN,3393,JFK,DCA,NaN,213,NaN,NaN
336772,2013,9,30,NaN,NaN,NaN,NaN,9E,NaN,3525,LGA,SYR,NaN,198,NaN,NaN
336773,2013,9,30,NaN,NaN,NaN,NaN,MQ,N535MQ,3461,LGA,BNA,NaN,764,NaN,NaN
336774,2013,9,30,NaN,NaN,NaN,NaN,MQ,N511MQ,3572,LGA,CLE,NaN,419,NaN,NaN
336775,2013,9,30,NaN,NaN,NaN,NaN,MQ,N839MQ,3531,LGA,RDU,NaN,431,NaN,NaN

## Select Non-Missing Data in Pandas Dataframe

In [16]:
newdf = df[df.origin.notnull()]
print(newdf.shape)

(336776, 16)

## How to Filter Pandas DataFrames by Column of Strings

## Filtering by single string

#### To filter a DataFrame by a single string value in a column, we can use the str.contains() method. The str.contains() method returns a Boolean mask that can be used to select the rows that contain the specified string value in the column.

In [1]:
import numpy as np
import pandas as pd

In [3]:
# create a dataframe
data = {"Name": ["John", "Jane", "Mary", "Adam"],
        "City": ["New York", "Los Angeles", "Chicago", "Houston"]}
df = pd.DataFrame(data)
print(df)
print('\n')

# Filter the DataFrame by a string value in the 'City' column

filtered_df = df[df['City'].str.contains("Los Angeles")]
print(filtered_df)

   Name         City
0  John     New York
1  Jane  Los Angeles
2  Mary      Chicago
3  Adam      Houston


   Name         City
1  Jane  Los Angeles

In [4]:
# create a dataframe
data = {"Name": ["John", "Jane", "Mary", "Adam"],
        "City": ["New York", "Los Angeles", "Chicago", "Houston"]}
df = pd.DataFrame(data)
print(df)
print('\n')

# Filter the DataFrame by a string value in the 'City' column

filtered_df = df[df['City']=="Los Angeles"]
print(filtered_df)

   Name         City
0  John     New York
1  Jane  Los Angeles
2  Mary      Chicago
3  Adam      Houston


   Name         City
1  Jane  Los Angeles

## Filtering by Multiple Strings

In [5]:
# create a dataframe
data = {"Name": ["John", "Jane", "Mary", "Adam"],
        "City": ["New York", "Los Angeles", "Chicago", "Houston"]}
df = pd.DataFrame(data)
print(df)
print('\n')

# Filter the DataFrame by a string value in the 'City' column

filtered_df = df[df['City'].str.contains("Los Angeles|Chicago")]
print(filtered_df)

   Name         City
0  John     New York
1  Jane  Los Angeles
2  Mary      Chicago
3  Adam      Houston


   Name         City
1  Jane  Los Angeles
2  Mary      Chicago

## Filtering by a List of Strings

In [19]:
# create a dataframe
data = {"Name": ["John", "Jane", "Mary", "Adam"],
        "City": ["New York", "Los Angeles", "Chicago", "Houston"]}
df = pd.DataFrame(data)
print(df)
print('\n')

# Filter the DataFrame by a string value in the 'City' column

filtered_df = df[df['City'].isin(["Los Angeles","Chicago"])]
print(filtered_df)

   Name         City
0  John     New York
1  Jane  Los Angeles
2  Mary      Chicago
3  Adam      Houston


   Name         City
1  Jane  Los Angeles
2  Mary      Chicago

In [35]:
df.to_csv("Myfile.csv")