In [1]:
import pandas as pd
import numpy as np

In [2]:
# Creating Dataframe
list = [['Geek', 25], ['is', 30], 
       ['for', 26], ['Geeksforgeeks', 22]]
#df = pd.DataFrame(list, columns=['Tag','Number'])
df = pd.DataFrame(list, columns=['Tag','Number'], index=['a','b','c','d'])
print(df)

list2 = [['Geek1', 28, 'Analyst'],
        ['Geek2', 35, 'Manager'],
        ['Geek3', 29, 'Developer']]
columns = ['Name', 'Age', 'Occupation']

df2 = pd.DataFrame(data=list2,  columns=columns)
print(df2)

df3 = pd.DataFrame(data=list2,  columns=columns, dtype=float)
print(df3)

             Tag  Number
a           Geek      25
b             is      30
c            for      26
d  Geeksforgeeks      22
    Name  Age Occupation
0  Geek1   28    Analyst
1  Geek2   35    Manager
2  Geek3   29  Developer
    Name   Age Occupation
0  Geek1  28.0    Analyst
1  Geek2  35.0    Manager
2  Geek3  29.0  Developer

In [3]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Age         3 non-null      float64
 2   Occupation  3 non-null      object
dtypes: float64(1), object(2)
memory usage: 200.0+ bytes

In [4]:
data = {'Category':['Array', 'Stack', 'Queue'],
        'Marks':[20, 21, 19]}
df4 = pd.DataFrame(data)
print(df4)
print(df4.transpose())

  Category  Marks
0    Array     20
1    Stack     21
2    Queue     19
              0      1      2
Category  Array  Stack  Queue
Marks        20     21     19

In [5]:
data = {'Area':['Array', 'Stack', 'Queue'],
        'Student_1':[20, 21, 19], 'Student_2':[15, 20, 14]} 
df5 = pd.DataFrame(data,index=['Cat_1','Cat_2','Cat_3'])
print(df5)

data = {'Area':['Array', 'Stack', 'Queue'],
        'Student_1':[20, 21, 19], 'Student_2':[15, 20, 14]} 
df6 = pd.DataFrame(data,index=['Cat_1','Cat_2','Cat_3'], columns=['A','Area','B','C'])
print(df6)

        Area  Student_1  Student_2
Cat_1  Array         20         15
Cat_2  Stack         21         20
Cat_3  Queue         19         14
         A   Area    B    C
Cat_1  NaN  Array  NaN  NaN
Cat_2  NaN  Stack  NaN  NaN
Cat_3  NaN  Queue  NaN  NaN

In [6]:
# Creating a dataframe with missing values from a list 

data1 = [['Geek1', 28, 'Engineer'],
        ['Geek2', None, 'Data Scientist'],
        ['Geek3', 32,None]]
columns = ['Name','Age','Occupation']
df7 = pd.DataFrame(data1,columns=columns)
print(df7)
#print(df7.replace({None:np.nan})) # Replacing None with NaN for Missing value

    Name   Age      Occupation
0  Geek1  28.0        Engineer
1  Geek2   NaN  Data Scientist
2  Geek3  32.0            None

In [7]:
# Creating a dataframe using list of tuples
data = [('Peter', 18, 7),
        ('Riff', 15, 6),
        ('John', 17, 8),
        ('Michel', 18, 7),
        ('Sheli', 17, 5) ]
df8 = pd.DataFrame(data, columns=['Name','Age','Score'])
print(df8)

     Name  Age  Score
0   Peter   18      7
1    Riff   15      6
2    John   17      8
3  Michel   18      7
4   Sheli   17      5

In [8]:
print(df8.size)
print(df8.shape)
print(df8.ndim)

15
(5, 3)
2

In [9]:
cars = pd.read_csv("Automobile_data.csv")

In [10]:
print(cars)

          company   body-style  length engine-type  avg-mileage
0     alfa-romero  convertible   168.8        dohc           21
1     alfa-romero    hatchback   171.2        ohcv           19
2            audi        sedan   176.6         ohc           24
3            audi        sedan   176.6         ohc           18
4            audi        sedan   177.3         ohc           19
5            audi        wagon   192.7         ohc           19
6             bmw        sedan   176.8         ohc           23
7             bmw        sedan   176.8         ohc           23
8             bmw        sedan   176.8         ohc           21
9             bmw        sedan   189.0         ohc           16
10            bmw        sedan   193.8         ohc           16
11            bmw        sedan   197.0         ohc           15
12      chevrolet    hatchback   141.1         ohc           47
13      chevrolet    hatchback   155.9         ohc           38
14      chevrolet        sedan   158.8         ohc           38
15          dodge    hatchback   157.3         ohc           31
16          dodge    hatchback   157.3         ohc           31
17          honda        wagon   157.1         ohc           30
18          honda        sedan   175.4         ohc           24
19          honda        sedan   169.1         ohc           25
20          isuzu        sedan   170.7         ohc           24
21          isuzu        sedan   155.9         ohc           38
22          isuzu        sedan   155.9         ohc           38
23         jaguar        sedan   199.6        dohc           15
24         jaguar        sedan   199.6        dohc           15
25         jaguar        sedan   191.7        ohcv           13
26          mazda    hatchback   159.1         ohc           30
27          mazda    hatchback   159.1         ohc           31
28          mazda    hatchback   159.1         ohc           31
29          mazda    hatchback   169.0       rotor           17
30          mazda        sedan   175.0         ohc           31
31  mercedes-benz        sedan   190.9         ohc           22
32  mercedes-benz        wagon   190.9         ohc           22
33  mercedes-benz        sedan   208.1        ohcv           14
34  mercedes-benz      hardtop   199.2        ohcv           14
35     mitsubishi    hatchback   157.3         ohc           37
36     mitsubishi    hatchback   157.3         ohc           31
37     mitsubishi        sedan   172.4         ohc           25
38     mitsubishi        sedan   172.4         ohc           25
39         nissan        sedan   165.3         ohc           45
40         nissan        sedan   165.3         ohc           31
41         nissan        sedan   165.3         ohc           31
42         nissan        wagon   170.2         ohc           31
43         nissan        sedan   184.6        ohcv           19
44        porsche      hardtop   168.9        ohcf           17
45        porsche  convertible   168.9        ohcf           17
46        porsche    hatchback   175.7       dohcv           17
47         toyota    hatchback   158.7         ohc           35
48         toyota    hatchback   158.7         ohc           31
49         toyota    hatchback   158.7         ohc           31
50         toyota        wagon   169.7         ohc           31
51         toyota        wagon   169.7         ohc           27
52         toyota        wagon   169.7         ohc           27
53         toyota        wagon   187.8        dohc           19
54     volkswagen        sedan   171.7         ohc           37
55     volkswagen        sedan   171.7         ohc           27
56     volkswagen        sedan   171.7         ohc           37
57     volkswagen        sedan   171.7         ohc           26
58          volvo        sedan   188.8         ohc           23
59          volvo        wagon   188.8         ohc           23

In [11]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   company      60 non-null     object
 1   body-style   60 non-null     object
 2   length       60 non-null     float64
 3   engine-type  60 non-null     object
 4   avg-mileage  60 non-null     int64
dtypes: float64(1), int64(1), object(3)
memory usage: 2.5+ KB

In [12]:
cars.describe()

           length  avg-mileage
count   60.000000    60.000000
mean   173.170000    25.883333
std     14.128914     8.174146
min    141.100000    13.000000
25%    159.100000    19.000000
50%    171.450000    25.000000
75%    179.125000    31.000000
max    208.100000    47.000000

## Dataframe attribute

In [13]:
cars.index

RangeIndex(start=0, stop=60, step=1)

In [14]:
cars.columns

Index(['company', 'body-style', 'length', 'engine-type', 'avg-mileage'], dtype='object')

In [15]:
cars.dtypes

company         object
body-style      object
length         float64
engine-type     object
avg-mileage      int64
dtype: object

In [16]:
cars.values

array([['alfa-romero', 'convertible', 168.8, 'dohc', 21],
       ['alfa-romero', 'hatchback', 171.2, 'ohcv', 19],
       ['audi', 'sedan', 176.6, 'ohc', 24],
       ['audi', 'sedan', 176.6, 'ohc', 18],
       ['audi', 'sedan', 177.3, 'ohc', 19],
       ['audi', 'wagon', 192.7, 'ohc', 19],
       ['bmw', 'sedan', 176.8, 'ohc', 23],
       ['bmw', 'sedan', 176.8, 'ohc', 23],
       ['bmw', 'sedan', 176.8, 'ohc', 21],
       ['bmw', 'sedan', 189.0, 'ohc', 16],
       ['bmw', 'sedan', 193.8, 'ohc', 16],
       ['bmw', 'sedan', 197.0, 'ohc', 15],
       ['chevrolet', 'hatchback', 141.1, 'ohc', 47],
       ['chevrolet', 'hatchback', 155.9, 'ohc', 38],
       ['chevrolet', 'sedan', 158.8, 'ohc', 38],
       ['dodge', 'hatchback', 157.3, 'ohc', 31],
       ['dodge', 'hatchback', 157.3, 'ohc', 31],
       ['honda', 'wagon', 157.1, 'ohc', 30],
       ['honda', 'sedan', 175.4, 'ohc', 24],
       ['honda', 'sedan', 169.1, 'ohc', 25],
       ['isuzu', 'sedan', 170.7, 'ohc', 24],
       ['isuzu', 'sedan', 155.9, 'ohc', 38],
       ['isuzu', 'sedan', 155.9, 'ohc', 38],
       ['jaguar', 'sedan', 199.6, 'dohc', 15],
       ['jaguar', 'sedan', 199.6, 'dohc', 15],
       ['jaguar', 'sedan', 191.7, 'ohcv', 13],
       ['mazda', 'hatchback', 159.1, 'ohc', 30],
       ['mazda', 'hatchback', 159.1, 'ohc', 31],
       ['mazda', 'hatchback', 159.1, 'ohc', 31],
       ['mazda', 'hatchback', 169.0, 'rotor', 17],
       ['mazda', 'sedan', 175.0, 'ohc', 31],
       ['mercedes-benz', 'sedan', 190.9, 'ohc', 22],
       ['mercedes-benz', 'wagon', 190.9, 'ohc', 22],
       ['mercedes-benz', 'sedan', 208.1, 'ohcv', 14],
       ['mercedes-benz', 'hardtop', 199.2, 'ohcv', 14],
       ['mitsubishi', 'hatchback', 157.3, 'ohc', 37],
       ['mitsubishi', 'hatchback', 157.3, 'ohc', 31],
       ['mitsubishi', 'sedan', 172.4, 'ohc', 25],
       ['mitsubishi', 'sedan', 172.4, 'ohc', 25],
       ['nissan', 'sedan', 165.3, 'ohc', 45],
       ['nissan', 'sedan', 165.3, 'ohc', 31],
       ['nissan', 'sedan', 165.3, 'ohc', 31],
       ['nissan', 'wagon', 170.2, 'ohc', 31],
       ['nissan', 'sedan', 184.6, 'ohcv', 19],
       ['porsche', 'hardtop', 168.9, 'ohcf', 17],
       ['porsche', 'convertible', 168.9, 'ohcf', 17],
       ['porsche', 'hatchback', 175.7, 'dohcv', 17],
       ['toyota', 'hatchback', 158.7, 'ohc', 35],
       ['toyota', 'hatchback', 158.7, 'ohc', 31],
       ['toyota', 'hatchback', 158.7, 'ohc', 31],
       ['toyota', 'wagon', 169.7, 'ohc', 31],
       ['toyota', 'wagon', 169.7, 'ohc', 27],
       ['toyota', 'wagon', 169.7, 'ohc', 27],
       ['toyota', 'wagon', 187.8, 'dohc', 19],
       ['volkswagen', 'sedan', 171.7, 'ohc', 37],
       ['volkswagen', 'sedan', 171.7, 'ohc', 27],
       ['volkswagen', 'sedan', 171.7, 'ohc', 37],
       ['volkswagen', 'sedan', 171.7, 'ohc', 26],
       ['volvo', 'sedan', 188.8, 'ohc', 23],
       ['volvo', 'wagon', 188.8, 'ohc', 23]], dtype=object)

In [17]:
cars.empty

False

In [18]:
cars.size

300

In [19]:
cars.shape

(60, 5)

In [20]:
# Create DataFrame from dict
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

print("DataFrame : ", student_df)

print("DataFrame Index : ", student_df.index)
print("DataFrame Columns : ", student_df.columns)

print("DataFrame Column types : ", student_df.dtypes)

print("DataFrame is empty? : ", student_df.empty)

print("DataFrame Shape : ", student_df.shape)
print("DataFrame Size : ", student_df.size)

print("DataFrame Values : ", student_df.values)

DataFrame :      Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
DataFrame Index :  RangeIndex(start=0, stop=3, step=1)
DataFrame Columns :  Index(['Name', 'Age', 'Marks'], dtype='object')
DataFrame Column types :  Name      object
Age        int64
Marks    float64
dtype: object
DataFrame is empty? :  False
DataFrame Shape :  (3, 3)
DataFrame Size :  9
DataFrame Values :  [['Joe' 20 85.1]
 ['Nat' 21 77.8]
 ['Harry' 19 91.54]]

## Dataframe functions

In [21]:
# Create DataFrame from dict
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

# display dataframe
print("DataFrame : ", student_df)

# select top 2 rows
print(student_df.head(2))

# select bottom 2 rows
print(student_df.tail(2))

# select value at row index 0 and column 'Name'
print(student_df.at[0, 'Name'])

# select value at first row and first column
print(student_df.iat[0, 0])

# select values of 'Name' column
print(student_df.get('Name'))

# select values from row index 0 to 2 and 'Name' column
print(student_df.loc[0:2, ['Name']])

# select values from row index 0 to 2(exclusive) and column position 0 to 2(exclusive)
print(student_df.iloc[0:2, 0:2])

DataFrame :      Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
  Name  Age  Marks
0  Joe   20   85.1
1  Nat   21   77.8
    Name  Age  Marks
1    Nat   21  77.80
2  Harry   19  91.54
Joe
Joe
0      Joe
1      Nat
2    Harry
Name: Name, dtype: object
    Name
0    Joe
1    Nat
2  Harry
  Name  Age
0  Joe   20
1  Nat   21

## Insert columns

In [1]:
import numpy as np
import pandas as pd

In [5]:
# Create dataframe from dict

student_dict = {'Name':['Joe','Nat','Harry'],
                'Age':[20,21,19],
               'Marks':[85.10,77.80,91.54]}
student_df = pd.DataFrame(student_dict)
print(student_df)

student_df['Branch'] = 'Computer Science and Engineering'
print(student_df)

#insert new column in dataframe and display

student_df.insert(loc=2, column='Class',value='A')
print(student_df)

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
    Name  Age  Marks                            Branch
0    Joe   20  85.10  Computer Science and Engineering
1    Nat   21  77.80  Computer Science and Engineering
2  Harry   19  91.54  Computer Science and Engineering
    Name  Age Class  Marks                            Branch
0    Joe   20     A  85.10  Computer Science and Engineering
1    Nat   21     A  77.80  Computer Science and Engineering
2  Harry   19     A  91.54  Computer Science and Engineering

## Drop Single Column

In [2]:
import pandas as pd

In [3]:
student_dict = {'name':['Joe','Nat'], 'age':[20,21], 'marks':[85.10,77.80]}
student_df = pd.DataFrame(student_dict)
print(student_df)

#drop column
student_df = student_df.drop(columns='age')
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name  marks
0  Joe   85.1
1  Nat   77.8

In [4]:
student_dict = {'name':['Joe','Nat'], 'age':[20,21], 'marks':[85.10,77.80]}
student_df = pd.DataFrame(student_dict)
print(student_df)

#drop column using del 
del student_df['age']
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name  marks
0  Joe   85.1
1  Nat   77.8

## Drop multiple columns

In [5]:
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}

student_df = pd.DataFrame(student_dict)
print(student_df.columns.values)

# drop 2 columns at a time
student_df = student_df.drop(columns=['age', 'marks'])

print(student_df.columns.values)

['name' 'age' 'marks']
['name']

In [6]:
#Using drop with axis='columns' or axis=1
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}

student_df = pd.DataFrame(student_dict)
print(student_df.columns.values)
print(student_df)

student_df = student_ 
print(student_df.columns.values)
print(student_df)

['name' 'age' 'marks']
  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8

NameError: name 'student_' is not defined

In [26]:
#Using drop with axis='columns' or axis=1
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}

student_df = pd.DataFrame(student_dict)
print(student_df.columns.values)
print(student_df)

student_df = student_df.drop(['age','name'], axis='columns')
print(student_df.columns.values)

print(student_df)

['name' 'age' 'marks']
  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
['marks']
   marks
0   85.1
1   77.8

In [27]:
# Drop column using inplace

import pandas as pd

student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}

student_df = pd.DataFrame(student_dict)
print(student_df)

# drop columns in place
student_df.drop(columns=['age', 'marks'], inplace=False)
print(student_df)

student_df.drop(columns=['age', 'marks'], inplace=True)
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name
0  Joe
1  Nat

In [ ]:
## Drop column by suppressing errors

In [28]:

student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}

student_df = pd.DataFrame(student_dict)
print(student_df)

student_df = student_df.drop(columns='salary',errors='ignore') # No change in the student_df
print(student_df)

student_df = student_df.drop(columns='salary') # KeyError: "['salary'] not found in axis"
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8

KeyError: "['salary'] not found in axis"

## Drop the last column

In [32]:
student_dict = {"name":["Joe","Nat"], "age":[20,21],"marks":[85.10,77.80]}
student_df = pd.DataFrame(student_dict)
print(student_df)

# find position of the last columns and drop
pos = len(student_df.columns)-1
print(pos)

student_df = student_df.drop(columns=student_df.columns[pos])
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
2
  name  age
0  Joe   20
1  Nat   21

In [33]:
student_dict = {"name":["Joe","Nat"], "age":[20,21],"marks":[85.10,77.80]}
student_df = pd.DataFrame(student_dict)
print(student_df)

student_df = student_df.drop(columns=student_df.columns[-1])
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name  age
0  Joe   20
1  Nat   21

## Drop range of columns using iloc

In [34]:
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}
student_df = pd.DataFrame(student_dict)
print(student_df)
print(student_df.columns)
print(student_df.values)

student_df = student_df.drop(columns=student_df.iloc[:,1:3])
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
Index(['name', 'age', 'marks'], dtype='object')
[['Joe' 20 85.1]
 ['Nat' 21 77.8]]
  name
0  Joe
1  Nat

## Drop first n columns

In [2]:
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80], "class": ["A", "B"],
                "city": ["London", "Zurich"]}
student_df = pd.DataFrame(student_dict)
print(student_df)

print(student_df.drop(columns=student_df.iloc[:,range(2)]))
print(student_df)

print(student_df.drop(columns=student_df.iloc[:,range(2)],inplace=True))
print(student_df)

  name  age  marks class    city
0  Joe   20   85.1     A  London
1  Nat   21   77.8     B  Zurich
   marks class    city
0   85.1     A  London
1   77.8     B  Zurich
  name  age  marks class    city
0  Joe   20   85.1     A  London
1  Nat   21   77.8     B  Zurich
None
   marks class    city
0   85.1     A  London
1   77.8     B  Zurich

## Drop all the columns using loc

In [36]:
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}

student_df = pd.DataFrame(student_dict)
print(student_df)

student_df = student_df.drop(columns=student_df.loc[:])
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
Empty DataFrame
Columns: []
Index: [0, 1]

In [39]:
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}

student_df = pd.DataFrame(student_dict)
print(student_df)

student_df = student_df.drop(columns=student_df.iloc[:,:])
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
Empty DataFrame
Columns: []
Index: [0, 1]

In [ ]:
## Drop column using pandas DataFrame.pop() function(it can not delete multiple columns)

In [40]:
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}
student_df = pd.DataFrame(student_dict)
print(student_df)

student_df.pop('age')
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name  marks
0  Joe   85.1
1  Nat   77.8

In [ ]:
## Drop column using pandas DataFrame delete(it can not delete multiple columns)

In [41]:
student_dict = {"name": ["Joe", "Nat"], "age": [20, 21], "marks": [85.10, 77.80]}
student_df = pd.DataFrame(student_dict)
print(student_df)

del student_df['age']
print(student_df)

  name  age  marks
0  Joe   20   85.1
1  Nat   21   77.8
  name  marks
0  Joe   85.1
1  Nat   77.8

In [42]:
mo = pd.read_excel('mobile_not_seeded_30_1_2024.xlsx')

In [43]:
type(mo)

pandas.core.frame.DataFrame

In [44]:
mo.head(5)

    district                       block   fps_id     rc_id  units scheme
0    Khandwa      Nagar Praishad, MUNDI   1312001  20327341      1    PHH
1  Singrauli      Nagar Nigam, SINGROULI  5008007  20333201      4    PHH
2    Khandwa    Janpad Panchayat, HARSUD  1305010  23263540      2    PHH
3      Sidhi  Janpad Panchayat, MAJHAULI  1504054  23972011      1    PHH
4    Khandwa    Janpad Panchayat, PUNASA  1303021  28446598      4    PHH

In [45]:
mo.shape

(939109, 6)

In [46]:
mo.columns

Index(['district', 'block', 'fps_id', 'rc_id', 'units', 'scheme'], dtype='object')

In [47]:
m1 = mo.groupby(['district','block','fps_id'],as_index=False)['rc_id'].count()

In [48]:
m1.sort_values(['district','rc_id'],ascending=[True,False])

      district                       block   fps_id  rc_id
199       Agar    Janpad Panchayat, SUSNER  1907026    181
131       Agar  Janpad Panchayat, NALKHEDA  1908005    108
70        Agar     Janpad Panchayat, BAROD  1906013    106
228       Agar    Janpad Panchayat, SUSNER  5103018     92
266       Agar     Nagar Praishad, SUSNER   1917002     86
...        ...                         ...      ...    ...
27074  Vidisha    Janpad Panchayat, Sironj  2706054      1
27092  Vidisha    Janpad Panchayat, Sironj  2706092      1
27134  Vidisha   Janpad Panchayat, Vidisha  2701011      1
27154  Vidisha   Janpad Panchayat, Vidisha  2701031      1
27159  Vidisha   Janpad Panchayat, Vidisha  2701036      1

[27288 rows x 4 columns]

In [49]:
status = pd.read_excel('status.xlsx')

In [50]:
status.head()

    fps_id  Total_Cards  Status
0  1905003          355  Online
1  1905004          483  Online
2  1905005          264  Online
3  1905006          359  Online
4  1905007          685  Online

In [51]:
Final = pd.merge(m1,status, on='fps_id',how='left')

In [52]:
Final['Remain'] = Final['rc_id']/Final['Total_Cards']*100

In [53]:
Final['Remain'] = round(Final['Remain'],0)

In [54]:
Final.sort_values(['district','Remain'],ascending=[True,False]).to_excel('FInal Not Seeded.xlsx')

## Drop Duplicates in Pandas DataFrame

### Drop duplicates but keep first

In [1]:
import numpy as np
import pandas as pd

In [3]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
#create dataframe
student_df = pd.DataFrame(student_dict)
print(student_df)

#drop duplicate rows
student_df = student_df.drop_duplicates()
print('\n')
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

### Drop Duplicates but Keep Last

In [60]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
#create dataframe
student_df = pd.DataFrame(student_dict)
print(student_df)
print('\n')
#drop duplicate rows
student_df = student_df.drop_duplicates(keep='last')
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80

### Drop all duplicates

In [62]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
#create dataframe
student_df = pd.DataFrame(student_dict)
print(student_df)
print('\n')
#drop duplicate rows
student_df = student_df.drop_duplicates(keep=False)
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
2  Harry   19  91.54

## Drop duplicates from defined columns

In [68]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
# create dataframe from dict
student_df = pd.DataFrame(student_dict)
print(student_df)
print('\n')

student_df = student_df.drop_duplicates(subset=['age','marks'])
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

## Drop duplicates in place

In [70]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
# create dataframe from dict
student_df = pd.DataFrame(student_dict)
print(student_df)
print('\n')

student_df.drop_duplicates(inplace=False)
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80

In [71]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
# create dataframe from dict
student_df = pd.DataFrame(student_dict)
print(student_df)
print('\n')

student_df.drop_duplicates(inplace=True)
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

## Drop duplicates and reset the index

In [75]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
# create dataframe from dict
student_df = pd.DataFrame(student_dict)
print(student_df)
print('\n')

student_df = student_df.drop_duplicates(keep='last',ignore_index=False)
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80

In [76]:
student_dict = {'name': ["Joe", "Nat", "Harry", "Joe", "Nat"],
               'age': [20, 21, 19, 20, 21],
               'marks': [85.10, 77.80, 91.54, 85.10, 77.80] }
# create dataframe from dict
student_df = pd.DataFrame(student_dict)
print(student_df)
print('\n')

student_df = student_df.drop_duplicates(keep='last',ignore_index=True)
print(student_df)

    name  age  marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
3    Joe   20  85.10
4    Nat   21  77.80


    name  age  marks
0  Harry   19  91.54
1    Joe   20  85.10
2    Nat   21  77.80

## Creating a Dataframe to drop Rows

In [19]:
df = pd.read_csv('nba.csv')

In [20]:
df.shape

(458, 9)

In [21]:
df.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0

In [23]:
df.Age.unique()

array([25., 27., 22., 29., 21., 24., 20., 26., 28., 32., 23., 30., 33.,
       34., 37., 36., 31., 38., 39., 19., 35., 40., nan])

In [24]:
df.Age.value_counts()

Age
24.0    47
25.0    45
27.0    41
23.0    41
26.0    36
28.0    31
30.0    31
29.0    28
22.0    26
31.0    22
20.0    19
21.0    19
33.0    14
32.0    13
34.0    10
36.0    10
35.0     9
37.0     4
38.0     4
40.0     3
39.0     2
19.0     2
Name: count, dtype: int64

#### Delete Rows Based on Multiple Conditions on a Column Using drop()

In [25]:
# Delete all rows with column 'Age' has value 20 to 25 
indexAge = df[(df.Age>=20) & (df.Age<=25)].index

In [26]:
indexAge

Index([  0,   1,   3,   6,   7,   8,   9,  10,  13,  16,
       ...
       438, 441, 443, 444, 445, 446, 447, 449, 452, 454],
      dtype='int64', length=197)

In [27]:
len(indexAge)

197

In [28]:
df.drop(indexAge, inplace=True)

In [29]:
df.Age.unique()

array([27., 29., 26., 28., 32., 30., 33., 34., 37., 36., 31., 38., 39.,
       19., 35., 40., nan])

In [30]:
df.Age.value_counts()

Age
27.0    41
26.0    36
28.0    31
30.0    31
29.0    28
31.0    22
33.0    14
32.0    13
34.0    10
36.0    10
35.0     9
37.0     4
38.0     4
40.0     3
39.0     2
19.0     2
Name: count, dtype: int64

In [33]:
# Delete rows where the 'Name' is 'John Holland' or the 'Position' is 'SG'
indexAge = df[(df.Name =='John Holland')| (df.Position == 'SG')].index
df.drop(indexAge, inplace=True)

In [34]:
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
...,...,...,...,...,...,...,...,...,...
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df.sort_values('Name')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
275,Alexis Ajinca,New Orleans Pelicans,42.0,C,28.0,7-2,248.0,NaN,4389607.0
...,...,...,...,...,...,...,...,...,...
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN