In [4]:
import numpy as np
import pandas as pd

In [5]:
student = pd.read_csv("students_marks (4).csv")

In [6]:
student.head()

  StudentID  Math  Science  English  History  Art
0      S001    44       48       70       18   51
1      S002    47       49       85       17   30
2      S003    64       69       31       93   53
3      S004    67       41       13       84   58
4      S005    67       35       71        2   43

In [7]:
student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  100 non-null    object
 1   Math       100 non-null    int64
 2   Science    100 non-null    int64
 3   English    100 non-null    int64
 4   History    100 non-null    int64
 5   Art        100 non-null    int64
dtypes: int64(5), object(1)
memory usage: 4.8+ KB

In [8]:
student.columns

Index(['StudentID', 'Math', 'Science', 'English', 'History', 'Art'], dtype='object')

In [9]:
student[['StudentID','Math']]

   StudentID  Math
0       S001    44
1       S002    47
2       S003    64
3       S004    67
4       S005    67
..       ...   ...
95      S096    58
96      S097    23
97      S098    79
98      S099    13
99      S100    85

[100 rows x 2 columns]

In [10]:
student.Math

0     44
1     47
2     64
3     67
4     67
      ..
95    58
96    23
97    79
98    13
99    85
Name: Math, Length: 100, dtype: int64

In [11]:
student['Total_Marks'] = student.Math + student.Science  +student.English+student.History +student.Art

In [12]:
student['Percentage'] = round((student.Total_Marks/500)*100,2)

In [13]:
student

   StudentID  Math  Science  English  History  Art  Total_Marks  Percentage
0       S001    44       48       70       18   51          231        46.2
1       S002    47       49       85       17   30          228        45.6
2       S003    64       69       31       93   53          310        62.0
3       S004    67       41       13       84   58          263        52.6
4       S005    67       35       71        2   43          218        43.6
..       ...   ...      ...      ...      ...  ...          ...         ...
95      S096    58       61       67       91   98          375        75.0
96      S097    23       83       35       51   97          289        57.8
97      S098    79       33       30       99   43          284        56.8
98      S099    13       32       29       18    3           95        19.0
99      S100    85      100       33       34   12          264        52.8

[100 rows x 8 columns]

In [14]:
student['Percentage'] = round((student.Total_Marks/500)*100,1)

In [15]:
student

   StudentID  Math  Science  English  History  Art  Total_Marks  Percentage
0       S001    44       48       70       18   51          231        46.2
1       S002    47       49       85       17   30          228        45.6
2       S003    64       69       31       93   53          310        62.0
3       S004    67       41       13       84   58          263        52.6
4       S005    67       35       71        2   43          218        43.6
..       ...   ...      ...      ...      ...  ...          ...         ...
95      S096    58       61       67       91   98          375        75.0
96      S097    23       83       35       51   97          289        57.8
97      S098    79       33       30       99   43          284        56.8
98      S099    13       32       29       18    3           95        19.0
99      S100    85      100       33       34   12          264        52.8

[100 rows x 8 columns]

In [16]:
Feedback = []
for i in student.Percentage:
    if i>=75:
        Feedback.append('Hons')
    elif i >= 60:
        Feedback.append('First Division')
    elif i>=40:
        Feedback.append('Second Division')
    elif i>=33:
        Feedback.append('Third Division')
    else:
        Feedback.append('Fail')

student['Result'] = Feedback
student

,StudentID,Math,Science,English,History,Art,Total_Marks,Percentage,Result
0,S001,44,48,70,18,51,231,46.2,Second Division
1,S002,47,49,85,17,30,228,45.6,Second Division
2,S003,64,69,31,93,53,310,62.0,First Division
3,S004,67,41,13,84,58,263,52.6,Second Division
4,S005,67,35,71,2,43,218,43.6,Second Division
...,...,...,...,...,...,...,...,...,...
95,S096,58,61,67,91,98,375,75.0,Hons
96,S097,23,83,35,51,97,289,57.8,Second Division
97,S098,79,33,30,99,43,284,56.8,Second Division
98,S099,13,32,29,18,3,95,19.0,Fail
99,S100,85,100,33,34,12,264,52.8,Second Division

In [17]:
student.nunique()

StudentID      100
Math            63
Science         63
English         65
History         67
Art             66
Total_Marks     80
Percentage      80
Result           5
dtype: int64

In [18]:
student.Result.value_counts()

Result
Second Division    60
First Division     18
Fail               11
Third Division      9
Hons                2
Name: count, dtype: int64

In [19]:
student.Result.value_counts().sort_values(ascending=False)

Result
Second Division    60
First Division     18
Fail               11
Third Division      9
Hons                2
Name: count, dtype: int64

In [20]:
student.columns[0]

'StudentID'

In [21]:
student.columns[3:5]

Index(['English', 'History'], dtype='object')

In [22]:
#how to get column name in pandas data frame 
for i in student.columns:
    print(i)

StudentID
Math
Science
English
History
Art
Total_Marks
Percentage
Result

In [23]:
student.columns

Index(['StudentID', 'Math', 'Science', 'English', 'History', 'Art',
       'Total_Marks', 'Percentage', 'Result'],
      dtype='object')

In [24]:
student.columns.values

array(['StudentID', 'Math', 'Science', 'English', 'History', 'Art',
       'Total_Marks', 'Percentage', 'Result'], dtype=object)

In [25]:
list(student.columns)

['StudentID',
 'Math',
 'Science',
 'English',
 'History',
 'Art',
 'Total_Marks',
 'Percentage',
 'Result']

In [26]:
student.keys()

Index(['StudentID', 'Math', 'Science', 'English', 'History', 'Art',
       'Total_Marks', 'Percentage', 'Result'],
      dtype='object')

In [27]:
student.columns.values.tolist()

['StudentID',
 'Math',
 'Science',
 'English',
 'History',
 'Art',
 'Total_Marks',
 'Percentage',
 'Result']

In [28]:
sorted(student)

['Art',
 'English',
 'History',
 'Math',
 'Percentage',
 'Result',
 'Science',
 'StudentID',
 'Total_Marks']

In [29]:
#how to rename columns in pandas dataframe
emp = pd.read_csv("employees_with_errors (4).csv")

In [30]:
emp.head()

  Employe ID       Nmae  Aeg Departmnt  Slary
0       E001  Employee1   20     Sales  54777
1       E002  Employee2   23        HR  43824
2       E003  Employee3   23     Sales  32418
3       E004  Employee4   59        IT  42843
4       E005  Employee5   29     Sales  66223

In [31]:
emp.columns.tolist()

['Employe ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary']

In [32]:
emp.rename(columns={'Employe ID' :'Employee_ID'})

   Employee_ID        Nmae  Aeg  Departmnt  Slary
0         E001   Employee1   20      Sales  54777
1         E002   Employee2   23         HR  43824
2         E003   Employee3   23      Sales  32418
3         E004   Employee4   59         IT  42843
4         E005   Employee5   29      Sales  66223
5         E006   Employee6   39         IT  91570
6         E007   Employee7   41    Finance  36521
7         E008   Employee8   56    Finance  86894
8         E009   Employee9   43         HR  44254
9         E010  Employee10   26         IT  81939
10        E011  Employee11   44         IT  67073
11        E012  Employee12   44         IT  53310
12        E013  Employee13   32         IT  61785
13        E014  Employee14   21  Marketing  94570
14        E015  Employee15   58  Marketing  86356
15        E016  Employee16   59    Finance  53306
16        E017  Employee17   43  Marketing  66950
17        E018  Employee18   44         HR  63920
18        E019  Employee19   37  Marketing  63538
19        E020  Employee20   57      Sales  38286
20        E021  Employee21   45         IT  48728
21        E022  Employee22   33    Finance  43640
22        E023  Employee23   28      Sales  98627
23        E024  Employee24   29  Marketing  75663
24        E025  Employee25   40      Sales  33912
25        E026  Employee26   36      Sales  80586
26        E027  Employee27   25      Sales  51752
27        E028  Employee28   35  Marketing  89715
28        E029  Employee29   20      Sales  37997
29        E030  Employee30   38      Sales  83006
30        E031  Employee31   55      Sales  70800
31        E032  Employee32   44         HR  45620
32        E033  Employee33   49      Sales  84268
33        E034  Employee34   39  Marketing  99069
34        E035  Employee35   39    Finance  98473
35        E036  Employee36   34         HR  72512
36        E037  Employee37   59         IT  49608
37        E038  Employee38   52         IT  47340
38        E039  Employee39   21  Marketing  31913
39        E040  Employee40   29         HR  82086
40        E041  Employee41   52         HR  43429
41        E042  Employee42   51         IT  43907
42        E043  Employee43   30    Finance  65489
43        E044  Employee44   43      Sales  40088
44        E045  Employee45   55    Finance  45588
45        E046  Employee46   31         HR  68395
46        E047  Employee47   48  Marketing  90155
47        E048  Employee48   54    Finance  68214
48        E049  Employee49   20    Finance  30469
49        E050  Employee50   20         HR  73295

In [33]:
emp.rename(columns={'Employe ID' :'Employee_ID'}, inplace=True)

In [34]:
emp.columns.tolist()

['Employee_ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary']

In [35]:
emp.rename(columns={'Nmae':'Name', 'Aeg':'Age'}, inplace=True)

In [36]:
#method 2 by assigning a list of new coloumn names
import numpy as np 
import pandas as pd

In [37]:
emp1 = pd.read_csv("employees_with_errors (4).csv")

In [38]:
emp1.columns

Index(['Employe ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary'], dtype='object')

In [39]:
emp1.columns[1] = ['Name']

TypeError: Index does not support mutable operations

In [ ]:
emp1.columns = ['Employee_ID','Name', 'Age','Department','Salary']

In [ ]:
emp1.columns.tolist()

In [40]:
#rename column names using data frame set axis fuction
emp2 = pd.read_csv("employees_with_errors (4).csv")

In [41]:
emp2.columns

Index(['Employe ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary'], dtype='object')

In [42]:
emp2.set_axis(['Employee_ID'], axis='columns')

ValueError: Length mismatch: Expected axis has 5 elements, new values have 1 elements

In [ ]:
emp2 = emp2.set_axis(['Employee_ID','Name', 'Age','Department','Salary'], axis='columns')

In [ ]:
emp2

In [72]:
emp4 = pd.read_csv("employees_with_errors (4).csv")

In [73]:
emp4.columns.values.tolist()

['Employe ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary']

In [74]:
emp4.set_axis(['Employee_ID','Name', 'Age','Department','Salary'], axis='columns', inplace=True)

TypeError: DataFrame.set_axis() got an unexpected keyword argument 'inplace'

In [43]:
emp4.columns.values.tolist()

NameError: name 'emp4' is not defined

In [44]:
emp2.columns.tolist()

['Employe ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary']

In [45]:
# Rename column names using DataFrame add_prefix() and add_suffix() functions
emp3 = pd.read_csv("employees_with_errors (4).csv")

In [46]:
emp3.columns.tolist()

['Employe ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary']

In [47]:
emp3 = emp3.add_prefix('CT_')
emp3 = emp3.add_suffix('_Indrapuri')

In [48]:
emp = pd.read_csv("employees_with_errors (4).csv")
emp3.columns

Index(['CT_Employe ID_Indrapuri', 'CT_Nmae_Indrapuri', 'CT_Aeg_Indrapuri',
       'CT_Departmnt_Indrapuri', 'CT_Slary_Indrapuri'],
      dtype='object')

In [49]:
#Method 5: Replace specific texts of column names using Dataframe.columns.str.replace function
emp4 = pd.read_csv("employees_with_errors (4).csv")

In [50]:
emp4.columns.tolist()

['Employe ID', 'Nmae', 'Aeg', 'Departmnt', 'Slary']

In [51]:
emp4 = emp4.add_prefix('Indrapuri_')

In [52]:
emp4.columns.tolist()

['Indrapuri_Employe ID',
 'Indrapuri_Nmae',
 'Indrapuri_Aeg',
 'Indrapuri_Departmnt',
 'Indrapuri_Slary']

In [53]:
emp4.columns = emp4.columns.str.upper()

In [54]:
emp4

,INDRAPURI_EMPLOYE ID,INDRAPURI_NMAE,INDRAPURI_AEG,INDRAPURI_DEPARTMNT,INDRAPURI_SLARY
0,E001,Employee1,20,Sales,54777
1,E002,Employee2,23,HR,43824
2,E003,Employee3,23,Sales,32418
3,E004,Employee4,59,IT,42843
4,E005,Employee5,29,Sales,66223
5,E006,Employee6,39,IT,91570
6,E007,Employee7,41,Finance,36521
7,E008,Employee8,56,Finance,86894
8,E009,Employee9,43,HR,44254
9,E010,Employee10,26,IT,81939
10,E011,Employee11,44,IT,67073
11,E012,Employee12,44,IT,53310
12,E013,Employee13,32,IT,61785
13,E014,Employee14,21,Marketing,94570
14,E015,Employee15,58,Marketing,86356
15,E016,Employee16,59,Finance,53306
16,E017,Employee17,43,Marketing,66950
17,E018,Employee18,44,HR,63920
18,E019,Employee19,37,Marketing,63538
19,E020,Employee20,57,Sales,38286
20,E021,Employee21,45,IT,48728
21,E022,Employee22,33,Finance,43640
22,E023,Employee23,28,Sales,98627
23,E024,Employee24,29,Marketing,75663
24,E025,Employee25,40,Sales,33912
25,E026,Employee26,36,Sales,80586
26,E027,Employee27,25,Sales,51752
27,E028,Employee28,35,Marketing,89715
28,E029,Employee29,20,Sales,37997
29,E030,Employee30,38,Sales,83006
30,E031,Employee31,55,Sales,70800
31,E032,Employee32,44,HR,45620
32,E033,Employee33,49,Sales,84268
33,E034,Employee34,39,Marketing,99069
34,E035,Employee35,39,Finance,98473
35,E036,Employee36,34,HR,72512
36,E037,Employee37,59,IT,49608
37,E038,Employee38,52,IT,47340
38,E039,Employee39,21,Marketing,31913
39,E040,Employee40,29,HR,82086
40,E041,Employee41,52,HR,43429
41,E042,Employee42,51,IT,43907
42,E043,Employee43,30,Finance,65489
43,E044,Employee44,43,Sales,40088
44,E045,Employee45,55,Finance,45588
45,E046,Employee46,31,HR,68395
46,E047,Employee47,48,Marketing,90155
47,E048,Employee48,54,Finance,68214
48,E049,Employee49,20,Finance,30469
49,E050,Employee50,20,HR,73295

In [55]:
#Return the Index label if some condition is satisfied over a column in Pandas Dataframe¶
emp5 = pd.read_csv("employees_with_errors (4).csv")

In [56]:
emp5.head()

  Employe ID       Nmae  Aeg Departmnt  Slary
0       E001  Employee1   20     Sales  54777
1       E002  Employee2   23        HR  43824
2       E003  Employee3   23     Sales  32418
3       E004  Employee4   59        IT  42843
4       E005  Employee5   29     Sales  66223

In [57]:
len(emp5[emp5.Aeg>=50])

12

In [58]:
Index_label = emp5[emp5.Aeg>=50].index

In [59]:
emp5.iloc[41]

Employe ID          E042
Nmae          Employee42
Aeg                   51
Departmnt             IT
Slary              43907
Name: 41, dtype: object

In [60]:
Index_label

Index([3, 7, 14, 15, 19, 30, 36, 37, 40, 41, 44, 47], dtype='int64')

In [61]:
Index_label1 = emp5[emp5.Aeg>=50].index.tolist()
Index_label1

[3, 7, 14, 15, 19, 30, 36, 37, 40, 41, 44, 47]

In [62]:
emp5.iloc[Index_label]

   Employe ID        Nmae  Aeg  Departmnt  Slary
3        E004   Employee4   59         IT  42843
7        E008   Employee8   56    Finance  86894
14       E015  Employee15   58  Marketing  86356
15       E016  Employee16   59    Finance  53306
19       E020  Employee20   57      Sales  38286
30       E031  Employee31   55      Sales  70800
36       E037  Employee37   59         IT  49608
37       E038  Employee38   52         IT  47340
40       E041  Employee41   52         HR  43429
41       E042  Employee42   51         IT  43907
44       E045  Employee45   55    Finance  45588
47       E048  Employee48   54    Finance  68214

In [63]:
#Get n-largest values or n-smallest values from a particular column in Pandas DataFrame¶
student1 = student.copy()

In [64]:
student1.shape

(100, 9)

In [65]:
student1.columns.tolist()

['StudentID',
 'Math',
 'Science',
 'English',
 'History',
 'Art',
 'Total_Marks',
 'Percentage',
 'Result']

In [66]:
# Getting top 5 students
student1.nlargest(15, ['Math'])

,StudentID,Math,Science,English,History,Art,Total_Marks,Percentage,Result
89,S090,100,24,35,92,91,342,68.4,First Division
33,S034,99,82,84,28,8,301,60.2,First Division
77,S078,99,67,36,72,80,354,70.8,First Division
94,S095,99,60,25,49,74,307,61.4,First Division
74,S075,91,26,88,99,20,324,64.8,First Division
11,S012,88,36,54,39,53,270,54.0,Second Division
12,S013,88,34,79,39,48,288,57.6,Second Division
19,S020,88,21,88,18,49,264,52.8,Second Division
34,S035,88,46,10,81,99,324,64.8,First Division
9,S010,87,0,18,91,65,261,52.2,Second Division
17,S018,87,42,95,70,35,329,65.8,First Division
99,S100,85,100,33,34,12,264,52.8,Second Division
81,S082,84,4,69,0,91,248,49.6,Second Division
6,S007,83,95,24,12,18,232,46.4,Second Division
32,S033,82,67,11,73,89,322,64.4,First Division

In [67]:
student1.Total_Marks.sort_values(ascending=False).head(5)

29    397
95    375
31    360
77    354
20    343
Name: Total_Marks, dtype: int64

In [68]:
student1.sort_values(['Math','Total_Marks'],ascending=False).head(10)

,StudentID,Math,Science,English,History,Art,Total_Marks,Percentage,Result
89,S090,100,24,35,92,91,342,68.4,First Division
77,S078,99,67,36,72,80,354,70.8,First Division
94,S095,99,60,25,49,74,307,61.4,First Division
33,S034,99,82,84,28,8,301,60.2,First Division
74,S075,91,26,88,99,20,324,64.8,First Division
34,S035,88,46,10,81,99,324,64.8,First Division
12,S013,88,34,79,39,48,288,57.6,Second Division
11,S012,88,36,54,39,53,270,54.0,Second Division
19,S020,88,21,88,18,49,264,52.8,Second Division
17,S018,87,42,95,70,35,329,65.8,First Division

In [69]:
student1.nsmallest(5,'Total_Marks')

,StudentID,Math,Science,English,History,Art,Total_Marks,Percentage,Result
87,S088,3,56,1,4,9,73,14.6,Fail
56,S057,36,19,3,13,23,94,18.8,Fail
98,S099,13,32,29,18,3,95,19.0,Fail
52,S053,28,32,9,19,25,113,22.6,Fail
63,S064,42,24,10,36,7,119,23.8,Fail

In [70]:
student1.Total_Marks.sort_values().head(5)

87     73
56     94
98     95
52    113
63    119
Name: Total_Marks, dtype: int64

In [71]:
student1.sort_values('Total_Marks').head(5)

,StudentID,Math,Science,English,History,Art,Total_Marks,Percentage,Result
87,S088,3,56,1,4,9,73,14.6,Fail
56,S057,36,19,3,13,23,94,18.8,Fail
98,S099,13,32,29,18,3,95,19.0,Fail
52,S053,28,32,9,19,25,113,22.6,Fail
63,S064,42,24,10,36,7,119,23.8,Fail

In [76]:
#Change Data Type for one or more columns in Pandas Dataframe
#To Change Column Type in Pandas DataFrames, There are different ways of changing DataType for one or more columns in Pandas Da
# sample dataframe
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [1.1, '1.0', '1.3', 2, 5]})
print(df.dtypes)
# converting all columns to string type
df = df.astype(str)
print(df.dtypes)

A     int64
B    object
C    object
dtype: object
A    object
B    object
C    object
dtype: object

In [77]:
# sample dataframe
df = pd.DataFrame({
    'A': [1, 2, 3, '4', '5'],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [1.1, '2.1', 3.0, '4.1', '5.1']})
 
# using apply method
df[['A', 'C']] = df[['A', 'C']].apply(pd.to_numeric)
print(df.dtypes)

A      int64
B     object
C    float64
dtype: object