In [10]:
import numpy as np 
import pandas as pd

In [11]:
df = pd.read_csv("complete.csv")

In [12]:
df

,awardYear,category,categoryFullName,sortOrder,portion,prizeAmount,prizeAmountAdjusted,dateAwarded,prizeStatus,motivation,...,org_founded_country,org_founded_countryNow,org_founded_locationString,ind_or_org,residence_1,residence_2,affiliation_1,affiliation_2,affiliation_3,affiliation_4
0,2001,Economic Sciences,The Sveriges Riksbank Prize in Economic Scienc...,2,1/3,10000000,12295082,2001-10-10,received,for their analyses of markets with asymmetric ...,...,NaN,NaN,NaN,Individual,NaN,NaN,"Stanford University, Stanford, CA, USA",NaN,NaN,NaN
1,1975,Physics,The Nobel Prize in Physics,1,1/3,630000,3404179,1975-10-17,received,for the discovery of the connection between co...,...,NaN,NaN,NaN,Individual,NaN,NaN,"Niels Bohr Institute, Copenhagen, Denmark",NaN,NaN,NaN
2,2004,Chemistry,The Nobel Prize in Chemistry,1,1/3,10000000,11762861,2004-10-06,received,for the discovery of ubiquitin-mediated protei...,...,NaN,NaN,NaN,Individual,NaN,NaN,"Technion - Israel Institute of Technology, Hai...",NaN,NaN,NaN
3,1982,Chemistry,The Nobel Prize in Chemistry,1,1,1150000,3102518,1982-10-18,received,for his development of crystallographic electr...,...,NaN,NaN,NaN,Individual,NaN,NaN,"MRC Laboratory of Molecular Biology, Cambridge...",NaN,NaN,NaN
4,1979,Physics,The Nobel Prize in Physics,2,1/3,800000,2988048,1979-10-15,received,for their contributions to the theory of the u...,...,NaN,NaN,NaN,Individual,NaN,NaN,"International Centre for Theoretical Physics, ...","Imperial College, London, United Kingdom",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,1972,Physics,The Nobel Prize in Physics,1,1/3,480000,3345725,NaN,received,for their jointly developed theory of supercon...,...,NaN,NaN,NaN,Individual,NaN,NaN,"University of Illinois, Urbana, IL, USA",NaN,NaN,NaN
946,1954,Chemistry,The Nobel Prize in Chemistry,1,1,181647,2640218,NaN,received,for his research into the nature of the chemic...,...,NaN,NaN,NaN,Individual,NaN,NaN,"California Institute of Technology (Caltech), ...",NaN,NaN,NaN
947,1911,Chemistry,The Nobel Prize in Chemistry,1,1,140695,7327865,NaN,received,in recognition of her services to the advancem...,...,NaN,NaN,NaN,Individual,NaN,NaN,"Sorbonne University, Paris, France",NaN,NaN,NaN
948,1981,Peace,The Nobel Peace Prize,1,1,1000000,2929688,1981-10-14,received,for promoting the fundamental rights of refugees,...,Switzerland,Switzerland,"Geneva, Switzerland",Organization,NaN,NaN,NaN,NaN,NaN,NaN
949,1963,Peace,The Nobel Peace Prize,1,1/2,265000,2839286,1963-10-10,received,for promoting the principles of the Geneva Con...,...,Switzerland,Switzerland,"Geneva, Switzerland",Organization,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.columns.tolist()

['awardYear',
 'category',
 'categoryFullName',
 'sortOrder',
 'portion',
 'prizeAmount',
 'prizeAmountAdjusted',
 'dateAwarded',
 'prizeStatus',
 'motivation',
 'categoryTopMotivation',
 'award_link',
 'id',
 'name',
 'knownName',
 'givenName',
 'familyName',
 'fullName',
 'penName',
 'gender',
 'laureate_link',
 'birth_date',
 'birth_city',
 'birth_cityNow',
 'birth_continent',
 'birth_country',
 'birth_countryNow',
 'birth_locationString',
 'death_date',
 'death_city',
 'death_cityNow',
 'death_continent',
 'death_country',
 'death_countryNow',
 'death_locationString',
 'orgName',
 'nativeName',
 'acronym',
 'org_founded_date',
 'org_founded_city',
 'org_founded_cityNow',
 'org_founded_continent',
 'org_founded_country',
 'org_founded_countryNow',
 'org_founded_locationString',
 'ind_or_org',
 'residence_1',
 'residence_2',
 'affiliation_1',
 'affiliation_2',
 'affiliation_3',
 'affiliation_4']

In [14]:
df.shape

(950, 52)

In [15]:
df.size

49400

In [16]:
df.isnull()

,awardYear,category,categoryFullName,sortOrder,portion,prizeAmount,prizeAmountAdjusted,dateAwarded,prizeStatus,motivation,...,org_founded_country,org_founded_countryNow,org_founded_locationString,ind_or_org,residence_1,residence_2,affiliation_1,affiliation_2,affiliation_3,affiliation_4
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,True,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,True,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,True,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,True,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,False,False,False,False,False,False,False,True,False,False,...,True,True,True,False,True,True,False,True,True,True
946,False,False,False,False,False,False,False,True,False,False,...,True,True,True,False,True,True,False,True,True,True
947,False,False,False,False,False,False,False,True,False,False,...,True,True,True,False,True,True,False,True,True,True
948,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
949,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True

In [17]:
df.columns

Index(['awardYear', 'category', 'categoryFullName', 'sortOrder', 'portion',
       'prizeAmount', 'prizeAmountAdjusted', 'dateAwarded', 'prizeStatus',
       'motivation', 'categoryTopMotivation', 'award_link', 'id', 'name',
       'knownName', 'givenName', 'familyName', 'fullName', 'penName', 'gender',
       'laureate_link', 'birth_date', 'birth_city', 'birth_cityNow',
       'birth_continent', 'birth_country', 'birth_countryNow',
       'birth_locationString', 'death_date', 'death_city', 'death_cityNow',
       'death_continent', 'death_country', 'death_countryNow',
       'death_locationString', 'orgName', 'nativeName', 'acronym',
       'org_founded_date', 'org_founded_city', 'org_founded_cityNow',
       'org_founded_continent', 'org_founded_country',
       'org_founded_countryNow', 'org_founded_locationString', 'ind_or_org',
       'residence_1', 'residence_2', 'affiliation_1', 'affiliation_2',
       'affiliation_3', 'affiliation_4'],
      dtype='object')

In [18]:
len(df.columns)

52

In [19]:
df= df[['awardYear', 'category', 'prizeAmount', 'prizeAmountAdjusted', 'name', 'gender', 'birth_continent']]

In [20]:
df

,awardYear,category,prizeAmount,prizeAmountAdjusted,name,gender,birth_continent
0,2001,Economic Sciences,10000000,12295082,A. Michael Spence,male,North America
1,1975,Physics,630000,3404179,Aage N. Bohr,male,Europe
2,2004,Chemistry,10000000,11762861,Aaron Ciechanover,male,Asia
3,1982,Chemistry,1150000,3102518,Aaron Klug,male,Europe
4,1979,Physics,800000,2988048,Abdus Salam,male,Asia
...,...,...,...,...,...,...,...
945,1972,Physics,480000,3345725,John Bardeen,male,North America
946,1954,Chemistry,181647,2640218,Linus Pauling,male,North America
947,1911,Chemistry,140695,7327865,Marie Curie,female,Europe
948,1981,Peace,1000000,2929688,Office of the United Nations High Commissioner...,NaN,NaN
949,1963,Peace,265000,2839286,International Committee of the Red Cross,NaN,NaN

In [21]:
df.awardYear.nunique()

116

In [22]:
df.category.nunique()

6

In [23]:
df.category.unique()

array(['Economic Sciences', 'Physics', 'Chemistry', 'Peace',
       'Physiology or Medicine', 'Literature'], dtype=object)

In [24]:
df.prizeAmount.max()

np.int64(10000000)

In [25]:
grouped = df.groupby('category')

In [26]:
grouped

In [27]:
grouped_category_year = df.groupby(['category','awardYear'])

In [28]:
grouped_category_year

In [29]:
df.head(20)

,awardYear,category,prizeAmount,prizeAmountAdjusted,name,gender,birth_continent
0,2001,Economic Sciences,10000000,12295082,A. Michael Spence,male,North America
1,1975,Physics,630000,3404179,Aage N. Bohr,male,Europe
2,2004,Chemistry,10000000,11762861,Aaron Ciechanover,male,Asia
3,1982,Chemistry,1150000,3102518,Aaron Klug,male,Europe
4,1979,Physics,800000,2988048,Abdus Salam,male,Asia
5,2019,Economic Sciences,9000000,9000000,Abhijit Banerjee,male,Asia
6,2019,Peace,9000000,9000000,Abiy Ahmed Ali,male,Africa
7,2009,Chemistry,10000000,10958504,Ada E. Yonath,female,Asia
8,2011,Physics,10000000,10545557,Adam G. Riess,male,North America
9,1939,Chemistry,148822,4227898,Adolf Butenandt,male,Europe
10,1905,Chemistry,138089,7615202,Adolf von Baeyer,male,Europe
11,1928,Chemistry,156939,4458494,Adolf Windaus,male,Europe
12,1980,Peace,880000,2889667,Adolfo Pérez Esquivel,male,South America
13,1999,Chemistry,7900000,10049186,Ahmed Zewail,male,Africa
14,2010,Chemistry,10000000,10819388,Akira Suzuki,male,Asia
15,2019,Chemistry,9000000,9000000,Akira Yoshino,male,Asia
16,2007,Peace,10000000,11301989,Al Gore,male,North America
17,2000,Chemistry,9000000,11333109,Alan Heeger,male,North America
18,1963,Physiology or Medicine,265000,2839286,Alan Hodgkin,male,Europe
19,2000,Chemistry,9000000,11333109,Alan MacDiarmid,male,Oceania

In [30]:
df[df.category=='Chemistry']

,awardYear,category,prizeAmount,prizeAmountAdjusted,name,gender,birth_continent
2,2004,Chemistry,10000000,11762861,Aaron Ciechanover,male,Asia
3,1982,Chemistry,1150000,3102518,Aaron Klug,male,Europe
7,2009,Chemistry,10000000,10958504,Ada E. Yonath,female,Asia
9,1939,Chemistry,148822,4227898,Adolf Butenandt,male,Europe
10,1905,Chemistry,138089,7615202,Adolf von Baeyer,male,Europe
...,...,...,...,...,...,...,...
940,1986,Chemistry,2000000,4098361,Yuan T. Lee,male,Asia
941,2005,Chemistry,10000000,11711430,Yves Chauvin,male,Europe
943,1980,Chemistry,880000,2889667,Frederick Sanger,male,Europe
946,1954,Chemistry,181647,2640218,Linus Pauling,male,North America
947,1911,Chemistry,140695,7327865,Marie Curie,female,Europe

In [31]:
grouped.groups

{'Chemistry': [2, 3, 7, 9, 10, 11, 13, 14, 15, 17, 19, 39, 62, 64, 66, 71, 75, 80, 81, 86, 92, 104, 107, 112, 129, 135, 153, 169, 175, 178, 181, 188, 197, 199, 203, 210, 215, 223, 227, 239, 247, 249, 258, 264, 265, 268, 272, 274, 280, 282, 284, 289, 296, 298, 310, 311, 317, 318, 337, 341, 343, 348, 352, 357, 362, 365, 366, 372, 374, 384, 394, 395, 396, 415, 416, 419, 434, 440, 442, 444, 446, 448, 450, 455, 456, 459, 461, 463, 465, 469, 475, 504, 505, 508, 518, 522, 523, 524, 539, 549, ...], 'Economic Sciences': [0, 5, 45, 46, 58, 90, 96, 139, 140, 145, 152, 156, 157, 180, 187, 193, 207, 219, 231, 232, 246, 250, 269, 279, 283, 295, 305, 324, 346, 369, 418, 422, 425, 426, 430, 432, 438, 458, 467, 476, 485, 510, 525, 527, 537, 538, 546, 580, 594, 595, 605, 611, 636, 637, 657, 669, 670, 678, 700, 708, 716, 724, 734, 737, 739, 745, 747, 749, 750, 753, 758, 767, 800, 805, 854, 856, 860, 864, 871, 882, 896, 912, 916, 924], 'Literature': [21, 31, 40, 49, 52, 98, 100, 101, 102, 111, 115, 142, 149, 159, 170, 177, 201, 202, 220, 221, 233, 235, 237, 253, 257, 259, 275, 277, 278, 286, 312, 315, 316, 321, 326, 333, 345, 347, 350, 355, 359, 364, 370, 373, 385, 397, 400, 403, 406, 411, 435, 439, 441, 454, 468, 479, 480, 482, 483, 492, 501, 506, 511, 516, 556, 569, 581, 602, 604, 606, 613, 614, 618, 631, 633, 635, 640, 652, 653, 655, 656, 665, 675, 683, 699, 761, 765, 771, 774, 777, 779, 780, 784, 786, 788, 796, 799, 803, 836, 840, ...], 'Peace': [6, 12, 16, 25, 26, 27, 34, 36, 44, 47, 48, 54, 61, 65, 72, 78, 79, 82, 95, 99, 116, 119, 120, 126, 137, 146, 151, 166, 167, 171, 200, 204, 205, 206, 209, 213, 225, 236, 240, 244, 255, 260, 266, 267, 270, 287, 303, 320, 329, 356, 360, 361, 377, 386, 387, 388, 389, 390, 391, 392, 393, 433, 447, 449, 471, 477, 481, 489, 491, 500, 512, 514, 517, 528, 529, 530, 533, 534, 540, 542, 544, 545, 547, 553, 555, 560, 562, 574, 578, 590, 593, 603, 607, 608, 609, 612, 615, 616, 617, 619, ...], 'Physics': [1, 4, 8, 20, 23, 24, 30, 32, 38, 51, 59, 60, 67, 68, 69, 70, 74, 84, 89, 97, 103, 105, 108, 109, 114, 117, 118, 122, 125, 127, 128, 130, 133, 141, 143, 144, 155, 162, 163, 164, 165, 168, 173, 174, 176, 179, 183, 195, 212, 214, 216, 222, 224, 228, 230, 234, 238, 241, 243, 251, 256, 263, 271, 276, 291, 292, 297, 301, 306, 307, 308, 323, 327, 328, 330, 335, 336, 338, 349, 351, 353, 354, 363, 367, 375, 376, 378, 381, 382, 398, 399, 402, 404, 405, 408, 410, 412, 413, 420, 421, ...], 'Physiology or Medicine': [18, 22, 28, 29, 33, 35, 37, 41, 42, 43, 50, 53, 55, 56, 57, 63, 73, 76, 77, 83, 85, 87, 88, 91, 93, 94, 106, 110, 113, 121, 123, 124, 131, 132, 134, 136, 138, 147, 148, 150, 154, 158, 160, 161, 172, 182, 184, 185, 186, 189, 190, 191, 192, 194, 196, 198, 208, 211, 217, 218, 226, 229, 242, 245, 248, 252, 254, 261, 262, 273, 281, 285, 288, 290, 293, 294, 299, 300, 302, 304, 309, 313, 314, 319, 322, 325, 331, 332, 334, 339, 340, 342, 344, 358, 368, 371, 379, 380, 383, 401, ...]}

In [32]:
grouped.indices

{'Chemistry': array([  2,   3,   7,   9,  10,  11,  13,  14,  15,  17,  19,  39,  62,
         64,  66,  71,  75,  80,  81,  86,  92, 104, 107, 112, 129, 135,
        153, 169, 175, 178, 181, 188, 197, 199, 203, 210, 215, 223, 227,
        239, 247, 249, 258, 264, 265, 268, 272, 274, 280, 282, 284, 289,
        296, 298, 310, 311, 317, 318, 337, 341, 343, 348, 352, 357, 362,
        365, 366, 372, 374, 384, 394, 395, 396, 415, 416, 419, 434, 440,
        442, 444, 446, 448, 450, 455, 456, 459, 461, 463, 465, 469, 475,
        504, 505, 508, 518, 522, 523, 524, 539, 549, 558, 559, 563, 567,
        571, 572, 585, 591, 596, 599, 627, 630, 632, 641, 643, 644, 648,
        659, 661, 666, 667, 668, 671, 673, 679, 681, 686, 713, 715, 717,
        719, 720, 722, 723, 725, 726, 729, 732, 738, 742, 744, 746, 751,
        756, 759, 763, 766, 773, 776, 798, 810, 813, 814, 817, 827, 828,
        829, 832, 839, 848, 853, 855, 862, 866, 880, 885, 886, 888, 889,
        892, 894, 897, 902, 904, 914, 915, 920, 921, 922, 940, 941, 943,
        946, 947]),
 'Economic Sciences': array([  0,   5,  45,  46,  58,  90,  96, 139, 140, 145, 152, 156, 157,
        180, 187, 193, 207, 219, 231, 232, 246, 250, 269, 279, 283, 295,
        305, 324, 346, 369, 418, 422, 425, 426, 430, 432, 438, 458, 467,
        476, 485, 510, 525, 527, 537, 538, 546, 580, 594, 595, 605, 611,
        636, 637, 657, 669, 670, 678, 700, 708, 716, 724, 734, 737, 739,
        745, 747, 749, 750, 753, 758, 767, 800, 805, 854, 856, 860, 864,
        871, 882, 896, 912, 916, 924]),
 'Literature': array([ 21,  31,  40,  49,  52,  98, 100, 101, 102, 111, 115, 142, 149,
        159, 170, 177, 201, 202, 220, 221, 233, 235, 237, 253, 257, 259,
        275, 277, 278, 286, 312, 315, 316, 321, 326, 333, 345, 347, 350,
        355, 359, 364, 370, 373, 385, 397, 400, 403, 406, 411, 435, 439,
        441, 454, 468, 479, 480, 482, 483, 492, 501, 506, 511, 516, 556,
        569, 581, 602, 604, 606, 613, 614, 618, 631, 633, 635, 640, 652,
        653, 655, 656, 665, 675, 683, 699, 761, 765, 771, 774, 777, 779,
        780, 784, 786, 788, 796, 799, 803, 836, 840, 842, 850, 861, 867,
        868, 878, 881, 883, 910, 917, 919, 927, 928, 929, 930, 936]),
 'Peace': array([  6,  12,  16,  25,  26,  27,  34,  36,  44,  47,  48,  54,  61,
         65,  72,  78,  79,  82,  95,  99, 116, 119, 120, 126, 137, 146,
        151, 166, 167, 171, 200, 204, 205, 206, 209, 213, 225, 236, 240,
        244, 255, 260, 266, 267, 270, 287, 303, 320, 329, 356, 360, 361,
        377, 386, 387, 388, 389, 390, 391, 392, 393, 433, 447, 449, 471,
        477, 481, 489, 491, 500, 512, 514, 517, 528, 529, 530, 533, 534,
        540, 542, 544, 545, 547, 553, 555, 560, 562, 574, 578, 590, 593,
        603, 607, 608, 609, 612, 615, 616, 617, 619, 620, 628, 634, 639,
        642, 664, 677, 688, 697, 703, 705, 710, 727, 736, 787, 793, 795,
        806, 823, 846, 847, 852, 865, 875, 876, 877, 895, 926, 934, 935,
        937, 944, 948, 949]),
 'Physics': array([  1,   4,   8,  20,  23,  24,  30,  32,  38,  51,  59,  60,  67,
         68,  69,  70,  74,  84,  89,  97, 103, 105, 108, 109, 114, 117,
        118, 122, 125, 127, 128, 130, 133, 141, 143, 144, 155, 162, 163,
        164, 165, 168, 173, 174, 176, 179, 183, 195, 212, 214, 216, 222,
        224, 228, 230, 234, 238, 241, 243, 251, 256, 263, 271, 276, 291,
        292, 297, 301, 306, 307, 308, 323, 327, 328, 330, 335, 336, 338,
        349, 351, 353, 354, 363, 367, 375, 376, 378, 381, 382, 398, 399,
        402, 404, 405, 408, 410, 412, 413, 420, 421, 424, 428, 429, 436,
        445, 451, 453, 457, 460, 462, 470, 472, 487, 495, 498, 499, 509,
        513, 515, 521, 526, 532, 535, 536, 541, 548, 550, 552, 557, 561,
        564, 565, 566, 573, 576, 577, 579, 583, 586, 588, 592, 601, 610,
        621, 622, 623, 629, 647, 650, 651, 654, 658, 674, 676, 682, 684,
        690, 691, 693, 694, 695, 696, 698, 702, 707, 711, 714, 721, 730,
        731, 735, 743, 752, 755, 770, 772, 775, 781, 785, 790, 792, 797,
        801, 802, 808, 822, 833, 834, 835, 844, 851, 870, 872, 879, 884,
        887, 890, 893, 900, 901, 903, 905, 907, 908, 909, 913, 925, 931,
        932, 933, 938, 942, 945]),
 'Physiology or Medicine': array([ 18,  22,  28,  29,  33,  35,  37,  41,  42,  43,  50,  53,  55,
         56,  57,  63,  73,  76,  77,  83,  85,  87,  88,  91,  93,  94,
        106, 110, 113, 121, 123, 124, 131, 132, 134, 136, 138, 147, 148,
        150, 154, 158, 160, 161, 172, 182, 184, 185, 186, 189, 190, 191,
        192, 194, 196, 198, 208, 211, 217, 218, 226, 229, 242, 245, 248,
        252, 254, 261, 262, 273, 281, 285, 288, 290, 293, 294, 299, 300,
        302, 304, 309, 313, 314, 319, 322, 325, 331, 332, 334, 339, 340,
        342, 344, 358, 368, 371, 379, 380, 383, 401, 407, 409, 414, 417,
        423, 427, 431, 437, 443, 452, 464, 466, 473, 474, 478, 484, 486,
        488, 490, 493, 494, 496, 497, 502, 503, 507, 519, 520, 531, 543,
        551, 554, 568, 570, 575, 582, 584, 587, 589, 597, 598, 600, 624,
        625, 626, 638, 645, 646, 649, 660, 662, 663, 672, 680, 685, 687,
        689, 692, 701, 704, 706, 709, 712, 718, 728, 733, 740, 741, 748,
        754, 757, 760, 762, 764, 768, 769, 778, 782, 783, 789, 791, 794,
        804, 807, 809, 811, 812, 815, 816, 818, 819, 820, 821, 824, 825,
        826, 830, 831, 837, 838, 841, 843, 845, 849, 857, 858, 859, 863,
        869, 873, 874, 891, 898, 899, 906, 911, 918, 923, 939])}

In [33]:
len(grouped)

6

In [34]:
grouped.ngroups

6

In [35]:
grouped.get_group('Chemistry')

,awardYear,category,prizeAmount,prizeAmountAdjusted,name,gender,birth_continent
2,2004,Chemistry,10000000,11762861,Aaron Ciechanover,male,Asia
3,1982,Chemistry,1150000,3102518,Aaron Klug,male,Europe
7,2009,Chemistry,10000000,10958504,Ada E. Yonath,female,Asia
9,1939,Chemistry,148822,4227898,Adolf Butenandt,male,Europe
10,1905,Chemistry,138089,7615202,Adolf von Baeyer,male,Europe
...,...,...,...,...,...,...,...
940,1986,Chemistry,2000000,4098361,Yuan T. Lee,male,Asia
941,2005,Chemistry,10000000,11711430,Yves Chauvin,male,Europe
943,1980,Chemistry,880000,2889667,Frederick Sanger,male,Europe
946,1954,Chemistry,181647,2640218,Linus Pauling,male,North America
947,1911,Chemistry,140695,7327865,Marie Curie,female,Europe

In [37]:
grouped.get_group(['Economic Science', 'Physics'])

TypeError: unhashable type: 'list'

In [38]:
grouped.agg(np.mean)

C:\Users\HP\AppData\Local\Temp\ipykernel_23360\1243003623.py:1: FutureWarning: The provided callable <function mean at 0x0000025D8788CFE0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grouped.agg(np.mean)

TypeError: agg function failed [how->mean,dtype->object]

In [41]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.mean)

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\377985497.py:1: FutureWarning: The provided callable <function mean at 0x0000022A7A247600> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.mean)

                         prizeAmount  prizeAmountAdjusted
category
Chemistry               3.629279e+06         6.257868e+06
Economic Sciences       6.105845e+06         7.837779e+06
Literature              2.493811e+06         5.598256e+06
Peace                   3.124879e+06         6.163907e+06
Physics                 3.407939e+06         6.086978e+06
Physiology or Medicine  3.072973e+06         5.738301e+06

In [44]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.median)

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\3741155779.py:1: FutureWarning: The provided callable <function median at 0x0000022A7A390860> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.median)

                        prizeAmount  prizeAmountAdjusted
category
Chemistry                  800000.0            5117217.0
Economic Sciences         7550000.0            9000000.0
Literature                 269000.0            4366629.0
Peace                      480000.0            5238085.0
Physics                    700000.0            4907955.0
Physiology or Medicine     510000.0            4098361.0

In [43]:
df.info

<bound method DataFrame.info of      awardYear           category  prizeAmount  prizeAmountAdjusted  \
0         2001  Economic Sciences     10000000             12295082
1         1975            Physics       630000              3404179
2         2004          Chemistry     10000000             11762861
3         1982          Chemistry      1150000              3102518
4         1979            Physics       800000              2988048
..         ...                ...          ...                  ...
945       1972            Physics       480000              3345725
946       1954          Chemistry       181647              2640218
947       1911          Chemistry       140695              7327865
948       1981              Peace      1000000              2929688
949       1963              Peace       265000              2839286

                                                  name  gender birth_continent
0                                    A. Michael Spence    male   North America
1                                         Aage N. Bohr    male          Europe
2                                    Aaron Ciechanover    male            Asia
3                                           Aaron Klug    male          Europe
4                                          Abdus Salam    male            Asia
..                                                 ...     ...             ...
945                                       John Bardeen    male   North America
946                                      Linus Pauling    male   North America
947                                        Marie Curie  female          Europe
948  Office of the United Nations High Commissioner...     NaN             NaN
949           International Committee of the Red Cross     NaN             NaN

[950 rows x 7 columns]>

In [45]:
grouped[['prizeAmount','prizeAmountAdjusted']].median

In [46]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.max)

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\3663710181.py:1: FutureWarning: The provided callable <function max at 0x0000022A7A246C00> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.max)

                        prizeAmount  prizeAmountAdjusted
category
Chemistry                  10000000             12295082
Economic Sciences          10000000             12295082
Literature                 10000000             12295082
Peace                      10000000             12295082
Physics                    10000000             12295082
Physiology or Medicine     10000000             12295082

In [47]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.min)

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\3288830877.py:1: FutureWarning: The provided callable <function min at 0x0000022A7A246D40> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.min)

                        prizeAmount  prizeAmountAdjusted
category
Chemistry                    114935              2394643
Economic Sciences            375000              2889667
Literature                   114935              2377268
Peace                        116960              2377268
Physics                      114935              2377268
Physiology or Medicine       114935              2377268

In [48]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.sum)

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\2116602024.py:1: FutureWarning: The provided callable <function sum at 0x0000022A7A246200> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.sum)

                        prizeAmount  prizeAmountAdjusted
category
Chemistry                 667787418           1151447726
Economic Sciences         512891000            658373449
Literature                289282102            649397731
Peace                     418733807            825963521
Physics                   725890928           1296526352
Physiology or Medicine    672981066           1256687857

In [49]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.size)

                        prizeAmount  prizeAmountAdjusted
category
Chemistry                       184                  184
Economic Sciences                84                   84
Literature                      116                  116
Peace                           134                  134
Physics                         213                  213
Physiology or Medicine          219                  219

In [50]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.std)

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\3340171541.py:1: FutureWarning: The provided callable <function std at 0x0000022A7A247740> is currently using DataFrameGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.std)

                         prizeAmount  prizeAmountAdjusted
category
Chemistry               4.070588e+06         3.276027e+06
Economic Sciences       3.787630e+06         3.313153e+06
Literature              3.653734e+06         3.029512e+06
Peace                   3.934391e+06         3.189886e+06
Physics                 4.013073e+06         3.294268e+06
Physiology or Medicine  3.898539e+06         3.241781e+06

In [51]:
grouped[['prizeAmount','prizeAmountAdjusted']].count()

                        prizeAmount  prizeAmountAdjusted
category
Chemistry                       184                  184
Economic Sciences                84                   84
Literature                      116                  116
Peace                           134                  134
Physics                         213                  213
Physiology or Medicine          219                  219

In [52]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(np.len)

AttributeError: module 'numpy' has no attribute 'len'

In [53]:
grouped[['prizeAmount','prizeAmountAdjusted']].agg(len)

                        prizeAmount  prizeAmountAdjusted
category
Chemistry                       184                  184
Economic Sciences                84                   84
Literature                      116                  116
Peace                           134                  134
Physics                         213                  213
Physiology or Medicine          219                  219

In [54]:
df.groupby('category').sum()

,awardYear,prizeAmount,prizeAmountAdjusted,name,gender,birth_continent
category,,,,,,
Chemistry,362912,667787418,1151447726,Aaron CiechanoverAaron KlugAda E. YonathAdolf ...,malemalefemalemalemalemalemalemalemalemalemale...,AsiaEuropeAsiaEuropeEuropeEuropeAfricaAsiaAsia...
Economic Sciences,167674,512891000,658373449,A. Michael SpenceAbhijit BanerjeeAlvin E. Roth...,malemalemalemalemalemalemalemalemalemalemalema...,North AmericaAsiaNorth AmericaAsiaEuropeEurope...
Literature,227468,289282102,649397731,Albert CamusAlexandr SolzhenitsynAlice MunroAn...,malemalefemalemalemalemalemalemalemalemalemale...,AfricaEuropeNorth AmericaEuropeEuropeEuropeEur...
Peace,263248,418733807,825963521,Abiy Ahmed AliAdolfo Pérez EsquivelAl GoreAlbe...,malemalemalemalemalemalemalemalefemalemalemale...,AfricaSouth AmericaNorth AmericaEuropeAfricaEu...
Physics,419837,725890928,1296526352,Aage N. BohrAbdus SalamAdam G. RiessAlbert A. ...,malemalemalemalemalemalemalemalemalemalemalema...,EuropeAsiaNorth AmericaEuropeEuropeEuropeOcean...
Physiology or Medicine,431508,672981066,1256687857,Alan HodgkinAlbert ClaudeAlbert Szent-GyörgyiA...,malemalemalemalemalemalemalemalemalemalemalema...,EuropeEuropeEuropeEuropeEuropeNorth AmericaNor...

In [57]:
df.groupby(['prizeAmount','prizeAmountAdjusted']).sum()

                                 awardYear  \
prizeAmount prizeAmountAdjusted
114935      3169164                   9615
116719      3218355                   5772
116960      3273134                  11556
118165      3211005                  11550
121333      2499993                  13615
...                                    ...
10000000    11711430                 26065
            11762861                 24048
            11807305                 22033
            12034660                 26026
            12295082                 30015

                                                                          category  \
prizeAmount prizeAmountAdjusted
114935      3169164              Physiology or MedicineChemistryPhysiology or M...
116719      3218355                        PhysicsPhysiology or MedicineLiterature
116960      3273134              PeaceLiteraturePeacePhysicsPhysiology or Medic...
118165      3211005                    PeaceLiteraturePhysicsPhysicsChemistryPeace
121333      2499993              ChemistryPeacePhysiology or MedicineLiterature...
...                                                                            ...
10000000    11711430             Physiology or MedicineLiteraturePeacePhysiolog...
            11762861             ChemistryChemistryPhysicsEconomic SciencesLite...
            11807305             PhysicsPhysicsEconomic SciencesLiteraturePhysi...
            12034660             Economic SciencesPhysiology or MedicineLiterat...
            12295082             Economic SciencesChemistryPhysicsPhysicsEconom...

                                                                              name  \
prizeAmount prizeAmountAdjusted
114935      3169164              Frederick G. BantingFritz PreglJohn MacleodRob...
116719      3218355                Manne SiegbahnWillem EinthovenWladyslaw Reymont
116960      3273134              Aristide BriandGrazia DeleddaGustav Stresemann...
118165      3211005              Charles G. DawesGeorge Bernard ShawGustav Hert...
121333      2499993              Artturi VirtanenCordell HullErnst B. ChainGabr...
...                                                                            ...
10000000    11711430             Barry J. MarshallHarold PinterInternational At...
            11762861             Aaron CiechanoverAvram HershkoDavid J. GrossEd...
            11807305             Alexei AbrikosovAnthony J. LeggettClive W.J. G...
            12034660             Daniel KahnemanH. Robert HorvitzImre KertészJi...
            12295082             A. Michael SpenceBarry SharplessCarl WiemanEri...

                                                                            gender  \
prizeAmount prizeAmountAdjusted
114935      3169164                                           malemalemalemalemale
116719      3218355                                                   malemalemale
116960      3273134                                     malefemalemalemalemalemale
118165      3211005                                       malemalemalemalemalemale
121333      2499993                                 malemalemalefemalemalemalemale
...                                                                            ...
10000000    11711430              malemalemalemalemalemalemalemalemalemalemalemale
            11762861             malemalemalemalefemalemalemalemalemalefemalema...
            11807305                malemalemalemalemalemalemalemalefemalemalemale
            12034660             malemalemalemalemalemalemalemalemalemalemalema...
            12295082             malemalemalemalemalemalemalemalemalemalemalema...

                                                                   birth_continent
prizeAmount prizeAmountAdjusted
114935      3169164                   North AmericaEuropeEuropeNorth AmericaEurope
116719      3218355                                               EuropeAsiaEurope
116960      3273134                           EuropeEuropeEuropeEuropeEuropeEurope
118165      3211005                    North AmericaEuropeEuropeEuropeEuropeEurope
121333      2499993              EuropeNorth AmericaEuropeSouth AmericaEuropeOc...
...                                                                            ...
10000000    11711430             OceaniaEuropeOceaniaNorth AmericaAfricaNorth A...
            11762861             AsiaEuropeNorth AmericaNorth AmericaEuropeEuro...
            11807305             EuropeEuropeEuropeAfricaNorth AmericaNorth Ame...
            12034660             AsiaNorth AmericaEuropeNorth AmericaNorth Amer...
            12295082             North AmericaNorth AmericaNorth AmericaNorth A...

[114 rows x 5 columns]

In [58]:
df.groupby(['prizeAmount','prizeAmountAdjusted'])['prizeAmount'].sum()

prizeAmount  prizeAmountAdjusted
114935       3169164                   574675
116719       3218355                   350157
116960       3273134                   701760
118165       3211005                   708990
121333       2499993                   849331
                                      ...
10000000     11711430               130000000
             11762861               120000000
             11807305               110000000
             12034660               130000000
             12295082               150000000
Name: prizeAmount, Length: 114, dtype: int64

In [59]:
df.groupby('category')[['prizeAmountAdjusted','prizeAmount']].sum()

                        prizeAmountAdjusted  prizeAmount
category
Chemistry                        1151447726    667787418
Economic Sciences                 658373449    512891000
Literature                        649397731    289282102
Peace                             825963521    418733807
Physics                          1296526352    725890928
Physiology or Medicine           1256687857    672981066

In [60]:
df.groupby('category')[['prizeAmountAdjusted','prizeAmount']].agg([np.sum,np.mean,np.median])

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\1078242908.py:1: FutureWarning: The provided callable <function sum at 0x0000022A7A246200> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('category')[['prizeAmountAdjusted','prizeAmount']].agg([np.sum,np.mean,np.median])
C:\Users\HP\AppData\Local\Temp\ipykernel_15444\1078242908.py:1: FutureWarning: The provided callable <function mean at 0x0000022A7A247600> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('category')[['prizeAmountAdjusted','prizeAmount']].agg([np.sum,np.mean,np.median])
C:\Users\HP\AppData\Local\Temp\ipykernel_15444\1078242908.py:1: FutureWarning: The provided callable <function median at 0x0000022A7A390860> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('category')[['prizeAmountAdjusted','prizeAmount']].agg([np.sum,np.mean,np.median])
C:\Users\HP\AppData\Local\Temp\ipykernel_15444\1078242908.py:1: FutureWarning: The provided callable <function sum at 0x0000022A7A246200> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('category')[['prizeAmountAdjusted','prizeAmount']].agg([np.sum,np.mean,np.median])

                       prizeAmountAdjusted                           \
                                       sum          mean     median
category
Chemistry                       1151447726  6.257868e+06  5117217.0
Economic Sciences                658373449  7.837779e+06  9000000.0
Literature                       649397731  5.598256e+06  4366629.0
Peace                            825963521  6.163907e+06  5238085.0
Physics                         1296526352  6.086978e+06  4907955.0
Physiology or Medicine          1256687857  5.738301e+06  4098361.0

                       prizeAmount
                               sum          mean     median
category
Chemistry                667787418  3.629279e+06   800000.0
Economic Sciences        512891000  6.105845e+06  7550000.0
Literature               289282102  2.493811e+06   269000.0
Peace                    418733807  3.124879e+06   480000.0
Physics                  725890928  3.407939e+06   700000.0
Physiology or Medicine   672981066  3.072973e+06   510000.0

In [61]:
grouped.agg({'prizeAmount':[np.sum,np.size],'prizeAmountAdjusted':np.mean})

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\469950434.py:1: FutureWarning: The provided callable <function sum at 0x0000022A7A246200> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grouped.agg({'prizeAmount':[np.sum,np.size],'prizeAmountAdjusted':np.mean})
C:\Users\HP\AppData\Local\Temp\ipykernel_15444\469950434.py:1: FutureWarning: The provided callable <function mean at 0x0000022A7A247600> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grouped.agg({'prizeAmount':[np.sum,np.size],'prizeAmountAdjusted':np.mean})

                       prizeAmount      prizeAmountAdjusted
                               sum size                mean
category
Chemistry                667787418  184        6.257868e+06
Economic Sciences        512891000   84        7.837779e+06
Literature               289282102  116        5.598256e+06
Peace                    418733807  134        6.163907e+06
Physics                  725890928  213        6.086978e+06
Physiology or Medicine   672981066  219        5.738301e+06

In [62]:
df.groupby('category').agg({'prizeAmount':[np.sum,np.size],'prizeAmountAdjusted':np.mean})

C:\Users\HP\AppData\Local\Temp\ipykernel_15444\3934615713.py:1: FutureWarning: The provided callable <function sum at 0x0000022A7A246200> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('category').agg({'prizeAmount':[np.sum,np.size],'prizeAmountAdjusted':np.mean})
C:\Users\HP\AppData\Local\Temp\ipykernel_15444\3934615713.py:1: FutureWarning: The provided callable <function mean at 0x0000022A7A247600> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('category').agg({'prizeAmount':[np.sum,np.size],'prizeAmountAdjusted':np.mean})

                       prizeAmount      prizeAmountAdjusted
                               sum size                mean
category
Chemistry                667787418  184        6.257868e+06
Economic Sciences        512891000   84        7.837779e+06
Literature               289282102  116        5.598256e+06
Peace                    418733807  134        6.163907e+06
Physics                  725890928  213        6.086978e+06
Physiology or Medicine   672981066  219        5.738301e+06

In [63]:
df1 = pd.read_csv("nba.csv")

In [64]:
df1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [65]:
df1.nunique()

Name        457
Team         30
Number       53
Position      5
Age          22
Height       18
Weight       87
College     118
Salary      309
dtype: int64

In [69]:
df1..groupby("College")["College"].count()

SyntaxError: invalid syntax (2576171305.py, line 1)

In [70]:
df1.groupby(['Team','Position']).count()

                             Name  Number  Age  Height  Weight  College  \
Team               Position
Atlanta Hawks      C            3       3    3       3       3        1
                   PF           4       4    4       4       4        4
                   PG           2       2    2       2       2        1
                   SF           2       2    2       2       2        1
                   SG           4       4    4       4       4        4
...                           ...     ...  ...     ...     ...      ...
Washington Wizards C            3       3    3       3       3        1
                   PF           2       2    2       2       2        2
                   PG           2       2    2       2       2        2
                   SF           4       4    4       4       4        4
                   SG           4       4    4       4       4        4

                             Salary
Team               Position
Atlanta Hawks      C              3
                   PF             4
                   PG             2
                   SF             2
                   SG             4
...                             ...
Washington Wizards C              3
                   PF             2
                   PG             2
                   SF             4
                   SG             4

[149 rows x 7 columns]

In [71]:
df1.groupby(['Team','Position']).first()

                                         Name  Number   Age Height  Weight  \
Team               Position
Atlanta Hawks      C               Al Horford    15.0  30.0   6-10   245.0
                   PF          Kris Humphries    43.0  31.0    6-9   235.0
                   PG         Dennis Schroder    17.0  22.0    6-1   172.0
                   SF           Kent Bazemore    24.0  26.0    6-5   201.0
                   SG        Tim Hardaway Jr.    10.0  24.0    6-6   205.0
...                                       ...     ...   ...    ...     ...
Washington Wizards C            Marcin Gortat    13.0  32.0   6-11   240.0
                   PF             Drew Gooden    90.0  34.0   6-10   250.0
                   PG          Ramon Sessions     7.0  30.0    6-3   190.0
                   SF            Jared Dudley     1.0  30.0    6-7   225.0
                   SG           Alan Anderson     6.0  33.0    6-6   220.0

                                          College      Salary
Team               Position
Atlanta Hawks      C                      Florida  12000000.0
                   PF                   Minnesota   1000000.0
                   PG                 Wake Forest   1763400.0
                   SF                Old Dominion   2000000.0
                   SG                    Michigan   1304520.0
...                                           ...         ...
Washington Wizards C         North Carolina State  11217391.0
                   PF                      Kansas   3300000.0
                   PG                      Nevada   2170465.0
                   SF              Boston College   4375000.0
                   SG              Michigan State   4000000.0

[149 rows x 7 columns]

In [72]:
df1.groupby(['Team','Position']).last()

                                        Name  Number   Age Height  Weight  \
Team               Position
Atlanta Hawks      C          Walter Tavares    22.0  24.0    7-3   260.0
                   PF             Mike Scott    32.0  27.0    6-8   237.0
                   PG            Jeff Teague     0.0  27.0    6-2   186.0
                   SF        Thabo Sefolosha    25.0  32.0    6-7   220.0
                   SG        Lamar Patterson    13.0  24.0    6-5   225.0
...                                      ...     ...   ...    ...     ...
Washington Wizards C            Nene Hilario    42.0  33.0   6-11   250.0
                   PF        Markieff Morris     5.0  26.0   6-10   245.0
                   PG              John Wall     2.0  25.0    6-4   195.0
                   SF        Marcus Thornton    15.0  29.0    6-4   205.0
                   SG         Garrett Temple    17.0  30.0    6-6   195.0

                                          College      Salary
Team               Position
Atlanta Hawks      C                      Florida   1000000.0
                   PF                    Virginia   3333333.0
                   PG                 Wake Forest   8000000.0
                   SF                Old Dominion   4000000.0
                   SG                  Pittsburgh    525093.0
...                                           ...         ...
Washington Wizards C         North Carolina State  13000000.0
                   PF                      Kansas   8000000.0
                   PG                    Kentucky  15851950.0
                   SF                         LSU    200600.0
                   SG                         LSU   1100602.0

[149 rows x 7 columns]

In [73]:
df1.groupby(['Team','Position']), as_index=False).first()

SyntaxError: unmatched ')' (3504600523.py, line 1)