In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv("product.csv")

In [3]:
df2  = pd.read_csv("store.csv")

In [4]:
df1

   ProductID ProductName  StoreID  Price
0       1001   Product X      101   9.99
1       1002   Product Y      102  19.99
2       1003   Product Z      101  14.99
3       1004   Product W      104  29.99
4       1005   Product V      105  24.99

In [5]:
df2

   StoreID StoreName     Location  Manager
0      101   Store A     New York    Alice
1      102   Store B  Los Angeles      Bob
2      103   Store C      Chicago  Charlie
3      104   Store D      Houston    David
4      105   Store E      Phoenix      Eve

In [6]:
df2['ProductID'] = [np.nan,np.nan,np.nan, 1004,1005]

In [13]:
df2

   StoreID StoreName     Location  Manager  ProductID
0      101   Store A     New York    Alice        NaN
1      102   Store B  Los Angeles      Bob        NaN
2      103   Store C      Chicago  Charlie        NaN
3      104   Store D      Houston    David     1004.0
4      105   Store E      Phoenix      Eve     1005.0

In [34]:
final = pd.merge(df1,df2, on = ['StoreID','ProductID'], how = 'inner')

In [35]:
final

   ProductID ProductName  StoreID  Price StoreName Location Manager
0       1004   Product W      104  29.99   Store D  Houston   David
1       1005   Product V      105  24.99   Store E  Phoenix     Eve

In [36]:
final = pd.merge(df1,df2, on = ['StoreID','ProductID'], how = 'left')

In [37]:
final

   ProductID ProductName  StoreID  Price StoreName Location Manager
0       1001   Product X      101   9.99       NaN      NaN     NaN
1       1002   Product Y      102  19.99       NaN      NaN     NaN
2       1003   Product Z      101  14.99       NaN      NaN     NaN
3       1004   Product W      104  29.99   Store D  Houston   David
4       1005   Product V      105  24.99   Store E  Phoenix     Eve

In [38]:
final = pd.merge(df1,df2, on = ['StoreID','ProductID'], how = 'right')

In [39]:
final

   ProductID ProductName  StoreID  Price StoreName     Location  Manager
0        NaN         NaN      101    NaN   Store A     New York    Alice
1        NaN         NaN      102    NaN   Store B  Los Angeles      Bob
2        NaN         NaN      103    NaN   Store C      Chicago  Charlie
3     1004.0   Product W      104  29.99   Store D      Houston    David
4     1005.0   Product V      105  24.99   Store E      Phoenix      Eve

In [40]:
final = pd.merge(df1,df2, on = ['StoreID','ProductID'], how = 'outer')

In [41]:
final

   ProductID ProductName  StoreID  Price StoreName     Location  Manager
0     1001.0   Product X      101   9.99       NaN          NaN      NaN
1     1002.0   Product Y      102  19.99       NaN          NaN      NaN
2     1003.0   Product Z      101  14.99       NaN          NaN      NaN
3     1004.0   Product W      104  29.99   Store D      Houston    David
4     1005.0   Product V      105  24.99   Store E      Phoenix      Eve
5        NaN         NaN      101    NaN   Store A     New York    Alice
6        NaN         NaN      102    NaN   Store B  Los Angeles      Bob
7        NaN         NaN      103    NaN   Store C      Chicago  Charlie