In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("C://Users/lenovo/Downloads/Oct-Nov-Dec 2022-Status.xlsx", sheet_name=None)

In [4]:
df.keys()

dict_keys(['Oct-22', 'Nov-22', 'Dec-22'])

In [6]:
Oct_22 = df['Oct-22']

In [7]:
type(Oct_22)

pandas.core.frame.DataFrame

In [13]:
Oct_22.columns

Index(['statecode', 'rationcardid', 'card_type', 'total_quantity', 'month',
       'year', 'Remark', 'RC_length'],
      dtype='object')

In [17]:
Oct_22['RC_length'] = Oct_22['rationcardid'].str.len()

In [18]:
Oct_22

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length
0,23,007540801340,PHH,32.0,NaN,NaN,NaN,12
1,23,007770400060,PHH,28.0,NaN,NaN,NaN,12
2,23,008181600063,PHH,20.0,NaN,NaN,NaN,12
3,23,008301500314,PHH,20.0,NaN,NaN,NaN,12
4,23,008301500316,PHH,50.0,NaN,NaN,NaN,12
...,...,...,...,...,...,...,...,...
59166,23,8111115556,PHH,10.0,5.0,2022.0,NACO,10
59167,23,8111115557,PHH,10.0,5.0,2022.0,NACO,10
59168,23,8111115558,PHH,10.0,5.0,2022.0,NACO,10
59169,23,8111115559,PHH,10.0,5.0,2022.0,NACO,10
59170,23,8111115560,PHH,10.0,5.0,2022.0,NACO,10

In [20]:
Oct_22.RC_length.value_counts()

8     55922
10     2604
12      368
20      184
24       77
11        8
15        8
Name: RC_length, dtype: int64

In [22]:
Oct1_22 = Oct_22.copy()

In [23]:
IndexRC = Oct1_22[Oct1_22.RC_length>10].index

In [28]:
len(IndexRC.to_list())

645

In [29]:
Oct1_22.drop(IndexRC,inplace=True)

In [30]:
Oct1_22.RC_length.value_counts()

8     55922
10     2604
Name: RC_length, dtype: int64

In [32]:
Nov_22 = df['Nov-22']

In [33]:
Nov_22.shape

(127794, 7)

In [34]:
Dec_22 = df['Dec-22']

In [35]:
Dec_22.shape

(47421, 7)

In [36]:
Oct_22.shape

(59171, 8)

In [37]:
Oct_22.head(2)

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length
0,23,007540801340,PHH,32.0,NaN,NaN,NaN,12
1,23,007770400060,PHH,28.0,NaN,NaN,NaN,12

In [40]:
Nov_22['RC_length'] = Nov_22.rationcardid.str.len()

In [41]:
Nov_22.head(2)

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length
0,23,007761700004,AAY,59.0,NaN,NaN,NaN,12
1,23,007770400060,PHH,24.0,NaN,NaN,NaN,12

In [49]:
Dec_22['RC_length'] = Dec_22['rationcardid'].str.len()

AttributeError: Can only use .str accessor with string values!

In [52]:
Dec_22.rationcardid = Dec_22.rationcardid.astype(str)

In [53]:
Dec_22.head(2)

   statecode  rationcardid card_type  total_quantity  month  year Remark
0         23  7082100703.0       PHH             6.0    NaN   NaN    NaN
1         23  7090700163.0       PHH            72.0    NaN   NaN    NaN

In [55]:
Dec_22.rationcardid = Dec_22.rationcardid.str[:-1]

In [57]:
Dec_22.rationcardid = Dec_22.rationcardid.str[:-1]

In [58]:
Dec_22.head()

   statecode rationcardid card_type  total_quantity  month  year Remark
0         23   7082100703       PHH             6.0    NaN   NaN    NaN
1         23   7090700163       PHH            72.0    NaN   NaN    NaN
2         23   7761700004       AAY            10.0    NaN   NaN    NaN
3         23   7766700009       PHH            24.0    NaN   NaN    NaN
4         23   7766700010       PHH            60.0    NaN   NaN    NaN

In [59]:
Dec_22['RC_length'] = Dec_22['rationcardid'].str.len()

In [60]:
Dec_22.head(2)

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length
0,23,7082100703,PHH,6.0,NaN,NaN,NaN,10
1,23,7090700163,PHH,72.0,NaN,NaN,NaN,10

In [62]:
Oct_22['Month'] = 'October'

In [63]:
Nov_22['Month'] = 'November'
Dec_22['Month'] = 'December'

In [64]:
Oct_22.head()

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length,Month
0,23,007540801340,PHH,32.0,NaN,NaN,NaN,12,October
1,23,007770400060,PHH,28.0,NaN,NaN,NaN,12,October
2,23,008181600063,PHH,20.0,NaN,NaN,NaN,12,October
3,23,008301500314,PHH,20.0,NaN,NaN,NaN,12,October
4,23,008301500316,PHH,50.0,NaN,NaN,NaN,12,October

In [65]:
Nov_22.head()

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length,Month
0,23,007761700004,AAY,59.0,NaN,NaN,NaN,12,November
1,23,007770400060,PHH,24.0,NaN,NaN,NaN,12,November
2,23,007782600018,PHH,70.0,NaN,NaN,NaN,12,November
3,23,007782600020,PHH,20.0,NaN,NaN,NaN,12,November
4,23,008179800902,PHH,32.0,NaN,NaN,NaN,12,November

In [66]:
Dec_22.head()

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length,Month
0,23,7082100703,PHH,6.0,NaN,NaN,NaN,10,December
1,23,7090700163,PHH,72.0,NaN,NaN,NaN,10,December
2,23,7761700004,AAY,10.0,NaN,NaN,NaN,10,December
3,23,7766700009,PHH,24.0,NaN,NaN,NaN,10,December
4,23,7766700010,PHH,60.0,NaN,NaN,NaN,10,December

In [68]:
final = pd.concat([Oct_22,Nov_22,Dec_22])

In [69]:
final

,statecode,rationcardid,card_type,total_quantity,month,year,Remark,RC_length,Month
0,23,007540801340,PHH,32.0,NaN,NaN,NaN,12,October
1,23,007770400060,PHH,28.0,NaN,NaN,NaN,12,October
2,23,008181600063,PHH,20.0,NaN,NaN,NaN,12,October
3,23,008301500314,PHH,20.0,NaN,NaN,NaN,12,October
4,23,008301500316,PHH,50.0,NaN,NaN,NaN,12,October
...,...,...,...,...,...,...,...,...,...
47416,23,8111115556,PHH,8.0,5.0,2022.0,NACO,10,December
47417,23,8111115557,PHH,8.0,5.0,2022.0,NACO,10,December
47418,23,8111115558,PHH,8.0,5.0,2022.0,NACO,10,December
47419,23,8111115559,PHH,8.0,5.0,2022.0,NACO,10,December
47420,23,8111115560,PHH,8.0,5.0,2022.0,NACO,10,December

In [83]:
Summary = final.groupby(['Month','RC_length','RC_length'], as_index=False)['RC_length'].count()

In [84]:
Summary.sort_values(['Month','RC_length'],ascending=[False, False])

       Month  RC_length
16   October      55922
17   October       2604
19   October        368
21   October        184
22   October         77
18   October          8
20   October          8
9   November     124118
10  November       2525
12  November        743
14  November        265
15  November        121
13  November         13
11  November          9
3   December      43461
5   December       2893
7   December        731
4   December        222
2   December         64
6   December         36
8   December         11
1   December          2
0   December          1

In [85]:
Summary

       Month  RC_length
0   December          1
1   December          2
2   December         64
3   December      43461
4   December        222
5   December       2893
6   December         36
7   December        731
8   December         11
9   November     124118
10  November       2525
11  November          9
12  November        743
13  November         13
14  November        265
15  November        121
16   October      55922
17   October       2604
18   October          8
19   October        368
20   October          8
21   October        184
22   October         77

In [88]:
final.groupby(['Month','RC_length','RC_length'], as_index=False)['RC_length'].count()

       Month  RC_length
0   December          1
1   December          2
2   December         64
3   December      43461
4   December        222
5   December       2893
6   December         36
7   December        731
8   December         11
9   November     124118
10  November       2525
11  November          9
12  November        743
13  November         13
14  November        265
15  November        121
16   October      55922
17   October       2604
18   October          8
19   October        368
20   October          8
21   October        184
22   October         77

In [89]:
final.columns

Index(['statecode', 'rationcardid', 'card_type', 'total_quantity', 'month',
       'year', 'Remark', 'RC_length', 'Month'],
      dtype='object')

In [90]:
final.shape

(234386, 9)

In [98]:
f1 = final.value_counts(['Month','RC_length']).reset_index()

In [99]:
type(f1)

pandas.core.frame.DataFrame

In [102]:
f1.columns = ['Month','RC_length', 'Count']

In [103]:
f1

       Month  RC_length   Count
0   November          8  124118
1    October          8   55922
2   December          8   43461
3   December         10    2893
4    October         10    2604
5   November         10    2525
6   November         12     743
7   December         12     731
8    October         12     368
9   November         20     265
10  December          9     222
11   October         20     184
12  November         24     121
13   October         24      77
14  December          7      64
15  December         11      36
16  November         15      13
17  December         15      11
18  November         11       9
19   October         11       8
20   October         15       8
21  December          6       2
22  December          1       1

In [116]:
f1.sort_values(['Month','Count'], ascending=[False,False])

       Month  RC_length   Count
1    October          8   55922
4    October         10    2604
8    October         12     368
11   October         20     184
13   October         24      77
19   October         11       8
20   October         15       8
0   November          8  124118
5   November         10    2525
6   November         12     743
9   November         20     265
12  November         24     121
16  November         15      13
18  November         11       9
2   December          8   43461
3   December         10    2893
7   December         12     731
10  December          9     222
14  December          7      64
15  December         11      36
17  December         15      11
21  December          6       2
22  December          1       1