In [1]:
import numpy as np
import pandas as pd

In [3]:
f1=pd.read_excel("Registration details.xlsx")
f2=pd.read_excel("exam results.xlsx")

In [5]:
f1.columns

Index(['ADMISSION DATE', 'NAME OF STUDENT ', 'GENDER', 'DOB',
       'STUDENT EMAIL ID ', 'NO. OF ADMISIONS ', 'ENQUIRY NO.',
       'REGISTRATION NO'],
      dtype='object')

In [7]:
f2.columns

Index(['REGISTRATION NO', 'Name', 'No of questions Attempted ', 'Correct',
       'Incorrect', 'Marks Obtained', 'Percentage'],
      dtype='object')

In [9]:
f1.shape

(102, 8)

In [11]:
f2.shape

(32, 7)

In [13]:
f1.isna().sum()

ADMISSION DATE        88
NAME OF STUDENT       83
GENDER                83
DOB                   88
STUDENT EMAIL ID      88
NO. OF ADMISIONS     102
ENQUIRY NO.           88
REGISTRATION NO       88
dtype: int64

In [17]:
del f1['NO. OF ADMISIONS ']

In [19]:
f1.shape

(102, 7)

In [21]:
f1.dropna(inplace=True)

In [23]:
f1.isna().sum()

ADMISSION DATE       0
NAME OF STUDENT      0
GENDER               0
DOB                  0
STUDENT EMAIL ID     0
ENQUIRY NO.          0
REGISTRATION NO      0
dtype: int64

In [25]:
f1.shape

(14, 7)

In [27]:
#merge two files - result consist all columns

In [31]:
result1 =pd.merge(f1,f2,on=['REGISTRATION NO'])

In [33]:
result1

,ADMISSION DATE,NAME OF STUDENT,GENDER,DOB,STUDENT EMAIL ID,ENQUIRY NO.,REGISTRATION NO,Name,No of questions Attempted,Correct,Incorrect,Marks Obtained,Percentage
0,2020-03-28,millind arora,MALE,1980-05-10,milind@example.com,EN10-05-80,RG10-05-1980,millind arora,25,25,0,50,100
1,2020-03-29,abhinav,MALE,1980-06-11,abhind@example.com,EN11-06-80,RG11-06-1980,abhinav,25,25,0,50,100
2,2020-03-29,rahul tripathi,MALE,1980-07-13,rahind@example.com,EN13-07-80,RG13-07-1980,rahul tripathi,25,25,0,50,100
3,2020-03-29,sumit,MALE,1980-08-14,sumind@example.com,EN14-08-80,RG14-08-1980,sumit,25,24,1,48,96
4,2020-03-29,amit saini,MALE,1980-09-15,amiind@example.com,EN15-09-80,RG15-09-1980,amit saini,25,24,1,48,96
5,2020-03-29,akanshsha sudan,FEMALE,1980-10-17,akaind@example.com,EN17-10-80,RG17-10-1980,akanshsha sudan,25,24,1,48,96
6,2020-03-29,abhishek kumar,MALE,1980-11-18,abhind@example.com,EN18-11-80,RG18-11-1980,abhishek kumar,25,23,2,46,92
7,2020-03-30,yatharth aggarwal,MALE,1980-12-20,yatind@example.com,EN20-12-80,RG20-12-1980,yatharth aggarwal,25,23,2,46,92
8,2020-03-30,yograj,MALE,1981-01-21,yogind@example.com,EN21-01-81,RG21-01-1981,yograj,25,23,2,46,92
9,2020-03-30,parmeet kaur,FEMALE,1981-02-22,parind@example.com,EN22-02-81,RG22-02-1981,parmeet kaur,25,22,3,44,88
10,2020-03-30,ankit,MALE,1981-03-26,ankind@example.com,EN26-03-81,RG26-03-1981,ankit,25,22,3,44,88
11,2020-03-30,FAZAL ANSARI,MALE,1981-04-27,FAZind@example.com,EN27-04-81,RG27-04-1981,FAZAL ANSARI,25,22,3,44,88
12,2020-03-30,mayank,MALE,1981-05-29,mayind@example.com,EN29-05-81,RG29-05-1981,mayank,25,22,3,44,88
13,2020-03-30,ronak,MALE,1981-06-30,ronind@example.com,EN30-06-81,RG30-06-1981,ronak,25,22,3,44,88

In [35]:
result2 =pd.merge(f1,f2,on=['REGISTRATION NO'],how='left')
result2

,ADMISSION DATE,NAME OF STUDENT,GENDER,DOB,STUDENT EMAIL ID,ENQUIRY NO.,REGISTRATION NO,Name,No of questions Attempted,Correct,Incorrect,Marks Obtained,Percentage
0,2020-03-28,millind arora,MALE,1980-05-10,milind@example.com,EN10-05-80,RG10-05-1980,millind arora,25,25,0,50,100
1,2020-03-29,abhinav,MALE,1980-06-11,abhind@example.com,EN11-06-80,RG11-06-1980,abhinav,25,25,0,50,100
2,2020-03-29,rahul tripathi,MALE,1980-07-13,rahind@example.com,EN13-07-80,RG13-07-1980,rahul tripathi,25,25,0,50,100
3,2020-03-29,sumit,MALE,1980-08-14,sumind@example.com,EN14-08-80,RG14-08-1980,sumit,25,24,1,48,96
4,2020-03-29,amit saini,MALE,1980-09-15,amiind@example.com,EN15-09-80,RG15-09-1980,amit saini,25,24,1,48,96
5,2020-03-29,akanshsha sudan,FEMALE,1980-10-17,akaind@example.com,EN17-10-80,RG17-10-1980,akanshsha sudan,25,24,1,48,96
6,2020-03-29,abhishek kumar,MALE,1980-11-18,abhind@example.com,EN18-11-80,RG18-11-1980,abhishek kumar,25,23,2,46,92
7,2020-03-30,yatharth aggarwal,MALE,1980-12-20,yatind@example.com,EN20-12-80,RG20-12-1980,yatharth aggarwal,25,23,2,46,92
8,2020-03-30,yograj,MALE,1981-01-21,yogind@example.com,EN21-01-81,RG21-01-1981,yograj,25,23,2,46,92
9,2020-03-30,parmeet kaur,FEMALE,1981-02-22,parind@example.com,EN22-02-81,RG22-02-1981,parmeet kaur,25,22,3,44,88
10,2020-03-30,ankit,MALE,1981-03-26,ankind@example.com,EN26-03-81,RG26-03-1981,ankit,25,22,3,44,88
11,2020-03-30,FAZAL ANSARI,MALE,1981-04-27,FAZind@example.com,EN27-04-81,RG27-04-1981,FAZAL ANSARI,25,22,3,44,88
12,2020-03-30,mayank,MALE,1981-05-29,mayind@example.com,EN29-05-81,RG29-05-1981,mayank,25,22,3,44,88
13,2020-03-30,ronak,MALE,1981-06-30,ronind@example.com,EN30-06-81,RG30-06-1981,ronak,25,22,3,44,88

In [39]:
result3 =pd.merge(f1,f2,on=['REGISTRATION NO'],how='right')
result3

,ADMISSION DATE,NAME OF STUDENT,GENDER,DOB,STUDENT EMAIL ID,ENQUIRY NO.,REGISTRATION NO,Name,No of questions Attempted,Correct,Incorrect,Marks Obtained,Percentage
0,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1989,ABHINAV,25,21,4,42,84
1,2020-03-29,abhinav,MALE,1980-06-11,abhind@example.com,EN11-06-80,RG11-06-1980,abhinav,25,25,0,50,100
2,2020-03-29,abhishek kumar,MALE,1980-11-18,abhind@example.com,EN18-11-80,RG18-11-1980,abhishek kumar,25,23,2,46,92
3,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1991,Agam Singh Talwar,25,21,4,42,84
4,2020-03-29,akanshsha sudan,FEMALE,1980-10-17,akaind@example.com,EN17-10-80,RG17-10-1980,akanshsha sudan,25,24,1,48,96
5,2020-03-29,amit saini,MALE,1980-09-15,amiind@example.com,EN15-09-80,RG15-09-1980,amit saini,25,24,1,48,96
6,2020-03-30,ankit,MALE,1981-03-26,ankind@example.com,EN26-03-81,RG26-03-1981,ankit,25,22,3,44,88
7,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1987,Ankit,25,21,4,42,84
8,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1998,Divyanshi,25,19,6,38,76
9,2020-03-30,FAZAL ANSARI,MALE,1981-04-27,FAZind@example.com,EN27-04-81,RG27-04-1981,FAZAL ANSARI,25,22,3,44,88
10,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1997,FAZAL ANSARI,25,19,6,38,76
11,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1986,Gursimran,25,22,3,44,88
12,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1988,Kanwal Jeet Singh,25,21,4,42,84
13,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1994,Manish Rawat,25,19,6,38,76
14,2020-03-30,mayank,MALE,1981-05-29,mayind@example.com,EN29-05-81,RG29-05-1981,mayank,25,22,3,44,88
15,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1996,Mayank,25,19,6,38,76
16,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1999,Mehtab Kalra,25,18,7,36,72
17,2020-03-28,millind arora,MALE,1980-05-10,milind@example.com,EN10-05-80,RG10-05-1980,millind arora,25,25,0,50,100
18,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1990,Nikita Grover,24,21,3,42,84
19,2020-03-30,parmeet kaur,FEMALE,1981-02-22,parind@example.com,EN22-02-81,RG22-02-1981,parmeet kaur,25,22,3,44,88
20,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1982,POOJA CHAURASIA,25,22,3,44,88
21,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1995,Rahul Sharma,25,19,6,38,76
22,2020-03-29,rahul tripathi,MALE,1980-07-13,rahind@example.com,EN13-07-80,RG13-07-1980,rahul tripathi,25,25,0,50,100
23,2020-03-30,ronak,MALE,1981-06-30,ronind@example.com,EN30-06-81,RG30-06-1981,ronak,25,22,3,44,88
24,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1985,Saurabh Sharma,25,22,3,44,88
25,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1983,Shubham Gupta,25,22,3,44,88
26,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1993,Sumit,25,19,6,38,76
27,2020-03-29,sumit,MALE,1980-08-14,sumind@example.com,EN14-08-80,RG14-08-1980,sumit,25,24,1,48,96
28,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1992,Tanya,25,20,5,40,80
29,2020-03-30,yatharth aggarwal,MALE,1980-12-20,yatind@example.com,EN20-12-80,RG20-12-1980,yatharth aggarwal,25,23,2,46,92
30,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1984,Yatharth Aggarwal,25,22,3,44,88
31,2020-03-30,yograj,MALE,1981-01-21,yogind@example.com,EN21-01-81,RG21-01-1981,yograj,25,23,2,46,92

In [41]:
result4 =pd.merge(f1,f2,on=['REGISTRATION NO'],how='outer')
result4

,ADMISSION DATE,NAME OF STUDENT,GENDER,DOB,STUDENT EMAIL ID,ENQUIRY NO.,REGISTRATION NO,Name,No of questions Attempted,Correct,Incorrect,Marks Obtained,Percentage
0,2020-03-28,millind arora,MALE,1980-05-10,milind@example.com,EN10-05-80,RG10-05-1980,millind arora,25,25,0,50,100
1,2020-03-29,abhinav,MALE,1980-06-11,abhind@example.com,EN11-06-80,RG11-06-1980,abhinav,25,25,0,50,100
2,2020-03-29,rahul tripathi,MALE,1980-07-13,rahind@example.com,EN13-07-80,RG13-07-1980,rahul tripathi,25,25,0,50,100
3,2020-03-29,sumit,MALE,1980-08-14,sumind@example.com,EN14-08-80,RG14-08-1980,sumit,25,24,1,48,96
4,2020-03-29,amit saini,MALE,1980-09-15,amiind@example.com,EN15-09-80,RG15-09-1980,amit saini,25,24,1,48,96
5,2020-03-29,akanshsha sudan,FEMALE,1980-10-17,akaind@example.com,EN17-10-80,RG17-10-1980,akanshsha sudan,25,24,1,48,96
6,2020-03-29,abhishek kumar,MALE,1980-11-18,abhind@example.com,EN18-11-80,RG18-11-1980,abhishek kumar,25,23,2,46,92
7,2020-03-30,yatharth aggarwal,MALE,1980-12-20,yatind@example.com,EN20-12-80,RG20-12-1980,yatharth aggarwal,25,23,2,46,92
8,2020-03-30,yograj,MALE,1981-01-21,yogind@example.com,EN21-01-81,RG21-01-1981,yograj,25,23,2,46,92
9,2020-03-30,parmeet kaur,FEMALE,1981-02-22,parind@example.com,EN22-02-81,RG22-02-1981,parmeet kaur,25,22,3,44,88
10,2020-03-30,ankit,MALE,1981-03-26,ankind@example.com,EN26-03-81,RG26-03-1981,ankit,25,22,3,44,88
11,2020-03-30,FAZAL ANSARI,MALE,1981-04-27,FAZind@example.com,EN27-04-81,RG27-04-1981,FAZAL ANSARI,25,22,3,44,88
12,2020-03-30,mayank,MALE,1981-05-29,mayind@example.com,EN29-05-81,RG29-05-1981,mayank,25,22,3,44,88
13,2020-03-30,ronak,MALE,1981-06-30,ronind@example.com,EN30-06-81,RG30-06-1981,ronak,25,22,3,44,88
14,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1982,POOJA CHAURASIA,25,22,3,44,88
15,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1983,Shubham Gupta,25,22,3,44,88
16,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1984,Yatharth Aggarwal,25,22,3,44,88
17,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1985,Saurabh Sharma,25,22,3,44,88
18,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1986,Gursimran,25,22,3,44,88
19,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1987,Ankit,25,21,4,42,84
20,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1988,Kanwal Jeet Singh,25,21,4,42,84
21,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1989,ABHINAV,25,21,4,42,84
22,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1990,Nikita Grover,24,21,3,42,84
23,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1991,Agam Singh Talwar,25,21,4,42,84
24,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1992,Tanya,25,20,5,40,80
25,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1993,Sumit,25,19,6,38,76
26,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1994,Manish Rawat,25,19,6,38,76
27,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1995,Rahul Sharma,25,19,6,38,76
28,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1996,Mayank,25,19,6,38,76
29,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1997,FAZAL ANSARI,25,19,6,38,76
30,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1998,Divyanshi,25,19,6,38,76
31,NaT,NaN,NaN,NaT,NaN,NaN,RG30-06-1999,Mehtab Kalra,25,18,7,36,72

In [47]:
f1.columns

Index(['ADMISSION DATE', 'NAME OF STUDENT ', 'GENDER', 'DOB',
       'STUDENT EMAIL ID ', 'ENQUIRY NO.', 'REGISTRATION NO'],
      dtype='object')

In [49]:
f2.columns

Index(['REGISTRATION NO', 'Name', 'No of questions Attempted ', 'Correct',
       'Incorrect', 'Marks Obtained', 'Percentage'],
      dtype='object')

In [53]:
result5=pd.merge(f1[['REGISTRATION NO','STUDENT EMAIL ID ']],f2[['REGISTRATION NO','Name','Marks Obtained', 'Percentage']],on=['REGISTRATION NO'])

In [55]:
result5

,REGISTRATION NO,STUDENT EMAIL ID,Name,Marks Obtained,Percentage
0,RG10-05-1980,milind@example.com,millind arora,50,100
1,RG11-06-1980,abhind@example.com,abhinav,50,100
2,RG13-07-1980,rahind@example.com,rahul tripathi,50,100
3,RG14-08-1980,sumind@example.com,sumit,48,96
4,RG15-09-1980,amiind@example.com,amit saini,48,96
5,RG17-10-1980,akaind@example.com,akanshsha sudan,48,96
6,RG18-11-1980,abhind@example.com,abhishek kumar,46,92
7,RG20-12-1980,yatind@example.com,yatharth aggarwal,46,92
8,RG21-01-1981,yogind@example.com,yograj,46,92
9,RG22-02-1981,parind@example.com,parmeet kaur,44,88
10,RG26-03-1981,ankind@example.com,ankit,44,88
11,RG27-04-1981,FAZind@example.com,FAZAL ANSARI,44,88
12,RG29-05-1981,mayind@example.com,mayank,44,88
13,RG30-06-1981,ronind@example.com,ronak,44,88