In [176]:
import pandas as pd
import numpy as np

In [177]:
df=pd.read_csv('RegularSeasonCompactResults.csv')

In [178]:
df

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [179]:
df.ndim

2

# To check the top 5 rows of tke data

In [180]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

# To check the top 10 rows of tke data

In [181]:
df.head(10)

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0
6    1985      25   1228      64   1226      44    N      0
7    1985      25   1242      58   1268      56    N      0
8    1985      25   1260      98   1133      80    H      0
9    1985      25   1305      97   1424      89    H      0

# To check the last 5 rows of tke data

In [182]:
df.tail()

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

In [183]:
df.tail(10)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145279    2016     131   1392      80   1436      74    H      0
145280    2016     131   1401      71   1261      38    N      0
145281    2016     131   1419      82   1426      71    N      0
145282    2016     131   1433      76   1172      54    N      0
145283    2016     131   1451      62   1285      59    N      0
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

In [184]:
df.head(150)

     Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0      1985      20   1228      81   1328      64    N      0
1      1985      25   1106      77   1354      70    H      0
2      1985      25   1112      63   1223      56    H      0
3      1985      25   1165      70   1432      54    H      0
4      1985      25   1192      86   1447      74    H      0
..      ...     ...    ...     ...    ...     ...  ...    ...
145    1985      32   1151      64   1122      54    H      0
146    1985      32   1155      90   1144      55    H      0
147    1985      32   1185      85   1152      76    H      0
148    1985      32   1196      68   1199      65    A      0
149    1985      32   1201      61   1453      46    H      0

[150 rows x 8 columns]

# to check the no of rows by indexing

In [185]:
df[10:20]

    Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
10    1985      25   1307     103   1288      71    H      0
11    1985      25   1344      75   1438      71    N      0
12    1985      25   1374      91   1411      72    H      0
13    1985      25   1412      70   1397      65    N      0
14    1985      25   1417      87   1225      58    H      0
15    1985      26   1116      65   1368      62    H      0
16    1985      26   1120      92   1391      50    H      0
17    1985      26   1135      65   1306      60    A      0
18    1985      26   1143      58   1388      53    H      0
19    1985      26   1153      50   1184      48    H      0

In [186]:
df[55:61]

    Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
55    1985      27   1268      72   1397      49    N      0
56    1985      27   1314      81   1200      65    N      0
57    1985      27   1323      67   1264      56    H      0
58    1985      27   1412      50   1242      46    N      0
59    1985      27   1458      93   1288      78    H      0
60    1985      28   1104      81   1137      56    H      0

# to check the shape of the data

In [187]:
df.shape

(145289, 8)

# to get the list of the columns

In [188]:
df.columns

Index(['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc',
       'Numot'],
      dtype='object')

In [189]:
df.columns.tolist()

['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc', 'Numot']

# to get the info about the data

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145289 entries, 0 to 145288
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Season  145289 non-null  int64
 1   Daynum  145289 non-null  int64
 2   Wteam   145289 non-null  int64
 3   Wscore  145289 non-null  int64
 4   Lteam   145289 non-null  int64
 5   Lscore  145289 non-null  int64
 6   Wloc    145289 non-null  object
 7   Numot   145289 non-null  int64
dtypes: int64(7), object(1)
memory usage: 8.9+ MB

# to get the satistical info about the data

In [191]:
df.describe()

,Season,Daynum,Wteam,Wscore,Lteam,Lscore,Numot
count,145289.000000,145289.000000,145289.000000,145289.000000,145289.000000,145289.000000,145289.000000
mean,2001.574834,75.223816,1286.720646,76.600321,1282.864064,64.497009,0.044387
std,9.233342,33.287418,104.570275,12.173033,104.829234,11.380625,0.247819
min,1985.000000,0.000000,1101.000000,34.000000,1101.000000,20.000000,0.000000
25%,1994.000000,47.000000,1198.000000,68.000000,1191.000000,57.000000,0.000000
50%,2002.000000,78.000000,1284.000000,76.000000,1280.000000,64.000000,0.000000
75%,2010.000000,103.000000,1379.000000,84.000000,1375.000000,72.000000,0.000000
max,2016.000000,132.000000,1464.000000,186.000000,1464.000000,150.000000,6.000000

# aggregate functions

In [192]:
df[['Wteam']]

        Wteam
0        1228
1        1106
2        1112
3        1165
4        1192
...       ...
145284   1114
145285   1163
145286   1246
145287   1277
145288   1386

[145289 rows x 1 columns]

In [193]:
df['Wteam'].mean()

np.float64(1286.7206464357246)

In [194]:
df['Wteam'].median()

np.float64(1284.0)

In [195]:
df['Wteam'].mode()

0    1181
Name: Wteam, dtype: int64

In [196]:
df['Wteam'].std()

np.float64(104.57027504914535)

In [197]:
df['Wteam'].var()

np.float64(10934.94242385391)

In [198]:
np.mean(df['Wteam'])

np.float64(1286.7206464357246)

In [199]:
np.std(df['Wteam'])

np.float64(104.5699151786287)

In [200]:
np.var(df['Wteam'])

np.float64(10934.867160465603)

In [201]:
df['Wteam'].min()

np.int64(1101)

In [202]:
df['Wteam'].max()

np.int64(1464)

In [203]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

# Indexing and slicing

In [204]:
df[-1:-21:-2]

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145288    2016     132   1386      87   1433      74    N      0
145286    2016     132   1246      82   1401      77    N      1
145284    2016     132   1114      70   1419      50    N      0
145282    2016     131   1433      76   1172      54    N      0
145280    2016     131   1401      71   1261      38    N      0
145278    2016     131   1386      82   1173      79    N      0
145276    2016     131   1372      82   1394      60    N      0
145274    2016     131   1345      76   1276      59    N      0
145272    2016     131   1314      61   1438      57    N      0
145270    2016     131   1277      64   1268      61    N      0

In [205]:
df[0:6]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0

# iloc:used to fetch the data by only int indexing

In [206]:
df.iloc[0:6]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0

In [207]:
df.iloc[0:6,0:3]

   Season  Daynum  Wteam
0    1985      20   1228
1    1985      25   1106
2    1985      25   1112
3    1985      25   1165
4    1985      25   1192
5    1985      25   1218

In [208]:
df.iloc[-1:-6:-1,-1:-3:-1]

        Numot Wloc
145288      0    N
145287      0    N
145286      1    N
145285      0    N
145284      0    N

In [209]:
df.iloc[0:3,2:5]

   Wteam  Wscore  Lteam
0   1228      81   1328
1   1106      77   1354
2   1112      63   1223

# loc : used to fetch the data by the labels

In [210]:
df.loc[2:6]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0
6    1985      25   1228      64   1226      44    N      0

In [211]:
df.loc[2:6,['Daynum','Wteam']]

   Daynum  Wteam
2      25   1112
3      25   1165
4      25   1192
5      25   1218
6      25   1228

In [212]:
df['Wscore']

0         81
1         77
2         63
3         70
4         86
          ..
145284    70
145285    72
145286    82
145287    66
145288    87
Name: Wscore, Length: 145289, dtype: int64

In [213]:
df['Wscore'].max()

np.int64(186)

In [214]:
df['Wscore'].idxmax()

24970

In [215]:
df.iloc[24970]

Season    1991
Daynum      68
Wteam     1258
Wscore     186
Lteam     1109
Lscore     140
Wloc         H
Numot        0
Name: 24970, dtype: object

In [216]:
df['Wscore'].idxmin()

128582

In [217]:
df.iloc[128582]

Season    2013
Daynum     116
Wteam     1264
Wscore      34
Lteam     1193
Lscore      31
Wloc         H
Numot        0
Name: 128582, dtype: object

# to check the uniqevalue in th data

In [218]:
df['Season'].unique()

array([1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
       1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

In [219]:
df['Season'].nunique()

32

# to check the count of the value in the data

In [220]:
df['Season'].value_counts()

Season
2016    5369
2014    5362
2015    5354
2013    5320
2010    5263
2012    5253
2009    5249
2011    5246
2008    5163
2007    5043
2006    4757
2005    4675
2003    4616
2004    4571
2002    4555
2000    4519
2001    4467
1999    4222
1998    4167
1997    4155
1992    4127
1991    4123
1996    4122
1995    4077
1994    4060
1990    4045
1989    4037
1993    3982
1988    3955
1987    3915
1986    3783
1985    3737
Name: count, dtype: int64

In [221]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

# to sort the data according to particular columns

In [222]:
df.sort_values(by =['Wscore'])

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
128582    2013     116   1264      34   1193      31    H      0
5364      1986      77   1229      35   1166      34    A      0
69336     2001     126   1206      35   1423      33    N      0
118590    2011     130   1336      36   1458      33    N      0
20246     1990      47   1374      36   1426      31    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
20022     1990      40   1116     166   1109     101    H      0
24341     1991      47   1328     172   1258     112    H      0
19653     1990      30   1328     173   1109     101    H      0
17867     1989      92   1258     181   1109     150    H      0
24970     1991      68   1258     186   1109     140    H      0

[145289 rows x 8 columns]

In [223]:
df.sort_values(by =['Wscore'])

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
128582    2013     116   1264      34   1193      31    H      0
5364      1986      77   1229      35   1166      34    A      0
69336     2001     126   1206      35   1423      33    N      0
118590    2011     130   1336      36   1458      33    N      0
20246     1990      47   1374      36   1426      31    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
20022     1990      40   1116     166   1109     101    H      0
24341     1991      47   1328     172   1258     112    H      0
19653     1990      30   1328     173   1109     101    H      0
17867     1989      92   1258     181   1109     150    H      0
24970     1991      68   1258     186   1109     140    H      0

[145289 rows x 8 columns]

In [224]:
df.sort_values(by =['Wscore'],ascending=False)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
24970     1991      68   1258     186   1109     140    H      0
17867     1989      92   1258     181   1109     150    H      0
19653     1990      30   1328     173   1109     101    H      0
24341     1991      47   1328     172   1258     112    H      0
20022     1990      40   1116     166   1109     101    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
20246     1990      47   1374      36   1426      31    H      0
118590    2011     130   1336      36   1458      33    N      0
69336     2001     126   1206      35   1423      33    N      0
5364      1986      77   1229      35   1166      34    A      0
128582    2013     116   1264      34   1193      31    H      0

[145289 rows x 8 columns]

In [225]:
df.sort_values(by =['Wscore'],ascending=True)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
128582    2013     116   1264      34   1193      31    H      0
5364      1986      77   1229      35   1166      34    A      0
69336     2001     126   1206      35   1423      33    N      0
118590    2011     130   1336      36   1458      33    N      0
20246     1990      47   1374      36   1426      31    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
20022     1990      40   1116     166   1109     101    H      0
24341     1991      47   1328     172   1258     112    H      0
19653     1990      30   1328     173   1109     101    H      0
17867     1989      92   1258     181   1109     150    H      0
24970     1991      68   1258     186   1109     140    H      0

[145289 rows x 8 columns]

In [226]:
df.sort_values(by =['Wteam'],ascending=True)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
139440    2015     120   1101      83   1223      71    H      0
143283    2016      89   1101      80   1249      71    H      0
142816    2016      78   1101      75   1270      67    H      0
137131    2015      71   1101      95   1322      81    A      0
135619    2015      31   1101      72   1170      61    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
65724     2001      33   1464      63   1331      62    A      0
33576     1993      79   1464     104   1138      89    H      0
173       1985      32   1464      81   1106      55    N      0
82        1985      28   1464      71   1134      58    H      0
689       1985      47   1464      74   1375      73    H      0

[145289 rows x 8 columns]

In [227]:
df.sort_values(by =['Wteam'],ascending=False)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
114074    2011      23   1464      73   1405      67    H      0
4467      1986      47   1464      64   1320      62    H      0
144171    2016     106   1464      92   1227      91    H      2
5396      1986      77   1464      75   1184      69    H      0
5341      1986      75   1464      75   1287      48    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
139440    2015     120   1101      83   1223      71    H      0
143283    2016      89   1101      80   1249      71    H      0
135619    2015      31   1101      72   1170      61    H      0
137131    2015      71   1101      95   1322      81    A      0
136740    2015      62   1101      87   1146      70    H      0

[145289 rows x 8 columns]

In [228]:
df.sort_values(by =['Wteam','Wscore'],ascending=[False,True])

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
62239     2000      65   1464      43   1237      41    A      0
12511     1988      57   1464      48   1186      47    H      0
40469     1995      46   1464      53   1293      48    N      0
119031    2012      18   1464      53   1415      49    H      1
11835     1988      33   1464      54   1368      51    N      0
...        ...     ...    ...     ...    ...     ...  ...    ...
136740    2015      62   1101      87   1146      70    H      0
142481    2016      71   1101      87   1322      72    H      0
144622    2016     117   1101      87   1309      84    H      0
144430    2016     111   1101      91   1368      80    H      0
137131    2015      71   1101      95   1322      81    A      0

[145289 rows x 8 columns]

In [229]:
df["Wloc"].value_counts()

Wloc
H    86471
A    44229
N    14589
Name: count, dtype: int64

In [230]:
df.sample(20)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
75079     2003      44   1387      83   1212      54    H      0
133729    2014     111   1304      76   1345      57    H      0
109214    2010      33   1237      86   1295      74    H      0
16803     1989      68   1110      70   1206      68    H      0
135142    2015      21   1360      77   1444      70    H      0
40607     1995      50   1241      70   1117      52    A      0
14617     1988     110   1292      92   1398      87    H      0
62703     2000      75   1424      98   1102      73    A      0
92688     2007      11   1160      78   1176      64    H      0
56998     1999      39   1216      89   1148      82    N      0
112623    2010     113   1243      83   1403      64    A      0
77904     2003     111   1103      84   1325      82    H      1
49888     1997      79   1231      66   1321      63    A      0
97841     2008       5   1463      82   1357      71    H      0
66939     2001      70   1428      83   1461      71    H      0
77597     2003     103   1444      67   1132      65    A      0
1636      1985      79   1153      73   1376      51    H      0
21055     1990      72   1400      83   1395      80    A      0
103340    2009      19   1415      59   1319      52    H      0
109682    2010      47   1320      64   1315      41    A      0

# to get the values only from the data

In [231]:
df.values

array([[1985, 20, 1228, ..., 64, 'N', 0],
       [1985, 25, 1106, ..., 70, 'H', 0],
       [1985, 25, 1112, ..., 56, 'H', 0],
       ...,
       [2016, 132, 1246, ..., 77, 'N', 1],
       [2016, 132, 1277, ..., 62, 'N', 0],
       [2016, 132, 1386, ..., 74, 'N', 0]], dtype=object)

# to get the dtype of all the columns

In [232]:
df.dtypes

Season     int64
Daynum     int64
Wteam      int64
Wscore     int64
Lteam      int64
Lscore     int64
Wloc      object
Numot      int64
dtype: object

# to get the null values

In [233]:
df.isnull()

        Season  Daynum  Wteam  Wscore  Lteam  Lscore   Wloc  Numot
0        False   False  False   False  False   False  False  False
1        False   False  False   False  False   False  False  False
2        False   False  False   False  False   False  False  False
3        False   False  False   False  False   False  False  False
4        False   False  False   False  False   False  False  False
...        ...     ...    ...     ...    ...     ...    ...    ...
145284   False   False  False   False  False   False  False  False
145285   False   False  False   False  False   False  False  False
145286   False   False  False   False  False   False  False  False
145287   False   False  False   False  False   False  False  False
145288   False   False  False   False  False   False  False  False

[145289 rows x 8 columns]

In [234]:
df.isnull().sum()

Season    0
Daynum    0
Wteam     0
Wscore    0
Lteam     0
Lscore    0
Wloc      0
Numot     0
dtype: int64

# to check the duplicate rows in the data

In [235]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
145284    False
145285    False
145286    False
145287    False
145288    False
Length: 145289, dtype: bool

In [236]:
df.duplicated().sum()

np.int64(0)

In [237]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

# to rename the columns

In [238]:
df.rename(columns={'Season':'Year'})

        Year  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0       1985      20   1228      81   1328      64    N      0
1       1985      25   1106      77   1354      70    H      0
2       1985      25   1112      63   1223      56    H      0
3       1985      25   1165      70   1432      54    H      0
4       1985      25   1192      86   1447      74    H      0
...      ...     ...    ...     ...    ...     ...  ...    ...
145284  2016     132   1114      70   1419      50    N      0
145285  2016     132   1163      72   1272      58    N      0
145286  2016     132   1246      82   1401      77    N      1
145287  2016     132   1277      66   1345      62    N      0
145288  2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [239]:
df

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [240]:
df.rename(columns={'Season':'Year'},inplace=True)

In [241]:
df

        Year  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0       1985      20   1228      81   1328      64    N      0
1       1985      25   1106      77   1354      70    H      0
2       1985      25   1112      63   1223      56    H      0
3       1985      25   1165      70   1432      54    H      0
4       1985      25   1192      86   1447      74    H      0
...      ...     ...    ...     ...    ...     ...  ...    ...
145284  2016     132   1114      70   1419      50    N      0
145285  2016     132   1163      72   1272      58    N      0
145286  2016     132   1246      82   1401      77    N      1
145287  2016     132   1277      66   1345      62    N      0
145288  2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [242]:
df.head()

   Year  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0  1985      20   1228      81   1328      64    N      0
1  1985      25   1106      77   1354      70    H      0
2  1985      25   1112      63   1223      56    H      0
3  1985      25   1165      70   1432      54    H      0
4  1985      25   1192      86   1447      74    H      0

In [243]:
df.rename(columns={'Wteam':'Team','Wscore':'Score','Lteam':'Team'},inplace=True)

In [244]:
df

        Year  Daynum  Team  Score  Team  Lscore Wloc  Numot
0       1985      20  1228     81  1328      64    N      0
1       1985      25  1106     77  1354      70    H      0
2       1985      25  1112     63  1223      56    H      0
3       1985      25  1165     70  1432      54    H      0
4       1985      25  1192     86  1447      74    H      0
...      ...     ...   ...    ...   ...     ...  ...    ...
145284  2016     132  1114     70  1419      50    N      0
145285  2016     132  1163     72  1272      58    N      0
145286  2016     132  1246     82  1401      77    N      1
145287  2016     132  1277     66  1345      62    N      0
145288  2016     132  1386     87  1433      74    N      0

[145289 rows x 8 columns]

# to drop the columns

In [245]:
df.drop(columns=['Wloc','Numot'],inplace=True)

In [246]:
df

        Year  Daynum  Team  Score  Team  Lscore
0       1985      20  1228     81  1328      64
1       1985      25  1106     77  1354      70
2       1985      25  1112     63  1223      56
3       1985      25  1165     70  1432      54
4       1985      25  1192     86  1447      74
...      ...     ...   ...    ...   ...     ...
145284  2016     132  1114     70  1419      50
145285  2016     132  1163     72  1272      58
145286  2016     132  1246     82  1401      77
145287  2016     132  1277     66  1345      62
145288  2016     132  1386     87  1433      74

[145289 rows x 6 columns]

In [247]:
df

        Year  Daynum  Team  Score  Team  Lscore
0       1985      20  1228     81  1328      64
1       1985      25  1106     77  1354      70
2       1985      25  1112     63  1223      56
3       1985      25  1165     70  1432      54
4       1985      25  1192     86  1447      74
...      ...     ...   ...    ...   ...     ...
145284  2016     132  1114     70  1419      50
145285  2016     132  1163     72  1272      58
145286  2016     132  1246     82  1401      77
145287  2016     132  1277     66  1345      62
145288  2016     132  1386     87  1433      74

[145289 rows x 6 columns]

In [248]:
df.head()

   Year  Daynum  Team  Score  Team  Lscore
0  1985      20  1228     81  1328      64
1  1985      25  1106     77  1354      70
2  1985      25  1112     63  1223      56
3  1985      25  1165     70  1432      54
4  1985      25  1192     86  1447      74

In [249]:
df['New_Year']=df['Year']+10

In [250]:
df

        Year  Daynum  Team  Score  Team  Lscore  New_Year
0       1985      20  1228     81  1328      64      1995
1       1985      25  1106     77  1354      70      1995
2       1985      25  1112     63  1223      56      1995
3       1985      25  1165     70  1432      54      1995
4       1985      25  1192     86  1447      74      1995
...      ...     ...   ...    ...   ...     ...       ...
145284  2016     132  1114     70  1419      50      2026
145285  2016     132  1163     72  1272      58      2026
145286  2016     132  1246     82  1401      77      2026
145287  2016     132  1277     66  1345      62      2026
145288  2016     132  1386     87  1433      74      2026

[145289 rows x 7 columns]

# to set any columns as an index

In [251]:
df.set_index('Year',inplace=True)

In [252]:
df

      Daynum  Team  Score  Team  Lscore  New_Year
Year
1985      20  1228     81  1328      64      1995
1985      25  1106     77  1354      70      1995
1985      25  1112     63  1223      56      1995
1985      25  1165     70  1432      54      1995
1985      25  1192     86  1447      74      1995
...      ...   ...    ...   ...     ...       ...
2016     132  1114     70  1419      50      2026
2016     132  1163     72  1272      58      2026
2016     132  1246     82  1401      77      2026
2016     132  1277     66  1345      62      2026
2016     132  1386     87  1433      74      2026

[145289 rows x 6 columns]

In [253]:
df

      Daynum  Team  Score  Team  Lscore  New_Year
Year
1985      20  1228     81  1328      64      1995
1985      25  1106     77  1354      70      1995
1985      25  1112     63  1223      56      1995
1985      25  1165     70  1432      54      1995
1985      25  1192     86  1447      74      1995
...      ...   ...    ...   ...     ...       ...
2016     132  1114     70  1419      50      2026
2016     132  1163     72  1272      58      2026
2016     132  1246     82  1401      77      2026
2016     132  1277     66  1345      62      2026
2016     132  1386     87  1433      74      2026

[145289 rows x 6 columns]

# to reset_index()

In [254]:
df.reset_index(inplace=True)

In [255]:
df

        Year  Daynum  Team  Score  Team  Lscore  New_Year
0       1985      20  1228     81  1328      64      1995
1       1985      25  1106     77  1354      70      1995
2       1985      25  1112     63  1223      56      1995
3       1985      25  1165     70  1432      54      1995
4       1985      25  1192     86  1447      74      1995
...      ...     ...   ...    ...   ...     ...       ...
145284  2016     132  1114     70  1419      50      2026
145285  2016     132  1163     72  1272      58      2026
145286  2016     132  1246     82  1401      77      2026
145287  2016     132  1277     66  1345      62      2026
145288  2016     132  1386     87  1433      74      2026

[145289 rows x 7 columns]

# to rename the index

In [256]:
df.rename(index={0:'Bhopal'},inplace=True)

In [257]:
df

        Year  Daynum  Team  Score  Team  Lscore  New_Year
Bhopal  1985      20  1228     81  1328      64      1995
1       1985      25  1106     77  1354      70      1995
2       1985      25  1112     63  1223      56      1995
3       1985      25  1165     70  1432      54      1995
4       1985      25  1192     86  1447      74      1995
...      ...     ...   ...    ...   ...     ...       ...
145284  2016     132  1114     70  1419      50      2026
145285  2016     132  1163     72  1272      58      2026
145286  2016     132  1246     82  1401      77      2026
145287  2016     132  1277     66  1345      62      2026
145288  2016     132  1386     87  1433      74      2026

[145289 rows x 7 columns]

In [258]:
df.insert(2,"New_Year2",df['Year']+10)

In [259]:
df

        Year  Daynum  New_Year2  Team  Score  Team  Lscore  New_Year
Bhopal  1985      20       1995  1228     81  1328      64      1995
1       1985      25       1995  1106     77  1354      70      1995
2       1985      25       1995  1112     63  1223      56      1995
3       1985      25       1995  1165     70  1432      54      1995
4       1985      25       1995  1192     86  1447      74      1995
...      ...     ...        ...   ...    ...   ...     ...       ...
145284  2016     132       2026  1114     70  1419      50      2026
145285  2016     132       2026  1163     72  1272      58      2026
145286  2016     132       2026  1246     82  1401      77      2026
145287  2016     132       2026  1277     66  1345      62      2026
145288  2016     132       2026  1386     87  1433      74      2026

[145289 rows x 8 columns]

In [358]:
import pandas as pd
import numpy as np

In [359]:
x={'Id':[1,2,3,4],"Name":['ram','shyam','sanyam','priyam'],'Age':[20,21,22,23]}

In [360]:
x=pd.DataFrame(x)

In [361]:
x

   Id    Name  Age
0   1     ram   20
1   2   shyam   21
2   3  sanyam   22
3   4  priyam   23

In [362]:
y={'Id':[3,4,5,6],"City":['Bhopal','Indore','Bhopal','Goa'],'Salary':[10,20,30,40]}

In [363]:
y=pd.DataFrame(y)

In [364]:
y

   Id    City  Salary
0   3  Bhopal      10
1   4  Indore      20
2   5  Bhopal      30
3   6     Goa      40

In [365]:
a=pd.concat([x,y],axis=0)

In [366]:
a

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0     NaN     NaN
3   4  priyam  23.0     NaN     NaN
0   3     NaN   NaN  Bhopal    10.0
1   4     NaN   NaN  Indore    20.0
2   5     NaN   NaN  Bhopal    30.0
3   6     NaN   NaN     Goa    40.0

In [367]:
b=pd.concat([x,y],axis=0,ignore_index=True)

In [368]:
b

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0     NaN     NaN
3   4  priyam  23.0     NaN     NaN
4   3     NaN   NaN  Bhopal    10.0
5   4     NaN   NaN  Indore    20.0
6   5     NaN   NaN  Bhopal    30.0
7   6     NaN   NaN     Goa    40.0

In [369]:
a=pd.concat([x,y],axis=1)

In [370]:
a

   Id    Name  Age  Id    City  Salary
0   1     ram   20   3  Bhopal      10
1   2   shyam   21   4  Indore      20
2   3  sanyam   22   5  Bhopal      30
3   4  priyam   23   6     Goa      40

In [371]:
a

   Id    Name  Age  Id    City  Salary
0   1     ram   20   3  Bhopal      10
1   2   shyam   21   4  Indore      20
2   3  sanyam   22   5  Bhopal      30
3   4  priyam   23   6     Goa      40

In [372]:
b=pd.concat([x,y],axis=0,keys=["x","y"])

In [373]:
b

     Id    Name   Age    City  Salary
x 0   1     ram  20.0     NaN     NaN
  1   2   shyam  21.0     NaN     NaN
  2   3  sanyam  22.0     NaN     NaN
  3   4  priyam  23.0     NaN     NaN
y 0   3     NaN   NaN  Bhopal    10.0
  1   4     NaN   NaN  Indore    20.0
  2   5     NaN   NaN  Bhopal    30.0
  3   6     NaN   NaN     Goa    40.0

In [374]:
x._append(y)

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0     NaN     NaN
3   4  priyam  23.0     NaN     NaN
0   3     NaN   NaN  Bhopal    10.0
1   4     NaN   NaN  Indore    20.0
2   5     NaN   NaN  Bhopal    30.0
3   6     NaN   NaN     Goa    40.0

In [375]:
x

   Id    Name  Age
0   1     ram   20
1   2   shyam   21
2   3  sanyam   22
3   4  priyam   23

In [376]:
y

   Id    City  Salary
0   3  Bhopal      10
1   4  Indore      20
2   5  Bhopal      30
3   6     Goa      40

In [377]:
inner=pd.merge(x,y,on='Id',how='inner')

In [378]:
inner

   Id    Name  Age    City  Salary
0   3  sanyam   22  Bhopal      10
1   4  priyam   23  Indore      20

In [379]:
Left=pd.merge(x,y,on='Id',how='left')

In [380]:
Left

   Id    Name  Age    City  Salary
0   1     ram   20     NaN     NaN
1   2   shyam   21     NaN     NaN
2   3  sanyam   22  Bhopal    10.0
3   4  priyam   23  Indore    20.0

In [381]:
right=pd.merge(x,y,on='Id',how='right')

In [382]:
right

   Id    Name   Age    City  Salary
0   3  sanyam  22.0  Bhopal      10
1   4  priyam  23.0  Indore      20
2   5     NaN   NaN  Bhopal      30
3   6     NaN   NaN     Goa      40

In [383]:
outer=pd.merge(x,y,on='Id',how='outer')

In [384]:
outer

   Id    Name   Age    City  Salary
0   1     ram  20.0     NaN     NaN
1   2   shyam  21.0     NaN     NaN
2   3  sanyam  22.0  Bhopal    10.0
3   4  priyam  23.0  Indore    20.0
4   5     NaN   NaN  Bhopal    30.0
5   6     NaN   NaN     Goa    40.0

In [385]:
x

   Id    Name  Age
0   1     ram   20
1   2   shyam   21
2   3  sanyam   22
3   4  priyam   23

In [386]:
inner

   Id    Name  Age    City  Salary
0   3  sanyam   22  Bhopal      10
1   4  priyam   23  Indore      20

In [ ]:
outer

In [331]:
outer['Last_name']='Sharma'

In [332]:
outer

   Id    Name   Age    City  Salary Last_name
0   1     ram  20.0     NaN     NaN    Sharma
1   2   shyam  21.0     NaN     NaN    Sharma
2   3  sanyam  22.0  Bhopal    10.0    Sharma
3   4  priyam  23.0  Indore    20.0    Sharma
4   5     NaN   NaN  Bhopal    30.0    Sharma
5   6     NaN   NaN     Goa    40.0    Sharma

In [356]:
outer['full_name']=outer['Name']+outer['Last_name']

KeyError: 'Name'

In [357]:
outer

   Id   Age    City Salary     full_namr
0   1  20.0       x      x     ramSharma
1   2  21.0       x      x   shyamSharma
2   3  22.0  Bhopal   10.0  sanyamSharma
3   4  23.0  Indore   20.0  priyamSharma
4   5     x  Bhopal   30.0             x
5   6     x     Goa   40.0             x

In [335]:
outer

   Id    Name   Age    City  Salary Last_name     full_namr
0   1     ram  20.0     NaN     NaN    Sharma     ramSharma
1   2   shyam  21.0     NaN     NaN    Sharma   shyamSharma
2   3  sanyam  22.0  Bhopal    10.0    Sharma  sanyamSharma
3   4  priyam  23.0  Indore    20.0    Sharma  priyamSharma
4   5     NaN   NaN  Bhopal    30.0    Sharma           NaN
5   6     NaN   NaN     Goa    40.0    Sharma           NaN

In [336]:
outer.fillna('x',inplace=True)

C:\Users\dell\AppData\Local\Temp\ipykernel_11044\895014583.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'x' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  outer.fillna('x',inplace=True)

In [337]:
outer

   Id    Name   Age    City Salary Last_name     full_namr
0   1     ram  20.0       x      x    Sharma     ramSharma
1   2   shyam  21.0       x      x    Sharma   shyamSharma
2   3  sanyam  22.0  Bhopal   10.0    Sharma  sanyamSharma
3   4  priyam  23.0  Indore   20.0    Sharma  priyamSharma
4   5       x     x  Bhopal   30.0    Sharma             x
5   6       x     x     Goa   40.0    Sharma             x

In [338]:
outer['Name']=outer['Name'].replace("x","SHAYAM")

In [339]:
outer

   Id    Name   Age    City Salary Last_name     full_namr
0   1     ram  20.0       x      x    Sharma     ramSharma
1   2   shyam  21.0       x      x    Sharma   shyamSharma
2   3  sanyam  22.0  Bhopal   10.0    Sharma  sanyamSharma
3   4  priyam  23.0  Indore   20.0    Sharma  priyamSharma
4   5  SHAYAM     x  Bhopal   30.0    Sharma             x
5   6  SHAYAM     x     Goa   40.0    Sharma             x

In [341]:
outer.drop(columns=['Name','Last_name'],inplace=True)

In [342]:
outer

   Id   Age    City Salary     full_namr
0   1  20.0       x      x     ramSharma
1   2  21.0       x      x   shyamSharma
2   3  22.0  Bhopal   10.0  sanyamSharma
3   4  23.0  Indore   20.0  priyamSharma
4   5     x  Bhopal   30.0             x
5   6     x     Goa   40.0             x

In [355]:
outer[['Fist_name','L_Name']]=outer['full_namr'].str.split(" ",expand=True)

ValueError: Columns must be same length as key