In [1]:
import numpy as np
import pandas as pd

In [2]:
table = pd.read_html("https://en.wikipedia.org/wiki/2011_census_of_India")

In [3]:
len(table)

13

In [4]:
table[1]

        0                      1       2
0  ← 2001  9 to 28 February 2011  2024 →

In [5]:
print(table)

[                                 15th census of India  \
0                 ← 2001 9 to 28 February 2011 2024 →
1                                              ← 2001
2   President of India Pratibha Patil receiving th...
3                                 General information
4                                             Country
5                                           Authority
6                                             Website
7                                             Results
8                                    Total population
9                                 Most populous state
10                               Least populous state
11                                   Scheduled Castes
12                                   Scheduled Tribes

                               15th census of India.1 Unnamed: 2
0                 ← 2001 9 to 28 February 2011 2024 →        NaN
1                               9 to 28 February 2011     2024 →
2   President of India Pratibha Patil receiving th...        NaN
3                                 General information        NaN
4                                               India        NaN
5                                               RGCCI        NaN
6                                  censusindia.gov.in        NaN
7                                             Results        NaN
8                          1,210,854,977 ( 17.70%[1])        NaN
9                         Uttar Pradesh (199,812,341)        NaN
10                                   Sikkim (610,577)        NaN
11                                          201378372        NaN
12                                          104545716        NaN  ,         0                      1       2
0  ← 2001  9 to 28 February 2011  2024 →,                                                    0
0  Building number Census house number Predominan...,                                                    0
0  Name of the person Relationship to head Sex Da...,                                                    0
0  Name of the person and resident status Name of...,                                  0               1            2
0                       Population           Total   1210854977
1                       Population           Males    623724568
2                       Population         Females    586469294
3                         Literacy           Total          74%
4                         Literacy           Males       82.10%
5                         Literacy         Females       65.46%
6            Density of population         per km2          382
7                        Sex ratio  per 1000 males  943 females
8  Child sex ratio (0–6 age group)  per 1000 males  919 females,    State / Union Territory (UT)                         Capital   Type  \
   State / Union Territory (UT)                         Capital   Type
0                 Uttar Pradesh                         Lucknow  State
1                   Maharashtra                          Mumbai  State
2                         Bihar                           Patna  State
3                   West Bengal                         Kolkata  State
4             Andhra Pradesh[a]                       Hyderabad  State
5                Madhya Pradesh                          Bhopal  State
6                    Tamil Nadu                         Chennai  State
7                     Rajasthan                          Jaipur  State
8                     Karnataka                       Bengaluru  State
9                       Gujarat                     Gandhinagar  State
10                       Odisha                    Bhubaneshwar  State
11                       Kerala              Thiruvananthapuram  State
12                    Jharkhand                          Ranchi  State
13                        Assam                          Dispur  State
14                       Punjab                      Chandigarh  State
15                 Chhattisgarh                          Raipur  State
16                      Haryana                      Chandigarh  State
17                        Delhi                           Delhi     UT
18            Jammu and Kashmir  Jammu(winter) Srinagar(summer)  State
19                  Uttarakhand                        Dehradun  State
20             Himachal Pradesh                          Shimla  State
21                      Tripura                        Agartala  State
22                    Meghalaya                        Shillong  State
23                      Manipur                          Imphal  State
24                     Nagaland                          Kohima  State
25                          Goa                          Panaji  State
26            Arunachal Pradesh                        Itanagar  State
27                   Puducherry                     Pondicherry     UT
28                      Mizoram                          Aizawl  State
29                   Chandigarh                      Chandigarh     UT
30                       Sikkim                         Gangtok  State
31  Andaman and Nicobar Islands                      Port Blair     UT
32       Dadra and Nagar Haveli                        Silvassa     UT
33                Daman and Diu                           Daman     UT
34                  Lakshadweep                       Kavaratti     UT
35                        India                           India  India

    Population                     Males    Females Sex Ratio [42]  \
        number % of total[44]      Males    Females Sex Ratio [42]
0    199812341         16.50%  104480510   95331831            912
1    112374333          9.28%   58243056   54131277            929
2    104099452          8.60%   54278157   49821295            918
3     91276115          7.54%   46809027   44467088            950
4     84580777          6.99%   42442146   42138631            993
5     72626809          6.00%   37612306   35014503            931
6     72147030          5.96%   36137975   36009055            996
7     68548437          5.66%   35550997   32997440            928
8     61095297          5.05%   30966657   30128640            973
9     60439692          4.99%   31491260   28948432            919
10    41974218          3.47%   21212136   20762082            979
11    33406061          2.76%   16027412   17378649           1084
12    32988134          2.72%   16930315   16057819            948
13    31205576          2.58%   15939443   15266133            958
14    27743338          2.29%   14639465   13103873            895
15    25545198          2.11%   12832895   12712303            991
16    25351462          2.09%   13494734   11856728            879
17    16787941          1.39%    8887326    7800615            868
18    12541302          1.04%    6640662    5900640            889
19    10086292          0.83%    5137773    4948519            963
20     6864602          0.57%    3481873    3382729            972
21     3673917          0.30%    1874376    1799541            960
22     2966889          0.25%    1491832    1475057            989
23     2721756          0.21%    1290171    1280219            992
24     1978502          0.16%    1024649     953853            931
25     1458545          0.12%     739140     719405            973
26     1383727          0.11%     713912     669815            938
27     1247953          0.10%     612511     635442           1037
28     1097206          0.09%     555339     541867            976
29     1055450          0.09%     580663     474787            818
30      610577          0.05%     323070     287507            890
31      380581          0.03%     202871     177710            876
32      343709          0.03%     193760     149949            774
33      243247          0.02%     150301      92946            618
34       64473          0.01%      33123      31350            946
35  1210854977           100%  623724248  586469174            943

   Literacy rate (%) Population            Area[43] (km2) Density (1/km2)  \
   Literacy rate (%)  Rural[45]  Urban[45] Area[43] (km2) Density (1/km2)
0             67.68%  155111022   44470455         240928             828
1             82.34%   61545441   50827531         307713             365
2             61.80%   92075028   11729609          94163            1102
3             76.26%   62213676   29134060          88752            1030
4             67.02%   56361702   28219075         275045             308
5             69.32%   52537899   20059666         308245             236
6             80.09%   37189229   34949729         130058             555
7             66.11%   51540236   17080776         342239             201
8             75.36%   37552529   23578175         191791             319
9             78.03%   34670817   25712811         196024             308
10            72.87%   34951234    6996124         155707             269
11            94.00%   17445506   15932171          38863             859
12            66.41%   25036946    7929292          79714             414
13            72.19%   26780526    4388756          78438             397
14            75.84%   17316800   10387436          50362             550
15            70.28%   19603658    5936538         135191             189
16            75.55%   16531493    8821588          44212             573
17            86.21%     944727   12905780           1484           11297
18            67.16%    9134820    3414106         222236              56
19            79.63%    7025583    3091169          53483             189
20            82.80%    6167805     688704          55673             123
21            87.22%    2710051     960981          10486             350
22            74.43%    2368971     595036          22429             132
23            79.21%    1899624     822132          22327             122
24            79.55%    1406861     573741          16579             119
25            88.70%     551414     906309           3702             394
26            65.38%    1069165     313446          83743              17
27            85.85%     394341     850123            479            2598
28            91.33%     529037     561997          21081              52
29            86.05%      29004    1025682            114            9252
30            81.42%     455962     151726           7096              86
31            86.63%     244411     135533           8249              46
32            76.24%     183024     159829            491             698
33            87.10%      60331     182580            112            2169
34            91.85%      14121      50308             32            2013
35            74.04%  833087662  377105760        3287240             382

   Decadal Growth% (2001–11)
   Decadal Growth% (2001–11)
0                      20.1%
1                      16.0%
2                      25.1%
3                      13.9%
4                     10.98%
5                      20.3%
6                      15.6%
7                      21.4%
8                      15.7%
9                      19.2%
10                     14.0%
11                      4.9%
12                     22.3%
13                     16.9%
14                     13.7%
15                     22.6%
16                     19.9%
17                       21%
18                     23.7%
19                     19.2%
20                     12.8%
21                     14.7%
22                     27.8%
23                     18.7%
24                     −0.5%
25                      8.2%
26                     25.9%
27                     27.7%
28                     22.8%
29                     17.1%
30                     12.4%
31                      6.7%
32                     55.5%
33                     53.5%
34                      6.2%
35                    17.64%  ,                                Year  Hindus Muslims Christians  Sikhs  \
0                              1951   84.1%    9.8%       2.3%  1.79%
1                              1961  83.45%  10.69%      2.44%  1.79%
2                              1971  82.73%  11.21%      2.60%  1.89%
3                              1981  82.30%  11.75%      2.44%  1.92%
4                              1991  81.53%  12.61%      2.32%  1.94%
5                              2001  80.46%  13.43%      2.34%  1.87%
6                              2011  79.80%  14.23%      2.37%  1.72%
7  Change in growth rate since 1951   5.12%  45.21%      3.04%  3.91%

  Buddhists   Jains Zoroastrians Atheists or other religion
0     0.74%   0.46%        0.13%                       0.8%
1     0.74%   0.46%        0.09%                       0.8%
2     0.70%   0.48%        0.09%                      0.41%
3     0.70%   0.47%        0.09%                      0.42%
4     0.77%   0.40%        0.08%                      0.44%
5     0.77%   0.41%        0.06%                       0.8%
6     0.70%   0.37%        0.05%                       0.9%
7     5.41%  19.56%       61.53%                     12.51%  ,      Language First language speakers                  \
     Language                num.[82] % of total pop.
0       Hindi               528347193          43.63%
1     English                  259678           0.02%
2     Bengali                97237669            8.3%
3     Marathi                83026680           7.09%
4      Telugu                81127740           6.93%
5       Tamil                69026881           5.89%
6    Gujarati                55492554           4.74%
7        Urdu                50772631           4.34%
8     Kannada                43706512           3.73%
9        Odia                37521324            3.2%
10  Malayalam                34838819           2.97%
11    Punjabi                33124726           2.83%
12   Maithili                13063042           1.08%
13   Sanskrit                   24821          <0.01%

   Second language speakers Third language speakers Total speakers  \
   Second language speakers Third language speakers   num.[72][83]
0                 139207180                24000000      692000000
1                  83125221                46000000      129000000
2                   9037222                 1000000      107000000
3                  13000000                 3000000       99000000
4                  12000000                 1000000       95000000
5                   7000000                 1000000       77000000
6                   4000000                 1000000       60000000
7                  11000000                 1000000       63000000
8                  14000000                 1000000       59000000
9                   5000000                  390000       43000000
10                   500000                  210000       36000000
11                  2230000                  720000       36600000
12                   400000                  130000       13583464
13                  1230000                 1960000        3190000


   % of total pop.
0            57.1%
1            10.6%
2             8.9%
3             8.2%
4             7.8%
5             6.3%
6               5%
7             5.2%
8            4.94%
9            3.56%
10            2.9%
11              3%
12           1.12%
13           0.19%  ,    Effective literacy rate (1901–2011)[citation needed][85]              \
                                                      S.No. Census year
0                                                   1              1901
1                                                   2              1911
2                                                   3              1921
3                                                   4              1931
4                                                   5              1941
5                                                   6              1951
6                                                   7              1961
7                                                   8              1971
8                                                   9              1981
9                                                  10              1991
10                                                 11              2001
11                                                 12              2011


   Total (%) Male (%) Female (%)
0      5.35%    9.83%      0.60%
1      5.92%   10.56%      1.05%
2      7.16%   12.21%      1.81%
3      9.50%   15.59%      2.93%
4     16.10%   24.90%      7.30%
5     16.67%   24.95%      9.45%
6     24.02%   34.44%     12.95%
7     29.45%   39.45%     18.69%
8     36.23%   46.89%     24.82%
9     42.84%   52.74%     32.17%
10    64.83%   75.26%     53.67%
11    74.04%   82.14%     65.46%  ,                                   vteCensus of India  \
0                                   Pre-independence
1                                  National censuses
2                                  Post-Independence
3                                  National censuses
4                                     Other censuses
5  See also: Registrar General and Census Commiss...

                                vteCensus of India.1
0                    National censuses Overview 1891
1                                      Overview 1891
2  National censuses 1951 1961 1971 1981 1991 200...
3            1951 1961 1971 1981 1991 2001 2011 2024
4  Indian economic census 2011 Socio Economic and...
5  See also: Registrar General and Census Commiss...  ,                    0              1
0  National censuses  Overview 1891,                    0                                                  1
0  National censuses            1951 1961 1971 1981 1991 2001 2011 2024
1     Other censuses  Indian economic census 2011 Socio Economic and...]

In [6]:
table[0]

,15th census of India,15th census of India.1,Unnamed: 2
0,← 2001 9 to 28 February 2011 2024 →,← 2001 9 to 28 February 2011 2024 →,NaN
1,← 2001,9 to 28 February 2011,2024 →
2,President of India Pratibha Patil receiving th...,President of India Pratibha Patil receiving th...,NaN
3,General information,General information,NaN
4,Country,India,NaN
5,Authority,RGCCI,NaN
6,Website,censusindia.gov.in,NaN
7,Results,Results,NaN
8,Total population,"1,210,854,977 ( 17.70%[1])",NaN
9,Most populous state,"Uttar Pradesh (199,812,341)",NaN
10,Least populous state,"Sikkim (610,577)",NaN
11,Scheduled Castes,201378372,NaN
12,Scheduled Tribes,104545716,NaN

In [7]:
#choose specific table by match fuction
table1 = pd.read_html("https://en.wikipedia.org/wiki/2011_census_of_India",match = "Population distribution in India by states")

In [8]:
len(table1)

1

In [9]:
df=pd.DataFrame(table1[1])

IndexError: list index out of range

In [12]:
df=pd.DataFrame(table1[0])

In [13]:
df

   State / Union Territory (UT)                         Capital   Type  \
   State / Union Territory (UT)                         Capital   Type
0                 Uttar Pradesh                         Lucknow  State
1                   Maharashtra                          Mumbai  State
2                         Bihar                           Patna  State
3                   West Bengal                         Kolkata  State
4             Andhra Pradesh[a]                       Hyderabad  State
5                Madhya Pradesh                          Bhopal  State
6                    Tamil Nadu                         Chennai  State
7                     Rajasthan                          Jaipur  State
8                     Karnataka                       Bengaluru  State
9                       Gujarat                     Gandhinagar  State
10                       Odisha                    Bhubaneshwar  State
11                       Kerala              Thiruvananthapuram  State
12                    Jharkhand                          Ranchi  State
13                        Assam                          Dispur  State
14                       Punjab                      Chandigarh  State
15                 Chhattisgarh                          Raipur  State
16                      Haryana                      Chandigarh  State
17                        Delhi                           Delhi     UT
18            Jammu and Kashmir  Jammu(winter) Srinagar(summer)  State
19                  Uttarakhand                        Dehradun  State
20             Himachal Pradesh                          Shimla  State
21                      Tripura                        Agartala  State
22                    Meghalaya                        Shillong  State
23                      Manipur                          Imphal  State
24                     Nagaland                          Kohima  State
25                          Goa                          Panaji  State
26            Arunachal Pradesh                        Itanagar  State
27                   Puducherry                     Pondicherry     UT
28                      Mizoram                          Aizawl  State
29                   Chandigarh                      Chandigarh     UT
30                       Sikkim                         Gangtok  State
31  Andaman and Nicobar Islands                      Port Blair     UT
32       Dadra and Nagar Haveli                        Silvassa     UT
33                Daman and Diu                           Daman     UT
34                  Lakshadweep                       Kavaratti     UT
35                        India                           India  India

    Population                     Males    Females Sex Ratio [42]  \
        number % of total[44]      Males    Females Sex Ratio [42]
0    199812341         16.50%  104480510   95331831            912
1    112374333          9.28%   58243056   54131277            929
2    104099452          8.60%   54278157   49821295            918
3     91276115          7.54%   46809027   44467088            950
4     84580777          6.99%   42442146   42138631            993
5     72626809          6.00%   37612306   35014503            931
6     72147030          5.96%   36137975   36009055            996
7     68548437          5.66%   35550997   32997440            928
8     61095297          5.05%   30966657   30128640            973
9     60439692          4.99%   31491260   28948432            919
10    41974218          3.47%   21212136   20762082            979
11    33406061          2.76%   16027412   17378649           1084
12    32988134          2.72%   16930315   16057819            948
13    31205576          2.58%   15939443   15266133            958
14    27743338          2.29%   14639465   13103873            895
15    25545198          2.11%   12832895   12712303            991
16    25351462          2.09%   13494734   11856728            879
17    16787941          1.39%    8887326    7800615            868
18    12541302          1.04%    6640662    5900640            889
19    10086292          0.83%    5137773    4948519            963
20     6864602          0.57%    3481873    3382729            972
21     3673917          0.30%    1874376    1799541            960
22     2966889          0.25%    1491832    1475057            989
23     2721756          0.21%    1290171    1280219            992
24     1978502          0.16%    1024649     953853            931
25     1458545          0.12%     739140     719405            973
26     1383727          0.11%     713912     669815            938
27     1247953          0.10%     612511     635442           1037
28     1097206          0.09%     555339     541867            976
29     1055450          0.09%     580663     474787            818
30      610577          0.05%     323070     287507            890
31      380581          0.03%     202871     177710            876
32      343709          0.03%     193760     149949            774
33      243247          0.02%     150301      92946            618
34       64473          0.01%      33123      31350            946
35  1210854977           100%  623724248  586469174            943

   Literacy rate (%) Population            Area[43] (km2) Density (1/km2)  \
   Literacy rate (%)  Rural[45]  Urban[45] Area[43] (km2) Density (1/km2)
0             67.68%  155111022   44470455         240928             828
1             82.34%   61545441   50827531         307713             365
2             61.80%   92075028   11729609          94163            1102
3             76.26%   62213676   29134060          88752            1030
4             67.02%   56361702   28219075         275045             308
5             69.32%   52537899   20059666         308245             236
6             80.09%   37189229   34949729         130058             555
7             66.11%   51540236   17080776         342239             201
8             75.36%   37552529   23578175         191791             319
9             78.03%   34670817   25712811         196024             308
10            72.87%   34951234    6996124         155707             269
11            94.00%   17445506   15932171          38863             859
12            66.41%   25036946    7929292          79714             414
13            72.19%   26780526    4388756          78438             397
14            75.84%   17316800   10387436          50362             550
15            70.28%   19603658    5936538         135191             189
16            75.55%   16531493    8821588          44212             573
17            86.21%     944727   12905780           1484           11297
18            67.16%    9134820    3414106         222236              56
19            79.63%    7025583    3091169          53483             189
20            82.80%    6167805     688704          55673             123
21            87.22%    2710051     960981          10486             350
22            74.43%    2368971     595036          22429             132
23            79.21%    1899624     822132          22327             122
24            79.55%    1406861     573741          16579             119
25            88.70%     551414     906309           3702             394
26            65.38%    1069165     313446          83743              17
27            85.85%     394341     850123            479            2598
28            91.33%     529037     561997          21081              52
29            86.05%      29004    1025682            114            9252
30            81.42%     455962     151726           7096              86
31            86.63%     244411     135533           8249              46
32            76.24%     183024     159829            491             698
33            87.10%      60331     182580            112            2169
34            91.85%      14121      50308             32            2013
35            74.04%  833087662  377105760        3287240             382

   Decadal Growth% (2001–11)
   Decadal Growth% (2001–11)
0                      20.1%
1                      16.0%
2                      25.1%
3                      13.9%
4                     10.98%
5                      20.3%
6                      15.6%
7                      21.4%
8                      15.7%
9                      19.2%
10                     14.0%
11                      4.9%
12                     22.3%
13                     16.9%
14                     13.7%
15                     22.6%
16                     19.9%
17                       21%
18                     23.7%
19                     19.2%
20                     12.8%
21                     14.7%
22                     27.8%
23                     18.7%
24                     −0.5%
25                      8.2%
26                     25.9%
27                     27.7%
28                     22.8%
29                     17.1%
30                     12.4%
31                      6.7%
32                     55.5%
33                     53.5%
34                      6.2%
35                    17.64%

In [14]:
df.columns=[ 'State / Union Territory (UT)','Capital','Type', 'Population-number','Population % of total',
              'Males','Females', 'Sex Ratio [41]','Literacy rate (%)',  'Population-Rural','Population-Urban',
                'Area (km2)', 'Density (1/km2)',  'Decadal Growth% (2001–11)']

In [15]:
df.columns

Index(['State / Union Territory (UT)', 'Capital', 'Type', 'Population-number',
       'Population % of total', 'Males', 'Females', 'Sex Ratio [41]',
       'Literacy rate (%)', 'Population-Rural', 'Population-Urban',
       'Area (km2)', 'Density (1/km2)', 'Decadal Growth% (2001–11)'],
      dtype='object')

In [16]:
df=df[0:-1]

In [17]:
df

,State / Union Territory (UT),Capital,Type,Population-number,Population % of total,Males,Females,Sex Ratio [41],Literacy rate (%),Population-Rural,Population-Urban,Area (km2),Density (1/km2),Decadal Growth% (2001–11)
0,Uttar Pradesh,Lucknow,State,199812341,16.50%,104480510,95331831,912,67.68%,155111022,44470455,240928,828,20.1%
1,Maharashtra,Mumbai,State,112374333,9.28%,58243056,54131277,929,82.34%,61545441,50827531,307713,365,16.0%
2,Bihar,Patna,State,104099452,8.60%,54278157,49821295,918,61.80%,92075028,11729609,94163,1102,25.1%
3,West Bengal,Kolkata,State,91276115,7.54%,46809027,44467088,950,76.26%,62213676,29134060,88752,1030,13.9%
4,Andhra Pradesh[a],Hyderabad,State,84580777,6.99%,42442146,42138631,993,67.02%,56361702,28219075,275045,308,10.98%
5,Madhya Pradesh,Bhopal,State,72626809,6.00%,37612306,35014503,931,69.32%,52537899,20059666,308245,236,20.3%
6,Tamil Nadu,Chennai,State,72147030,5.96%,36137975,36009055,996,80.09%,37189229,34949729,130058,555,15.6%
7,Rajasthan,Jaipur,State,68548437,5.66%,35550997,32997440,928,66.11%,51540236,17080776,342239,201,21.4%
8,Karnataka,Bengaluru,State,61095297,5.05%,30966657,30128640,973,75.36%,37552529,23578175,191791,319,15.7%
9,Gujarat,Gandhinagar,State,60439692,4.99%,31491260,28948432,919,78.03%,34670817,25712811,196024,308,19.2%
10,Odisha,Bhubaneshwar,State,41974218,3.47%,21212136,20762082,979,72.87%,34951234,6996124,155707,269,14.0%
11,Kerala,Thiruvananthapuram,State,33406061,2.76%,16027412,17378649,1084,94.00%,17445506,15932171,38863,859,4.9%
12,Jharkhand,Ranchi,State,32988134,2.72%,16930315,16057819,948,66.41%,25036946,7929292,79714,414,22.3%
13,Assam,Dispur,State,31205576,2.58%,15939443,15266133,958,72.19%,26780526,4388756,78438,397,16.9%
14,Punjab,Chandigarh,State,27743338,2.29%,14639465,13103873,895,75.84%,17316800,10387436,50362,550,13.7%
15,Chhattisgarh,Raipur,State,25545198,2.11%,12832895,12712303,991,70.28%,19603658,5936538,135191,189,22.6%
16,Haryana,Chandigarh,State,25351462,2.09%,13494734,11856728,879,75.55%,16531493,8821588,44212,573,19.9%
17,Delhi,Delhi,UT,16787941,1.39%,8887326,7800615,868,86.21%,944727,12905780,1484,11297,21%
18,Jammu and Kashmir,Jammu(winter) Srinagar(summer),State,12541302,1.04%,6640662,5900640,889,67.16%,9134820,3414106,222236,56,23.7%
19,Uttarakhand,Dehradun,State,10086292,0.83%,5137773,4948519,963,79.63%,7025583,3091169,53483,189,19.2%
20,Himachal Pradesh,Shimla,State,6864602,0.57%,3481873,3382729,972,82.80%,6167805,688704,55673,123,12.8%
21,Tripura,Agartala,State,3673917,0.30%,1874376,1799541,960,87.22%,2710051,960981,10486,350,14.7%
22,Meghalaya,Shillong,State,2966889,0.25%,1491832,1475057,989,74.43%,2368971,595036,22429,132,27.8%
23,Manipur,Imphal,State,2721756,0.21%,1290171,1280219,992,79.21%,1899624,822132,22327,122,18.7%
24,Nagaland,Kohima,State,1978502,0.16%,1024649,953853,931,79.55%,1406861,573741,16579,119,−0.5%
25,Goa,Panaji,State,1458545,0.12%,739140,719405,973,88.70%,551414,906309,3702,394,8.2%
26,Arunachal Pradesh,Itanagar,State,1383727,0.11%,713912,669815,938,65.38%,1069165,313446,83743,17,25.9%
27,Puducherry,Pondicherry,UT,1247953,0.10%,612511,635442,1037,85.85%,394341,850123,479,2598,27.7%
28,Mizoram,Aizawl,State,1097206,0.09%,555339,541867,976,91.33%,529037,561997,21081,52,22.8%
29,Chandigarh,Chandigarh,UT,1055450,0.09%,580663,474787,818,86.05%,29004,1025682,114,9252,17.1%
30,Sikkim,Gangtok,State,610577,0.05%,323070,287507,890,81.42%,455962,151726,7096,86,12.4%
31,Andaman and Nicobar Islands,Port Blair,UT,380581,0.03%,202871,177710,876,86.63%,244411,135533,8249,46,6.7%
32,Dadra and Nagar Haveli,Silvassa,UT,343709,0.03%,193760,149949,774,76.24%,183024,159829,491,698,55.5%
33,Daman and Diu,Daman,UT,243247,0.02%,150301,92946,618,87.10%,60331,182580,112,2169,53.5%
34,Lakshadweep,Kavaratti,UT,64473,0.01%,33123,31350,946,91.85%,14121,50308,32,2013,6.2%

In [18]:
df.Type.nunique

<bound method IndexOpsMixin.nunique of 0     State
1     State
2     State
3     State
4     State
5     State
6     State
7     State
8     State
9     State
10    State
11    State
12    State
13    State
14    State
15    State
16    State
17       UT
18    State
19    State
20    State
21    State
22    State
23    State
24    State
25    State
26    State
27       UT
28    State
29       UT
30    State
31       UT
32       UT
33       UT
34       UT
Name: Type, dtype: object>