In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Math': [85, 92, 78, 90, 88],
    'Science': [91, 85, 89, 92, 94],
    'English': [78, 82, 84, 88, 90]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Student  Math  Science  English
0    Alice    85       91       78
1      Bob    92       85       82
2  Charlie    78       89       84
3    David    90       92       88
4      Eve    88       94       90

In [5]:
#extract series from data frame
math_series = df['Math']
print(math_series)

0    85
1    92
2    78
3    90
4    88
Name: Math, dtype: int64

In [6]:
#Find out mean, max, min, std and median of math_series
print('Mean:- ', math_series.mean())
print('Mean:- ', math_series.max())
print('Mean:- ', math_series.min())
print('Mean:- ', math_series.median())
print('Mean:- ', math_series.mode())

Mean:-  86.6
Mean:-  92
Mean:-  78
Mean:-  88.0
Mean:-  0    78
1    85
2    88
3    90
4    92
Name: Math, dtype: int64

In [7]:
#Students who scored more than 85 in Math
print('No. of students:-', math_series[math_series>85])

No. of students:- 1    92
3    90
4    88
Name: Math, dtype: int64

In [8]:
M1 = pd.Series(data['Math'], index=data['Student'])

In [9]:
M1

Alice      85
Bob        92
Charlie    78
David      90
Eve        88
dtype: int64

In [10]:
print('Name of students:-', M1[M1>85])

Name of students:- Bob      92
David    90
Eve      88
dtype: int64

In [ ]:
#Add 5 points to the math scores.

In [11]:
#Create a New Series as a Column (Total Score):
df['Total'] = df['Math'] + df['Science'] + df['English']

In [12]:
df

   Student  Math  Science  English  Total
0    Alice    85       91       78    254
1      Bob    92       85       82    259
2  Charlie    78       89       84    251
3    David    90       92       88    270
4      Eve    88       94       90    272

In [13]:
T1 = pd.Series(df.Total)

In [14]:
T1

0    254
1    259
2    251
3    270
4    272
Name: Total, dtype: int64

In [15]:
T1.index = list(df.Student)

In [16]:
T1

Alice      254
Bob        259
Charlie    251
David      270
Eve        272
Name: Total, dtype: int64

In [17]:
T1.sort_values()

Charlie    251
Alice      254
Bob        259
David      270
Eve        272
Name: Total, dtype: int64

In [18]:
T1.sort_index()

Alice      254
Bob        259
Charlie    251
David      270
Eve        272
Name: Total, dtype: int64

In [19]:
T1.sort_index(ascending=False)

Eve        272
David      270
Charlie    251
Bob        259
Alice      254
Name: Total, dtype: int64

In [20]:
T1.sort_values(ascending=False)

Eve        272
David      270
Bob        259
Alice      254
Charlie    251
Name: Total, dtype: int64

In [21]:
def categorize_performance(total_score):
    if total_score >=260:
        return 'High'
    elif total_score >= 240:
        return 'Medium'
    else:
        return 'Low'
df['Performance'] = df['Total'].apply(categorize_performance)

print(df)

   Student  Math  Science  English  Total Performance
0    Alice    85       91       78    254      Medium
1      Bob    92       85       82    259      Medium
2  Charlie    78       89       84    251      Medium
3    David    90       92       88    270        High
4      Eve    88       94       90    272        High