In [1]:
import numpy as np
import pandas as pd

In [2]:
#Creating series
S1 = pd.Series()
print(S1)

Series([], dtype: object)

In [3]:
#Creating a series from array
d1 = np.array(['c','o','d','i','n','g'])
S2 = pd.Series(d1)
print(S2)

0    c
1    o
2    d
3    i
4    n
5    g
dtype: object

In [4]:
#Creating a series from array with index
data = np.array(['c','o','d','i','n','g'])
S3 = pd.Series(data,index=[10,11,12,13,14,15])
print(S3)

10    c
11    o
12    d
13    i
14    n
15    g
dtype: object

In [8]:
#Create a series from lists
L1 = ['c','o','d','i','n','g']
S4 = pd.Series(L1)
print(S4)

0    c
1    o
2    d
3    i
4    n
5    g
dtype: object

In [9]:
#creating a series from list with index
L1 = ['c','o','d','i','n','g']
S4 = pd.Series(L1, index=[11,12,13,14,15,16])
print(S4)

11    c
12    o
13    d
14    i
15    n
16    g
dtype: object

In [6]:
#creating a series from dictionary
dict = {'K1': 10,'K2':20,'K3':30}
ser = pd.Series(dict)
print(ser)

K1    10
K2    20
K3    30
dtype: int64

In [13]:
#creating a series from dictionary with index
dict = {'K1': 10,'K2': 20,'K3': 30,'k5': 40,'k6':50}
ser = pd.Series(dict,index=[1,2,3,4])
print(ser)

1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [7]:
#creating a series from scaler value
S5 = pd.Series(10)
print(S5)

0    10
dtype: int64

In [18]:
#creating a series from scaler value with index
scalar_value = 5
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(scalar_value, index=index)
print(series)

a    5
b    5
c    5
d    5
e    5
dtype: int64

In [5]:
#create a series from range
S5 = pd.Series(200, index = range(1,40,2))
print(S5)

1     200
3     200
5     200
7     200
9     200
11    200
13    200
15    200
17    200
19    200
21    200
23    200
25    200
27    200
29    200
31    200
33    200
35    200
37    200
39    200
dtype: int64

In [10]:
S5 = pd.Series(10, index = range(1,20,2))
print(S5)

1     10
3     10
5     10
7     10
9     10
11    10
13    10
15    10
17    10
19    10
dtype: int64

In [11]:
#series with numpy linspace()
S6 = pd.Series(np.linspace(3,33,10))
print(S6)

0     3.000000
1     6.333333
2     9.666667
3    13.000000
4    16.333333
5    19.666667
6    23.000000
7    26.333333
8    29.666667
9    33.000000
dtype: float64

In [12]:
S6 = pd.Series(np.linspace(3,33,10,retstep=True))
print(S6)

0    [3.0, 6.333333333333334, 9.666666666666668, 13...
1                                             3.333333
dtype: object

In [13]:
S6 = pd.Series(np.linspace(3,33,100))
print(S6)

0      3.000000
1      3.303030
2      3.606061
3      3.909091
4      4.212121
        ...
95    31.787879
96    32.090909
97    32.393939
98    32.696970
99    33.000000
Length: 100, dtype: float64

In [14]:
S6 = pd.Series(np.linspace(3,33,10,endpoint=False))
print(S6)

0     3.0
1     6.0
2     9.0
3    12.0
4    15.0
5    18.0
6    21.0
7    24.0
8    27.0
9    30.0
dtype: float64

In [15]:
S6 = pd.Series(np.linspace(3,33,10, dtype=int))
print(S6)

0     3
1     6
2     9
3    13
4    16
5    19
6    23
7    26
8    29
9    33
dtype: int64

In [16]:
#creating a series using range fuction
S7 = pd.Series(range(10))
print(S7)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [17]:
S7 = pd.Series(range(1,10))
print(S7)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [18]:
S7 = pd.Series(range(1,30,3))
print(S7)

0     1
1     4
2     7
3    10
4    13
5    16
6    19
7    22
8    25
9    28
dtype: int64

In [23]:
#creating a series from mathematical expression
ser = np.arange(1,100)
print(ser)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]

In [24]:
ser1 = pd.Series(ser*2,index=ser)
print(ser1)

1       2
2       4
3       6
4       8
5      10
     ...
95    190
96    192
97    194
98    196
99    198
Length: 99, dtype: int64

In [25]:
ser1 = pd.Series(ser*5,index=ser)
print(ser1)

1       5
2      10
3      15
4      20
5      25
     ...
95    475
96    480
97    485
98    490
99    495
Length: 99, dtype: int64

In [26]:
ser1 = pd.Series(ser**2,index=ser)
print(ser1)

1        1
2        4
3        9
4       16
5       25
      ...
95    9025
96    9216
97    9409
98    9604
99    9801
Length: 99, dtype: int64

In [4]:
cities = ['kolkata', 'Chicago', 'Tornto', 'Lisbon']   #Pandas Series Attributes And Mehods
popu = [14.4, 2.56, 56.8, 90.7]
city_series = pd.Series(popu, index=cities)
city_series.index

Index(['kolkata', 'Chicago', 'Tornto', 'Lisbon'], dtype='object')

In [5]:
city_series.index = ['KOL', 'CHI', 'TOR', 'LIS']
city_series.index

Index(['KOL', 'CHI', 'TOR', 'LIS'], dtype='object')

In [4]:
S8 = pd.Series(range(10,35), name='Example')
S8

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
15    25
16    26
17    27
18    28
19    29
20    30
21    31
22    32
23    33
24    34
Name: Example, dtype: int64

In [5]:
S8.name

'Example'

In [6]:
S8.shape

(25,)

In [9]:
S8.size

25

In [10]:
S8.ndim

1

In [11]:
S8.hasnans

False

In [12]:
S8.index

RangeIndex(start=0, stop=25, step=1)

In [13]:
S8.dtypes

dtype('int64')

In [15]:
S8.info()

<class 'pandas.core.series.Series'>
RangeIndex: 25 entries, 0 to 24
Series name: Example
Non-Null Count  Dtype
--------------  -----
25 non-null     int64
dtypes: int64(1)
memory usage: 332.0 bytes

In [16]:
S8.head(4)

0    10
1    11
2    12
3    13
Name: Example, dtype: int64

In [17]:
S8.tail(2)

23    33
24    34
Name: Example, dtype: int64

In [19]:
S8.describe()

count    25.000000
mean     22.000000
std       7.359801
min      10.000000
25%      16.000000
50%      22.000000
75%      28.000000
max      34.000000
Name: Example, dtype: float64

In [20]:
S8.value_counts()

Example
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
Name: count, dtype: int64

In [21]:
S8.values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [23]:
S8.dtypes

dtype('int64')

In [24]:
S8.empty

False

In [25]:
S8.isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: Example, dtype: bool

In [26]:
S8.isna().sum()

np.int64(0)

In [27]:
S8.notna()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
Name: Example, dtype: bool

In [28]:
S8.notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
Name: Example, dtype: bool

In [29]:
S8.notna().sum()

np.int64(25)

In [30]:
S8.notnull().sum()

np.int64(25)

In [9]:
S8.isnull().sum()

np.int64(0)

In [32]:
S9 = pd.Series([1,2,3,4])
print(S9)

0    1
1    2
2    3
3    4
dtype: int64

In [12]:
S9.sum()

np.int64(10)

In [13]:
S9.array

<NumpyExtensionArray>
[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
Length: 4, dtype: int64

In [14]:
S9.nbytes

32

In [16]:
S9.add(1)

0    2
1    3
2    4
3    5
dtype: int64

In [17]:
S9.div(2)

0    0.5
1    1.0
2    1.5
3    2.0
dtype: float64

In [18]:
S9.mul(2)

0    2
1    4
2    6
3    8
dtype: int64

In [34]:
S10 = pd.Series([3,4,5,6])
print(S10)

0    3
1    4
2    5
3    6
dtype: int64

In [29]:
S9.add(S10)

0     4
1     6
2     8
3    10
dtype: int64

In [31]:
S9.div(S10)

0    0.333333
1    0.500000
2    0.600000
3    0.666667
dtype: float64

In [32]:
S9.mod(S10)

0    1
1    2
2    3
3    4
dtype: int64

In [35]:
S9.mul(S10)

0     3
1     8
2    15
3    24
dtype: int64

In [36]:
S9

0    1
1    2
2    3
3    4
dtype: int64

In [43]:
import pandas as pd

In [44]:
data = pd.read_csv("nba.csv")

In [45]:
data.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [6]:
# importing pandas 
import pandas as pd  
  
# reading the csv   
data = pd.read_csv("nba.csv")  
     
 
# creating series form weight column 
s1 = pd.Series(data['Weight'].head()) 

print(s1)
print(type(s1))
# using to_numpy() function 
print(s1.to_numpy())
print(s1.to_numpy(dtype='float'))
print(s1.to_numpy(dtype='int64'))
print(s1.to_numpy(dtype='str'))

0    180.0
1    235.0
2    205.0
3    185.0
4    231.0
Name: Weight, dtype: float64
<class 'pandas.core.series.Series'>
[180. 235. 205. 185. 231.]
[180. 235. 205. 185. 231.]
[180 235 205 185 231]
['180.0' '235.0' '205.0' '185.0' '231.0']

In [48]:
data.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0

In [49]:
data.shape

(458, 9)

In [50]:
len(data.columns)

9

In [51]:
data.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [53]:
data.Weight.head()

0    180.0
1    235.0
2    205.0
3    185.0
4    231.0
Name: Weight, dtype: float64

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [55]:
data.size

4122

In [56]:
data.ndim

2

In [2]:
#Pandas series.mod
a = pd.Series([5, 10, 14, np.nan], index=['a','b','c','d'])
b = pd.Series([2, np.nan, 4, 2], index=['a','b','c','d'])
print(a)
print(b)
print(a.mod(b))
print(a.mod(b,fill_value=3))

a     5.0
b    10.0
c    14.0
d     NaN
dtype: float64
a    2.0
b    NaN
c    4.0
d    2.0
dtype: float64
a    1.0
b    NaN
c    2.0
d    NaN
dtype: float64
a    1.0
b    1.0
c    2.0
d    1.0
dtype: float64

In [3]:
import pandas as pd

data = pd.read_csv("nba.csv")

#creating short data of 5 rows
short_data = data.head()

In [4]:
type(short_data)

pandas.core.frame.DataFrame

In [5]:
short_data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [6]:
#creating list with 5 values
list = [1, 2, 3, 4, 3]

#finding remainder
#creating new coloumn
short_data["Remainder"]= short_data["Salary"].mod(list, fill_value=8)

#display
short_data

C:\Users\HP\AppData\Local\Temp\ipykernel_13140\3686852893.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  short_data["Remainder"]= short_data["Salary"].mod(list, fill_value=8)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Remainder
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,0.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,1.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,0.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2.0

In [8]:
#Pandas.Series.Mode

s = pd.Series([4, 4, 2, 2, 4, None])
s.mode()

0    4.0
dtype: float64

In [9]:
s = pd.Series([2, 4, 8, 2, 4, 6, 6, None])
s.mode()

0    2.0
1    4.0
2    6.0
dtype: float64

In [12]:
#dropna = false , means do not consider counts of NaN

s = pd.Series([2, 4, None, None, 4, None])
print(s.mode(dropna=False))
s = pd.Series([2, 4, None, None, 4, None])
print(s.mode())

0   NaN
dtype: float64
0    4.0
dtype: float64

In [13]:
# Creating the Series 
sr = pd.Series([10, 25, 3, 25, 24, 6]) 
  
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr) 

# return the mean 
result = sr.mean() 
  
# Print the result 
print(result)

Coca Cola    10
Sprite       25
Coke          3
Fanta        25
Dew          24
ThumbsUp      6
dtype: int64
15.5

In [16]:
#creating the series 
sr = pd.Series([19.5, 16.8, None, 22.78, 16.8, 20.124, None, 18.1002, 19.5])

#print the series 
print(sr)

#return the mean 
#dont skip all the missing values
result1 = sr.mean(skipna=False)

#print the result
print(result1)

#skip all the missing values
result = sr.mean(skipna = True)

#print the result 
print(result)

0    19.5000
1    16.8000
2        NaN
3    22.7800
4    16.8000
5    20.1240
6        NaN
7    18.1002
8    19.5000
dtype: float64
nan
19.086314285714284

In [17]:
#creating the series 
sr = pd.Series([10, 25, 3, 25, 24, 6])

#create the index
index_ = ['coco cola', 'sprite', 'coke', 'fanta', 'dew', 'thumbsup']

#set the index
sr.index = index_

#print the series 
print(sr)

print("Maximum Value:- ", sr.max())
print("Mininmum Value:- ",sr.min())
print("Sum of Value:- ",sr.sum())
print("Standard Deviation value:- ",sr.std())

coco cola    10
sprite       25
coke          3
fanta        25
dew          24
thumbsup      6
dtype: int64
Maximum Value:-  25
Mininmum Value:-  3
Sum of Value:-  93
Standard Deviation value:-  10.290772565750348

In [18]:
import numpy as np

In [19]:
# Creating the Series 
sr = pd.Series([10, 25, 3, np.nan,25, 24, np.nan]) 
  
# Print the series 
print(sr) 
print(sr.isna())
print(sr.isnull())
print(sr.isna().sum())
print(sr.isnull().sum())
print(sr.notna())
print(sr.notnull())

0    10.0
1    25.0
2     3.0
3     NaN
4    25.0
5    24.0
6     NaN
dtype: float64
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
2
2
0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool
0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool

In [20]:
# Creating the Series 
sr = pd.Series([10, np.nan, 3,np.nan, 24, None]) 
  
# Print the series 
print(sr) 
print(sr.isna())
print(sr.isnull())
print("Total Missing Values:- ",sr.isna().sum())

0    10.0
1     NaN
2     3.0
3     NaN
4    24.0
5     NaN
dtype: float64
0    False
1     True
2    False
3     True
4    False
5     True
dtype: bool
0    False
1     True
2    False
3     True
4    False
5     True
dtype: bool
Total Missing Values:-  3

In [21]:
# Creating the Series 
sr = pd.Series([10, np.nan, 3,np.nan, 24, None]) 
  
# Print the series 
print(sr) 
print(sr.notna())
print(sr.notnull())
print("Total Not Missing Values:- ",sr.notnull().sum())

0    10.0
1     NaN
2     3.0
3     NaN
4    24.0
5     NaN
dtype: float64
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
Total Not Missing Values:-  3

In [4]:
import numpy as np
import pandas as pd

In [5]:
# Creating the Series 
sr = pd.Series([10, np.nan, 3,np.nan, 24, None]) 
  
# Print the series 
print(sr) 
print(sr.notna())
print(sr.notnull())
print("Total Missing Values:- ",sr.notnull().sum())

sr.dropna(inplace=True)
print("Total Missing Values:- ",sr.isnull().sum())

0    10.0
1     NaN
2     3.0
3     NaN
4    24.0
5     NaN
dtype: float64
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool
Total Missing Values:-  3
Total Missing Values:-  0

In [6]:
#pandas series drop
# Creating the Series 
sr = pd.Series([80, 25, 3, 25, 24, 6]) 
print(sr)
  
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr)

0    80
1    25
2     3
3    25
4    24
5     6
dtype: int64
Coca Cola    80
Sprite       25
Coke          3
Fanta        25
Dew          24
ThumbsUp      6
dtype: int64

In [7]:
# Creating the Series 
sr = pd.Series([80, 25, 3, 25, 24, 6]) 
print(sr)
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr) 

# drop the passed labels 
result = sr.drop(labels = ['Sprite', 'Dew'])  
  
# Print the result 
print(result)

0    80
1    25
2     3
3    25
4    24
5     6
dtype: int64
Coca Cola    80
Sprite       25
Coke          3
Fanta        25
Dew          24
ThumbsUp      6
dtype: int64
Coca Cola    80
Coke          3
Fanta        25
ThumbsUp      6
dtype: int64

In [8]:
a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
print(a)
print(b)
a.eq(b, fill_value=0)

a    1.0
b    1.0
c    1.0
d    NaN
dtype: float64
a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64

a     True
b    False
c    False
d    False
e    False
dtype: bool

In [9]:
# creating series 1  
series1 = pd.Series([70, 5, 0, 225, 1, 16, np.nan, 10, np.nan])  
     
# creating series 2  
series2 = pd.Series([70, np.nan, 2, 23, 1, 95, 53, 10, 5])  
   
# NaN replacement 
replace_nan = 5
   
# calling and returning to result variable 
result = series1.eq(series2, fill_value = replace_nan) 
   
# display  
result

0     True
1     True
2    False
3    False
4     True
5    False
6    False
7     True
8     True
dtype: bool

In [10]:
a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
print(a)
print(b)
a.le(b, fill_value=0)

a    1.0
b    1.0
c    1.0
d    NaN
dtype: float64
a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64

a     True
b    False
c    False
d     True
e    False
dtype: bool

In [11]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.le(series2, fill_value = replace_nan) 
  
# display  
result

0    False
1     True
2     True
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

In [12]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.lt(series2, fill_value = replace_nan) 
  
# display  
result

0    False
1     True
2    False
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

In [13]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.gt(series2, fill_value = replace_nan) 
  
# display  
result

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8    False
dtype: bool

In [14]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.ge(series2, fill_value = replace_nan) 
  
# display  
result

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8    False
dtype: bool

In [15]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, np.nan, 10, np.nan])  
    
# creating series 2  
series2 = pd.Series([27, np.nan, 2, 23, 5, 95, 4, 3, 19])  
  
# NaN replacement 
replace_nan = 7
  
# calling and returning to result variable 
result = series1.ne(series2, fill_value = replace_nan) 
  
# display  
result

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7     True
8     True
dtype: bool

In [16]:
# creating series 1  
series1 = pd.Series([70, 0, 2, 225, 1, 16, 2, 10, 6]) 
print(series1.idxmax())
print(series1.idxmin())
print(series1.sort_values())
print(series1.sort_values(ascending=False))
print(series1.sort_index())
print(series1.sort_index(ascending=False))
print(series1.head(2))
print(series1.head())
print(series1.tail(2))
print(series1.tail())

3
1
1      0
4      1
6      2
2      2
8      6
7     10
5     16
0     70
3    225
dtype: int64
3    225
0     70
5     16
7     10
8      6
2      2
6      2
4      1
1      0
dtype: int64
0     70
1      0
2      2
3    225
4      1
5     16
6      2
7     10
8      6
dtype: int64
8      6
7     10
6      2
5     16
4      1
3    225
2      2
1      0
0     70
dtype: int64
0    70
1     0
dtype: int64
0     70
1      0
2      2
3    225
4      1
dtype: int64
7    10
8     6
dtype: int64
4     1
5    16
6     2
7    10
8     6
dtype: int64

In [20]:
#series .between
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,New Age
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,25.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,25.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,22.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,22.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,25.0
...,...,...,...,...,...,...,...,...,...,...
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0,23.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0,25.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,22.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,25.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,25.0

In [22]:
d2 = pd.Series(data['Age'])

In [23]:
d2.between(20,25).sum()

np.int64(167)