In [1]:
import numpy as np
import pandas as pd

In [2]:
#pandas data frame 
df = pd.read_csv("nba.csv")

In [3]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [4]:
sample_df = df.sample(15)

In [5]:
sample_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
391,Joffrey Lauvergne,Denver Nuggets,77.0,C,24.0,6-11,220.0,NaN,1709719.0
112,Marcelo Huertas,Los Angeles Lakers,9.0,PG,33.0,6-3,200.0,NaN,525093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
327,Tyler Hansbrough,Charlotte Hornets,50.0,PF,30.0,6-9,250.0,North Carolina,947276.0
94,Branden Dawson,Los Angeles Clippers,22.0,SF,23.0,6-6,225.0,Michigan State,525093.0
307,Jonathon Simmons,San Antonio Spurs,17.0,SG,26.0,6-6,195.0,Houston,525093.0
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479.0
157,Taj Gibson,Chicago Bulls,22.0,PF,30.0,6-9,225.0,USC,8500000.0
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
407,Ricky Rubio,Minnesota Timberwolves,9.0,PG,25.0,6-4,194.0,NaN,12700000.0
206,Glenn Robinson III,Indiana Pacers,40.0,SG,22.0,6-7,222.0,Michigan,1100000.0

In [6]:
sample_df.sort_index()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
94,Branden Dawson,Los Angeles Clippers,22.0,SF,23.0,6-6,225.0,Michigan State,525093.0
112,Marcelo Huertas,Los Angeles Lakers,9.0,PG,33.0,6-3,200.0,NaN,525093.0
157,Taj Gibson,Chicago Bulls,22.0,PF,30.0,6-9,225.0,USC,8500000.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
206,Glenn Robinson III,Indiana Pacers,40.0,SG,22.0,6-7,222.0,Michigan,1100000.0
307,Jonathon Simmons,San Antonio Spurs,17.0,SG,26.0,6-6,195.0,Houston,525093.0
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479.0
327,Tyler Hansbrough,Charlotte Hornets,50.0,PF,30.0,6-9,250.0,North Carolina,947276.0
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
391,Joffrey Lauvergne,Denver Nuggets,77.0,C,24.0,6-11,220.0,NaN,1709719.0
407,Ricky Rubio,Minnesota Timberwolves,9.0,PG,25.0,6-4,194.0,NaN,12700000.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0

In [7]:
sample_df.sort_index(axis=0)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
94,Branden Dawson,Los Angeles Clippers,22.0,SF,23.0,6-6,225.0,Michigan State,525093.0
112,Marcelo Huertas,Los Angeles Lakers,9.0,PG,33.0,6-3,200.0,NaN,525093.0
157,Taj Gibson,Chicago Bulls,22.0,PF,30.0,6-9,225.0,USC,8500000.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
206,Glenn Robinson III,Indiana Pacers,40.0,SG,22.0,6-7,222.0,Michigan,1100000.0
307,Jonathon Simmons,San Antonio Spurs,17.0,SG,26.0,6-6,195.0,Houston,525093.0
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479.0
327,Tyler Hansbrough,Charlotte Hornets,50.0,PF,30.0,6-9,250.0,North Carolina,947276.0
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
391,Joffrey Lauvergne,Denver Nuggets,77.0,C,24.0,6-11,220.0,NaN,1709719.0
407,Ricky Rubio,Minnesota Timberwolves,9.0,PG,25.0,6-4,194.0,NaN,12700000.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0

In [8]:
df.sort_index(axis=1)

,Age,College,Height,Name,Number,Position,Salary,Team,Weight
0,25.0,Texas,6-2,Avery Bradley,0.0,PG,7730337.0,Boston Celtics,180.0
1,25.0,Marquette,6-6,Jae Crowder,99.0,SF,6796117.0,Boston Celtics,235.0
2,27.0,Boston University,6-5,John Holland,30.0,SG,NaN,Boston Celtics,205.0
3,22.0,Georgia State,6-5,R.J. Hunter,28.0,SG,1148640.0,Boston Celtics,185.0
4,29.0,NaN,6-10,Jonas Jerebko,8.0,PF,5000000.0,Boston Celtics,231.0
...,...,...,...,...,...,...,...,...,...
453,26.0,Butler,6-3,Shelvin Mack,8.0,PG,2433333.0,Utah Jazz,203.0
454,24.0,NaN,6-1,Raul Neto,25.0,PG,900000.0,Utah Jazz,179.0
455,26.0,NaN,7-3,Tibor Pleiss,21.0,C,2900000.0,Utah Jazz,256.0
456,26.0,Kansas,7-0,Jeff Withey,24.0,C,947276.0,Utah Jazz,231.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.sort_index(axis=1,ascending=False)

,Weight,Team,Salary,Position,Number,Name,Height,College,Age
0,180.0,Boston Celtics,7730337.0,PG,0.0,Avery Bradley,6-2,Texas,25.0
1,235.0,Boston Celtics,6796117.0,SF,99.0,Jae Crowder,6-6,Marquette,25.0
2,205.0,Boston Celtics,NaN,SG,30.0,John Holland,6-5,Boston University,27.0
3,185.0,Boston Celtics,1148640.0,SG,28.0,R.J. Hunter,6-5,Georgia State,22.0
4,231.0,Boston Celtics,5000000.0,PF,8.0,Jonas Jerebko,6-10,NaN,29.0
...,...,...,...,...,...,...,...,...,...
453,203.0,Utah Jazz,2433333.0,PG,8.0,Shelvin Mack,6-3,Butler,26.0
454,179.0,Utah Jazz,900000.0,PG,25.0,Raul Neto,6-1,NaN,24.0
455,256.0,Utah Jazz,2900000.0,C,21.0,Tibor Pleiss,7-3,NaN,26.0
456,231.0,Utah Jazz,947276.0,C,24.0,Jeff Withey,7-0,Kansas,26.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
data = pd.read_csv("nba.csv")

In [14]:
#before sorting
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data.sort_values("Name",axis=0, ascending=True,inplace=True, na_position='last')

In [17]:
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data.sort_values("Name",axis=0, ascending=True,inplace=True, na_position='first')

In [19]:
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
...,...,...,...,...,...,...,...,...,...
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0

In [21]:
data[['Team','Name']].sort_values(['Team','Name']).head(20)

               Team              Name
312   Atlanta Hawks        Al Horford
318   Atlanta Hawks   Dennis Schroder
323   Atlanta Hawks       Jeff Teague
309   Atlanta Hawks     Kent Bazemore
311   Atlanta Hawks      Kirk Hinrich
313   Atlanta Hawks    Kris Humphries
314   Atlanta Hawks       Kyle Korver
317   Atlanta Hawks   Lamar Patterson
316   Atlanta Hawks      Mike Muscala
319   Atlanta Hawks        Mike Scott
315   Atlanta Hawks      Paul Millsap
320   Atlanta Hawks   Thabo Sefolosha
321   Atlanta Hawks    Tiago Splitter
310   Atlanta Hawks  Tim Hardaway Jr.
322   Atlanta Hawks    Walter Tavares
5    Boston Celtics      Amir Johnson
0    Boston Celtics     Avery Bradley
12   Boston Celtics       Evan Turner
11   Boston Celtics     Isaiah Thomas
1    Boston Celtics       Jae Crowder

In [22]:
data[['Team','Name']].sort_values(['Team','Name'],ascending = True).head(20)

               Team              Name
312   Atlanta Hawks        Al Horford
318   Atlanta Hawks   Dennis Schroder
323   Atlanta Hawks       Jeff Teague
309   Atlanta Hawks     Kent Bazemore
311   Atlanta Hawks      Kirk Hinrich
313   Atlanta Hawks    Kris Humphries
314   Atlanta Hawks       Kyle Korver
317   Atlanta Hawks   Lamar Patterson
316   Atlanta Hawks      Mike Muscala
319   Atlanta Hawks        Mike Scott
315   Atlanta Hawks      Paul Millsap
320   Atlanta Hawks   Thabo Sefolosha
321   Atlanta Hawks    Tiago Splitter
310   Atlanta Hawks  Tim Hardaway Jr.
322   Atlanta Hawks    Walter Tavares
5    Boston Celtics      Amir Johnson
0    Boston Celtics     Avery Bradley
12   Boston Celtics       Evan Turner
11   Boston Celtics     Isaiah Thomas
1    Boston Celtics       Jae Crowder

In [24]:
data[['Team','Name']].sort_values(['Team','Name'],ascending= [True,False]).head(20)

               Team              Name
322   Atlanta Hawks    Walter Tavares
310   Atlanta Hawks  Tim Hardaway Jr.
321   Atlanta Hawks    Tiago Splitter
320   Atlanta Hawks   Thabo Sefolosha
315   Atlanta Hawks      Paul Millsap
319   Atlanta Hawks        Mike Scott
316   Atlanta Hawks      Mike Muscala
317   Atlanta Hawks   Lamar Patterson
314   Atlanta Hawks       Kyle Korver
313   Atlanta Hawks    Kris Humphries
311   Atlanta Hawks      Kirk Hinrich
309   Atlanta Hawks     Kent Bazemore
323   Atlanta Hawks       Jeff Teague
318   Atlanta Hawks   Dennis Schroder
312   Atlanta Hawks        Al Horford
14   Boston Celtics      Tyler Zeller
8    Boston Celtics      Terry Rozier
3    Boston Celtics       R.J. Hunter
9    Boston Celtics      Marcus Smart
7    Boston Celtics      Kelly Olynyk

In [25]:
data.sort_values(['Team','Name'],ascending=[True,False])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,NaN,9756250.0
320,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,NaN,4000000.0
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659.0
...,...,...,...,...,...,...,...,...,...
380,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
data.sort_values(['Team','Name'],ascending=[True,False],ignore_index=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
1,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
2,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,NaN,9756250.0
3,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,NaN,4000000.0
4,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659.0
...,...,...,...,...,...,...,...,...,...
453,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602.0
454,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
455,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
456,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN