In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_excel("DistrictWithLocalBody.xlsx")

In [5]:
df

           Sno District                  Local_Body
0            1    Bhind      Janpad Panchayat, Ater
1            2    Bhind      Janpad Panchayat, Ater
2            3    Bhind      Janpad Panchayat, Ater
3            4    Bhind      Janpad Panchayat, Ater
4            5    Bhind      Janpad Panchayat, Ater
...        ...      ...                         ...
873931  873932     Agar  Janpad Panchayat, NALKHEDA
873932  873933     Agar  Janpad Panchayat, NALKHEDA
873933  873934     Agar  Janpad Panchayat, NALKHEDA
873934  873935     Agar  Janpad Panchayat, NALKHEDA
873935  873936     Agar  Janpad Panchayat, NALKHEDA

[873936 rows x 3 columns]

In [5]:
df.head(2)

   Sno District              Local_Body
0    1    Bhind  Janpad Panchayat, Ater
1    2    Bhind  Janpad Panchayat, Ater

In [6]:
df.columns

Index(['Sno', 'District', 'Local_Body'], dtype='object')

In [7]:
df["District"]

0         Bhind
1         Bhind
2         Bhind
3         Bhind
4         Bhind
          ...
873931     Agar
873932     Agar
873933     Agar
873934     Agar
873935     Agar
Name: District, Length: 873936, dtype: object

In [8]:
df[["District","Local_Body"]]

       District                  Local_Body
0         Bhind      Janpad Panchayat, Ater
1         Bhind      Janpad Panchayat, Ater
2         Bhind      Janpad Panchayat, Ater
3         Bhind      Janpad Panchayat, Ater
4         Bhind      Janpad Panchayat, Ater
...         ...                         ...
873931     Agar  Janpad Panchayat, NALKHEDA
873932     Agar  Janpad Panchayat, NALKHEDA
873933     Agar  Janpad Panchayat, NALKHEDA
873934     Agar  Janpad Panchayat, NALKHEDA
873935     Agar  Janpad Panchayat, NALKHEDA

[873936 rows x 2 columns]

In [6]:
df["U"]=df["Local_Body"].str.upper()

In [7]:
df["L"]=df["Local_Body"].str.lower()

In [8]:
df["T"]=df["Local_Body"].str.title()

In [9]:
df["C"]=df["Local_Body"].str.capitalize()

In [10]:
df["No.ofcharacterinLB"]=df["Local_Body"].str.len()

In [11]:
df["F"]=df["Local_Body"].str[0]

In [19]:
df["swap"]=df["Local_Body"].str.swapcase()

In [20]:
df.head(2)

,Sno,District,Local_Body,U,L,T,C,No.ofcharacterinLB,F,swap
0,1,Bhind,"Janpad Panchayat, Ater","JANPAD PANCHAYAT, ATER","janpad panchayat, ater","Janpad Panchayat, Ater","Janpad panchayat, ater",22,J,"jANPAD pANCHAYAT, aTER"
1,2,Bhind,"Janpad Panchayat, Ater","JANPAD PANCHAYAT, ATER","janpad panchayat, ater","Janpad Panchayat, Ater","Janpad panchayat, ater",22,J,"jANPAD pANCHAYAT, aTER"

In [21]:
df["District"]=df["District"].str.replace("Agar","Agar Malwa")

In [22]:
df

,Sno,District,Local_Body,U,L,T,C,No.ofcharacterinLB,F,swap
0,1,Bhind,"Janpad Panchayat, Ater","JANPAD PANCHAYAT, ATER","janpad panchayat, ater","Janpad Panchayat, Ater","Janpad panchayat, ater",22,J,"jANPAD pANCHAYAT, aTER"
1,2,Bhind,"Janpad Panchayat, Ater","JANPAD PANCHAYAT, ATER","janpad panchayat, ater","Janpad Panchayat, Ater","Janpad panchayat, ater",22,J,"jANPAD pANCHAYAT, aTER"
2,3,Bhind,"Janpad Panchayat, Ater","JANPAD PANCHAYAT, ATER","janpad panchayat, ater","Janpad Panchayat, Ater","Janpad panchayat, ater",22,J,"jANPAD pANCHAYAT, aTER"
3,4,Bhind,"Janpad Panchayat, Ater","JANPAD PANCHAYAT, ATER","janpad panchayat, ater","Janpad Panchayat, Ater","Janpad panchayat, ater",22,J,"jANPAD pANCHAYAT, aTER"
4,5,Bhind,"Janpad Panchayat, Ater","JANPAD PANCHAYAT, ATER","janpad panchayat, ater","Janpad Panchayat, Ater","Janpad panchayat, ater",22,J,"jANPAD pANCHAYAT, aTER"
...,...,...,...,...,...,...,...,...,...,...
873931,873932,Agar Malwa,"Janpad Panchayat, NALKHEDA","JANPAD PANCHAYAT, NALKHEDA","janpad panchayat, nalkheda","Janpad Panchayat, Nalkheda","Janpad panchayat, nalkheda",26,J,"jANPAD pANCHAYAT, nalkheda"
873932,873933,Agar Malwa,"Janpad Panchayat, NALKHEDA","JANPAD PANCHAYAT, NALKHEDA","janpad panchayat, nalkheda","Janpad Panchayat, Nalkheda","Janpad panchayat, nalkheda",26,J,"jANPAD pANCHAYAT, nalkheda"
873933,873934,Agar Malwa,"Janpad Panchayat, NALKHEDA","JANPAD PANCHAYAT, NALKHEDA","janpad panchayat, nalkheda","Janpad Panchayat, Nalkheda","Janpad panchayat, nalkheda",26,J,"jANPAD pANCHAYAT, nalkheda"
873934,873935,Agar Malwa,"Janpad Panchayat, NALKHEDA","JANPAD PANCHAYAT, NALKHEDA","janpad panchayat, nalkheda","Janpad Panchayat, Nalkheda","Janpad panchayat, nalkheda",26,J,"jANPAD pANCHAYAT, nalkheda"
873935,873936,Agar Malwa,"Janpad Panchayat, NALKHEDA","JANPAD PANCHAYAT, NALKHEDA","janpad panchayat, nalkheda","Janpad Panchayat, Nalkheda","Janpad panchayat, nalkheda",26,J,"jANPAD pANCHAYAT, nalkheda"

In [24]:
df["F"]

0         J
1         J
2         J
3         J
4         J
         ..
873931    J
873932    J
873933    J
873934    J
873935    J
Name: F, Length: 873936, dtype: object

In [26]:
s=df["Local_Body"].str[0]

In [27]:
s

0         J
1         J
2         J
3         J
4         J
         ..
873931    J
873932    J
873933    J
873934    J
873935    J
Name: Local_Body, Length: 873936, dtype: object

In [28]:
urban=0
rural=0
l=len(s)
for i in range(l):
    if s[i]=="J":
        rural+=1
    else:
        urban+=1
print("Rural Body: ",rural)
print("Urban Body: ",urban)

Rural Body:  689831
Urban Body:  184105

In [29]:
df["Local_Body"].str.split(",")

0             [Janpad Panchayat,  Ater]
1             [Janpad Panchayat,  Ater]
2             [Janpad Panchayat,  Ater]
3             [Janpad Panchayat,  Ater]
4             [Janpad Panchayat,  Ater]
                      ...
873931    [Janpad Panchayat,  NALKHEDA]
873932    [Janpad Panchayat,  NALKHEDA]
873933    [Janpad Panchayat,  NALKHEDA]
873934    [Janpad Panchayat,  NALKHEDA]
873935    [Janpad Panchayat,  NALKHEDA]
Name: Local_Body, Length: 873936, dtype: object

In [30]:
df["Local_Body"].str.split(" ").str[-1]

0             Ater
1             Ater
2             Ater
3             Ater
4             Ater
            ...
873931    NALKHEDA
873932    NALKHEDA
873933    NALKHEDA
873934    NALKHEDA
873935    NALKHEDA
Name: Local_Body, Length: 873936, dtype: object

In [31]:
df["Local_Body"].str.split(" ").str[-2]

0         Panchayat,
1         Panchayat,
2         Panchayat,
3         Panchayat,
4         Panchayat,
             ...
873931    Panchayat,
873932    Panchayat,
873933    Panchayat,
873934    Panchayat,
873935    Panchayat,
Name: Local_Body, Length: 873936, dtype: object

In [32]:
df["Local_Body"].str.repeat(2)

0              Janpad Panchayat, AterJanpad Panchayat, Ater
1              Janpad Panchayat, AterJanpad Panchayat, Ater
2              Janpad Panchayat, AterJanpad Panchayat, Ater
3              Janpad Panchayat, AterJanpad Panchayat, Ater
4              Janpad Panchayat, AterJanpad Panchayat, Ater
                                ...
873931    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873932    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873933    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873934    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873935    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
Name: Local_Body, Length: 873936, dtype: object

In [33]:
df["Local_Body"].str.repeat(3)

0         Janpad Panchayat, AterJanpad Panchayat, AterJa...
1         Janpad Panchayat, AterJanpad Panchayat, AterJa...
2         Janpad Panchayat, AterJanpad Panchayat, AterJa...
3         Janpad Panchayat, AterJanpad Panchayat, AterJa...
4         Janpad Panchayat, AterJanpad Panchayat, AterJa...
                                ...
873931    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873932    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873933    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873934    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
873935    Janpad Panchayat, NALKHEDAJanpad Panchayat, NA...
Name: Local_Body, Length: 873936, dtype: object